import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Download, FileCheck2, Loader2, Plus, Save, Trash2 } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { messageFromError } from '../../portal/portalHelpers';

type Allocation = { label: string; montant: number; poids?: number; fonction: string };
type Support = { type: 'scpi'|'assurance_vie'|'cto'|'pea'; nom: string; isin?: string; societe_gestion?: string; montant: number; poids?: number; role?: string };
type Sequence = { phase: string; operation: string; montant?: number; commentaire?: string };
type Recommendation = {
  id?: string; dossier_id: string; statut: 'draft'|'validated'; diagnostic: string; projet_a_preserver: string;
  reserve_securite: number; epargne_a_arbitrer: number; allocation: Allocation[]; supports: Record<string, unknown>;
  sequencing: Sequence[]; fiscal_notes: string[]; protection_notes: string; controls: string[]; validated_at?: string|null;
};

const empty = (dossierId:string): Recommendation => ({ dossier_id:dossierId, statut:'draft', diagnostic:'', projet_a_preserver:'', reserve_securite:0, epargne_a_arbitrer:0, allocation:[], supports:{scpi:[],assurance_vie:[],cto:[],pea:[]}, sequencing:[], fiscal_notes:[], protection_notes:'', controls:[] });
const euro = (v:number) => new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v||0);

export default function CifAuditPage(){
  const [params]=useSearchParams(); const dossierId=params.get('dossier')??'';
  const [rec,setRec]=useState<Recommendation>(()=>empty(dossierId)); const [supports,setSupports]=useState<Support[]>([]);
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [generating,setGenerating]=useState(false);
  const [message,setMessage]=useState(''); const [error,setError]=useState(''); const [download,setDownload]=useState<string|null>(null);

  useEffect(()=>{ let active=true; (async()=>{ if(!dossierId) throw new Error('Dossier manquant.'); const {data:current,error:roleError}=await supabase.from('app_users').select('role,actif').maybeSingle(); if(roleError)throw roleError; if(!current?.actif||!['cif','admin'].includes(current.role))throw new Error('Accès réservé au cabinet.'); const {data,error}=await supabase.from('audit_recommendations').select('*').eq('dossier_id',dossierId).maybeSingle(); if(error)throw error; if(active&&data){ setRec(data as Recommendation); const grouped=(data.supports??{}) as Record<string,Support[]>; setSupports((['scpi','assurance_vie','cto','pea'] as const).flatMap(type=>(grouped[type]??[]).map(x=>({...x,type})))); } })().catch(e=>active&&setError(messageFromError(e))).finally(()=>active&&setLoading(false)); return()=>{active=false}; },[dossierId]);

  const allocationTotal=useMemo(()=>rec.allocation.reduce((s,x)=>s+(Number(x.montant)||0),0),[rec.allocation]);
  const setAllocation=(i:number,patch:Partial<Allocation>)=>setRec(r=>({...r,statut:'draft',validated_at:null,allocation:r.allocation.map((x,j)=>j===i?{...x,...patch}:x)}));
  const setSupport=(i:number,patch:Partial<Support>)=>setSupports(xs=>xs.map((x,j)=>j===i?{...x,...patch}:x));
  const groupedSupports=()=>Object.fromEntries((['scpi','assurance_vie','cto','pea'] as const).map(type=>[type,supports.filter(s=>s.type===type).map(({type:_,...x})=>x)]));
  const lines=(s:string)=>s.split('\n').map(x=>x.trim()).filter(Boolean);

  async function save(validate=false){ setSaving(true);setError('');setMessage('');setDownload(null); try{ const payload={...rec,statut:validate?'validated':'draft',validated_at:validate?new Date().toISOString():null,supports:groupedSupports(),updated_at:new Date().toISOString()}; const {data,error}=await supabase.from('audit_recommendations').upsert(payload,{onConflict:'dossier_id'}).select('*').single(); if(error)throw error; setRec(data as Recommendation); setMessage(validate?'Recommandation validée. L’audit V22 peut être généré.':'Brouillon enregistré.'); }catch(e){setError(messageFromError(e));}finally{setSaving(false);} }
  async function generate(){ if(rec.statut!=='validated'){setError('Valide d’abord la recommandation conseiller.');return;} setGenerating(true);setError('');setMessage(''); try{ const {data,error}=await supabase.functions.invoke('generate-cif-audit',{body:{dossier_id:dossierId}}); if(error)throw error; if(!data?.ok)throw new Error(data?.error||'Génération impossible.'); setDownload(data.signed_url??null); setMessage(data.reused?'Audit V22 existant réutilisé.':'Audit V22 généré et archivé.'); }catch(e){setError(messageFromError(e));}finally{setGenerating(false);} }

  if(loading)return <div className="min-h-screen bg-slate-50 p-10 text-sm text-slate-500">Chargement de l’audit…</div>;
  if(error&&!dossierId)return <div className="p-10 text-red-700">{error}</div>;
  return <div className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6"><div className="mx-auto max-w-6xl space-y-6">
    <div><Link to={`/cabinet/synthese?dossier=${encodeURIComponent(dossierId)}`} className="inline-flex items-center gap-2 text-sm font-semibold text-slate-500"><ArrowLeft className="h-4 w-4"/> Retour à la synthèse</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-blue-600">Audit patrimonial</p><h1 className="mt-2 text-3xl font-semibold text-slate-950">Modèle maître V22</h1><p className="mt-2 text-sm text-slate-500">Les faits viennent du recueil, du profil et de l’ESG. La recommandation ci-dessous doit être validée par le conseiller avant génération.</p></div>
    {error&&<div className="rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</div>}{message&&<div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{message}</div>}
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-semibold">Décision patrimoniale</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Épargne à arbitrer<input type="number" value={rec.epargne_a_arbitrer} onChange={e=>setRec(r=>({...r,statut:'draft',epargne_a_arbitrer:Number(e.target.value)}))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="text-sm font-semibold">Réserve de sécurité<input type="number" value={rec.reserve_securite} onChange={e=>setRec(r=>({...r,statut:'draft',reserve_securite:Number(e.target.value)}))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label></div><label className="mt-4 block text-sm font-semibold">Projet à préserver<input value={rec.projet_a_preserver} onChange={e=>setRec(r=>({...r,statut:'draft',projet_a_preserver:e.target.value}))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="mt-4 block text-sm font-semibold">Diagnostic / décision proposée<textarea rows={5} value={rec.diagnostic} onChange={e=>setRec(r=>({...r,statut:'draft',diagnostic:e.target.value}))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center justify-between"><div><h2 className="text-xl font-semibold">Allocation cible</h2><p className="mt-1 text-sm text-slate-500">Total : {euro(allocationTotal)}</p></div><button onClick={()=>setRec(r=>({...r,statut:'draft',allocation:[...r.allocation,{label:'',montant:0,fonction:''}]}))} className="inline-flex items-center gap-2 rounded-xl border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700"><Plus className="h-4 w-4"/> Ajouter</button></div><div className="mt-5 space-y-3">{rec.allocation.map((x,i)=><div key={i} className="grid gap-2 rounded-2xl bg-slate-50 p-3 sm:grid-cols-[1.3fr_.7fr_1.8fr_auto]"><input placeholder="Poche (SCPI, PEA…)" value={x.label} onChange={e=>setAllocation(i,{label:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2"/><input type="number" placeholder="Montant" value={x.montant} onChange={e=>setAllocation(i,{montant:Number(e.target.value)})} className="rounded-xl border border-slate-200 px-3 py-2"/><input placeholder="Fonction patrimoniale" value={x.fonction} onChange={e=>setAllocation(i,{fonction:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2"/><button onClick={()=>setRec(r=>({...r,statut:'draft',allocation:r.allocation.filter((_,j)=>j!==i)}))} className="rounded-xl p-2 text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div>)}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><div className="flex items-center justify-between"><h2 className="text-xl font-semibold">Supports sélectionnés</h2><button onClick={()=>setSupports(xs=>[...xs,{type:'scpi',nom:'',montant:0}])} className="inline-flex items-center gap-2 rounded-xl border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700"><Plus className="h-4 w-4"/> Ajouter</button></div><div className="mt-5 space-y-3">{supports.map((x,i)=><div key={i} className="grid gap-2 rounded-2xl bg-slate-50 p-3 lg:grid-cols-[.7fr_1.5fr_1.2fr_.7fr_.6fr_1.4fr_auto]"><select value={x.type} onChange={e=>setSupport(i,{type:e.target.value as Support['type']})} className="rounded-xl border border-slate-200 px-3 py-2"><option value="scpi">SCPI</option><option value="assurance_vie">Assurance-vie</option><option value="cto">CTO</option><option value="pea">PEA</option></select><input placeholder="Support" value={x.nom} onChange={e=>setSupport(i,{nom:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2"/><input placeholder="ISIN / société" value={x.isin??x.societe_gestion??''} onChange={e=>setSupport(i,{isin:e.target.value,societe_gestion:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2"/><input type="number" placeholder="Montant" value={x.montant} onChange={e=>setSupport(i,{montant:Number(e.target.value)})} className="rounded-xl border border-slate-200 px-3 py-2"/><input type="number" placeholder="%" value={x.poids??''} onChange={e=>setSupport(i,{poids:Number(e.target.value)})} className="rounded-xl border border-slate-200 px-3 py-2"/><input placeholder="Rôle / justification" value={x.role??''} onChange={e=>setSupport(i,{role:e.target.value})} className="rounded-xl border border-slate-200 px-3 py-2"/><button onClick={()=>setSupports(xs=>xs.filter((_,j)=>j!==i))} className="rounded-xl p-2 text-slate-400 hover:text-red-600"><Trash2 className="h-4 w-4"/></button></div>)}</div></section>
    <section className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:p-8"><h2 className="text-xl font-semibold">Notes et contrôles</h2><label className="mt-4 block text-sm font-semibold">Fiscalité — une conclusion par ligne<textarea rows={4} value={rec.fiscal_notes.join('\n')} onChange={e=>setRec(r=>({...r,statut:'draft',fiscal_notes:lines(e.target.value)}))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="mt-4 block text-sm font-semibold">Protection<textarea rows={3} value={rec.protection_notes} onChange={e=>setRec(r=>({...r,statut:'draft',protection_notes:e.target.value}))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label><label className="mt-4 block text-sm font-semibold">Contrôles avant exécution — un par ligne<textarea rows={4} value={rec.controls.join('\n')} onChange={e=>setRec(r=>({...r,statut:'draft',controls:lines(e.target.value)}))} className="mt-2 w-full rounded-xl border border-slate-200 px-4 py-3"/></label></section>
    <div className="sticky bottom-4 flex flex-wrap items-center justify-end gap-3 rounded-2xl border border-slate-200 bg-white/95 p-4 shadow-lg backdrop-blur"><span className={`mr-auto rounded-full px-3 py-2 text-xs font-bold ${rec.statut==='validated'?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}`}>{rec.statut==='validated'?'Recommandation validée':'Brouillon'}</span><button disabled={saving} onClick={()=>save(false)} className="inline-flex items-center gap-2 rounded-xl border border-slate-300 px-4 py-3 text-sm font-semibold"><Save className="h-4 w-4"/> Enregistrer</button><button disabled={saving} onClick={()=>save(true)} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white"><FileCheck2 className="h-4 w-4"/> Valider la recommandation</button><button disabled={generating||rec.statut!=='validated'} onClick={generate} className="inline-flex items-center gap-2 rounded-xl bg-emerald-700 px-4 py-3 text-sm font-semibold text-white disabled:opacity-40">{generating?<Loader2 className="h-4 w-4 animate-spin"/>:<FileCheck2 className="h-4 w-4"/>} Générer l’audit V22</button>{download&&<a href={download} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><Download className="h-4 w-4"/> Télécharger</a>}</div>
  </div></div>;
}
