import { useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, Leaf, UserRoundCheck } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { supabase } from '../../lib/supabase';
import { dossierHref, fetchPortalProgress, messageFromError, selectedProgress, type PortalProgress } from '../../portal/portalHelpers';

interface QpiResult { score_tolerance: number | null; score_max: number | null; profil_indicatif: string | null; }
interface EsgPref { taxonomie_choix: string | null; taxonomie_min_pct: number | null; sfdr_choix: string | null; sfdr_min_pct: number | null; pai_choix: string | null; pai_priorites: string[]; exclusions_sectorielles: string[]; }

export default function ClientSummaryPage() {
  const [searchParams] = useSearchParams();
  const [rows, setRows] = useState<PortalProgress[]>([]);
  const [qpi, setQpi] = useState<QpiResult | null>(null);
  const [esg, setEsg] = useState<EsgPref | null>(null);
  const [errorMessage, setErrorMessage] = useState('');
  const dossierId = searchParams.get('dossier');
  const progress = useMemo(() => selectedProgress(rows, dossierId), [rows, dossierId]);

  useEffect(() => { void fetchPortalProgress().then(async (progressRows) => { setRows(progressRows); const row = selectedProgress(progressRows, dossierId); if (!row) return; if (row.qpi_session_id) { const { data } = await supabase.from('portal_qpi_result').select('score_tolerance,score_max,profil_indicatif').eq('session_id', row.qpi_session_id).maybeSingle(); setQpi(data as QpiResult | null); } if (row.esg_session_id && ['completed','validated'].includes(row.esg_status)) { const { data } = await supabase.from('esg_preferences').select('taxonomie_choix,taxonomie_min_pct,sfdr_choix,sfdr_min_pct,pai_choix,pai_priorites,exclusions_sectorielles').eq('session_id', row.esg_session_id).maybeSingle(); setEsg(data as EsgPref | null); } }).catch((error) => setErrorMessage(messageFromError(error))); }, [dossierId]);
  if (!progress) return <p>Aucun dossier sélectionné.</p>;
  const allDone = progress.next_step === 'TERMINE';
  return <div className="space-y-8"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-slate-500">Synthèse</p><h2 className="mt-2 text-3xl font-semibold">État de votre parcours</h2></div>
    <section className={`rounded-3xl border p-6 sm:p-8 ${allDone ? 'border-emerald-200 bg-emerald-50' : 'border-slate-200 bg-white'}`}><div className="flex gap-4">{allDone ? <CheckCircle2 className="h-7 w-7 text-emerald-700" /> : <Clock3 className="h-7 w-7 text-slate-500" />}<div><h3 className="text-xl font-semibold">{allDone ? 'Questionnaires terminés' : 'Parcours en cours'}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{allDone ? 'Vos réponses sont enregistrées. Le cabinet peut maintenant procéder aux analyses et contrôles nécessaires avant toute recommandation personnalisée.' : 'Complétez l’étape suivante pour poursuivre votre dossier.'}</p>{!allDone && <Link to={progress.next_step === 'RECUEIL' ? dossierHref('/espace-client/recueil', progress.dossier_id) : progress.next_step === 'QPI' ? dossierHref('/espace-client/profil-investisseur', progress.dossier_id) : dossierHref('/espace-client/esg', progress.dossier_id)} className="mt-4 inline-block font-semibold text-slate-900 underline">Poursuivre</Link>}</div></div></section>
    {qpi && <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><UserRoundCheck className="h-6 w-6" /><h3 className="text-lg font-semibold">Profil investisseur — indicateur</h3></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs uppercase tracking-[0.12em] text-slate-500">Tolérance Q21–Q25</p><p className="mt-2 text-2xl font-semibold">{qpi.score_tolerance ?? '—'} / {qpi.score_max ?? 24}</p></div><div className="rounded-2xl bg-slate-50 p-5"><p className="text-xs uppercase tracking-[0.12em] text-slate-500">Profil indicatif</p><p className="mt-2 text-lg font-semibold">{qpi.profil_indicatif ?? 'En cours de calcul'}</p></div></div><p className="mt-4 text-xs leading-5 text-slate-500">Cet indicateur ne constitue pas à lui seul le profil opérationnel final. Le cabinet intègre capacité de perte, horizon, liquidité, connaissances, expérience et contrôles de cohérence.</p></section>}
    {progress.esg_opt_in && esg && <section className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-8"><div className="flex items-center gap-3"><Leaf className="h-6 w-6" /><h3 className="text-lg font-semibold">Préférences de durabilité</h3></div><div className="mt-5 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4 text-sm"><p className="font-semibold">Taxonomie</p><p className="mt-1 text-slate-600">{esg.taxonomie_choix === 'oui' ? `Minimum ${esg.taxonomie_min_pct ?? '—'} %` : 'Pas de seuil exprimé'}</p></div><div className="rounded-2xl bg-slate-50 p-4 text-sm"><p className="font-semibold">SFDR durable</p><p className="mt-1 text-slate-600">{esg.sfdr_choix === 'oui' ? `Minimum ${esg.sfdr_min_pct ?? '—'} %` : 'Pas de seuil exprimé'}</p></div><div className="rounded-2xl bg-slate-50 p-4 text-sm"><p className="font-semibold">PAI</p><p className="mt-1 text-slate-600">{esg.pai_choix === 'oui' ? 'Prise en compte demandée' : 'Non demandée'}</p></div></div>{esg.pai_priorites.length > 0 && <p className="mt-4 text-sm text-slate-600"><strong>Priorités PAI :</strong> {esg.pai_priorites.join(', ')}</p>}{esg.exclusions_sectorielles.length > 0 && <p className="mt-2 text-sm text-slate-600"><strong>Exclusions :</strong> {esg.exclusions_sectorielles.join(', ')}</p>}</section>}
    {errorMessage && <p className="rounded-2xl bg-red-50 p-4 text-red-700">{errorMessage}</p>}
  </div>;
}
