import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'assurance-vie-fiscalite',
  category: 'assurance-vie',
  title: 'Fiscalité de l\'assurance-vie : rachats, gains, abattements et transmission',
  metaTitle: 'Fiscalité de l\'assurance-vie : rachats, gains, abattements et transmission',
  metaDescription: 'La fiscalité de l\'assurance-vie dépend de la date des versements, de l\'âge du souscripteur, de la durée de détention et du régime des rachats. Analyse des abattements, du PFU, des prélèvements sociaux et de la transmission par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/assurance-vie-fiscalite/',
  badge: 'Assurance-vie &bull; Fiscalité &bull; Rachat &bull; Abattement &bull; Transmission &bull; CGP-CIF',
  intro: 'L\'assurance-vie est le placement préféré des Français, mais sa fiscalité est souvent mal comprise. Entre le régime des rachats avant et après 8 ans, les abattements annuels, le prélèvement forfaitaire unique (PFU), les prélèvements sociaux et les règles de transmission, il est facile de s\'y perdre. Pourtant, une bonne compréhension de ces mécanismes est essentielle pour optimiser son contrat et éviter les mauvaises surprises fiscales. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous détaille la fiscalité de l\'assurance-vie, rachat par rachat, pour vous aider à faire les bons choix patrimoniaux.',
  shortAnswer: 'La fiscalité de l\'assurance-vie repose sur le régime des rachats et la transmission. En cas de rachat avant 8 ans, les gains sont soumis au PFU (12,8 % + 17,2 % de PS) ou au barème progressif sur option. Après 8 ans, un abattement annuel de 4 600 € (célibataire) ou 9 200 € (couple) s\'applique sur les gains avant imposition. Au-delà de cet abattement, les gains sont imposés à 7,5 % (ou au barème progressif). Les prélèvements sociaux (17,2 %) sont dus dans tous les cas sur la totalité des gains. Pour la transmission, les capitaux versés avant 70 ans bénéficient d\'un abattement de 152 500 € par bénéficiaire. Après 70 ans, l\'abattement global est de 30 500 € sur l\'ensemble des bénéficiaires. Les primes versées après 70 ans sont soumises aux droits de succession au-delà de cet abattement.',
  summaryItems: [
    { label: 'Régime général : gains imposés, capital non imposé', anchor: 'regime-general' },
    { label: 'Rachat avant 8 ans : PFU et barème progressif', anchor: 'rachat-avant-8-ans' },
    { label: 'Rachat après 8 ans : abattement et taux réduit', anchor: 'rachat-apres-8-ans' },
    { label: 'Prélèvements sociaux : 17,2 % sur les gains', anchor: 'prelevements-sociaux' },
    { label: 'Tableau récapitulatif de la fiscalité des rachats', anchor: 'tableau-rachats' },
    { label: 'Transmission avant 70 ans : abattement de 152 500 € par bénéficiaire', anchor: 'transmission-avant-70-ans' },
    { label: 'Transmission après 70 ans : abattement global de 30 500 €', anchor: 'transmission-apres-70-ans' },
    { label: 'Exemple pédagogique : rachat après 8 ans', anchor: 'exemple-pedagogique' },
    { label: 'Erreurs fréquentes avec la fiscalité de l\'assurance-vie', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance sur la fiscalité de l\'assurance-vie', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour optimiser la fiscalité', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 20,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['assurance-vie', 'fiscalité', 'rachat', 'abattement', 'transmission', 'PFU', 'prélèvements sociaux', 'CGP-CIF'],
  sections: [
    {
      id: 'regime-general',
      title: "Régime général : seuls les gains sont imposés, pas le capital",
      level: 'h2',
      type: 'normal',
      content: [
        "L'un des principes fondamentaux de la fiscalité de l'assurance-vie est que seuls les gains (intérêts, plus-values) sont soumis à imposition. Le capital versé par le souscripteur n'est jamais imposé, quelle que soit la date du rachat ou l'âge du souscripteur.",
        "Ce principe distingue l'assurance-vie de nombreux autres placements financiers et constitue l'un de ses principaux avantages fiscaux. En contrepartie, l'assurance-vie est soumise à des règles d'imposition spécifiques qui varient selon la durée de détention du contrat et l'âge du souscripteur.",
        "La fiscalité applicable dépend de plusieurs facteurs :",
        "- La date de souscription du contrat (avant ou après le 27 septembre 2017, date d'entrée en vigueur du PFU) ;",
        "- La durée de détention du contrat (avant ou après 8 ans) ;",
        "- Le montant des gains réalisés lors du rachat ;",
        "- L'option choisie entre le PFU et le barème progressif de l'impôt sur le revenu.",
        "Pour les contrats souscrits avant le 27 septembre 2017, des règles transitoires peuvent s'appliquer. Pour les contrats souscrits depuis cette date, le régime du PFU s'applique de plein droit, avec une option possible pour le barème progressif.",
        "Il est important de noter que la fiscalité s'applique au moment du rachat, et non pendant la phase d'épargne. Tant que l'épargnant n'effectue pas de rachat, les gains sont capitalisés dans le contrat sans imposition, ce qui permet un effet de composition avantageux.",
      ],
    },
    {
      id: 'rachat-avant-8-ans',
      title: "Rachat avant 8 ans : PFU et option pour le barème progressif",
      level: 'h2',
      type: 'normal',
      content: [
        "En cas de rachat avant 8 ans de détention du contrat, les gains sont soumis au prélèvement forfaitaire unique (PFU) au taux de 12,8 % (hors prélèvements sociaux). Ce taux s'applique de plein droit, sans abattement.",
        "Le contribuable peut toutefois opter pour le barème progressif de l'impôt sur le revenu si cette option lui est plus favorable. L'option pour le barème progressif est globale : elle s'applique à l'ensemble des revenus de capitaux mobiliers et des plus-values de cession de valeurs mobilières pour l'année concernée.",
        "Le taux d'imposition effectif dans le cadre du barème progressif dépend de la TMI du contribuable. Pour un contribuable à 30 % de TMI, le taux d'imposition sur les gains est de 30 %, ce qui est moins avantageux que le PFU à 12,8 %. En revanche, pour un contribuable à 0 % ou 11 % de TMI, le barème progressif peut être plus favorable.",
        "Avant 4 ans de détention, le taux d'imposition est identique à celui applicable entre 4 et 8 ans : il n'existe pas de différence fiscale entre ces deux périodes pour les rachats. En revanche, le régime change significativement après 8 ans avec l'application d'un abattement annuel.",
        "Il est donc déconseillé d'effectuer un rachat avant 8 ans sauf nécessité impérieuse, car la fiscalité est moins favorable qu'après 8 ans (absence d'abattement et taux d'imposition potentiellement plus élevé).",
      ],
    },
    {
      id: 'rachat-apres-8-ans',
      title: "Rachat après 8 ans : abattement annuel et taux réduit",
      level: 'h2',
      type: 'normal',
      content: [
        "Après 8 ans de détention, le régime fiscal de l'assurance-vie devient plus favorable avec l'application d'un abattement annuel sur les gains soumis à l'impôt sur le revenu. Cet abattement est de 4 600 € par an pour une personne seule et de 9 200 € par an pour un couple soumis à imposition commune.",
        "Au-delà de cet abattement, les gains sont imposés à un taux réduit de 7,5 % (dans la limite des primes versées, avec des modalités spécifiques selon la date de souscription). Pour les contrats de plus de 8 ans, les gains peuvent également être soumis au barème progressif sur option.",
        "L'abattement annuel est un avantage fiscal considérable : il permet à un célibataire de réaliser jusqu'à 4 600 € de gains par an sans impôt sur le revenu, et jusqu'à 9 200 € pour un couple. Cet abattement se reconstitue chaque année, ce qui permet d'optimiser les rachats en les étalant dans le temps.",
        "Exemple : un couple marié dispose d'un contrat d'assurance-vie de plus de 8 ans avec 50 000 € de gains. S'il effectue un rachat partiel de 50 000 € (dont 20 000 € de gains), l'abattement de 9 200 € s'applique. Seuls 10 800 € de gains sont soumis à l'impôt au taux de 7,5 %, soit 810 € d'impôt sur le revenu.",
        "Il est important de comprendre que l'abattement s'applique sur l'impôt sur le revenu uniquement. Les prélèvements sociaux (17,2 %) restent dus sur la totalité des gains, sans abattement, quel que soit l'âge du contrat.",
      ],
    },
    {
      id: 'prelevements-sociaux',
      title: 'Prélèvements sociaux : 17,2 % sur la totalité des gains',
      level: 'h2',
      type: 'normal',
      content: [
        "Les prélèvements sociaux au taux de 17,2 % s'appliquent sur la totalité des gains réalisés lors d'un rachat, quel que soit l'âge du contrat et quelle que soit la durée de détention. Ils sont prélevés directement par l'assureur au moment du rachat.",
        "Ce taux de 17,2 % se décompose comme suit : 9,2 % de contribution sociale généralisée (CSG), 0,5 % de contribution au remboursement de la dette sociale (CRDS), et 7,5 % de prélèvement de solidarité. La CSG est partiellement déductible du revenu imposable à hauteur de 6,8 % (pour les revenus de capitaux mobiliers).",
        "Les prélèvements sociaux s'appliquent uniquement sur les gains, jamais sur le capital. Ils sont calculés sur la différence entre la valeur de rachat et le total des primes versées (pour un rachat total) ou au prorata pour un rachat partiel.",
        "Contrairement à l'impôt sur le revenu, les prélèvements sociaux ne bénéficient d'aucun abattement, même après 8 ans de détention. Ils sont dus dans tous les cas, sans exception, sur la totalité des gains.",
        "Pour les contrats détenus dans le cadre d'une assurance-vie luxembourgeoise, des règles spécifiques peuvent s'appliquer concernant le prélèvement des prélèvements sociaux, selon que le contrat est ou non rapatrié fiscalement en France.",
      ],
    },
    {
      id: 'tableau-rachats',
      title: 'Tableau récapitulatif de la fiscalité des rachats',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous récapitule la fiscalité applicable aux rachats d\'assurance-vie selon la durée de détention et l\'option choisie.',
      ],
      table: {
        headers: ['Durée de détention', 'Régime par défaut', 'Option barème progressif', 'Abattement annuel IR', 'Prélèvements sociaux'],
        rows: [
          ['Moins de 8 ans', 'PFU : 12,8 % sur les gains', 'TMI applicable (0 % à 45 %)', 'Aucun', '17,2 % sur tous les gains'],
          ['Plus de 8 ans (célibataire)', '7,5 % sur les gains après abattement', 'TMI applicable après abattement', '4 600 €', '17,2 % sur tous les gains'],
          ['Plus de 8 ans (couple)', '7,5 % sur les gains après abattement', 'TMI applicable après abattement', '9 200 €', '17,2 % sur tous les gains'],
        ],
      },
    },
    {
      id: 'transmission-avant-70-ans',
      title: 'Transmission avant 70 ans : abattement de 152 500 € par bénéficiaire',
      level: 'h2',
      type: 'normal',
      content: [
        "L'un des avantages fiscaux les plus puissants de l'assurance-vie concerne la transmission des capitaux aux bénéficiaires désignés. Pour les primes versées avant les 70 ans de l'assuré, chaque bénéficiaire bénéficie d'un abattement de 152 500 € sur les capitaux reçus (capital + gains).",
        "Au-delà de cet abattement, les capitaux sont soumis à un prélèvement spécifique de 20 % sur la fraction comprise entre 152 500 € et 852 500 €, et de 31,25 % au-delà de 852 500 €. Ce prélèvement est nettement inférieur aux droits de succession applicables en ligne directe (qui peuvent atteindre 45 %) ou entre frères et sœurs (jusqu'à 55 %).",
        "Les gains générés par le contrat sont totalement exonérés de droits de succession pour la part inférieure à l'abattement. C'est un avantage considérable par rapport à la transmission d'actifs financiers classiques (comptes-titres, livrets) qui sont intégralement soumis aux droits de succession.",
        "Le bénéfice de cet avantage suppose que le contrat ait été correctement désigné avec une clause bénéficiaire en bonne et due forme. En l'absence de clause bénéficiaire ou en cas de clause mal rédigée, les capitaux tombent dans la succession et sont soumis au droit commun des successions.",
        "Il est essentiel de noter que cet abattement s'applique par bénéficiaire et non par contrat. Un assuré disposant de plusieurs contrats d'assurance-vie peut cumuler les abattements pour chaque bénéficiaire, dans la limite de 152 500 € par bénéficiaire tous contrats confondus.",
      ],
    },
    {
      id: 'transmission-apres-70-ans',
      title: 'Transmission après 70 ans : abattement global de 30 500 €',
      level: 'h2',
      type: 'normal',
      content: [
        "Pour les primes versées après les 70 ans de l'assuré, le régime fiscal de transmission est différent et moins avantageux. Un abattement global de 30 500 € s'applique sur l'ensemble des primes versées après 70 ans, tous contrats confondus, quel que soit le nombre de bénéficiaires.",
        "Au-delà de cet abattement, les primes versées après 70 ans sont soumises aux droits de succession au taux applicable selon le lien de parenté avec le bénéficiaire. Les gains générés par ces primes sont exonérés de droits de succession.",
        "Ce régime moins favorable incite les souscripteurs à constituer leur épargne et à désigner leurs bénéficiaires avant 70 ans pour optimiser la transmission. Il est généralement recommandé d'effectuer les versements importants avant cet âge clé.",
        "Pour les contrats multisupports, il est important de distinguer les primes versées avant et après 70 ans, car les règles fiscales applicables à la transmission diffèrent selon la date de versement de chaque prime.",
        "La gestion de la transmission après 70 ans nécessite une stratégie patrimoniale spécifique, qui peut inclure le recours à d'autres outils (donation, démembrement) pour optimiser la transmission globale du patrimoine.",
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : rachat partiel après 8 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "Prenons l'exemple d'un couple marié (M. et Mme Martin) qui dispose d'un contrat d'assurance-vie souscrit il y a 12 ans. Ils ont versé 150 000 € sur le contrat, qui vaut aujourd'hui 210 000 € (soit 60 000 € de gains).",
        "Ils souhaitent effectuer un rachat partiel de 50 000 € pour financer des travaux dans leur résidence principale. Le contrat ayant plus de 8 ans, ils bénéficient d'un abattement annuel de 9 200 €.",
        "Calcul de la part de gains dans le rachat : (50 000 € × 60 000 €) / 210 000 € = 14 286 € de gains inclus dans le rachat.",
        "Impôt sur le revenu : après abattement de 9 200 €, il reste 14 286 € - 9 200 € = 5 086 € de gains imposables au taux réduit de 7,5 %, soit 381 € d'impôt sur le revenu.",
        "Prélèvements sociaux : 14 286 € × 17,2 % = 2 457 €.",
        "Total des prélèvements : 381 € + 2 457 € = 2 838 €.",
        "Net perçu par le couple : 50 000 € - 2 838 € = 47 162 €.",
        "Cet exemple montre l'avantage de l'abattement annuel après 8 ans. Sans cet abattement, l'impôt sur le revenu aurait été de 14 286 € × 7,5 % = 1 071 € au lieu de 381 €. Ces chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes avec la fiscalité de l\'assurance-vie',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que plusieurs erreurs reviennent régulièrement chez les épargnants concernant la fiscalité de l\'assurance-vie :'],
      listItems: [
        'Croire que l\'assurance-vie est totalement exonérée d\'impôt : les gains sont imposables, seuls le capital est exonéré.',
        'Confondre l\'abattement après 8 ans (4 600/9 200 € sur l\'IR) avec une exonération totale : les prélèvements sociaux restent dus sur la totalité des gains.',
        'Penser que l\'abattement de 4 600 € s\'applique aux prélèvements sociaux : il ne s\'applique qu\'à l\'impôt sur le revenu.',
        'Effectuer un rachat avant 8 ans sans nécessité impérieuse, ce qui fait perdre le bénéfice de l\'abattement et du taux réduit.',
        'Oublier de déclarer les rachats aux impôts : l\'assureur transmet les informations mais le contribuable doit vérifier sa déclaration.',
        'Négliger la clause bénéficiaire : en l\'absence de clause ou avec une clause mal rédigée, les capitaux peuvent être soumis aux droits de succession.',
        'Ne pas optimiser l\'étalement des rachats après 8 ans pour maximiser l\'abattement annuel.',
        'Confondre le régime fiscal des contrats souscrits avant et après le 27 septembre 2017.',
        'Oublier que le PFU (12,8 %) et les prélèvements sociaux (17,2 %) sont deux prélèvements distincts qui se cumulent.',
        'Ignorer la déductibilité partielle de la CSG (6,8 %) pour les contrats soumis au barème progressif.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance sur la fiscalité de l\'assurance-vie',
      level: 'h2',
      type: 'risk',
      content: [
        'La fiscalité de l\'assurance-vie comporte des subtilités qu\'il est essentiel de connaître pour éviter les mauvaises surprises.',
      ],
      listItems: [
        'Les frais de gestion du contrat réduisent les gains et donc l\'impôt potentiel, mais ils réduisent aussi le rendement net du placement. Il convient de choisir un contrat avec des frais compétitifs.',
        'Les arbitrages entre fonds en euros et unités de compte peuvent générer des plus-values imposables s\'ils sont réalisés sur un contrat soumis au PFU. Sur les contrats anciens, certains arbitrages peuvent être exonérés.',
        'La clause bénéficiaire doit être régulièrement mise à jour pour tenir compte des changements de situation familiale (mariage, divorce, décès, naissance).',
        'Les contrats d\'assurance-vie luxembourgeois peuvent offrir des avantages fiscaux supplémentaires mais nécessitent une analyse spécifique et sont soumis à des règles déclaratives particulières.',
        'L\'assurance-vie n\'est pas un outil de défiscalisation à court terme : son avantage fiscal se déploie sur le long terme (après 8 ans).',
        'En cas de rachat partiel, la fiscalité s\'applique proportionnellement à la part de gains dans le rachat. Il est important de bien comprendre ce mécanisme avant d\'effectuer un rachat.',
        'Les règles fiscales de l\'assurance-vie peuvent évoluer. Il convient de suivre les réformes fiscales et d\'adapter sa stratégie en conséquence.',
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour optimiser la fiscalité de l\'assurance-vie',
      level: 'h2',
      type: 'method-steps',
      content: [
        'L\'optimisation de la fiscalité de l\'assurance-vie suit une méthode structurée en 6 étapes, dans le respect du cadre réglementaire des CGP-CIF.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation patrimoniale et fiscale', description: 'Recensement complet des contrats existants, des versements effectués, des gains accumulés, de la date de souscription, de la clause bénéficiaire et de la situation familiale.' },
        { title: 'Évaluation des objectifs', description: 'Définition des objectifs de l\'assurance-vie : préparation de la retraite, transmission, épargne de précaution, optimisation fiscale. Chaque objectif oriente la stratégie de gestion.' },
        { title: 'Optimisation de la clause bénéficiaire', description: 'Vérification et rédaction d\'une clause bénéficiaire adaptée à la situation familiale. Mise à jour régulière en fonction des changements de situation (mariage, divorce, naissance, décès).' },
        { title: 'Planification des rachats', description: 'Établissement d\'un calendrier de rachats optimisé pour maximiser l\'abattement annuel après 8 ans, en fonction des besoins de trésorerie et des objectifs patrimoniaux.' },
        { title: 'Choix entre PFU et barème progressif', description: 'Simulation de l\'impôt dû selon l\'option choisie pour chaque année de rachat, en fonction de l\'ensemble des revenus du foyer fiscal.' },
        { title: 'Suivi et révision périodique', description: 'Révision régulière de la stratégie en fonction des évolutions fiscales, des changements de situation personnelle et des performances des supports. Documentation complète des recommandations.' },
      ],
    },
    {
      id: 'faq',
      title: 'Questions fréquentes sur la fiscalité de l\'assurance-vie',
      level: 'h2',
      type: 'faq',
      content: ['Retrouvez les réponses aux questions les plus fréquentes concernant la fiscalité de l\'assurance-vie.'],
      listItems: [
        'Quels sont les gains imposables dans un contrat d\'assurance-vie ?',
        'Comment est calculé l\'abattement annuel après 8 ans ?',
        'Le rachat avant 8 ans est-il toujours fiscalement désavantageux ?',
        'Quelle différence entre PFU et barème progressif ?',
        'Les prélèvements sociaux sont-ils dus sur tous les rachats ?',
        'Comment sont imposés les rachats partiels ?',
        'Quel est l\'avantage fiscal de la transmission avant 70 ans ?',
        'Que se passe-t-il en cas de décès sans clause bénéficiaire ?',
        'Peut-on cumuler plusieurs contrats pour optimiser la transmission ?',
        'L\'assurance-vie est-elle utile pour un non-imposable ?',
      ],
    },
  ],
  faq: [
    { question: 'Quels sont les gains imposables dans un contrat d\'assurance-vie ?', answer: 'Les gains imposables sont les intérêts, les plus-values et les dividendes générés par le contrat, correspondant à la différence entre la valeur de rachat et le total des primes versées. Le capital n\'est jamais imposé.' },
    { question: 'Comment est calculé l\'abattement annuel après 8 ans ?', answer: 'L\'abattement est de 4 600 € par an pour une personne seule et de 9 200 € par an pour un couple soumis à imposition commune. Il s\'applique uniquement à l\'impôt sur le revenu (pas aux prélèvements sociaux) et se reconstitue chaque année.' },
    { question: 'Le rachat avant 8 ans est-il toujours fiscalement désavantageux ?', answer: 'Le rachat avant 8 ans est moins avantageux qu\'après 8 ans car il ne bénéficie ni de l\'abattement annuel ni du taux réduit à 7,5 %. Toutefois, il peut être justifié dans certains cas (besoin de trésorerie important, opportunité d\'investissement).' },
    { question: 'Quelle différence entre PFU et barème progressif ?', answer: 'Le PFU (prélèvement forfaitaire unique) est un taux fixe de 12,8 % sur les gains. Le barème progressif est le taux de la TMI (0 % à 45 %). L\'option pour le barème progressif est intéressante lorsque la TMI est inférieure à 12,8 %.' },
    { question: 'Les prélèvements sociaux sont-ils dus sur tous les rachats ?', answer: 'Oui, les prélèvements sociaux de 17,2 % sont dus sur la totalité des gains, quel que soit l\'âge du contrat, la durée de détention ou le montant du rachat. Aucun abattement ne s\'applique.' },
    { question: 'Comment sont imposés les rachats partiels ?', answer: 'Lors d\'un rachat partiel, la part de gains est calculée proportionnellement au montant du rachat par rapport à la valeur totale du contrat. Seule cette part de gains est soumise à l\'impôt et aux prélèvements sociaux.' },
    { question: 'Quel est l\'avantage fiscal de la transmission avant 70 ans ?', answer: 'Chaque bénéficiaire désigné bénéficie d\'un abattement de 152 500 € sur les capitaux reçus. Au-delà, un prélèvement de 20 % ou 31,25 % s\'applique, ce qui reste inférieur aux droits de succession classiques.' },
    { question: 'Que se passe-t-il en cas de décès sans clause bénéficiaire ?', answer: 'En l\'absence de clause bénéficiaire ou avec une clause mal rédigée, les capitaux de l\'assurance-vie tombent dans la succession et sont soumis au droit commun des successions, sans bénéficier des abattements spécifiques.' },
    { question: 'Peut-on cumuler plusieurs contrats pour optimiser la transmission ?', answer: 'Oui, l\'abattement de 152 500 € s\'applique par bénéficiaire, tous contrats confondus. Disposer de plusieurs contrats peut permettre d\'optimiser la répartition des capitaux entre bénéficiaires et d\'utiliser pleinement les abattements.' },
    { question: 'L\'assurance-vie est-elle utile pour un non-imposable ?', answer: 'Oui, l\'assurance-vie reste utile même pour un non-imposable, notamment pour la transmission (abattement de 152 500 € par bénéficiaire) et pour la capitalisation des gains sans imposition pendant la durée du contrat.' },
  ],
  ctaTitle: 'Vous souhaitez optimiser la fiscalité de votre assurance-vie ?',
  ctaText: 'Un échange personnalisé permet d\'analyser votre contrat, d\'optimiser vos rachats et votre transmission. Eric Bellaiche, CGP-CIF, vous accompagne dans la gestion de votre assurance-vie.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie : comment choisir', position: 'inline' },
    { href: '/articles/assurance-vie-apres-70-ans/', label: 'Assurance-vie après 70 ans : fiscalité et stratégies', position: 'inline' },
    { href: '/articles/scpi-assurance-vie-ou-direct/', label: 'SCPI en direct ou via assurance-vie', position: 'inline' },
    { href: '/articles/transmission-patrimoine-famille-recomposee/', label: 'Transmission du patrimoine en famille recomposée', position: 'inline' },
  ],
  complianceNotes: [
    'Les simulations présentées sont basées sur des hypothèses fiscales en vigueur au 11 juin 2026 et ne préjugent pas des évolutions futures.',
    'Ce contenu est fourni à titre d\'information générale et ne constitue pas un conseil personnalisé.',
  ],
  hasRisks: false,
};

export default article;
