import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'assurance-vie-apres-70-ans',
  category: 'assurance-vie',
  title: 'Assurance-vie après 70 ans : fiscalité, succession et stratégies patrimoniales',
  metaTitle: 'Assurance-vie après 70 ans : fiscalité, succession et stratégies patrimoniales',
  metaDescription: 'Les versements sur une assurance-vie après 70 ans changent les règles fiscales de succession : abattement global de 30 500 €, droits de succession au-delà, exonération des gains. Analyse et stratégies par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/assurance-vie-apres-70-ans/',
  badge: 'Assurance-vie &bull; 70 ans &bull; Succession &bull; Fiscalité &bull; Transmission &bull; CGP-CIF',
  intro: 'L\'assurance-vie après 70 ans est souvent perçue comme moins avantageuse fiscalement qu\'avant cet âge clé. Cette perception est en partie exacte, mais la réalité est plus nuancée. Si l\'abattement successoral passe de 152 500 € par bénéficiaire à un abattement global de 30 500 € tous contrats confondus, les gains restent exonérés de droits de succession. En fonction de la situation patrimoniale, des objectifs de transmission et de l\'espérance de vie, continuer à alimenter son contrat après 70 ans peut encore être pertinent. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous détaille la fiscalité applicable après 70 ans et les stratégies patrimoniales à envisager.',
  shortAnswer: 'Après 70 ans, les primes versées sur un contrat d\'assurance-vie bénéficient d\'un régime fiscal spécifique pour la transmission. Un abattement global de 30 500 € s\'applique sur l\'ensemble des primes versées après 70 ans, tous contrats confondus, quel que soit le nombre de bénéficiaires. Au-delà de cet abattement, les primes sont soumises aux droits de succession au taux applicable selon le lien de parenté avec le bénéficiaire. En revanche, les gains générés par ces primes sont exonérés de droits de succession. Le capital déjà présent sur le contrat avant 70 ans conserve son régime antérieur plus favorable (abattement de 152 500 € par bénéficiaire). Il est donc possible de conserver un contrat existant après 70 ans sans perdre les avantages acquis. Il est également possible d\'effectuer de nouveaux versements après 70 ans dans une optique de transmission, mais l\'avantage fiscal est moins important.',
  summaryItems: [
    { label: 'Le changement de régime fiscal à 70 ans', anchor: 'changement-regime-70-ans' },
    { label: 'Abattement global de 30 500 € : comment ça marche', anchor: 'abattement-global' },
    { label: 'Gains exonérés de droits de succession après 70 ans', anchor: 'gains-exoneres' },
    { label: 'Distinction entre primes avant et après 70 ans', anchor: 'distinction-avant-apres' },
    { label: 'Tableau comparatif : avant et après 70 ans', anchor: 'tableau-comparatif' },
    { label: 'Stratégies patrimoniales après 70 ans', anchor: 'strategies-apres-70-ans' },
    { label: 'Exemple pédagogique : transmission après 70 ans', anchor: 'exemple-pedagogique' },
    { label: 'Erreurs fréquentes avec l\'assurance-vie après 70 ans', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour optimiser après 70 ans', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 19,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['assurance-vie', '70 ans', 'succession', 'fiscalité', 'transmission', 'droits de succession', 'CGP-CIF'],
  sections: [
    {
      id: 'changement-regime-70-ans',
      title: 'Le changement de régime fiscal à 70 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "Le passage à 70 ans constitue un seuil fiscal important pour l'assurance-vie. À partir de cet âge, le régime fiscal applicable aux nouveaux versements change pour la transmission, tandis que les primes déjà versées avant 70 ans conservent leur régime antérieur.",
        "Ce changement est prévu par l'article 990 I du Code général des impôts. Il vise à encadrer les versements effectués à un âge avancé, lorsque l'objectif de transmission devient prépondérant par rapport à l'objectif d'épargne.",
        "Concrètement, à partir du 70e anniversaire de l'assuré, les primes versées sur l'ensemble de ses contrats d'assurance-vie sont soumises à un régime fiscal spécifique pour la transmission. Ce régime est moins avantageux que celui applicable avant 70 ans, mais il conserve des avantages non négligeables.",
        "Il est important de noter que ce changement ne remet pas en cause le régime fiscal des primes versées avant 70 ans. Les capitaux correspondant à ces primes conservent leur régime antérieur, avec un abattement de 152 500 € par bénéficiaire. Seules les primes versées après 70 ans sont concernées par le nouveau régime.",
        "La date retenue pour le calcul est celle du 70e anniversaire de l'assuré, et non la date de souscription du contrat. Un contrat souscrit après 70 ans est donc intégralement soumis au régime des versements après 70 ans.",
        "Pour les contrats souscrits avant 70 ans et toujours en cours après 70 ans, il est essentiel de distinguer comptablement les primes versées avant et après 70 ans, car le régime fiscal applicable à la transmission diffère selon la date de chaque versement.",
      ],
    },
    {
      id: 'abattement-global',
      title: "Abattement global de 30 500 € : comment ça fonctionne",
      level: 'h2',
      type: 'normal',
      content: [
        "L'abattement global de 30 500 € est l'une des caractéristiques principales du régime fiscal de l'assurance-vie après 70 ans. Contrairement à l'abattement avant 70 ans qui est individuel par bénéficiaire (152 500 € chacun), l'abattement après 70 ans est global et unique pour l'ensemble des bénéficiaires.",
        "Cet abattement de 30 500 € s'applique sur le total des primes versées après 70 ans, tous contrats d'assurance-vie confondus. Il est réparti entre les bénéficiaires au prorata des primes reçues par chacun. Si un assuré a versé 100 000 € après 70 ans à répartir entre deux bénéficiaires, l'abattement de 30 500 € est réparti proportionnellement.",
        "Au-delà de cet abattement, les primes sont soumises aux droits de succession au taux applicable selon le lien de parenté entre l'assuré et le bénéficiaire :",
        "- Conjoint ou partenaire de Pacs : exonération totale de droits de succession (cette exonération s'applique également aux primes versées après 70 ans) ;",
        "- Enfants : abattement de 100 000 € par enfant (qui se cumule avec l'abattement de 30 500 €) puis taxation au barème des droits de succession en ligne directe (5 % à 45 %) ;",
        "- Frères et sœurs : abattement de 15 932 € puis taxation de 35 % à 45 % ;",
        "- Neveux et nièces : abattement de 7 967 € puis taxation à 55 % ;",
        "- Personnes sans lien de parenté : abattement de 1 594 € puis taxation à 60 %.",
        "Il est essentiel de comprendre que cet abattement s'applique sur les primes, et non sur les capitaux reçus par les bénéficiaires. Cela signifie que les gains générés par les primes versées après 70 ans sont exonérés de droits de succession, ce qui constitue un avantage fiscal important.",
      ],
    },
    {
      id: 'gains-exoneres',
      title: 'Gains exonérés de droits de succession après 70 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "Si le régime des primes versées après 70 ans est moins favorable qu'avant 70 ans, un avantage fiscal important subsiste : les gains générés par ces primes sont totalement exonérés de droits de succession.",
        "Cela signifie que seules les primes elles-mêmes sont soumises au régime fiscal de la transmission après 70 ans. Les intérêts, plus-values et dividendes générés par ces primes bénéficient d'une exonération totale de droits de succession, quel que soit leur montant.",
        "Cet avantage est particulièrement significatif pour les contrats à dominante d'unités de compte, où le potentiel de gains est plus élevé (mais aussi le risque). Plus le contrat performe, plus l'exonération des gains est avantageuse pour les bénéficiaires.",
        "Exemple : un assuré verse 50 000 € après 70 ans. Au moment de son décès, ces 50 000 € sont devenus 70 000 € grâce aux gains. Seuls les 50 000 € de primes sont soumis au régime fiscal de la transmission après 70 ans (après abattement). Les 20 000 € de gains sont exonérés.",
        "Cette exonération des gains constitue une différence fondamentale avec la transmission d'autres actifs financiers (comptes-titres, épargne salariale) qui sont intégralement soumis aux droits de succession, sans exonération des plus-values.",
      ],
    },
    {
      id: 'distinction-avant-apres',
      title: 'Distinction entre primes avant et après 70 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "Pour un contrat d'assurance-vie souscrit avant 70 ans et toujours en cours après 70 ans, les primes versées avant et après 70 ans sont soumises à des régimes fiscaux distincts pour la transmission.",
        "Les primes versées avant 70 ans conservent leur régime antérieur : chaque bénéficiaire bénéficie d'un abattement de 152 500 € sur les capitaux reçus (capital + gains), avec un prélèvement de 20 % jusqu'à 852 500 € et 31,25 % au-delà.",
        "Les primes versées après 70 ans sont soumises au régime spécifique : abattement global de 30 500 € tous contrats confondus, puis droits de succession au taux applicable selon le lien de parenté.",
        "Cette distinction a des conséquences pratiques importantes. Lors du décès de l'assuré, l'assureur doit établir un décompte séparé des primes versées avant et après 70 ans pour déterminer le régime fiscal applicable à chaque partie du capital.",
        "Pour l'épargnant, il est essentiel de connaître la répartition des primes sur ses contrats pour anticiper la fiscalité de la transmission. Un contrat alimenté principalement avant 70 ans offrira un avantage successoral plus important qu'un contrat alimenté après 70 ans.",
        "Il est également possible d'ouvrir un nouveau contrat après 70 ans. Dans ce cas, la totalité des primes versées sur ce nouveau contrat sera soumise au régime des versements après 70 ans, mais les gains resteront exonérés de droits de succession.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif : avant et après 70 ans',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous compare les régimes fiscaux de l\'assurance-vie pour la transmission, avant et après 70 ans.',
      ],
      table: {
        headers: ['Critère', 'Avant 70 ans', 'Après 70 ans'],
        rows: [
          ['Abattement', '152 500 € par bénéficiaire', '30 500 € global (tous contrats, tous bénéficiaires)'],
          ['Assiette de l\'abattement', 'Capitaux (primes + gains)', 'Primes uniquement'],
          ['Au-delà de l\'abattement', 'Prélèvement de 20 % (jusqu\'à 852 500 €) puis 31,25 %', 'Droits de succession selon lien de parenté'],
          ['Gains', 'Inclus dans l\'abattement, puis taxés au prélèvement spécifique', 'Exonérés de droits de succession'],
          ['Conjoint/Pacs', 'Exonération totale', 'Exonération totale'],
          ['Enfants', 'Abattement 152 500 € + prélèvement 20-31,25 % ou droits succession', 'Abattement 30 500 € + abattement 100 000 € + barème successoral'],
          ['Pluralité de contrats', 'Abattement par bénéficiaire, tous contrats confondus', 'Abattement global unique, tous contrats confondus'],
        ],
      },
    },
    {
      id: 'strategies-apres-70-ans',
      title: 'Stratégies patrimoniales après 70 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "Malgré un régime fiscal moins favorable, plusieurs stratégies patrimoniales peuvent être envisagées pour l'assurance-vie après 70 ans.",
        "Conserver un contrat existant sans nouveaux versements : c'est la stratégie la plus simple. Les primes déjà versées avant 70 ans conservent leur régime favorable (152 500 € par bénéficiaire). Le contrat continue de fonctionner normalement avec gestion des arbitrages et rachats possibles.",
        "Effectuer des versements après 70 ans dans une optique de donation : plutôt que de verser sur l'assurance-vie, il peut être plus avantageux d'effectuer des donations directes aux enfants (donations de sommes d'argent, donations de titres) qui bénéficient d'abattements spécifiques renouvelables tous les 15 ans.",
        "Utiliser l'assurance-vie comme outil de transmission pour les bénéficiaires non héritiers : l'assurance-vie permet de transmettre des capitaux à des bénéficiaires qui ne sont pas héritiers réservataires (concubin, ami, association) avec une fiscalité potentiellement plus avantageuse que les droits de succession classiques.",
        "Ouvrir un nouveau contrat après 70 ans avec une stratégie de croissance : puisque les gains sont exonérés de droits de succession, un contrat orienté vers les unités de compte (potentiel de croissance plus élevé) peut être intéressant, malgré le risque associé.",
        "Combiner assurance-vie et donation temporaire d'usufruit : cette technique permet de transmettre des capitaux à des bénéficiaires tout en conservant les revenus sa vie durant. Elle peut être utilisée en complément de l'assurance-vie.",
        "Il est recommandé de consulter un CGP-CIF pour déterminer la stratégie la plus adaptée à sa situation personnelle, car les arbitrages entre assurance-vie, donation et autres outils patrimoniaux dépendent de nombreux paramètres (âge, état de santé, composition de la famille, objectifs).",
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : transmission après 70 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "Prenons l'exemple de M. Dupont, décédé à 82 ans, qui avait souscrit un contrat d'assurance-vie à 60 ans. Il a versé 200 000 € avant 70 ans et 80 000 € après 70 ans. Les bénéficiaires sont ses deux enfants. Au moment du décès, le contrat vaut 350 000 € (dont 280 000 € de primes et 70 000 € de gains).",
        "Traitement fiscal des primes versées avant 70 ans (200 000 €) :",
        "- Abattement : 152 500 € par enfant, soit 305 000 € au total pour les deux enfants ;",
        "- Les 200 000 € de primes + les gains associés (calculés au prorata : (200 000/280 000) × 70 000 € = 50 000 €) sont dans la limite de l'abattement de 152 500 € par enfant ;",
        "- Aucun droit n'est dû sur cette partie si chaque enfant reçoit moins de 152 500 € au titre des primes versées avant 70 ans.",
        "Traitement fiscal des primes versées après 70 ans (80 000 €) :",
        "- Abattement global de 30 500 € à répartir entre les deux enfants ;",
        "- Base imposable : 80 000 € - 30 500 € = 49 500 € ;",
        "- Chaque enfant est imposé sur sa part (24 750 € chacun) au barème des droits de succession en ligne directe ;",
        "- Les gains associés aux primes versées après 70 ans (20 000 € calculés au prorata) sont exonérés de droits de succession.",
        "Résultat : les enfants reçoivent 350 000 € avec une imposition limitée à environ 3 000 à 5 000 € de droits de succession sur la part des primes versées après 70 ans excédant l'abattement.",
        "Cet exemple montre l'importance de la distinction entre primes avant et après 70 ans, et l'avantage fiscal dont bénéficient encore les héritiers malgré le régime spécifique applicable après 70 ans. Ces chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes avec l\'assurance-vie après 70 ans',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que plusieurs erreurs reviennent régulièrement concernant l\'assurance-vie après 70 ans :'],
      listItems: [
        'Croire que tous les avantages fiscaux disparaissent après 70 ans : les gains restent exonérés de droits de succession et les primes avant 70 ans conservent leur régime favorable.',
        'Confondre abattement global et abattement par bénéficiaire : après 70 ans, l\'abattement de 30 500 € est global, pas individuel.',
        'Penser qu\'il ne faut plus rien verser après 70 ans : selon les objectifs, des versements après 70 ans peuvent encore être pertinents, notamment pour les bénéficiaires non héritiers.',
        'Oublier que les primes versées avant 70 ans conservent leur régime antérieur, même après 70 ans.',
        'Négliger l\'option de donation en complément de l\'assurance-vie pour optimiser la transmission globale.',
        'Ne pas mettre à jour la clause bénéficiaire après 70 ans pour tenir compte des changements de situation familiale.',
        'Ignorer l\'exonération des gains après 70 ans : c\'est un avantage fiscal important qui est souvent méconnu.',
        'Confondre la date du 70e anniversaire avec la date de souscription du contrat.',
        'Ouvrir un nouveau contrat après 70 ans sans avoir optimisé l\'utilisation des contrats existants ouverts avant 70 ans.',
        'Ne pas consulter un conseiller en gestion de patrimoine pour établir une stratégie de transmission après 70 ans adaptée à sa situation.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance pour l\'assurance-vie après 70 ans',
      level: 'h2',
      type: 'risk',
      content: [
        'L\'assurance-vie après 70 ans comporte des points de vigilance spécifiques qu\'il convient de connaître.',
      ],
      listItems: [
        'L\'abattement global de 30 500 € est rapidement atteint en cas de versements importants après 70 ans. Au-delà, la fiscalité successorale peut être significative, notamment pour les bénéficiaires éloignés (neveux, nièces, personnes sans lien de parenté).',
        'Pour le conjoint ou partenaire de Pacs, l\'exonération totale de droits de succession s\'applique quel que soit l\'âge de l\'assuré, ce qui rend l\'assurance-vie après 70 ans particulièrement intéressante pour protéger le conjoint survivant.',
        'Les contrats d\'assurance-vie luxembourgeois peuvent offrir des opportunités supplémentaires après 70 ans, mais nécessitent une analyse spécifique des implications fiscales et déclaratives.',
        'Si l\'objectif principal est la transmission, d\'autres outils (donation, démembrement, assurance-vie) peuvent être combinés pour optimiser la transmission globale du patrimoine.',
        'La désignation des bénéficiaires doit être précise et adaptée à la situation familiale. Une clause bénéficiaire standard peut ne pas être optimale.',
        'Les frais de gestion du contrat continuent de s\'appliquer après 70 ans. Il convient de vérifier que le contrat reste compétitif en termes de frais.',
        'En cas de donation au profit des enfants avant 70 ans, les sommes données sont sorties du patrimoine et ne sont pas soumises aux droits de succession, ce qui peut être plus avantageux que de les conserver sur un contrat d\'assurance-vie.',
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour optimiser l'assurance-vie après 70 ans",
      level: 'h2',
      type: 'method-steps',
      content: [
        "L'optimisation de l'assurance-vie après 70 ans suit une méthode structurée en 6 étapes, dans le respect du cadre réglementaire des CGP-CIF.",
      ],
      methodSteps: [
        { title: 'Bilan des contrats existants', description: 'Recensement complet des contrats, des primes versées avant et après 70 ans, des gains accumulés, de la clause bénéficiaire et de la situation familiale.' },
        { title: 'Analyse des objectifs de transmission', description: 'Identification des bénéficiaires souhaités, des objectifs de protection du conjoint, de transmission aux enfants ou à d\'autres personnes, et de la stratégie successorale globale.' },
        { title: 'Comparaison avec les alternatives patrimoniales', description: 'Mise en perspective de l\'assurance-vie après 70 ans avec d\'autres outils : donation (présente ou future), démembrement, PER, immobilier. Évaluation de la solution la plus adaptée.' },
        { title: 'Optimisation de la clause bénéficiaire', description: 'Rédaction d\'une clause bénéficiaire précise, adaptée à la situation familiale et aux objectifs de transmission. Prise en compte des spécificités des familles recomposées.' },
        { title: 'Décision sur les nouveaux versements', description: "Analyse de l'opportunité d'effectuer de nouveaux versements après 70 ans en fonction de l'espérance de vie, des objectifs et de la fiscalité applicable." },
        { title: 'Suivi et révision périodique', description: 'Révision régulière de la stratégie en fonction des évolutions familiales, législatives et patrimoniales. Documentation complète des recommandations et de la stratégie mise en place.' },
      ],
    },
    {
      id: 'faq',
      title: 'Questions fréquentes sur l\'assurance-vie après 70 ans',
      level: 'h2',
      type: 'faq',
      content: ['Retrouvez les réponses aux questions les plus fréquentes concernant l\'assurance-vie après 70 ans.'],
      listItems: [
        'Que devient l\'assurance-vie après 70 ans ?',
        'Quel est l\'abattement applicable après 70 ans ?',
        'Les gains sont-ils imposés après 70 ans ?',
        'Faut-il arrêter de verser après 70 ans ?',
        'Le conjoint est-il exonéré de droits après 70 ans ?',
        'La clause bénéficiaire doit-elle être modifiée après 70 ans ?',
        'Peut-on ouvrir un nouveau contrat après 70 ans ?',
        'Quelle est la différence avec les primes versées avant 70 ans ?',
        'Comment optimiser sa transmission après 70 ans ?',
        'Faut-il privilégier la donation à l\'assurance-vie après 70 ans ?',
      ],
    },
  ],
  faq: [
    { question: 'Que devient l\'assurance-vie après 70 ans ?', answer: 'Les contrats existants continuent de fonctionner normalement. Les primes versées avant 70 ans conservent leur régime fiscal favorable pour la transmission (abattement de 152 500 € par bénéficiaire). Les nouvelles primes versées après 70 ans sont soumises à un régime spécifique (abattement global de 30 500 €).' },
    { question: 'Quel est l\'abattement applicable après 70 ans ?', answer: 'Un abattement global de 30 500 € s\'applique sur l\'ensemble des primes versées après 70 ans, tous contrats d\'assurance-vie confondus. Cet abattement est unique pour tous les bénéficiaires, contrairement à l\'abattement avant 70 ans qui est individuel (152 500 € par bénéficiaire).' },
    { question: 'Les gains sont-ils imposés après 70 ans ?', answer: 'Non, les gains générés par les primes versées après 70 ans sont exonérés de droits de succession. Seules les primes elles-mêmes sont soumises au régime fiscal de la transmission après application de l\'abattement.' },
    { question: 'Faut-il arrêter de verser après 70 ans ?', answer: 'Pas nécessairement. Des versements après 70 ans peuvent encore être pertinents, notamment pour protéger le conjoint (exonération totale) ou pour transmettre à des bénéficiaires non héritiers. L\'opportunité dépend de la situation personnelle et des objectifs.' },
    { question: 'Le conjoint est-il exonéré de droits après 70 ans ?', answer: 'Oui, le conjoint survivant ou partenaire de Pacs bénéficie d\'une exonération totale de droits de succession sur les primes versées après 70 ans, comme sur la transmission de l\'assurance-vie en général.' },
    { question: 'La clause bénéficiaire doit-elle être modifiée après 70 ans ?', answer: 'Il est recommandé de vérifier et, si nécessaire, de mettre à jour la clause bénéficiaire après 70 ans pour tenir compte des changements de situation familiale (mariage, divorce, décès, naissance) et des objectifs de transmission.' },
    { question: 'Peut-on ouvrir un nouveau contrat après 70 ans ?', answer: 'Oui, il est possible d\'ouvrir un nouveau contrat d\'assurance-vie après 70 ans. La totalité des primes versées sera soumise au régime des versements après 70 ans, mais les gains resteront exonérés de droits de succession.' },
    { question: 'Quelle est la différence avec les primes versées avant 70 ans ?', answer: 'Les primes versées avant 70 ans bénéficient d\'un abattement de 152 500 € par bénéficiaire, avec un prélèvement spécifique au-delà (20 % ou 31,25 %). Les primes versées après 70 ans bénéficient d\'un abattement global de 30 500 €, avec application des droits de succession au-delà.' },
    { question: 'Comment optimiser sa transmission après 70 ans ?', answer: 'L\'optimisation passe par une analyse globale : bilan des contrats existants, comparaison avec la donation, ajustement de la clause bénéficiaire, et décision éclairée sur les nouveaux versements. Un CGP-CIF peut vous accompagner dans cette démarche.' },
    { question: 'Faut-il privilégier la donation à l\'assurance-vie après 70 ans ?', answer: 'La donation peut être plus avantageuse que l\'assurance-vie après 70 ans pour transmettre aux enfants, car elle bénéficie d\'abattements spécifiques (100 000 € par enfant) renouvelables tous les 15 ans. Le choix dépend de la situation personnelle et des objectifs patrimoniaux.' },
  ],
  ctaTitle: 'Vous souhaitez optimiser votre assurance-vie après 70 ans ?',
  ctaText: 'Un échange personnalisé permet d\'analyser votre situation, vos contrats et votre stratégie de transmission. Eric Bellaiche, CGP-CIF, vous accompagne dans l\'optimisation de votre patrimoine.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/assurance-vie-fiscalite/', label: 'Fiscalité de l\'assurance-vie', position: 'inline' },
    { href: '/articles/transmission-patrimoine-famille-recomposee/', label: 'Transmission du patrimoine en famille recomposée', position: 'inline' },
    { href: '/articles/structurer-son-patrimoine/', label: 'Structurer son patrimoine', position: 'inline' },
    { href: '/articles/scpi-assurance-vie-ou-direct/', label: 'SCPI en direct ou via assurance-vie', position: 'inline' },
  ],
  complianceNotes: [
    'Les simulations présentées sont basées sur des hypothèses fiscales en vigueur au 11 juin 2026 et ne préjugent pas des évolutions futures.',
    'Ce contenu est fourni à titre d\'information générale et ne constitue pas un conseil personnalisé.',
  ],
  hasRisks: false,
};

export default article;
