import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'audit-patrimonial-en-ligne',
  category: 'audit',
  title: 'Audit patrimonial en ligne : méthode, intérêt et points de vigilance',
  metaTitle: 'Audit patrimonial en ligne : méthode, intérêt et points de vigilance',
  metaDescription: "L'audit patrimonial permet d'obtenir une vision globale de sa situation : fiscalité, retraite, immobilier, transmission, placements, capacité de risque et objectifs. Eric Bellaiche, CGP-CIF ORIAS 13001580.",
  canonical: 'https://eric-bellaiche.fr/articles/audit-patrimonial-en-ligne/',
  badge: 'Audit patrimonial &bull; CGP-CIF &bull; ORIAS 13001580',
  intro: "Avant toute décision d'investissement patrimonial, une étape est trop souvent négligée : l'audit patrimonial. Pourtant, c'est elle qui permet de structurer une stratégie cohérente, d'identifier les leviers d'optimisation et d'éviter les décisions isolées. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, réalise des audits patrimoniaux en visioconférence pour vous accompagner dans cette démarche.",
  shortAnswer: "Un audit patrimonial est une analyse complète de votre situation : actifs immobiliers et financiers, passifs, fiscalité (IR, IFI, plus-values), retraite, prévoyance, transmission, capacité d'épargne, endettement et objectifs personnels. Il permet d'identifier les leviers d'optimisation et de structurer une stratégie cohérente, adaptée à votre profil. Réalisé en ligne, il est accessible depuis toute la France.",
  summaryItems: [
    { label: "Qu'est-ce qu'un audit patrimonial ?", anchor: 'quest-ce-quun-audit-patrimonial' },
    { label: 'Pourquoi faire un audit avant d\'investir', anchor: 'pourquoi-realiser' },
    { label: 'Ce qui est analysé dans un audit patrimonial', anchor: 'ce-qui-est-analyse' },
    { label: 'Tableau des sujets analysés', anchor: 'tableau-sujets' },
    { label: 'Audit patrimonial en ligne : avantages et limites', anchor: 'audit-en-ligne' },
    { label: 'Erreurs fréquentes sans audit préalable', anchor: 'erreurs-frequentes' },
    { label: 'Exemple pédagogique anonymisé', anchor: 'exemple-pedagogique' },
    { label: 'Méthode Eric Bellaiche pour l\'audit patrimonial', anchor: 'methode' },
    { label: 'Documents utiles à préparer', anchor: 'documents' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 13,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['audit patrimonial', 'bilan patrimonial', 'CGP-CIF', 'fiscalité', 'retraite', 'transmission', 'prévoyance', 'conseil patrimonial'],
  sections: [
    {
      id: 'quest-ce-quun-audit-patrimonial',
      title: "Qu'est-ce qu'un audit patrimonial ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Un audit patrimonial, également appelé bilan patrimonial, est une analyse complète et structurée de la situation financière, fiscale, immobilière et familiale d'une personne ou d'un couple. Il permet d'obtenir une vision d'ensemble du patrimoine et d'identifier les axes d'optimisation.",
        "L'audit est réalisé par un conseiller en gestion de patrimoine (CGP-CIF) qui recueille les données, analyse la situation et formalise des préconisations adaptées. Contrairement à une simple simulation en ligne, l'audit patrimonial prend en compte la globalité de la situation.",
        "Dans le cadre réglementaire des CGP-CIF, l'audit patrimonial respecte les obligations suivantes :",
        "- Analyse préalable de la situation du client avant toute recommandation ;",
        "- Évaluation des connaissances, de l'expérience, de la capacité de perte et de l'horizon de placement ;",
        "- Formalisation d'une déclaration d'adéquation en cas de recommandation ;",
        "- Aucune promesse de rendement ou de résultat.",
      ],
    },
    {
      id: 'pourquoi-realiser',
      title: "Pourquoi faire un audit avant d'investir ?",
      level: 'h2',
      type: 'normal',
      content: [
        'Investir sans vision d\'ensemble expose à des décisions isolées, parfois contradictoires. Les raisons de réaliser un audit patrimonial sont nombreuses :',
        "1. Avoir une vision globale : connaître précisément son patrimoine (actifs, passifs, liquidité, diversification) est le préalable à toute décision.",
        '2. Identifier les leviers fiscaux : TMI, IFI, plus-values, déficit foncier, chaque situation fiscale ouvre des opportunités spécifiques.',
        "3. Structurer une stratégie retraite : l'audit permet d'estimer le niveau de vie futur et d'identifier les enveloppes adaptées (PER, assurance-vie, immobilier).",
        '4. Anticiper la transmission : donation, succession, assurance-vie, chaque outil a des implications différentes.',
        '5. Optimiser les risques : évaluer sa capacité de perte, sa couverture prévoyance et son niveau d\'endettement.',
        "6. Éviter les erreurs : un investissement souscrit sans analyse préalable peut s'avérer inadapté, voire pénalisant.",
      ],
    },
    {
      id: 'ce-qui-est-analyse',
      title: 'Ce qui est analysé dans un audit patrimonial',
      level: 'h2',
      type: 'list',
      content: [
        'L\'audit patrimonial couvre l\'ensemble des dimensions financières, fiscales et personnelles :',
      ],
      listItems: [
        'Revenus : salaires, BNC, BIC, revenus fonciers, pensions, placements.',
        'Fiscalité : TMI, prélèvements sociaux, IFI, plus-values, déficits éventuels.',
        'Patrimoine immobilier : résidence principale, investissements locatifs, SCPI.',
        'Placements financiers : assurance-vie, PER, PEA, comptes-titres, livrets.',
        'Retraite : estimation des droits, écart de revenu potentiel, besoin de complément.',
        'Prévoyance : couverture décès, invalidité, arrêt de travail.',
        'Transmission : situation familiale, donation, succession, objectifs.',
        "Capacité d'épargne : revenus moins charges, capacité mensuelle à épargner.",
        'Endettement : crédits en cours, capacité d\'endettement restante, taux.',
        'Objectifs familiaux : projet d\'achat, éducation des enfants, départ en retraite, transmission.',
      ],
    },
    {
      id: 'tableau-sujets',
      title: 'Tableau : sujets analysés et impact patrimonial',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous synthétise les principaux sujets analysés lors d\'un audit patrimonial, les questions posées et l\'impact potentiel.',
      ],
      table: {
        headers: ['Sujet analysé', 'Question posée', 'Impact patrimonial'],
        rows: [
          ['Revenus', 'Sont-ils stables, croissants, variables ?', 'Détermine la capacité d\'épargne et le risque acceptable'],
          ['Fiscalité', 'Quelle est la TMI ? Y a-t-il un IFI ?', 'Oriente les choix d\'investissement et les enveloppes fiscales'],
          ['Immobilier', "Quelle part dans le patrimoine ? Quelle liquidité ?", "Évalue la diversification et l'exposition au risque immobilier"],
          ['Placements', 'Quels supports, quels frais, quelle performance ?', "Identifie les doublons, les frais excessifs, l'absence de diversification"],
          ['Retraite', "Quel est le taux de remplacement estimé ?", "Détermine le besoin d'épargne complémentaire"],
          ['Prévoyance', 'La couverture est-elle adaptée à la situation familiale ?', 'Évalue le risque financier en cas d\'aléa'],
          ['Transmission', "Quels objectifs, quels héritiers, quel âge ?", "Oriente le choix des outils (donation, AV, PER, SCI)"],
          ['Capacité d\'épargne', "Quel montant peut être épargné chaque mois ?", "Définit un plan d'épargne réaliste"],
          ['Endettement', "Quel est le taux d'endettement ?", "Détermine la capacité à souscrire un crédit"],
          ['Objectifs', "Quels sont les projets à 5, 10, 20 ans ?", "Structure la stratégie dans le temps"],
        ],
      },
    },
    {
      id: 'audit-en-ligne',
      title: 'Audit patrimonial en ligne : avantages et limites',
      level: 'h2',
      type: 'normal',
      content: [
        "L'audit patrimonial en ligne, réalisé en visioconférence, présente plusieurs avantages :",
        "- Accessibilité géographique : l'audit est réalisable depuis toute la France, sans déplacement.",
        "- Flexibilité : les rendez-vous peuvent être organisés à distance, en soirée ou le week-end.",
        '- Signature électronique : les documents peuvent être signés à distance.',
        '- Mêmes garanties réglementaires : le cadre CGP-CIF s\'applique quel que soit le mode de consultation.',
        "Points de vigilance :",
        "- L'audit en ligne nécessite une bonne préparation en amont (documents, questions).",
        "- L'échange en visioconférence doit être de qualité suffisante.",
        "- Certaines situations très complexes peuvent nécessiter un rendez-vous en présentiel.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes sans audit préalable',
      level: 'h2',
      type: 'list',
      content: ['De nombreux investisseurs commettent des erreurs faute d\'avoir réalisé un audit patrimonial préalable :'],
      listItems: [
        'Investir dans une SCPI sans vérifier la cohérence avec sa fiscalité personnelle.',
        "Souscrire une assurance-vie sans comparer les frais, les supports disponibles et l'adéquation avec ses objectifs.",
        'Ouvrir un PER sans anticiper la fiscalité de sortie et le besoin de liquidité.',
        'Acheter un bien immobilier locatif sans analyser l\'impact fiscal global.',
        "Négliger la prévoyance : décès, invalidité, arrêt de travail non couverts.",
        'Investir de manière redondante : plusieurs enveloppes avec les mêmes objectifs et les mêmes frais.',
        "Confondre capacité d'épargne et capacité d'investissement.",
        "Prendre une décision patrimoniale sous l'effet d'une opportunité sans vision d'ensemble.",
        'Ne pas anticiper la transmission, créant une situation fiscale défavorable pour les héritiers.',
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique anonymisé',
      level: 'h2',
      type: 'normal',
      content: [
        "Situation : un couple de 45 ans, deux enfants, TMI 30 %, propriétaire de sa résidence principale (valeur 400 000 €, crédit en cours 150 000 €), épargne de précaution de 30 000 € sur livret, assurance-vie de 80 000 € (contrat de 12 ans, frais élevés), PER de 20 000 €, pas de prévoyance décès.",
        "Sans audit : le couple pourrait souscrire une SCPI sans analyser sa TMI (30 %), ou augmenter son PER sans évaluer sa TMI future (estimée entre 11 % et 30 % selon les droits acquis).",
        "Après audit : plusieurs axes d'optimisation sont identifiés :",
        "- Arbitrage du contrat d'assurance-vie ancien vers un contrat plus performant ;",
        "- Complément PER si la TMI future estimée est effectivement plus basse ;",
        "- Mise en place d'une prévoyance décès adaptée à la situation familiale ;",
        "- Vérification de la cohérence d'un éventuel investissement SCPI avec la TMI actuelle.",
        "Cet exemple anonymisé ne constitue pas une recommandation personnalisée. Chaque situation nécessite une analyse spécifique.",
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour l\'audit patrimonial',
      level: 'h2',
      type: 'method-steps',
      content: [
        "Eric Bellaiche, CGP-CIF, applique une méthode structurée en 7 étapes pour chaque audit patrimonial. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète.",
      ],
      methodSteps: [
        { title: 'Recueil des données', description: "Analyse des documents fournis : avis d'imposition, relevés de comptes, contrats d'assurance-vie, PER, biens immobiliers, crédits, prévoyance." },
        { title: 'Entretien d\'analyse', description: "Échange en visioconférence pour comprendre les objectifs, la situation familiale, les projets, les contraintes et les attentes." },
        { title: 'Diagnostic patrimonial', description: "Analyse complète : fiscalité, actifs, passifs, retraite, prévoyance, transmission, capacité d'épargne, risque." },
        { title: 'Identification des leviers', description: "Repérage des axes d'optimisation : fiscalité, diversification, frais, rendement, protection, transmission." },
        { title: 'Proposition de stratégie', description: "Formalisation des préconisations adaptées à la situation, sans promesse de rendement, avec des simulations chiffrées." },
        { title: 'Mise en œuvre', description: "Accompagnement dans la mise en place des décisions : souscriptions, arbitrages, donations, crédits." },
        { title: 'Suivi périodique', description: "Rendez-vous réguliers pour ajuster la stratégie en fonction des évolutions personnelles, fiscales et économiques." },
      ],
    },
    {
      id: 'documents',
      title: 'Documents utiles à préparer pour un audit',
      level: 'h2',
      type: 'list',
      content: [
        "Pour faciliter l'audit, il est utile de préparer les documents suivants :",
      ],
      listItems: [
        "Avis d'imposition sur le revenu (N-2)",
        "Avis d'IFI si applicable",
        "Relevés des comptes bancaires et d'épargne (livrets, PEA, compte-titres)",
        "Relevés des contrats d'assurance-vie et PER",
        "Tableau des crédits en cours (capital restant dû, taux, durée)",
        'Actes de propriété immobilière',
        "Relevé de situation retraite (site info-retraite.fr)",
        "Contrats de prévoyance (décès, invalidité, arrêt de travail)",
        "Situation familiale (mariage, Pacs, enfants, donations éventuelles)",
      ],
    },
  ],
  faq: [
    { question: "Qu'est-ce qu'un audit patrimonial ?", answer: "Un audit patrimonial est une analyse complète de la situation d'un client : actifs, passifs, fiscalité, retraite, immobilier, placements, capacité de risque, objectifs. Il permet d'identifier les leviers d'optimisation." },
    { question: 'Un audit patrimonial est-il payant ?', answer: 'Eric Bellaiche propose un premier bilan gratuit en visioconférence. Un audit approfondi peut être réalisé sur devis, selon la complexité de la situation.' },
    { question: 'Peut-on réaliser un audit patrimonial à distance ?', answer: "Oui, l'audit est réalisé en visioconférence, avec signature électronique et suivi personnalisé. L'accompagnement est accessible depuis toute la France." },
    { question: "Quels sont les principaux avantages d'un audit patrimonial ?", answer: "L'audit permet d'obtenir une vision globale, d'identifier les leviers fiscaux, de structurer une stratégie retraite, d'anticiper la transmission et d'éviter les décisions d'investissement isolées." },
    { question: "Quels sont les risques à ne pas faire d'audit ?", answer: "Investir sans vision globale expose à des erreurs : fiscalité inadaptée, doublons de frais, absence de diversification, insuffisance de prévoyance, transmission mal anticipée." },
    { question: "Une SCPI peut-elle être recommandée sans audit préalable ?", answer: "Non. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable complète de la situation du client." },
    { question: "Comment se déroule un audit en ligne ?", answer: "Après un premier échange, vous transmettez vos documents. Un rendez-vous en visioconférence permet d'analyser votre situation. Une synthèse écrite vous est remise avec des préconisations." },
    { question: "Quelle est la durée d'un audit patrimonial ?", answer: "Le premier rendez-vous dure environ 1 heure. L'analyse complète et la remise de la synthèse peuvent prendre de quelques jours à 2 semaines selon la complexité." },
    { question: "L'audit patrimonial est-il réservé aux gros patrimoines ?", answer: "Non. Un audit est utile pour tout patrimoine, quel que soit son montant. Plus la situation est simple, plus l'audit est rapide, mais il reste pertinent." },
    { question: "Quelle différence entre un audit et un conseil ponctuel ?", answer: "L'audit est une analyse globale et structurée, préalable à toute recommandation. Un conseil ponctuel peut répondre à une question spécifique sans vision d'ensemble." },
  ],
  ctaTitle: 'Vous souhaitez faire le point sur votre situation patrimoniale ?',
  ctaText: 'Réservez un créneau gratuit pour un premier échange en visioconférence avec Eric Bellaiche, CGP-CIF.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI', position: 'inline' },
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie', position: 'inline' },
  ],
};

export default article;
