import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'audit-patrimonial-en-ligne',
  category: 'audit',
  title: 'Audit patrimonial en ligne : méthode, analyse et points de vigilance',
  metaTitle: 'Audit patrimonial en ligne : méthode, analyse et points de vigilance',
  metaDescription: "Un audit patrimonial en ligne permet d'analyser votre fiscalité, vos placements, votre immobilier, votre retraite, votre transmission et votre capacité d'investissement avant toute décision patrimoniale.",
  canonical: 'https://eric-bellaiche.fr/articles/audit-patrimonial-en-ligne/',
  badge: 'Audit patrimonial &bull; CGP-CIF &bull; ORIAS 13001580',
  intro: "Beaucoup de décisions patrimoniales sont prises sans vision d'ensemble : souscrire un produit d'épargne parce qu'il est défiscalisant, acheter une SCPI parce que le rendement est affiché à 6 %, ouvrir un PER parce que les versements sont déductibles. Ces décisions, prises isolément, peuvent créer des déséquilibres patrimoniaux. L'audit patrimonial est la démarche qui permet de structurer une stratégie cohérente, adaptée à votre situation personnelle, votre fiscalité, vos objectifs et votre tolérance au risque. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, réalise des audits patrimoniaux en visioconférence pour vous accompagner dans cette démarche.",
  shortAnswer: "Un audit patrimonial est une analyse complète et structurée de votre situation financière, fiscale, immobilière et familiale : actifs et passifs, revenus, fiscalité (IR, IFI, plus-values), placements financiers (assurance-vie, PER, PEA), immobilier, épargne, crédits, retraite, prévoyance, transmission, capacité d'épargne, endettement, objectifs personnels et tolérance au risque. Il permet d'identifier les leviers d'optimisation, de détecter les incohérences et de structurer une stratégie patrimoniale cohérente. Réalisé en ligne par un CGP-CIF, il est accessible depuis toute la France.",
  summaryItems: [
    { label: "Qu'est-ce qu'un audit patrimonial ?", anchor: 'quest-ce-quun-audit-patrimonial' },
    { label: 'Pourquoi faire un audit avant d\'investir', anchor: 'pourquoi-faire-audit' },
    { label: 'Ce qui est analysé dans un audit patrimonial', anchor: 'ce-qui-est-analyse' },
    { label: 'Tableau des sujets analysés', anchor: 'tableau-sujets' },
    { label: 'Audit patrimonial en ligne : avantages et limites', anchor: 'audit-en-ligne' },
    { label: 'Erreurs fréquentes sans audit', anchor: 'erreurs-frequentes' },
    { label: 'Exemple pédagogique anonymisé', anchor: 'exemple-pedagogique' },
    { label: 'Méthode Eric Bellaiche pour l\'audit patrimonial', anchor: 'methode' },
    { label: 'Documents utiles à préparer', anchor: 'documents' },
    { label: 'Combien coûte un audit patrimonial ?', anchor: 'cout-audit' },
    { label: 'Pour quels profils l\'audit est-il utile ?', anchor: 'profils-audit' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 18,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['audit patrimonial', 'bilan patrimonial', 'CGP-CIF', 'fiscalité', 'retraite', 'transmission', 'prévoyance', 'conseil patrimonial', 'épargne'],
  sections: [
    {
      id: 'quest-ce-quun-audit-patrimonial',
      title: "Qu'est-ce qu'un audit patrimonial ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Un audit patrimonial, également appelé bilan patrimonial, est une analyse complète et structurée de la situation financière, fiscale, immobilière et familiale d'une personne, d'un couple ou d'une famille. Il vise à obtenir une vision d'ensemble du patrimoine, à identifier les forces et faiblesses, et à déterminer les axes d'optimisation prioritaires.",
        "Contrairement à une simple simulation en ligne ou à un conseil ponctuel, l'audit patrimonial prend en compte la globalité de la situation : revenus professionnels, fiscalité personnelle, patrimoine immobilier et financier, endettement, capacité d'épargne, retraite, prévoyance, transmission et objectifs de vie.",
        "L'audit est réalisé par un conseiller en gestion de patrimoine (CGP-CIF) qui recueille les données, analyse la situation et formalise des préconisations adaptées. Dans le cadre réglementaire des CGP-CIF, l'audit patrimonial respecte des obligations strictes :",
        "- Analyse préalable complète de la situation du client avant toute recommandation ;",
        "- Évaluation des connaissances, de l'expérience financière, de la capacité de perte et de l'horizon de placement ;",
        "- Formalisation d'une déclaration d'adéquation en cas de recommandation d'investissement ;",
        "- Aucune promesse de rendement ou de résultat ;",
        "- Information claire sur les risques, les frais et les limites des solutions envisagées.",
        "L'audit patrimonial n'est pas un document commercial. C'est un outil de diagnostic qui permet d'éclairer les décisions et d'éviter les erreurs coûteuses.",
      ],
    },
    {
      id: 'pourquoi-faire-audit',
      title: "Pourquoi faire un audit avant d'investir ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Investir sans vision d'ensemble expose à des décisions isolées, parfois contradictoires, qui peuvent dégrader la performance globale du patrimoine. Les raisons de réaliser un audit patrimonial sont nombreuses et complémentaires :",
        "1. Éviter les décisions isolées : chaque investissement doit être cohérent avec les autres composantes du patrimoine. Une SCPI peut être pertinente dans un patrimoine diversifié, mais contre-productive si elle aggrave une exposition déjà trop forte à l'immobilier.",
        "2. Comprendre l'impact fiscal réel : la TMI, les prélèvements sociaux, l'IFI, le régime matrimonial, chaque paramètre fiscal influence le rendement net des investissements. Un audit permet de mesurer cet impact avant de souscrire.",
        "3. Vérifier l'endettement : un crédit permet un effet de levier, mais un endettement excessif ou mal structuré peut fragiliser le patrimoine. L'audit analyse la capacité d'endettement réelle et les taux en cours.",
        "4. Mesurer la liquidité : trop d'épargne liquide non rémunérée ou au contraire trop d'actifs illiquides (immobilier, SCPI) peut déséquilibrer un patrimoine. L'audit évalue le besoin de liquidité à court, moyen et long terme.",
        "5. Préparer la retraite : l'audit permet d'estimer le niveau de vie futur, d'identifier le besoin de complément de revenu et de déterminer les enveloppes adaptées (PER, assurance-vie, immobilier locatif).",
        "6. Anticiper la transmission : donation, succession, assurance-vie, chaque outil a des implications juridiques et fiscales différentes. L'audit permet de choisir les solutions adaptées à la situation familiale.",
        "7. Comparer plusieurs solutions : plutôt que de souscrire un produit unique, l'audit permet de comparer plusieurs allocations possibles et d'arbitrer en fonction des objectifs, du profil de risque et de l'horizon.",
        "8. Formaliser une stratégie : l'audit aboutit à une stratégie écrite, documentée, révisable dans le temps. C'est un cadre de référence pour les décisions futures.",
      ],
    },
    {
      id: 'ce-qui-est-analyse',
      title: 'Ce qui est analysé dans un audit patrimonial',
      level: 'h2',
      type: 'list',
      content: [
        "L'audit patrimonial couvre l'ensemble des dimensions financières, fiscales et personnelles du client. Voici les principaux sujets analysés :",
      ],
      listItems: [
        'Revenus : salaires, BNC, BIC, revenus fonciers, pensions de retraite, revenus financiers.',
        'Fiscalité : TMI, prélèvements sociaux, IFI, plus-values latentes, déficits fonciers éventuels, crédits d\'impôt.',
        'Patrimoine immobilier : résidence principale, résidence secondaire, investissements locatifs, SCPI, SCI.',
        'Placements financiers : assurance-vie, PER, PERP, PEA, comptes-titres, livrets réglementés, cryptomonnaies.',
        'Épargne disponible : livrets, liquidités, comptes courants.',
        'Crédits en cours : prêt immobilier, crédit à la consommation, crédit relais, prêt in fine.',
        'Retraite : estimation des droits (régime général, complémentaire, supplémentaire), taux de remplacement',
        'Prévoyance : couverture décès, invalidité, incapacité de travail, dépendance.',
        'Transmission : situation familiale, régime matrimonial, donation, succession, clauses bénéficiaires.',
        'Objectifs familiaux et personnels : achat immobilier, éducation des enfants, départ en retraite, transmission aux héritiers, projet de création d\'entreprise.',
        'Capacité d\'épargne mensuelle : revenus disponibles moins charges fixes, capacité réelle à épargner.',
        'Tolérance au risque : capacité de perte, horizon de placement, expérience des investissements.',
      ],
    },
    {
      id: 'tableau-sujets',
      title: 'Tableau des sujets analysés et impact patrimonial',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous détaille les principaux sujets analysés lors d\'un audit patrimonial, les questions posées par le conseiller et l\'impact potentiel sur la stratégie patrimoniale.',
      ],
      table: {
        headers: ['Sujet analysé', 'Questions posées', 'Impact patrimonial'],
        rows: [
          ['Revenus', 'Sont-ils stables ou variables ? Y a-t-il une tendance à la hausse ou à la baisse ?', "Détermine la capacité d'épargne et le niveau de risque acceptable"],
          ['Fiscalité IR', 'Quelle est la TMI ? Quel est le quotient familial ? Y a-t-il des déficits ?', "Oriente les choix d'investissement et les enveloppes fiscales (PER, AV, immobilier)"],
          ['IFI', 'Le patrimoine immobilier dépasse-t-il 1,3 M€ ? Quels biens sont concernés ?', "Détermine l'exposition à l'IFI et les stratégies de réduction possibles"],
          ['Patrimoine immobilier', 'Quelle part dans le patrimoine global ? Quel endettement ? Quelle liquidité ?', "Évalue la diversification et l'exposition au risque immobilier"],
          ['Assurance-vie', 'Quels contrats, quels frais, quels supports, quelle performance depuis l\'origine ?', "Identifie les doublons, les frais excessifs et les arbitrages possibles"],
          ['PER', 'Quel montant, quel plafond disponible, quelle stratégie de sortie ?', "Évalue la pertinence de la déduction fiscale et la cohérence avec la TMI future"],
          ['SCPI', "Quel taux d'endettement de la SCPI, quel TOF, quelle valeur de reconstitution ?", "Analyse la qualité du véhicule et l'adéquation avec la fiscalité personnelle"],
          ['Épargne disponible', 'Quel montant sur livrets ? Quelle trésorerie ?', "Définit l'épargne de précaution et la capacité d'investissement"],
          ['Crédits', "Quel taux, quelle durée, quel capital restant dû ? Y a-t-il un regroupement ?", "Détermine la capacité d'endettement restante"],
          ['Capacité d\'épargne', "Quel montant peut être épargné chaque mois après toutes charges ?", "Définit un plan d'épargne réaliste et adapté"],
          ['Retraite', "Quel est le taux de remplacement estimé ? Quel écart avec les revenus actuels ?", "Détermine le besoin d'épargne complémentaire et le choix des enveloppes"],
          ['Transmission', "Quel âge, quels héritiers, quelle situation matrimoniale, quelles donations déjà effectuées ?", "Oriente le choix des outils (donation, assurance-vie, PER, SCI, démembrement)"],
          ['Régime matrimonial', "Communauté, séparation de biens, participation aux acquêts ? Y a-t-il un contrat ?", "Impact sur la transmission et la gestion des biens"],
          ['Objectifs familiaux', "Quels sont les projets à 5, 10, 20 ans ?", "Structure la stratégie patrimoniale dans le temps"],
          ['Tolérance au risque', "Quelle est la capacité de perte ? Quelle expérience des placements ?", "Détermine la part de patrimoine investissable en actifs risqués"],
        ],
      },
    },
    {
      id: 'audit-en-ligne',
      title: 'Audit patrimonial en ligne : avantages et limites',
      level: 'h2',
      type: 'normal',
      content: [
        "L'audit patrimonial en ligne, réalisé en visioconférence, démocratise l'accès au conseil patrimonial. Il présente plusieurs avantages par rapport à un audit en cabinet traditionnel :",
        "Avantages :",
        "- Accessibilité géographique : l'audit est réalisable depuis toute la France, sans déplacement.",
        "- Flexibilité des horaires : les rendez-vous peuvent être organisés en soirée ou le week-end.",
        "- Dématérialisation des documents : les pièces justificatives sont partagées par email ou plateforme sécurisée.",
        "- Signature électronique : les documents peuvent être signés à distance.",
        "- Rapidité : l'audit peut être réalisé en quelques jours ouvrés.",
        "- Mêmes garanties réglementaires : le cadre CGP-CIF s'applique quel que soit le mode de consultation.",
        "Limites :",
        "- L'audit en ligne nécessite une bonne préparation en amont (documents, questions).",
        "- L'échange en visioconférence doit être de qualité suffisante.",
        "- Certaines situations très complexes (succession internationale, fiscalité étrangère) peuvent nécessiter un rendez-vous en présentiel.",
        "- Le relationnel humain est différent à distance qu'en face à face.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes sans audit préalable',
      level: 'h2',
      type: 'list',
      content: ['De nombreux investisseurs commettent des erreurs faute d\'avoir réalisé un audit patrimonial préalable. En voici les plus fréquentes :'],
      listItems: [
        'Investir uniquement pour réduire l\'impôt, sans vérifier la cohérence patrimoniale du produit.',
        'Acheter une SCPI sans mesurer l\'impact fiscal (TMI, PS, IFI) sur le rendement net.',
        'Ouvrir un PER sans anticiper la fiscalité de sortie et le besoin de liquidité à moyen terme.',
        'Conserver trop de liquidités sur des livrets non ou faiblement rémunérés.',
        'Sous-estimer les droits de succession et ne pas anticiper la transmission.',
        'Ignorer le régime matrimonial et ses implications sur la gestion des biens.',
        'Multiplier les produits sans stratégie : empiler des contrats sans vision globale.',
        'Confondre rendement brut et rendement net de fiscalité et de frais.',
        'Négliger la prévoyance : pas de couverture décès, invalidité ou arrêt de travail.',
        'Ne pas vérifier la cohérence globale : par exemple, immobilier locatif sans penser à l\'IFI.',
        'Prendre une décision patrimoniale sous l\'effet d\'une opportunité sans analyse préalable.',
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique anonymisé',
      level: 'h2',
      type: 'normal',
      content: [
        "Situation : un couple marié sous communauté, 45 ans et 43 ans, deux enfants de 12 et 14 ans. Revenus annuels : 120 000 € (salaires). TMI : 30 %. Résidence principale : valeur 450 000 €, crédit en cours 120 000 € à 1,2 % sur 10 ans. Assurance-vie : 90 000 € sur deux contrats ouverts il y a 12 ans (frais élevés, supports diversifiés). PER : 15 000 € ouvert l'année dernière. Épargne de précaution : 40 000 € sur livret A et LDD. Pas de prévoyance décès. Pas de donation. Projet : investir 50 000 € dans une SCPI.",
        "Sans audit : le couple pourrait souscrire une SCPI sans analyser l'impact fiscal (TMI 30 % + PS 17,2 % = 47,2 % d'imposition sur les revenus fonciers), ce qui réduirait le rendement net attendu de manière significative. Il pourrait également augmenter le PER sans évaluer la TMI future à la retraite.",
        "Après audit : plusieurs pistes d'optimisation sont identifiées :",
        "- Arbitrage des contrats d'assurance-vie anciens vers un contrat plus performant avec des frais réduits et une meilleure sélection de supports.",
        "- Étude de la pertinence d'un investissement SCPI en direct ou via assurance-vie, en fonction de la TMI et de l'horizon.",
        "- Mise en place d'une prévoyance décès adaptée à la situation familiale (capital décès pour les enfants).",
        "- Vérification du plafond PER disponible et de la cohérence avec la TMI future estimée.",
        "- Analyse de la répartition entre épargne de précaution, épargne investie et immobilier.",
        "Cet exemple anonymisé ne constitue pas une recommandation personnalisée. Chaque situation nécessite une analyse spécifique.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour l'audit patrimonial",
      level: 'h2',
      type: 'method-steps',
      content: [
        "Eric Bellaiche, CGP-CIF, applique une méthode structurée en 7 étapes pour chaque audit patrimonial. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète de la situation, du profil investisseur, des objectifs, de l'horizon et de la capacité de perte.",
      ],
      methodSteps: [
        { title: 'Premier échange et clarification des objectifs', description: "Échange téléphonique ou visio pour comprendre la situation, les attentes, les projets et fixer le cadre de l'audit (périmètre, documents nécessaires, délais)." },
        { title: 'Recueil des informations et documents', description: "Transmission sécurisée des documents : avis d'imposition, relevés de comptes, contrats d'assurance-vie, PER, actes immobiliers, crédits, prévoyance, situation familiale." },
        { title: 'Analyse patrimoniale et fiscale', description: "Diagnostic complet : fiscalité, actifs, passifs, retraite, prévoyance, transmission, capacité d'épargne, tolérance au risque. Identification des forces, faiblesses et incohérences." },
        { title: 'Analyse du profil investisseur', description: 'Évaluation des connaissances financières, de l\'expérience en investissement, de la capacité de perte, de l\'horizon de placement et de la sensibilité au risque.' },
        { title: 'Identification des incohérences et leviers', description: "Repérage des déséquilibres : fiscalité non optimisée, frais excessifs, absence de diversification, doublons de contrats, insuffisance de prévoyance, transmission non anticipée." },
        { title: 'Comparaison des pistes possibles', description: "Simulation de plusieurs scénarios d'arbitrage, d'investissement ou de restructuration, avec une évaluation des impacts fiscaux, financiers et successoraux." },
        { title: 'Formalisation et suivi périodique', description: "Synthèse écrite des préconisations, déclaration d'adéquation le cas échéant, plan d'actions prioritaires. Suivi annuel ou biannuel pour ajuster la stratégie." },
      ],
    },
    {
      id: 'documents',
      title: 'Documents utiles à préparer pour un audit',
      level: 'h2',
      type: 'list',
      content: [
        "Pour faciliter l'audit et gagner du temps, il est recommandé de préparer les documents suivants avant le premier rendez-vous :",
      ],
      listItems: [
        "Avis d'imposition sur le revenu (N-2) : indispensable pour connaître la TMI et les revenus du foyer.",
        "Avis d'IFI si applicable : nécessaire si le patrimoine immobilier dépasse 1,3 M€.",
        "Relevés des comptes bancaires et d'épargne : livrets, PEA, compte-titres, comptes courants.",
        "Relevés des contrats d'assurance-vie : relevés de situation annuels, montants, frais, supports.",
        "Relevés des PER, PERP, Madelin : montants, plafonds disponibles, options de sortie.",
        "Tableau des crédits en cours : capital restant dû, taux, durée restante, mensualités.",
        "Actes de propriété immobilière : résidence principale, secondaire, investissements locatifs, SCPI.",
        "Relevé de situation retraite : à télécharger sur le site info-retraite.fr (document unique).",
        "Contrats de prévoyance : décès, invalidité, incapacité, garantie des accidents de la vie.",
        "Statuts de SCI si existants : pour analyser les implications fiscales et successorales.",
        "Estimation immobilière : valeur estimée des biens immobiliers détenus.",
        "Situation familiale : mariage, Pacs, enfants, donations déjà effectuées, testament éventuel.",
      ],
    },
    {
      id: 'cout-audit',
      title: 'Combien coûte un audit patrimonial ?',
      level: 'h2',
      type: 'normal',
      content: [
        "Les modalités financières d'un audit patrimonial dépendent de plusieurs facteurs : la complexité de la situation, le périmètre de l'analyse, le temps nécessaire au diagnostic et à la formalisation des préconisations.",
        "Dans la pratique, on distingue plusieurs niveaux :",
        "- Un premier échange de découverte, gratuit et sans engagement, permet de clarifier les attentes et de vérifier que l'audit est pertinent.",
        "- Un bilan de découverte peut être proposé à un tarif forfaitaire modéré, incluant l'analyse des éléments principaux et une première orientation.",
        "- Un audit approfondi, avec analyse complète, simulation de scénarios, formalisation écrite et suivi, fait l'objet d'une lettre de mission précisant les honoraires.",
        "- Pour les situations simples, l'audit peut être réalisé rapidement et à moindre coût.",
        "Les modalités précises (tarif, durée, périmètre) sont toujours communiquées et validées avant le début de la mission, conformément aux obligations de transparence des CGP-CIF.",
      ],
    },
    {
      id: 'profils-audit',
      title: "Pour quels profils l'audit est-il utile ?",
      level: 'h2',
      type: 'list',
      content: [
        "L'audit patrimonial est utile pour tout patrimoine, quel que soit son montant. Certains profils en bénéficient particulièrement :",
      ],
      listItems: [
        'Cadres dirigeants fortement imposés : TMI élevée, optimisation fiscale nécessaire.',
        'Professions libérales : revenus variables, besoin de structuration et de prévoyance.',
        'Chefs d\'entreprise : enjeux de transmission, d\'épargne professionnelle et de diversification.',
        'Propriétaires immobiliers : exposition à l\'IFI, arbitrage entre immobilier et financier.',
        'Investisseurs SCPI : besoin de vérifier la cohérence fiscale et patrimoniale.',
        'Personnes préparant leur retraite : estimation du besoin de complément.',
        'Familles recomposées : enjeux successoraux et matrimoniaux spécifiques.',
        'Personnes souhaitant transmettre : donation, assurance-vie, SCI.',
        'Expatriés ou futurs expatriés : fiscalité internationale, convention fiscale, rapatriement.',
        'Personnes ayant plusieurs contrats d\'assurance-vie : doublons, frais, arbitrages.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance',
      level: 'h2',
      type: 'normal',
      content: [
        "L'audit patrimonial est un outil d'aide à la décision, pas une garantie de résultat. Plusieurs points doivent être gardés à l'esprit :",
        "- L'audit ne constitue pas une garantie de performance des investissements recommandés.",
        "- La fiscalité est évolutive : les règles peuvent changer en cours de détention des actifs.",
        "- Un audit doit être mis à jour régulièrement (tous les 1 à 3 ans) pour rester pertinent.",
        "- Tout investissement comporte des risques : perte en capital, liquidité, horizon de placement.",
        "- La cohérence entre rendement, risque et liquidité doit être vérifiée pour chaque décision.",
        "- L'audit ne remplace pas un conseil juridique ou notarial pour les aspects successoraux complexes.",
        "- Une recommandation personnalisée ne peut être formulée sans analyse préalable complète.",
      ],
    },
  ],
  faq: [
    { question: "Qu'est-ce qu'un audit patrimonial ?", answer: "Un audit patrimonial est une analyse complète de la situation d'un client : actifs, passifs, fiscalité, retraite, immobilier, placements, capacité de risque, objectifs. Il permet d'identifier les leviers d'optimisation et de structurer une stratégie cohérente." },
    { question: "Quelle différence entre un audit patrimonial et un simple bilan ?", answer: "Le bilan patrimonial est souvent un état des lieux rapide, tandis que l'audit patrimonial est une analyse approfondie et structurée qui aboutit à des préconisations formalisées et à un plan d'actions." },
    { question: 'Un audit patrimonial peut-il être réalisé à distance ?', answer: "Oui, l'audit est réalisé en visioconférence, avec partage de documents par email ou plateforme sécurisée, signature électronique et suivi personnalisé. Il est accessible depuis toute la France." },
    { question: "Quels documents faut-il préparer pour un audit ?", answer: "Avis d'imposition, relevés de comptes, contrats d'assurance-vie et PER, crédits en cours, actes immobiliers, relevé de situation retraite, contrats de prévoyance, situation familiale et tout document décrivant votre patrimoine." },
    { question: "L'audit patrimonial donne-t-il une recommandation d'investissement ?", answer: "L'audit aboutit à des préconisations adaptées à la situation, mais aucune recommandation personnalisée n'est formulée sans analyse préalable complète du profil investisseur, des objectifs, de l'horizon et de la capacité de perte." },
    { question: 'Combien de temps dure un audit patrimonial ?', answer: "Le premier rendez-vous dure environ 1 heure. L'analyse complète et la remise de la synthèse peuvent prendre de quelques jours à 2 semaines selon la complexité de la situation." },
    { question: "Un audit patrimonial est-il utile avant d'investir en SCPI ?", answer: "Oui, un audit permet de vérifier la cohérence d'un investissement SCPI avec la fiscalité personnelle, l'horizon, la capacité de perte, le mode de détention et le patrimoine global." },
    { question: "L'audit patrimonial permet-il de réduire l'impôt ?", answer: "L'audit identifie les leviers fiscaux adaptés à la situation (PER, déficit foncier, assurance-vie, SCPI fiscales, démembrement), mais ne garantit pas une réduction d'impôt. L'optimisation fiscale est encadrée et dépend de chaque situation." },
    { question: "Pourquoi analyser la retraite dans un audit patrimonial ?", answer: "L'analyse de la retraite permet d'estimer le taux de remplacement futur, d'identifier un éventuel besoin de complément de revenu et de choisir les enveloppes les plus adaptées (PER, assurance-vie, immobilier locatif)." },
    { question: "Pourquoi faire appel à un CGP-CIF pour un audit patrimonial ?", answer: "Un CGP-CIF est soumis à une réglementation stricte : il doit analyser votre situation avant toute recommandation, formaliser une déclaration d'adéquation et respecter des obligations de transparence. C'est une garantie de sérieux et de conformité." },
  ],
  ctaTitle: 'Vous souhaitez faire le point sur votre situation patrimoniale ?',
  ctaText: 'Un échange permet d\'identifier les points à analyser avant de prendre une décision d\'investissement, de retraite, de transmission ou d\'optimisation fiscale.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie : quelle enveloppe choisir', position: 'inline' },
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité', position: 'inline' },
  ],
};

export default article;
