import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'conseiller-scpi',
  category: 'scpi',
  title: 'Conseiller SCPI : pourquoi se faire accompagner avant d\'investir',
  metaTitle: 'Conseiller SCPI : pourquoi se faire accompagner avant d\'investir',
  metaDescription: 'Avant d\'investir en SCPI, un conseiller CGP-CIF peut analyser votre fiscalité, votre horizon, votre profil investisseur, le mode de détention, les risques et la cohérence patrimoniale du projet.',
  canonical: 'https://eric-bellaiche.fr/articles/conseiller-scpi/',
  badge: 'SCPI &bull; Conseil CGP-CIF &bull; ORIAS 13001580',
  intro: 'La SCPI attire souvent par le rendement affiché. Mais le vrai sujet n\'est pas le taux de distribution : c\'est la cohérence patrimoniale. Une mauvaise SCPI ou un mauvais mode de détention peut dégrader le rendement net, la liquidité ou la fiscalité. Un conseiller CGP-CIF ne doit pas vendre une SCPI isolée, mais analyser la situation globale.',
  shortAnswer: 'Un conseiller SCPI aide à vérifier si l\'investissement est adapté à votre fiscalité, votre horizon, votre capacité de perte, vos objectifs et votre mode de détention. Le rendement affiché ne suffit pas : il faut analyser la liquidité, les frais, le risque immobilier, la fiscalité, la diversification et la cohérence avec votre patrimoine global.',
  summaryItems: [
    { label: 'Pourquoi le rendement d\'une SCPI ne suffit pas', anchor: 'pourquoi-rendement-ne-suffit-pas' },
    { label: 'Ce qu\'un conseiller SCPI analyse avant une recommandation', anchor: 'ce-qu-un-conseiller-scpi-analyse' },
    { label: 'Les différents modes de détention d\'une SCPI', anchor: 'modes-de-detention' },
    { label: 'Les erreurs fréquentes avant une souscription SCPI', anchor: 'erreurs-frequentes' },
    { label: 'Les risques à connaître avant d\'investir', anchor: 'risques' },
    { label: 'La méthode Eric Bellaiche pour analyser un projet SCPI', anchor: 'methode' },
    { label: 'Quand consulter un conseiller SCPI ?', anchor: 'quand-consulter' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 12,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'conseiller SCPI', 'investissement SCPI', 'CGP-CIF', 'fiscalité'],
  sections: [
    {
      id: 'pourquoi-rendement-ne-suffit-pas',
      title: 'Pourquoi le rendement d\'une SCPI ne suffit pas',
      level: 'h2',
      type: 'normal',
      content: [
        'Le taux de distribution (TD) est le premier indicateur mis en avant par les sociétés de gestion. Pourtant, ce chiffre ne reflète qu\'une partie de la réalité d\'un investissement en SCPI.',
        'Le rendement brut affiché ne tient compte ni de la fiscalité personnelle de l\'investisseur (TMI, prélèvements sociaux, IFI), ni des frais de souscription (qui peuvent atteindre 8 à 12 %), ni du délai de jouissance (période durant laquelle les premières distributions ne sont pas perçues).',
        'Un investisseur doit également tenir compte de la performance passée non garantie. Le TD d\'une SCPI peut baisser d\'une année sur l\'autre, et le prix de part peut évoluer à la baisse.',
        'Enfin, le rendement seul ne reflète pas le risque de concentration. Investir dans une seule SCPI sans analyser la diversification sectorielle et géographique expose à un risque élevé.',
      ],
    },
    {
      id: 'ce-qu-un-conseiller-scpi-analyse',
      title: 'Ce qu\'un conseiller SCPI analyse avant une recommandation',
      level: 'h2',
      type: 'table',
      content: [
        'Avant toute recommandation personnalisée, un CGP-CIF analyse systématiquement les critères suivants. Chaque critère a un impact direct sur la pertinence et la cohérence de l\'investissement.',
      ],
      table: {
        headers: ['Critère', 'Pourquoi c\'est important', 'Impact possible'],
        rows: [
          ['TMI (tranche marginale d\'imposition)', 'Détermine l\'impôt sur les revenus fonciers', 'Un TMI à 30 % ou 41 % peut réduire fortement le rendement net'],
          ['Prélèvements sociaux', '17,2 % sur les revenus SCPI', 'Rendement net fiscal réduit de plus de 20 points cumulés avec l\'IR'],
          ['IFI', 'Les SCPI peuvent être soumises à l\'IFI selon le mode de détention', 'Impact fiscal supplémentaire pour les redevables'],
          ['Horizon de placement', 'Compatibilité avec la duration recommandée (8-10 ans)', 'Un horizon trop court peut générer une moins-value'],
          ['Capacité de perte', 'Évalue la tolérance au risque', 'Détermine le type de SCPI et la part du patrimoine investie'],
          ['Besoin de liquidité', 'Les SCPI sont peu liquides', 'Un besoin élevé peut déconseiller l\'investissement'],
          ['Objectif de revenus', 'Recherche de revenus réguliers vs capitalisation', 'Oriente le choix entre SCPI de rendement et SCPI fiscales'],
          ['Mode de détention', 'Direct, AV, crédit, démembrement, SCI', 'Impacte la fiscalité, les frais, la liquidité et la transmission'],
          ['Diversification sectorielle', 'Répartition bureaux/commerces/logistique/santé', 'Réduit le risque de concentration sectorielle'],
          ['Valeur de reconstitution', 'Comparaison avec le prix de souscription', 'Une prime d\'émission élevée peut indiquer un risque de survalorisation'],
          ['TOF (taux d\'occupation financier)', 'Mesure le taux de location effectif', 'Un TOF bas indique des périodes locatives fréquentes'],
          ['Capitalisation', 'Taille du véhicule', 'Une capitalisation élevée offre généralement une meilleure liquidité'],
        ],
      },
    },
    {
      id: 'modes-de-detention',
      title: 'Les différents modes de détention d\'une SCPI',
      level: 'h2',
      type: 'table',
      content: [
        'Les SCPI peuvent être détenues de plusieurs manières, chacune avec des implications fiscales, successorales et financières distinctes. Aucun mode n\'est meilleur : le choix dépend de la situation personnelle.',
      ],
      table: {
        headers: ['Mode de détention', 'Avantages', 'Limites', 'Profil potentiellement concerné'],
        rows: [
          ['Direct', 'Choix large de SCPI, simplicité, pas d\'intermédiaire', 'Revenus imposés à l\'IR + PS, pas d\'avantage successoral spécifique', 'Investisseurs cherchant la simplicité'],
          ['Assurance-vie', 'Fiscalité allégée après 8 ans, cadre successoral avantageux', 'Choix limité aux SCPI éligibles, frais supplémentaires', 'Objectif de transmission ou optimisation long terme'],
          ['À crédit', 'Effet de levier potentiel, déduction des intérêts', 'Risque accru, coût total du crédit', 'Capacité d\'endettement et TMI élevée'],
          ['Démembrement', 'Prix réduit pour le nu-propriétaire', 'Pas de revenus pendant le démembrement', 'Transmission ou revenus sans capital total'],
          ['Via SCI', 'Gestion collective, optimisation transmission', 'Complexité juridique, frais de structure', 'Familles avec vision long terme'],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Les erreurs fréquentes avant une souscription SCPI',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que certaines erreurs reviennent régulièrement avant un investissement en SCPI :'],
      listItems: [
        'Choisir uniquement le rendement : le TD ne reflète ni la fiscalité, ni les frais, ni la qualité du patrimoine sous-jacent.',
        'Ignorer la fiscalité personnelle : un TD de 6 % peut se transformer en 3 % net après impôt selon la TMI.',
        'Investir sur une seule SCPI : l\'absence de diversification augmente le risque.',
        'Négliger la liquidité : croire qu\'on peut revendre ses parts en quelques semaines est une erreur fréquente.',
        'Oublier le délai de jouissance : les premières distributions peuvent n\'intervenir que plusieurs mois après la souscription.',
        'Confondre revenus bruts et revenus nets : les frais de gestion et la fiscalité réduisent le rendement effectif.',
        'Ne pas vérifier la valeur de reconstitution : un prix très supérieur peut indiquer une survalorisation.',
        'Investir trop court terme : les SCPI sont inadaptées aux horizons de moins de 8 ans.',
        'Ne pas anticiper la transmission : le mode de détention impacte directement la transmission.',
        'Négliger l\'impact d\'un crédit : l\'effet de levier peut amplifier les gains comme les pertes.',
      ],
    },
    {
      id: 'risques',
      title: 'Les risques à connaître avant d\'investir',
      level: 'h2',
      type: 'risk',
      content: [
        'Comme tout investissement immobilier et financier, les SCPI comportent des risques qu\'il est essentiel de connaître avant toute souscription.',
      ],
      listItems: [
        'Risque de perte en capital : le prix des parts peut baisser.',
        'Risque de baisse des revenus : le taux de distribution peut varier.',
        'Risque de liquidité : la revente peut prendre plusieurs mois à plusieurs années.',
        'Risque immobilier : la valeur du patrimoine peut évoluer à la baisse.',
        'Risque de taux : une hausse des taux peut impacter les distributions.',
        'Risque fiscal : la fiscalité peut évoluer en cours de détention.',
        'Risque lié au mode de détention : chaque mode comporte ses propres risques.',
        'Horizon long terme : 8 à 10 ans sont généralement recommandés.',
      ],
    },
    {
      id: 'methode',
      title: 'La méthode Eric Bellaiche pour analyser un projet SCPI',
      level: 'h2',
      type: 'method-steps',
      content: [
        'L\'analyse d\'un projet SCPI suit une méthode structurée en 7 étapes, dans le respect du cadre réglementaire des CGP-CIF.',
      ],
      methodSteps: [
        { title: 'Recueil de la situation patrimoniale', description: 'Analyse complète des actifs, passifs, revenus, charges, fiscalité et objectifs patrimoniaux.' },
        { title: 'Définition des objectifs', description: 'Identification précise des objectifs : revenus, capitalisation, retraite, transmission, défiscalisation.' },
        { title: 'Analyse fiscale', description: 'Évaluation de l\'impact fiscal selon la TMI, les prélèvements sociaux, l\'IFI et le mode de détention.' },
        { title: 'Analyse du profil investisseur', description: 'Évaluation des connaissances, de l\'expérience, de la capacité de perte et de l\'horizon de placement.' },
        { title: 'Comparaison des modes de détention', description: 'Analyse comparative : direct, assurance-vie, crédit, démembrement ou SCI.' },
        { title: 'Sélection cohérente de solutions', description: 'Identification des types de SCPI et modes de détention adaptés, sans promesse de rendement.' },
        { title: 'Formalisation et suivi', description: 'Déclaration d\'adéquation, documentation, suivi périodique et ajustements éventuels.' },
      ],
    },
    {
      id: 'quand-consulter',
      title: 'Quand consulter un conseiller SCPI ?',
      level: 'h2',
      type: 'list',
      content: ['Certaines situations justifient particulièrement un accompagnement par un CGP-CIF :'],
      listItems: [
        'Investissement supérieur à 50 000 €',
        'TMI élevée (30 %, 41 % ou 45 %)',
        'Objectif de revenus complémentaires',
        'Préparation retraite',
        'Projet à crédit',
        'Hésitation entre direct et assurance-vie',
        'Besoin de transmission',
        'Patrimoine immobilier déjà important',
        'Besoin de diversification',
      ],
    },
  ],
  faq: [
    { question: 'Pourquoi passer par un conseiller pour investir en SCPI ?', answer: 'Un conseiller CGP-CIF analyse votre situation globale avant toute recommandation : fiscalité, horizon de placement, capacité de perte, objectifs. Cette analyse permet de vérifier la cohérence d\'un investissement en SCPI avec votre situation personnelle.' },
    { question: 'Une SCPI garantit-elle un rendement ?', answer: 'Non, les SCPI ne garantissent ni le rendement ni le capital. Les performances passées ne préjugent pas des performances futures. Il existe un risque de perte en capital et un risque de liquidité.' },
    { question: 'Quel est le rôle d\'un CGP-CIF dans une souscription SCPI ?', answer: 'Le CGP-CIF analyse le profil investisseur, la fiscalité, l\'horizon, la capacité de perte, le mode de détention et la cohérence patrimoniale. Il formalise une déclaration d\'adéquation si une recommandation est formulée.' },
    { question: 'Comment choisir entre SCPI en direct et assurance-vie ?', answer: 'Le choix dépend de la situation fiscale, de l\'horizon, des objectifs successoraux et du besoin de liquidité. L\'assurance-vie offre une fiscalité allégée des rachats. La détention directe offre un choix plus large de SCPI.' },
    { question: 'La fiscalité peut-elle réduire fortement le rendement d\'une SCPI ?', answer: 'Oui, selon la TMI, les prélèvements sociaux et l\'IFI, le rendement net de fiscalité peut être significativement inférieur au taux de distribution affiché. Une simulation personnalisée est recommandée.' },
    { question: 'Peut-on revendre facilement ses parts de SCPI ?', answer: 'Non, les parts de SCPI sont des actifs non cotés. Le délai de revente peut varier de quelques mois à plusieurs années. Un horizon de 8 à 10 ans est généralement recommandé.' },
    { question: 'Faut-il acheter des SCPI à crédit ?', answer: 'L\'achat à crédit peut permettre un effet de levier mais augmente le risque. La décision dépend de la situation fiscale et de l\'horizon de placement. Une analyse personnalisée est nécessaire.' },
    { question: 'Le démembrement de SCPI est-il adapté à tous les profils ?', answer: 'Non, le démembrement temporaire n\'est pas adapté à tous les profils. Le conseiller vérifie la cohérence avec les objectifs et l\'horizon.' },
    { question: 'Une SCPI est-elle adaptée à un objectif court terme ?', answer: 'Non, une SCPI n\'est pas adaptée à un objectif court terme en raison du risque de liquidité, des frais d\'entrée et de la volatilité potentielle du prix de part.' },
    { question: 'Une recommandation SCPI peut-elle être faite sans analyse du profil investisseur ?', answer: 'Non. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable de la situation du client : profil investisseur, connaissances, expérience, capacité de perte, objectifs et horizon d\'investissement.' },
  ],
  ctaTitle: 'Vous souhaitez vérifier la cohérence de votre projet SCPI ?',
  ctaText: 'Un échange permet d\'identifier les points à analyser avant une souscription : fiscalité, horizon, mode de détention, risques, liquidité et cohérence avec votre patrimoine global.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
