import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'conseiller-patrimoine-en-ligne',
  category: 'patrimoine',
  title: 'Conseiller en gestion de patrimoine en ligne : fonctionnement et intérêt',
  metaTitle: 'Conseiller en gestion de patrimoine en ligne : fonctionnement et intérêt | Eric Bellaiche',
  metaDescription: "Le conseiller en gestion de patrimoine en ligne permet un accompagnement à distance en visioconférence : analyse fiscale, placements, immobilier, retraite, transmission. Fonctionnement, avantages, réglementation CGP-CIF.",
  canonical: 'https://eric-bellaiche.fr/articles/conseiller-patrimoine-en-ligne/',
  badge: 'Conseiller patrimoine en ligne &bull; CGP-CIF &bull; ORIAS 13001580',
  intro: "Longtemps réservé à une clientèle fortunée située dans les grandes métropoles, le conseil en gestion de patrimoine s'est largement démocratisé avec l'essor de la visioconférence et des outils numériques sécurisés. Aujourd'hui, un particulier peut bénéficier d'un accompagnement patrimonial complet depuis son domicile, quel que soit son lieu de résidence en France. Le conseiller en gestion de patrimoine en ligne offre le même niveau d'expertise et les mêmes garanties réglementaires qu'un cabinet traditionnel, avec une flexibilité accrue. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, accompagne ses clients à distance dans l'analyse et la structuration de leur patrimoine.",
  shortAnswer: "Un conseiller en gestion de patrimoine en ligne (CGP-CIF) réalise des missions d'analyse patrimoniale, de conseil en investissement et de suivi personnalisé par visioconférence sécurisée. Il intervient sur les mêmes domaines qu'un conseiller en cabinet : fiscalité, placements financiers (assurance-vie, PER, PEA, SCPI), immobilier, retraite, prévoyance, transmission. La différence réside dans les modalités d'échange : rendez-vous à distance, partage dématérialisé de documents, signature électronique. Le cadre réglementaire est strictement identique : analyse préalable de la situation, déclaration d'adéquation, information sur les risques, interdiction de promesse de rendement. Le CGP en ligne permet d'accéder à un conseil patrimonial de qualité sans contrainte géographique.",
  summaryItems: [
    { label: "Qu'est-ce qu'un conseiller en gestion de patrimoine en ligne ?", anchor: 'quest-ce-quun-cgp-en-ligne' },
    { label: 'Comment se déroule un accompagnement à distance ?', anchor: 'deroulement-accompagnement' },
    { label: 'Avantages du CGP en ligne par rapport au cabinet traditionnel', anchor: 'avantages-cgp-en-ligne' },
    { label: 'Tableau comparatif : CGP en ligne vs CGP traditionnel', anchor: 'tableau-comparatif' },
    { label: "Ce que le CGP en ligne peut faire (et ne peut pas faire)", anchor: 'pouvoirs-cgp-en-ligne' },
    { label: "Réglementation et obligations du CGP-CIF à distance", anchor: 'reglementation-cgp' },
    { label: 'Erreurs fréquentes dans le choix d\'un conseiller en ligne', anchor: 'erreurs-choix-conseiller' },
    { label: 'Exemple pédagogique anonymisé', anchor: 'exemple-pedagogique' },
    { label: "Méthode Eric Bellaiche pour l'accompagnement patrimonial à distance", anchor: 'methode' },
    { label: 'Points de vigilance sur le conseil en ligne', anchor: 'points-vigilance' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 18,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['conseiller patrimoine', 'CGP', 'en ligne', 'visioconférence', 'accompagnement', 'CGP-CIF'],
  sections: [
    {
      id: 'quest-ce-quun-cgp-en-ligne',
      title: "Qu'est-ce qu'un conseiller en gestion de patrimoine en ligne ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Un conseiller en gestion de patrimoine (CGP) en ligne est un professionnel de la gestion de patrimoine inscrit au registre ORIAS en tant que CGP-CIF (Conseiller en Investissements Financiers) qui exerce tout ou partie de son activité à distance. Il utilise des outils numériques pour réaliser des audits patrimoniaux, proposer des recommandations d'investissement et assurer le suivi des stratégies mises en place.",
        "Le CGP en ligne n'est pas un conseiller robot ou un algorithme. C'est un expert humain, soumis aux mêmes obligations réglementaires, déontologiques et de formation qu'un conseiller exerçant en cabinet physique. La différence tient essentiellement au mode de relation client : les rendez-vous se font par visioconférence, les documents sont échangés par voie électronique sécurisée, et les signatures sont dématérialisées.",
        "Cette modalité d'exercice s'est développée avec la généralisation des outils de visioconférence, l'évolution des attentes des clients (flexibilité, réactivité, mobilité) et la reconnaissance de la signature électronique comme équivalent à la signature manuscrite. Elle répond également à un besoin de couverture territoriale : un CGP en ligne peut accompagner un client à Paris, à Marseille, dans une commune rurale ou à l'étranger.",
        "Les missions du CGP en ligne sont strictement identiques à celles d'un CGP traditionnel : analyse de la situation patrimoniale et fiscale, conseil en investissement, aide à la structuration du patrimoine, accompagnement sur la retraite, la prévoyance, la transmission et l'optimisation fiscale. La seule différence est l'absence de déplacement physique, compensée par des échanges visio réguliers et un suivi documenté.",
        "Le recours à un CGP en ligne est particulièrement adapté aux profils suivants : actifs très mobiles, professions libérales avec des horaires denses, expatriés, résidents dans des zones peu desservies par les cabinets patrimoniaux, ou simplement toute personne préférant la flexibilité du distanciel.",
      ],
    },
    {
      id: 'deroulement-accompagnement',
      title: 'Comment se déroule un accompagnement patrimonial à distance ?',
      level: 'h2',
      type: 'normal',
      content: [
        "L'accompagnement par un conseiller en gestion de patrimoine en ligne suit un processus structuré, comparable à celui d'un cabinet traditionnel. Voici les grandes étapes d'une relation type :",
        "1. Premier échange gratuit et sans engagement : un rendez-vous téléphonique ou visio de 20 à 30 minutes permet de comprendre votre situation, vos attentes, vos projets et de vérifier que le conseiller peut vous apporter une réponse adaptée. C'est aussi le moment de clarifier le cadre de la mission, les honoraires et les modalités pratiques.",
        "2. Audit patrimonial : si vous donnez suite, le conseiller vous demande de lui transmettre un ensemble de documents (avis d'imposition, relevés de comptes, contrats d'assurance-vie, PER, actes immobiliers, crédits en cours, situation familiale). Il analyse ces éléments et établit un diagnostic complet de votre situation.",
        "3. Présentation des préconisations : lors d'un rendez-vous visio dédié, le conseiller vous présente les résultats de l'analyse, les forces et faiblesses de votre patrimoine, et les pistes d'optimisation envisageables. Il compare plusieurs scénarios et vous explique les implications fiscales, juridiques et financières.",
        "4. Mise en œuvre et suivi : si vous validez les orientations proposées, le conseiller vous accompagne dans la mise en place des décisions : ouverture de contrats, arbitrages, souscriptions, donation, etc. Il assure un suivi périodique (annuel ou semestriel) pour ajuster la stratégie en fonction de l'évolution de votre situation et des marchés.",
        "Tout au long de ce processus, les échanges se font par visioconférence, email sécurisé ou téléphone. Les documents sont partagés via des plateformes sécurisées conformes au RGPD. La signature des lettres de mission et des documents contractuels se fait par signature électronique, reconnue comme ayant la même valeur juridique que la signature manuscrite.",
      ],
    },
    {
      id: 'avantages-cgp-en-ligne',
      title: 'Avantages du CGP en ligne par rapport au cabinet traditionnel',
      level: 'h2',
      type: 'normal',
      content: [
        "Le conseil en gestion de patrimoine en ligne présente des avantages significatifs qui expliquent son essor rapide. Ces avantages ne se limitent pas à la simple commodité : ils transforment en profondeur l'accessibilité et la qualité de la relation de conseil.",
        "Accessibilité géographique : le premier avantage est l'élimination des contraintes de déplacement. Que vous habitiez à Paris, à Lyon, dans une petite ville de province ou à l'étranger, vous pouvez bénéficier du même niveau d'expertise. Cette accessibilité est particulièrement précieuse pour les personnes vivant dans des zones où l'offre de conseil patrimonial est limitée ou inexistante.",
        "Flexibilité horaire : les rendez-vous en visioconférence peuvent être organisés en fonction de vos contraintes, y compris en soirée ou le week-end. Cette flexibilité est essentielle pour les actifs qui ne peuvent pas se libérer en journée, ou pour les professions libérales aux horaires irréguliers.",
        "Gain de temps : fini les déplacements en transport ou en voiture pour un rendez-vous d'une heure. La visioconférence permet un échange direct depuis votre domicile ou votre bureau, sans temps de trajet. Ce gain de temps facilite également la régularité des rendez-vous de suivi.",
        "Dématérialisation complète : la transmission des documents se fait par email sécurisé ou plateforme dédiée, la signature est électronique, les comptes-rendus sont envoyés par voie numérique. Tout est tracé, horodaté et conservé dans un espace client sécurisé.",
        "Mêmes garanties réglementaires : contrairement à une idée reçue, le conseil à distance n'est pas moins réglementé que le conseil en présentiel. Le CGP-CIF en ligne est soumis aux mêmes obligations : analyse préalable de la situation, déclaration d'adéquation, information sur les risques, transparence des frais, absence de promesse de rendement, assurance responsabilité civile professionnelle.",
        "Suivi réactif : le conseiller en ligne peut être contacté plus facilement par email ou téléphone entre les rendez-vous. Les échanges sont plus fréquents et souvent plus réactifs que dans un cabinet traditionnel où les agendas sont plus contraints.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif : CGP en ligne vs CGP en cabinet traditionnel',
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous compare les principales caractéristiques du conseil en gestion de patrimoine en ligne par rapport au conseil en cabinet traditionnel. Ces éléments vous aideront à choisir la modalité la mieux adaptée à vos besoins et à votre mode de vie.",
      ],
      table: {
        headers: ['Critère', 'CGP en ligne', 'CGP en cabinet traditionnel'],
        rows: [
          ['Lieu des rendez-vous', 'Visioconférence (domicile, bureau)', 'Cabinet physique (déplacement nécessaire)'],
          ['Disponibilité horaire', 'Soirée et week-end possibles', 'Horaires de bureau habituels'],
          ['Délai d\'obtention d\'un rendez-vous', 'Souvent 24 à 72 heures', 'Parfois 1 à 2 semaines'],
          ['Zone de couverture', 'France entière et international', 'Agence locale ou régionale'],
          ['Transmission des documents', 'Plateforme sécurisée, email crypté', 'Remise en main propre ou courrier'],
          ['Signature des documents', 'Signature électronique (valeur légale)', 'Signature manuscrite'],
          ['Relation client', 'À distance, avec visio régulière', 'En présentiel'],
          ["Qualification réglementaire", "CGP-CIF (identique)", "CGP-CIF (identique)"],
          ['Analyse préalable obligatoire', 'Oui', 'Oui'],
          ["Déclaration d'adéquation", 'Oui (identique)', 'Oui (identique)'],
          ['Assurance RC Pro', 'Obligatoire (identique)', 'Obligatoire (identique)'],
          ['Inscription ORIAS', 'Obligatoire (identique)', 'Obligatoire (identique)'],
          ['Suivi annuel', 'Possible et recommandé', 'Possible et recommandé'],
          ['Forfait ou honoraires', 'Transparence obligatoire', 'Transparence obligatoire'],
        ],
      },
    },
    {
      id: 'pouvoirs-cgp-en-ligne',
      title: "Ce que le CGP en ligne peut faire (et ne peut pas faire)",
      level: 'h2',
      type: 'list',
      content: [
        "Le périmètre d'intervention d'un conseiller en gestion de patrimoine en ligne couvre un large spectre, mais il existe des limites claires qu'il est important de connaître. Voici ce qu'il peut et ne peut pas faire :",
      ],
      listItems: [
        "Analyser votre situation patrimoniale et fiscale dans son ensemble, en prenant en compte vos revenus, vos actifs, vos dettes et vos objectifs.",
        "Vous recommander des investissements adaptés à votre profil, après avoir réalisé une analyse préalable complète de votre situation.",
        "Vous orienter vers des enveloppes fiscales adaptées : assurance-vie, PER, PEA, immobilier locatif, SCPI.",
        "Vous accompagner dans la constitution de votre dossier de crédit immobilier, sans pouvoir vous prêter directement des fonds.",
        "Vous aider à structurer votre transmission : donation, assurance-vie, démembrement, SCI.",
        "Vous conseiller sur votre prévoyance : couverture décès, invalidité, incapacité.",
        "Ne peut PAS vous faire de promesse de rendement sur un investissement (interdiction réglementaire absolue pour un CGP-CIF).",
        'Ne peut PAS vous garantir une réduction d\'impôt sans analyse préalable de votre situation fiscale complète.',
        "Ne peut PAS gérer directement vos comptes ou effectuer des transactions à votre place (le CGP conseille, vous décidez).",
        "Ne peut PAS vous vendre des produits sans avoir vérifié leur adéquation avec votre profil investisseur.",
        "Ne peut PAS intervenir sur des aspects juridiques relevant du notaire (testament, donation notariée, divorce).",
      ],
    },
    {
      id: 'reglementation-cgp',
      title: "Réglementation et obligations du CGP-CIF à distance",
      level: 'h2',
      type: 'normal',
      content: [
        "Le conseiller en gestion de patrimoine en ligne est soumis à la même réglementation qu'un CGP-CIF exerçant en cabinet physique. Cette réglementation, issue de la directive européenne MIF (Marchés d'Instruments Financiers) et du code monétaire et financier, impose des obligations strictes destinées à protéger le client.",
        "L'inscription au registre ORIAS est obligatoire pour tout CGP-CIF, quel que soit son mode d'exercice. Cette inscription est publique et vérifiable sur le site de l'ORIAS. Elle garantit que le conseiller a souscrit une assurance responsabilité civile professionnelle et respecte les exigences de compétence et d'honorabilité.",
        "Les principales obligations réglementaires applicables au CGP en ligne sont les suivantes :",
        "- Obligation d'analyse préalable : avant toute recommandation d'investissement, le conseiller doit analyser la situation personnelle du client, ses connaissances financières, son expérience, ses objectifs, son horizon de placement et sa capacité de perte.",
        "- Déclaration d'adéquation : toute recommandation d'investissement doit être formalisée dans une déclaration d'adéquation qui explique en quoi le produit ou le service est adapté au profil du client.",
        "- Information précontractuelle : le client doit recevoir une information claire, exacte et non trompeuse sur les frais, les risques, les caractéristiques des produits et les modalités de la relation.",
        "- Absence de promesse de rendement : le CGP-CIF ne peut en aucun cas garantir un rendement ou un résultat.",
        "- Gestion des conflits d'intérêts : le conseiller doit identifier, prévenir et gérer les situations de conflit d'intérêts, et informer le client lorsqu'un conflit ne peut être évité.",
        "- Conservation des documents : les documents relatifs à la relation client doivent être conservés pendant 5 ans.",
        "Ces obligations, applicables dans les mêmes conditions en présentiel et à distance, offrent une protection équivalente au client, quel que soit le mode de consultation choisi.",
      ],
    },
    {
      id: 'erreurs-choix-conseiller',
      title: "Erreurs fréquentes dans le choix d'un conseiller en ligne",
      level: 'h2',
      type: 'list',
      content: [
        "Le choix d'un conseiller en gestion de patrimoine en ligne mérite la même attention que celui d'un conseiller en cabinet. Voici les erreurs les plus fréquentes à éviter :",
      ],
      listItems: [
        "Ne pas vérifier l'inscription ORIAS du conseiller. Tout CGP-CIF doit être enregistré sur le site www.orias.fr. L'absence d'inscription est un signal d'alarme immédiat.",
        "Choisir un conseiller uniquement sur le critère du prix. Un accompagnement patrimonial de qualité a un coût, et un conseil trop bon marché peut cacher des frais cachés ou des commissions non déclarées.",
        "Confier son patrimoine à un conseiller qui promet des rendements élevés. Un CGP-CIF n'a pas le droit de promettre un rendement. Si un conseiller le fait, il enfreint la réglementation.",
        "Ne pas vérifier les domaines d'expertise du conseiller. Certains CGP sont spécialisés en SCPI, d'autres en retraite ou en transmission. Vérifiez que son expertise correspond à vos besoins.",
        "Signer une lettre de mission sans comprendre les honoraires. Les frais doivent être clairement indiqués : honoraires forfaitaires, commission sur souscription, frais de gestion annuels. Exigez une transparence totale.",
        "Ne pas poser de questions lors du premier échange. Le premier rendez-vous gratuit est l'occasion de tester la compétence et la pédagogie du conseiller. Profitez-en pour poser toutes vos questions.",
        "Choisir un conseiller sans vérifier son assurance RC Pro. Tout CGP-CIF doit avoir une assurance responsabilité civile professionnelle. Demandez-en la preuve.",
        "Se laisser influencer par une promesse de défiscalisation rapide. Les montages fiscaux promettant des économies d'impôt immédiates sont souvent risqués ou disproportionnés.",
        "Ne pas comparer plusieurs conseillers. Comme pour tout prestataire de service, il est prudent de rencontrer 2 à 3 conseillers avant de faire son choix.",
        "Négliger la qualité de la relation humaine. Même à distance, la relation de confiance est essentielle. Si le courant ne passe pas lors du premier échange, il est préférable de continuer à chercher.",
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique anonymisé',
      level: 'h2',
      type: 'normal',
      content: [
        'Situation : un cadre dirigeant de 52 ans, célibataire, sans enfant, habitant à Bordeaux. Revenus annuels : 180 000 €. TMI : 41 %. Résidence principale : 550 000 €, crédit en cours 80 000 € à 0,9 % sur 8 ans. Assurance-vie : 200 000 € sur un contrat unique, frais de gestion 0,75 %, supports diversifiés. PEA : 50 000 € investi en actions. PER : 80 000 €, plafond disponible 35 000 €. Épargne de précaution : 60 000 € sur livret A. Pas d\'immobilier locatif. Pas de prévoyance décès. Objectif : préparer sa retraite à 62 ans et optimiser sa fiscalité actuelle.',
        "Sans accompagnement : le client pourrait maximiser son versement PER pour réduire son impôt (35 000 € déductibles), sans vérifier si sa TMI future à la retraite sera suffisamment basse pour que l'opération soit fiscalement avantageuse. Il pourrait également souscrire un investissement locatif sans analyser l'impact IFI et le rendement net après TMI 41 % + PS 17,2 %.",
        "Après accompagnement par un CGP en ligne : plusieurs pistes sont identifiées et comparées :",
        "1. Analyse du PER : simulation de la TMI à la retraite estimée à 30 %. Le versement PER est partiellement pertinent, mais il faut comparer avec un investissement en assurance-vie (fiscalité plus souple à la sortie).",
        "2. Arbitrage de l'épargne de précaution : 60 000 € sur livret A est excessif pour un célibataire sans enfant. Réduction à 30 000 € et réinvestissement du solde sur l'assurance-vie ou le PEA.",
        "3. Mise en place d'une prévoyance : le client n'a pas de personne à charge, mais une garantie incapacité de travail est pertinente pour protéger ses revenus élevés jusqu'à la retraite.",
        "4. Diversification immobilière : étude de la pertinence d'une SCPI via assurance-vie, qui permet de diversifier sans alourdir l'IFI (car détenue en unité de compte dans un contrat d'assurance-vie de moins de 150 000 € de valeur de rachat).",
        "5. Comparaison de plusieurs scénarios de répartition PER/assurance-vie/immobilier pour déterminer le meilleur équilibre fiscal et financier.",
        "Cet exemple anonymisé ne constitue pas une recommandation personnalisée. Chaque situation nécessite une analyse spécifique préalable.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour l'accompagnement patrimonial à distance",
      level: 'h2',
      type: 'method-steps',
      content: [
        "Eric Bellaiche, CGP-CIF, applique une méthode structurée en 6 étapes pour chaque accompagnement patrimonial à distance. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète de la situation, du profil investisseur, des objectifs, de l'horizon et de la capacité de perte.",
      ],
      methodSteps: [
        { title: 'Premier contact et cadrage', description: "Échange gratuit par téléphone ou visio pour comprendre votre situation, vos attentes, vos projets patrimoniaux. Clarification du périmètre de la mission, des documents nécessaires, des honoraires et des modalités pratiques de l'accompagnement à distance." },
        { title: 'Recueil et analyse des documents', description: "Transmission sécurisée de vos documents : avis d'imposition, relevés de comptes, contrats d'assurance-vie, PER, PEA, actes immobiliers, crédits, prévoyance, situation familiale. Analyse complète de votre situation patrimoniale, fiscale et personnelle." },
        { title: 'Diagnostic patrimonial', description: "Identification des forces, faiblesses et incohérences de votre patrimoine. Analyse de votre fiscalité (TMI, IFI, plus-values), de votre capacité d'épargne, de votre endettement, de votre exposition au risque et de votre préparation à la retraite." },
        { title: 'Analyse du profil investisseur', description: "Évaluation de vos connaissances financières, de votre expérience en investissement, de votre capacité de perte, de votre horizon de placement et de votre sensibilité au risque. Cette analyse est obligatoire avant toute recommandation d'investissement." },
        { title: 'Préconisations et comparaison de scénarios', description: "Présentation en visioconférence des pistes d'optimisation identifiées, avec comparaison de plusieurs scénarios. Analyse des impacts fiscaux, financiers et successoraux de chaque option. Vous disposez de tous les éléments pour prendre vos décisions en connaissance de cause." },
        { title: 'Mise en œuvre et suivi périodique', description: "Accompagnement dans la mise en place des décisions : arbitrages, ouvertures de contrats, souscriptions, démarches administratives. Suivi annuel ou semestriel pour ajuster la stratégie en fonction de l'évolution de votre situation personnelle, fiscale et des marchés." },
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance sur le conseil en gestion de patrimoine en ligne',
      level: 'h2',
      type: 'normal',
      content: [
        "Le conseil en gestion de patrimoine en ligne présente de nombreux atouts, mais il convient d'être attentif à certains points spécifiques avant de s'engager :",
        "- La qualité de la connexion internet et de l'équipement (webcam, micro) est essentielle pour des échanges visio fluides. Un problème technique récurrent peut nuire à la qualité de la relation.",
        "- La relation à distance peut convenir à la majorité des situations, mais certaines personnes préfèrent un contact physique pour des sujets sensibles comme la transmission ou les questions familiales.",
        "- Vérifiez que le conseiller utilise des outils de partage de documents conformes au RGPD et des plateformes de visioconférence sécurisées.",
        "- Assurez-vous que le conseiller est bien inscrit à l'ORIAS et que son numéro d'inscription est vérifiable. Méfiez-vous des conseillers qui n'affichent pas clairement leur statut réglementaire.",
        "- Le conseil en ligne est adapté à la plupart des situations, mais les dossiers très complexes (succession internationale, fiscalité multi-pays, patrimoine d'entreprise) peuvent nécessiter des échanges en présentiel ou une coordination avec d'autres professionnels (notaire, expert-comptable).",
        "- Un accompagnement patrimonial de qualité ne se limite pas à un rendez-vous unique. Assurez-vous que le conseiller propose un suivi dans la durée.",
        "Ces points de vigilance ne remettent pas en cause la pertinence du conseil en ligne, mais permettent d'aborder cette modalité avec les bonnes précautions.",
      ],
    },
  ],
  faq: [
    { question: "Qu'est-ce qu'un conseiller en gestion de patrimoine en ligne ?", answer: "C'est un CGP-CIF qui exerce à distance par visioconférence. Il réalise les mêmes missions qu'un conseiller en cabinet : analyse patrimoniale, conseil en investissement, accompagnement retraite, transmission, prévoyance. Il est soumis à la même réglementation." },
    { question: "Est-ce qu'un CGP en ligne est moins compétent qu'un conseiller en cabinet ?", answer: "Non, la qualification et la réglementation sont strictement identiques. Le CGP en ligne est inscrit à l'ORIAS, soumis à une obligation de formation continue, et doit respecter les mêmes obligations d'analyse préalable et de déclaration d'adéquation." },
    { question: "Comment se passe la signature des documents à distance ?", answer: "La signature électronique est reconnue comme ayant la même valeur juridique que la signature manuscrite. Les documents sont signés via une plateforme sécurisée, avec un processus d'authentification du signataire." },
    { question: "Puis-je faire confiance à un CGP en ligne pour des questions patrimoniales sensibles ?", answer: "Oui, le CGP-CIF est soumis au secret professionnel et à des obligations de confidentialité strictes. Les échanges sont protégés et les documents sont transmis sur des plateformes sécurisées conformes au RGPD." },
    { question: "Quels sont les honoraires d'un CGP en ligne ?", answer: "Les honoraires sont librement fixés par le conseiller, mais doivent être transparents et communiqués avant tout engagement. Ils peuvent prendre la forme d'honoraires forfaitaires, de commissions sur souscription ou d'une combinaison des deux." },
    { question: "Le CGP en ligne peut-il me recommander des investissements immobiliers ?", answer: "Oui, le CGP peut vous conseiller sur l'opportunité et la structuration d'un investissement immobilier (locatif, SCPI, SCI), en analysant l'impact fiscal, le rendement net et la cohérence avec votre patrimoine global." },
    { question: "Un CGP en ligne peut-il suivre un client expatrié ?", answer: "Oui, le conseil en ligne est particulièrement adapté aux expatriés, sous réserve que le conseiller connaisse les conventions fiscales applicables. Certaines situations complexes peuvent nécessiter un expert en fiscalité internationale." },
    { question: "Comment vérifier qu'un CGP en ligne est bien inscrit à l'ORIAS ?", answer: "Rendez-vous sur le site www.orias.fr, saisissez le nom du conseiller ou sa société dans le moteur de recherche. Vérifiez que la mention CGP-CIF apparaît et que l'inscription est en cours de validité." },
    { question: "Puis-je changer de conseiller si je ne suis pas satisfait ?", answer: "Oui, vous pouvez à tout moment interrompre la relation, sous réserve des conditions prévues dans la lettre de mission. Il est recommandé de vérifier les modalités de résiliation avant de signer." },
    { question: "Le CGP en ligne peut-il m'aider à préparer ma retraite ?", answer: "Oui, l'accompagnement retraite fait partie des missions clés du CGP en ligne : estimation des droits, calcul du taux de remplacement, choix des enveloppes (PER, assurance-vie, immobilier), optimisation fiscale des versements." },
  ],
  ctaTitle: 'Vous souhaitez être accompagné par un conseiller en gestion de patrimoine en ligne ?',
  ctaText: 'Un premier échange gratuit permet de faire le point sur votre situation et de vérifier qu\'un accompagnement à distance est adapté à vos besoins. Aucun engagement, aucune recommandation personnalisée sans analyse préalable.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne : méthode et analyse', position: 'inline' },
    { href: '/articles/structurer-son-patrimoine/', label: 'Structurer son patrimoine : méthode et organisation', position: 'inline' },
    { href: '/articles/erreurs-gestion-patrimoine/', label: 'Les erreurs fréquentes en gestion de patrimoine', position: 'inline' },
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
  ],
};

export default article;
