import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'conseiller-scpi',
  category: 'scpi',
  title: 'Conseiller SCPI : pourquoi se faire accompagner avant d\'investir',
  metaTitle: 'Conseiller SCPI : pourquoi se faire accompagner avant d\'investir',
  metaDescription: 'Avant d\'investir en SCPI, un conseiller CGP-CIF peut analyser votre fiscalité, votre horizon, votre profil investisseur, le mode de détention, les risques et la cohérence patrimoniale du projet.',
  canonical: 'https://eric-bellaiche.fr/articles/conseiller-scpi/',
  badge: 'SCPI &bull; Conseil CGP-CIF &bull; ORIAS 13001580',
  intro: 'La SCPI attire par son taux de distribution affiché. Mais investir dans une SCPI sans analyse préalable expose à des risques fiscaux, de liquidité et de cohérence patrimoniale. Un conseiller CGP-CIF ne se limite pas à comparer des rendements : il analyse la situation globale, le profil investisseur, la fiscalité, l\'horizon et le mode de détention. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous accompagne dans cette démarche.',
  shortAnswer: 'Un conseiller SCPI aide à vérifier si l\'investissement est adapté à votre fiscalité, votre horizon, votre capacité de perte, vos objectifs et votre mode de détention. Le rendement affiché ne suffit pas : il faut analyser la liquidité, les frais, le risque immobilier, la fiscalité, la diversification et la cohérence avec votre patrimoine global. Aucune recommandation personnalisée n\'est formulée sans analyse préalable.',
  summaryItems: [
    { label: 'Pourquoi le rendement d\'une SCPI ne suffit pas', anchor: 'pourquoi-rendement-ne-suffit-pas' },
    { label: 'Ce qu\'un CGP-CIF analyse avant une recommandation', anchor: 'ce-qu-un-conseiller-scpi-analyse' },
    { label: 'Les différents modes de détention d\'une SCPI', anchor: 'modes-de-detention' },
    { label: 'Les erreurs fréquentes avant une souscription SCPI', anchor: 'erreurs-frequentes' },
    { label: 'Les risques à connaître avant d\'investir', anchor: 'risques' },
    { label: 'Exemple pédagogique : l\'impact du mode de détention', anchor: 'exemple-pedagogique' },
    { label: 'La méthode Eric Bellaiche pour analyser un projet SCPI', anchor: 'methode' },
    { label: 'Quand consulter un conseiller SCPI ?', anchor: 'quand-consulter' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 18,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'conseiller SCPI', 'investissement SCPI', 'CGP-CIF', 'fiscalité', 'mode de détention', 'risques SCPI'],
  sections: [
    {
      id: 'pourquoi-rendement-ne-suffit-pas',
      title: 'Pourquoi le rendement d\'une SCPI ne suffit pas',
      level: 'h2',
      type: 'normal',
      content: [
        'Le taux de distribution (TD) est l\'indicateur le plus visible, mais aussi le plus trompeur. Un TD de 6 % peut sembler attractif, mais plusieurs facteurs réduisent le rendement réellement perçu par l\'investisseur.',
        'Le rendement brut affiché ne tient compte :',
        "- ni de la fiscalité personnelle de l'investisseur (TMI et prélèvements sociaux) ;",
        "- ni des frais de souscription, qui peuvent atteindre 8 à 12 % ;",
        "- ni du délai de jouissance, période durant laquelle les premières distributions ne sont pas perçues malgré le versement des fonds ;",
        "- ni de la performance passée, qui n'est pas garantie pour l'avenir ;",
        "- ni du risque de concentration sectorielle ou géographique.",
        'Un investisseur qui ne regarde que le rendement brut peut sous-estimer l\'impact fiscal (qui peut diviser le rendement par deux pour une TMI élevée), négliger le risque de liquidité (revente pouvant prendre plusieurs mois à plusieurs années) et ignorer la cohérence de l\'investissement avec son patrimoine global.',
      ],
    },
    {
      id: 'ce-qu-un-conseiller-scpi-analyse',
      title: 'Ce qu\'un CGP-CIF analyse avant une recommandation',
      level: 'h2',
      type: 'table',
      content: [
        'Avant toute recommandation personnalisée, Eric Bellaiche, CGP-CIF, analyse systématiquement les critères suivants. Chaque critère a un impact direct sur la pertinence de l\'investissement.',
      ],
      table: {
        headers: ['Critère', 'Pourquoi c\'est important', 'Impact possible'],
        rows: [
          ['TMI (tranche marginale d\'imposition)', 'Détermine l\'impôt sur les revenus fonciers', 'Un TMI à 30 %, 41 % ou 45 % réduit fortement le rendement net'],
          ['Prélèvements sociaux', '17,2 % sur tous les revenus SCPI', 'Rendement net réduit de plus de 17 points de base'],
          ['IFI', 'Les SCPI en direct sont incluses dans le patrimoine immobilier', 'Impact fiscal supplémentaire pour les redevables IFI'],
          ['Horizon de placement', 'Compatibilité avec la duration SCPI (8-10 ans minimum)', 'Un horizon trop court peut générer une moins-value'],
          ['Capacité de perte', 'Évalue la tolérance au risque financier', 'Détermine la part du patrimoine investissable en SCPI'],
          ['Besoin de liquidité', 'Les SCPI sont peu liquides', 'Un besoin élevé peut déconseiller l\'investissement'],
          ['Objectif de revenus vs capitalisation', 'Recherche de revenus réguliers ou de valorisation long terme', 'Oriente le choix entre SCPI de rendement et SCPI fiscales'],
          ['Mode de détention', 'Direct, assurance-vie, crédit, démembrement, SCI', 'Impacte la fiscalité, les frais, la liquidité et la transmission'],
          ['Diversification sectorielle', 'Répartition bureaux, commerces, logistique, santé', 'Une concentration sectorielle augmente le risque'],
          ['Valeur de reconstitution vs prix de souscription', 'Indicateur de survalorisation potentielle', 'Une prime d\'émission élevée peut signaler un risque'],
          ['TOF (taux d\'occupation financier)', 'Mesure l\'efficacité locative', 'Un TOF bas indique des périodes de vacance fréquentes'],
          ['Capitalisation de la SCPI', 'Taille du véhicole et liquidité du marché secondaire', 'Une capitalisation élevée favorise la revente'],
        ],
      },
    },
    {
      id: 'modes-de-detention',
      title: 'Les différents modes de détention d\'une SCPI',
      level: 'h2',
      type: 'table',
      content: [
        'Les SCPI peuvent être détenues de plusieurs manières. Chaque mode de détention a des implications fiscales, successorales, financières et pratiques distinctes. Aucun mode n\'est meilleur en soi : le choix dépend de la situation personnelle de l\'investisseur.',
      ],
      table: {
        headers: ['Mode de détention', 'Fiscalité des revenus', 'Fiscalité des plus-values', 'Liquidité', 'Transmission', 'Profil concerné'],
        rows: [
          ['Direct', 'IR (TMI + PS)', 'IR + PS sur plus-values', 'Marché secondaire (délai variable)', 'Droits de mutation', 'Simplicité et choix large'],
          ['Assurance-vie', 'Capitalisation différée', 'Abattement après 8 ans', 'Rachat du contrat (délai variable)', 'Cadre avantageux', 'Transmission et long terme'],
          ['Crédit', 'Intérêts déductibles', 'IR + PS sur plus-value nette', 'Vente des parts ou remboursement', 'Transmission avec crédit', 'Effet de levier'],
          ['Démembrement', 'Aucun (perçus par l\'usufruitier)', 'Pas d\'imposition à la réunification', 'Cession de nue-propriété', 'Optimisation transmission', 'Transmission sans revenu'],
          ['Via SCI', 'IR ou IS selon régime', 'IR ou IS selon régime', 'Cession de parts sociales', 'Transmission de parts', 'Gestion collective'],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Les erreurs fréquentes avant une souscription SCPI',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que certaines erreurs reviennent régulièrement lors d\'un premier investissement en SCPI :'],
      listItems: [
        'Choisir uniquement sur le rendement : le TD ne reflète ni la fiscalité, ni les frais, ni la qualité du patrimoine sous-jacent.',
        'Ignorer la fiscalité personnelle : un TD de 6 % peut se transformer en 2,5 % net après impôt selon la TMI.',
        'Investir sur une seule SCPI : l\'absence de diversification augmente fortement le risque.',
        'Négliger la liquidité : croire qu\'on peut revendre ses parts en quelques semaines est une erreur fréquente.',
        'Oublier le délai de jouissance : les premières distributions peuvent intervenir 3 à 6 mois après la souscription.',
        'Confondre revenus bruts et revenus nets : frais de gestion, fiscalité et prélèvements réduisent le rendement effectif.',
        'Ne pas vérifier la valeur de reconstitution : un prix de souscription très supérieur peut indiquer une survalorisation.',
        'Investir trop court terme : les SCPI sont inadaptées aux horizons de moins de 8 ans.',
        'Ne pas anticiper la transmission : le mode de détention impacte directement la transmission.',
        'Négliger l\'impact d\'un crédit : l\'effet de levier amplifie les gains comme les pertes.',
        'Souscrire sans analyse du profil investisseur : une recommandation SCPI ne peut pas être formulée sans évaluation préalable.',
      ],
    },
    {
      id: 'risques',
      title: 'Les risques à connaître avant d\'investir en SCPI',
      level: 'h2',
      type: 'risk',
      content: [
        'Comme tout investissement immobilier et financier, les SCPI comportent des risques qu\'il est essentiel de connaître avant toute souscription.',
      ],
      listItems: [
        'Risque de perte en capital : le prix des parts peut baisser, et le capital investi n\'est pas garanti.',
        'Risque de baisse des revenus : le taux de distribution peut varier à la baisse d\'une année sur l\'autre.',
        'Risque de liquidité : la revente peut prendre plusieurs mois à plusieurs années selon la SCPI.',
        'Risque immobilier : la valeur du patrimoine sous-jacent peut évoluer défavorablement.',
        'Risque de taux : une hausse des taux peut impacter les valorisations et le rendement.',
        'Risque fiscal : la législation fiscale peut évoluer en cours de détention.',
        'Risque lié au mode de détention : chaque mode comporte ses propres risques (crédit, assurance-vie, SCI).',
        'Horizon long terme : 8 à 10 ans sont généralement recommandés pour lisser les cycles immobiliers.',
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : l\'impact du mode de détention sur le rendement net',
      level: 'h2',
      type: 'table',
      content: [
        "L'exemple ci-dessous compare le rendement net estimé d'une SCPI affichant un TD de 6 %, selon le mode de détention et la TMI. Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement.",
      ],
      table: {
        headers: ['Mode de détention', 'TD brut', 'TMI', 'Impact fiscal estimé', 'Rendement net estimé'],
        rows: [
          ['Direct', '6,0 %', '30 %', 'IR (30 %) + PS (17,2 %)', '~3,2 %'],
          ['Direct', '6,0 %', '41 %', 'IR (41 %) + PS (17,2 %)', '~2,5 %'],
          ['Assurance-vie (rachat après 8 ans)', '6,0 %', '30 %', 'Abattement annuel, puis 7,5 % + PS', '~5,3 %'],
          ['Assurance-vie (rachat après 8 ans)', '6,0 %', '41 %', 'Abattement annuel, puis 7,5 % + PS', '~5,3 %'],
          ['Crédit (déduction des intérêts)', '6,0 %', '30 %', 'Intérêts déductibles (variable)', 'Variable selon coût crédit'],
        ],
      },
    },
    {
      id: 'methode',
      title: 'La méthode Eric Bellaiche pour analyser un projet SCPI',
      level: 'h2',
      type: 'method-steps',
      content: [
        'L\'analyse d\'un projet SCPI suit une méthode structurée en 7 étapes, dans le respect du cadre réglementaire des CGP-CIF. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Recueil de la situation patrimoniale', description: 'Analyse complète des actifs, passifs, revenus, charges, fiscalité, objectifs patrimoniaux, familiaux et professionnels.' },
        { title: 'Définition des objectifs', description: 'Identification précise des objectifs : revenus complémentaires, capitalisation, préparation retraite, transmission, optimisation fiscale.' },
        { title: 'Analyse fiscale', description: 'Évaluation de l\'impact selon la TMI, les prélèvements sociaux, l\'IFI et le mode de détention envisagé.' },
        { title: 'Analyse du profil investisseur', description: 'Évaluation des connaissances, de l\'expérience en investissement immobilier et financier, de la capacité de perte et de l\'horizon.' },
        { title: 'Comparaison des modes de détention', description: 'Analyse comparative : direct, assurance-vie, crédit, démembrement ou SCI. Simulation de l\'impact sur le rendement net.' },
        { title: 'Sélection cohérente de solutions', description: 'Identification des types de SCPI et des modes de détention adaptés, sans promesse de rendement, dans le respect de la réglementation.' },
        { title: 'Formalisation et suivi', description: 'Déclaration d\'adéquation formelle, documentation des analyses, suivi périodique et ajustements éventuels.' },
      ],
    },
    {
      id: 'quand-consulter',
      title: 'Quand consulter un conseiller SCPI ?',
      level: 'h2',
      type: 'list',
      content: ['Certaines situations justifient particulièrement un accompagnement par un CGP-CIF avant un investissement en SCPI :'],
      listItems: [
        'Investissement supérieur à 50 000 €',
        'TMI élevée (30 %, 41 % ou 45 %)',
        'Objectif de revenus complémentaires pour la retraite',
        'Projet d\'acquisition à crédit',
        'Hésitation entre détention directe et assurance-vie',
        'Besoin de transmission patrimoniale',
        'Patrimoine immobilier déjà important',
        'Besoin de diversification sectorielle ou géographique',
        'Projet d\'investissement en SCPI fiscale (déficit foncier, Malraux)',
        'Situation fiscale complexe (IFI, revenus étrangers)',
      ],
    },
  ],
  faq: [
    { question: 'Pourquoi passer par un conseiller pour investir en SCPI ?', answer: 'Un conseiller CGP-CIF analyse votre situation globale avant toute recommandation : fiscalité, horizon de placement, capacité de perte, objectifs. Cette analyse permet de vérifier la cohérence d\'un investissement en SCPI avec votre situation personnelle.' },
    { question: 'Une SCPI garantit-elle un rendement ?', answer: 'Non, les SCPI ne garantissent ni le rendement ni le capital. Les performances passées ne préjugent pas des performances futures. Le risque de perte en capital et le risque de liquidité existent.' },
    { question: 'Quel est le rôle d\'un CGP-CIF dans une souscription SCPI ?', answer: 'Le CGP-CIF analyse le profil investisseur, la fiscalité, l\'horizon, la capacité de perte, le mode de détention et la cohérence patrimoniale. Il formalise une déclaration d\'adéquation si une recommandation est formulée.' },
    { question: 'Comment choisir entre SCPI en direct et assurance-vie ?', answer: 'Le choix dépend de la situation fiscale, de l\'horizon, des objectifs successoraux et du besoin de liquidité. L\'assurance-vie offre une fiscalité allégée des rachats. La détention directe offre un choix plus large de SCPI. Une analyse personnalisée est nécessaire.' },
    { question: 'La fiscalité peut-elle réduire fortement le rendement d\'une SCPI ?', answer: 'Oui. Selon la TMI, les prélèvements sociaux et l\'IFI, le rendement net de fiscalité peut être significativement inférieur au taux de distribution affiché. L\'écart peut atteindre 3 points pour une TMI élevée.' },
    { question: 'Peut-on revendre facilement ses parts de SCPI ?', answer: 'Non, les parts de SCPI sont des actifs non cotés. Le délai de revente varie de quelques mois à plusieurs années. Un horizon de 8 à 10 ans est généralement recommandé.' },
    { question: 'Faut-il acheter des SCPI à crédit ?', answer: 'L\'achat à crédit permet un effet de levier mais augmente le risque. La décision dépend de la situation fiscale, de l\'horizon et de la capacité d\'endettement. Une simulation personnalisée est nécessaire.' },
    { question: 'Le démembrement de SCPI est-il adapté à tous les profils ?', answer: 'Non. Le démembrement temporaire n\'est pas adapté aux profils recherchant des revenus immédiats. Il peut être pertinent dans une optique de transmission.' },
    { question: 'Une SCPI est-elle adaptée à un objectif court terme ?', answer: 'Non, une SCPI n\'est pas adaptée à un objectif inférieur à 8 ans en raison du risque de liquidité, des frais d\'entrée et de la volatilité potentielle du prix de part.' },
    { question: 'Une recommandation SCPI peut-elle être faite sans analyse du profil investisseur ?', answer: 'Non. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable de la situation du client : profil investisseur, connaissances, expérience, capacité de perte, objectifs et horizon d\'investissement.' },
  ],
  ctaTitle: 'Vous souhaitez vérifier la cohérence de votre projet SCPI ?',
  ctaText: 'Un échange permet d\'identifier les points à analyser avant une souscription : fiscalité, horizon, mode de détention, risques, liquidité et cohérence avec votre patrimoine global.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité : comprendre l\'impact fiscal', position: 'inline' },
    { href: '/articles/scpi-assurance-vie-ou-direct/', label: 'SCPI en direct ou via assurance-vie', position: 'inline' },
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne', position: 'inline' },
  ],
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
