import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'deficit-foncier',
  category: 'fiscalite',
  title: 'Déficit foncier : fonctionnement, fiscalité et points de vigilance',
  metaTitle: 'Déficit foncier : fonctionnement, plafond 10 700 €, imputation sur revenu global - CGP-CIF',
  metaDescription: 'Guide complet sur le déficit foncier : imputation sur le revenu global, plafond de 10 700 €, travaux éligibles, régime réel, déclaration, optimisation et risques. Analyse détaillée par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/deficit-foncier/',
  badge: 'Déficit foncier &bull; Fiscalité &bull; Revenus fonciers &bull; Optimisation &bull; CGP-CIF',
  intro: 'Le déficit foncier est l\'un des dispositifs d\'optimisation fiscale les plus efficaces et les plus accessibles pour les investisseurs immobiliers en location nue. Il permet d\'imputer les charges excédant les loyers perçus sur le revenu global du contribuable, réduisant ainsi l\'impôt sur le revenu dans une limite annuelle de 10 700 €. Pourtant, ce mécanisme, souvent présenté comme simple, recèle des subtilités importantes : distinction entre les différents types de travaux, traitement des intérêts d\'emprunt, règles de report et articulation avec les autres dispositifs. Mal utilisé, il peut conduire à des redressements fiscaux. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous propose une analyse complète du fonctionnement, des opportunités et des limites du déficit foncier.',
  shortAnswer: 'Le déficit foncier permet, pour les propriétaires bailleurs en location nue au régime réel, d\'imputer sur leur revenu global la différence entre leurs charges déductibles (travaux, taxe foncière, frais de gestion, assurances) et leurs loyers perçus, dans la limite de 10 700 € par an. Les intérêts d\'emprunt sont déductibles des revenus fonciers mais ne peuvent pas générer de déficit imputable sur le revenu global. Au-delà du plafond de 10 700 €, le surplus est reportable sur les revenus fonciers des années suivantes pendant 10 ans. Le dispositif est particulièrement intéressant pour les contribuables soumis à une TMI élevée (30 % ou plus), notamment en début de détention lorsque les travaux et les intérêts d\'emprunt sont importants.',
  summaryItems: [
    { label: 'Déficit foncier : définition et mécanisme', anchor: 'definition-mecanisme' },
    { label: 'Conditions d\'éligibilité et régime applicable', anchor: 'conditions-eligibilite' },
    { label: 'Plafond de 10 700 € et règles de report', anchor: 'plafond-report' },
    { label: 'Travaux éligibles et travaux exclus', anchor: 'travaux-eligibles-exclus' },
    { label: 'Traitement des intérêts d\'emprunt', anchor: 'interets-emprunt' },
    { label: 'Tableau récapitulatif : charges déductibles et non déductibles', anchor: 'tableau-charges' },
    { label: 'Exemple pédagogique : simulation d\'optimisation', anchor: 'exemple-optimisation' },
    { label: 'Articulation avec les autres dispositifs', anchor: 'articulation-dispositifs' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour utiliser le déficit foncier', anchor: 'methode-utilisation' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 21,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['déficit foncier', 'fiscalité', 'revenus fonciers', 'optimisation', 'immobilier', 'CGP-CIF'],
  sections: [
    {
      id: 'definition-mecanisme',
      title: 'Déficit foncier : définition et mécanisme fiscal',
      level: 'h2',
      type: 'normal',
      content: [
        'Le déficit foncier est un mécanisme fiscal qui intervient lorsque les charges déductibles d\'un bien immobilier loué nu excèdent les loyers perçus au cours d\'une année d\'imposition. Ce déficit peut, sous certaines conditions, être imputé sur le revenu global du contribuable, réduisant ainsi l\'assiette de l\'impôt sur le revenu.',
        'Le mécanisme est prévu à l\'article 156 du Code général des impôts. Il permet de déduire de l\'ensemble des revenus du foyer fiscal le déficit foncier constaté, dans la limite annuelle de 10 700 €. Pour un contribuable soumis à une TMI de 30 %, cela représente une économie d\'impôt maximale d\'environ 5 050 € par an (10 700 € x 47,2 % incluant les prélèvements sociaux).',
        'Le déficit foncier se calcule en soustrayant des loyers bruts perçus l\'ensemble des charges déductibles : taxe foncière, charges de copropriété non récupérées, frais de gestion, assurances, et surtout les travaux d\'entretien et de réparation. Les intérêts d\'emprunt sont également déductibles des revenus fonciers mais ne peuvent pas générer de déficit imputable sur le revenu global.',
        'Concrètement, si un bien génère 8 000 € de loyers annuels et que les charges déductibles (hors intérêts d\'emprunt) s\'élèvent à 15 000 € (dont 10 000 € de travaux), le déficit foncier imputable sur le revenu global est de 7 000 € (limitée à 10 700 € maximum). Si les charges dépassent 18 700 €, le surplus (au-delà de 10 700 €) est reportable sur les revenus fonciers des années suivantes.',
      ],
    },
    {
      id: 'conditions-eligibilite',
      title: 'Conditions d\'éligibilité et régime applicable',
      level: 'h2',
      type: 'normal',
      content: [
        'Pour bénéficier du déficit foncier, plusieurs conditions doivent être simultanément réunies. La première est d\'être propriétaire d\'un bien immobilier donné en location nue. Le dispositif ne s\'applique pas à la location meublée, qui relève des BIC.',
        'Le bien doit être loué ou offert à la location. Un bien vacant peut générer des charges déductibles sous condition qu\'il soit effectivement proposé à la location dans des conditions normales. Un bien en travaux non proposé à la location ne peut pas générer de déficit foncier.',
        'Le propriétaire doit avoir opté pour le régime réel d\'imposition des revenus fonciers. Le micro-foncier (abattement de 30 %) ne permet pas de déduire les charges réelles et ne peut donc pas générer de déficit foncier. L\'option pour le régime réel doit être exercée auprès de l\'administration fiscale, elle est valable pour un an et se renouvelle tacitement.',
        'Le propriétaire doit être imposable en France et les revenus fonciers doivent être déclarés en France. Les non-résidents peuvent également bénéficier du dispositif pour leurs biens situés en France, sous réserve de respecter les conditions de déclaration.',
        'Enfin, les travaux doivent être réalisés par des professionnels qualifiés et facturés. Les travaux réalisés par le propriétaire lui-même ne sont pas déductibles (hors cas spécifiques de l\'emploi d\'un salarié déclaré). Les factures doivent être conservées pour justifier les déductions en cas de contrôle fiscal.',
      ],
    },
    {
      id: 'plafond-report',
      title: 'Plafond de 10 700 € et règles de report',
      level: 'h2',
      type: 'normal',
      content: [
        'Le plafond d\'imputation du déficit foncier sur le revenu global est fixé à 10 700 € par an. Ce plafond est global, ce qui signifie qu\'il s\'applique à l\'ensemble des revenus fonciers du foyer fiscal, quel que soit le nombre de biens détenus. Si plusieurs biens génèrent un déficit, le total imputable est limité à 10 700 €.',
        'Au-delà de ce plafond, le surplus de déficit (appelé déficit non imputable) est reportable sur les revenus fonciers des années suivantes, pendant un délai maximum de 10 ans. Ce report s\'impute en priorité sur les revenus fonciers positifs des années suivantes, avant tout nouveau déficit.',
        'Exemple : si le déficit foncier d\'une année s\'élève à 25 000 €, les 10 700 € sont imputés sur le revenu global de l\'année en cours. Les 14 300 € restants sont reportés sur les revenus fonciers des années suivantes. Si l\'année suivante les revenus fonciers sont de 5 000 €, ces 5 000 € sont annulés par le report, et les 9 300 € restants sont reportés à nouveau sur l\'année suivante.',
        'Il est important de noter que le plafond de 10 700 € s\'applique au déficit foncier net de l\'année, après imputation des intérêts d\'emprunt. Les intérêts d\'emprunt, bien que déductibles des revenus fonciers sans limitation, ne peuvent pas générer de déficit imputable sur le revenu global.',
        'Le plafond de 10 700 € est un plafond annuel. Il n\'est pas possible de cumuler plusieurs années de plafond pour imputer un déficit exceptionnellement élevé. L\'optimisation du déficit foncier passe donc par un lissage des travaux sur plusieurs années pour ne pas dépasser le plafond annuel.',
      ],
    },
    {
      id: 'travaux-eligibles-exclus',
      title: 'Travaux éligibles et travaux exclus',
      level: 'h2',
      type: 'normal',
      content: [
        'La nature des travaux est le point le plus délicat du dispositif. L\'administration fiscale distingue trois catégories de travaux avec des traitements différents.',
        'Les travaux d\'entretien et de réparation sont intégralement déductibles des revenus fonciers. Il s\'agit des travaux destinés à maintenir le bien en bon état sans en modifier la structure : peinture, revêtements de sol, réparation de la plomberie ou de l\'électricité, remplacement d\'éléments vétustes par des éléments identiques, ravalement de façade, réfection de toiture à l\'identique.',
        'Les travaux d\'amélioration sont également déductibles. Ils visent à apporter un confort supplémentaire au logement sans en modifier la structure ni la destination : installation d\'un chauffage plus performant, remplacement de fenêtres par du double vitrage, création d\'une salle de bains supplémentaire, installation d\'une VMC. Ces travaux étaient soumis à un plafond spécifique avant 2016, mais ce plafond a été supprimé.',
        'Les travaux de reconstruction, d\'agrandissement ou de surélévation ne sont pas déductibles. Ils doivent être intégrés au prix de revient du bien et ne pourront être pris en compte que pour le calcul de la plus-value à la revente. Sont concernés : la création de surfaces habitables supplémentaires, le surélèvement d\'un étage, la transformation d\'un grenier en pièce à vivre avec modification de la charpente.',
        'La distinction entre ces catégories n\'est pas toujours évidente et fait l\'objet de nombreuses requalifications par l\'administration fiscale. Un même chantier peut comprendre des travaux des trois catégories. Il est recommandé de faire établir des devis séparés par type de travaux et de conserver l\'intégralité des factures détaillées.',
        'Les travaux réalisés par le propriétaire lui-même ne sont pas déductibles, sauf s\'il emploie un salarié déclaré pour les réaliser. Seuls les coûts de main-d\'œuvre et de matériaux facturés par des professionnels sont déductibles.',
      ],
    },
    {
      id: 'interets-emprunt',
      title: 'Traitement spécifique des intérêts d\'emprunt',
      level: 'h2',
      type: 'normal',
      content: [
        'Le traitement des intérêts d\'emprunt dans le cadre du déficit foncier est une source fréquente de confusion. Contrairement aux autres charges, les intérêts d\'emprunt ne peuvent pas générer de déficit imputable sur le revenu global.',
        'Le mécanisme est le suivant : les intérêts d\'emprunt sont déductibles des revenus fonciers sans limitation de montant. Ils viennent en déduction des loyers perçus avant les autres charges. Si, après déduction des intérêts, le résultat est positif, les autres charges (travaux, taxe foncière, etc.) peuvent générer un déficit foncier imputable dans la limite de 10 700 €.',
        'En revanche, si les intérêts d\'emprunt à eux seuls suffisent à créer un déficit (par exemple, un bien avec 10 000 € de loyers et 12 000 € d\'intérêts), ce déficit de 2 000 € n\'est pas imputable sur le revenu global. Il est simplement reporté sur les revenus fonciers des années suivantes.',
        'En pratique, le calcul du déficit foncier imputable se fait en deux temps :',
        '1. On calcule le résultat foncier après déduction des intérêts d\'emprunt. Si ce résultat est négatif, il est reporté sur les revenus fonciers futurs.',
        '2. Si le résultat après intérêts est positif, on déduit les autres charges (travaux, taxe foncière, etc.). La partie de ces autres charges qui excède le résultat après intérêts constitue le déficit foncier imputable sur le revenu global, dans la limite de 10 700 €.',
        'Cette règle a une conséquence importante : il est fiscalement plus efficace d\'avoir un faible emprunt (pour ne pas absorber le déficit imputable par les intérêts) ou, à l\'inverse, un emprunt très élevé pour financer des travaux, ce qui permet de cumuler intérêts et travaux dans la même année.',
      ],
    },
    {
      id: 'tableau-charges',
      title: 'Tableau récapitulatif : charges déductibles et non déductibles',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous récapitule les différentes catégories de charges et leur traitement fiscal dans le cadre du déficit foncier.',
      ],
      table: {
        headers: ['Type de charge', 'Déductible', 'Génère un déficit imputable (10 700 €)', 'Reportable'],
        rows: [
          ['Intérêts d\'emprunt (acquisition, travaux, etc.)', 'Oui, sans limitation', 'Non', 'Oui (sur revenus fonciers)'],
          ['Taxe foncière', 'Oui', 'Oui', 'Oui (sur revenus fonciers)'],
          ['Charges de copropriété non récupérées', 'Oui', 'Oui', 'Oui (sur revenus fonciers)'],
          ['Frais de gestion et d\'administration', 'Oui', 'Oui', 'Oui (sur revenus fonciers)'],
          ['Assurances (PNO, loyers impayés)', 'Oui', 'Oui', 'Oui (sur revenus fonciers)'],
          ['Travaux d\'entretien et de réparation', 'Oui, intégralement', 'Oui', 'Oui (sur revenus fonciers)'],
          ['Travaux d\'amélioration', 'Oui, intégralement', 'Oui', 'Oui (sur revenus fonciers)'],
          ['Travaux de reconstruction/agrandissement', 'Non (intégrés au prix de revient)', 'Non', 'Non'],
          ['Frais d\'acquisition du bien', 'Non (intégrés au prix de revient)', 'Non', 'Non'],
          ['Droits de mutation (notaire)', 'Non', 'Non', 'Non'],
          ['Travaux réalisés par le propriétaire', 'Non', 'Non', 'Non'],
          ['Amortissement du bien', 'Non (sauf LMNP/BIC)', 'Non', 'Non'],
        ],
      },
    },
    {
      id: 'exemple-optimisation',
      title: 'Exemple pédagogique : simulation d\'optimisation du déficit foncier',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous illustre l\'optimisation du déficit foncier sur 3 ans pour un investissement locatif de 200 000 € avec 50 000 € de travaux. Le propriétaire est imposé à une TMI de 30 % (soit 47,2 % avec PS). Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement ni une performance passée.',
      ],
      table: {
        headers: ['Critère', 'Année 1', 'Année 2', 'Année 3'],
        rows: [
          ['Loyers bruts perçus', '8 000 €', '9 000 €', '9 500 €'],
          ['Intérêts d\'emprunt', '4 500 €', '4 200 €', '3 900 €'],
          ['Résultat après intérêts d\'emprunt', '3 500 €', '4 800 €', '5 600 €'],
          ['Travaux déductibles réalisés', '15 000 €', '15 000 €', '10 000 €'],
          ['Autres charges (taxe foncière, assurance, frais)', '2 500 €', '2 500 €', '2 600 €'],
          ['Total charges hors intérêts', '17 500 €', '17 500 €', '12 600 €'],
          ['Déficit foncier imputable (limité à 10 700 €)', '10 700 €', '10 700 €', '7 000 €'],
          ['Économie d\'impôt (TMI 30 % + PS)', '~5 050 €', '~5 050 €', '~3 304 €'],
          ['Surplus reporté sur revenus fonciers futurs', '3 300 €', '2 000 €', '0 €'],
          ['Résultat foncier après imputation', '0 €', '0 €', '0 €'],
        ],
      },
    },
    {
      id: 'articulation-dispositifs',
      title: 'Articulation avec les autres dispositifs fiscaux',
      level: 'h2',
      type: 'normal',
      content: [
        'Le déficit foncier peut être combiné avec d\'autres stratégies patrimoniales, mais certaines articulations sont limitées par la réglementation fiscale.',
        'Le déficit foncier n\'est pas cumulable avec les dispositifs de défiscalisation type Pinel, Denormandie ou Malraux pour un même bien au titre de la même année. En revanche, ces dispositifs peuvent coexister dans un même patrimoine sur des biens différents.',
        'Le déficit foncier est compatible avec la détention en SCI à l\'IR. Dans ce cadre, le déficit est réparti entre les associés au prorata de leurs parts, et chaque associé peut imputer sa quote-part de déficit sur son revenu global dans la limite de 10 700 €. C\'est un avantage notable de la SCI à l\'IR par rapport à la détention en direct ou en SCI à l\'IS.',
        'Le déficit foncier et le LMNP sont exclusifs l\'un de l\'autre pour un même bien, car ils relèvent de catégories fiscales différentes (revenus fonciers vs BIC). En revanche, un investisseur peut parfaitement détenir des biens en location nue (avec déficit foncier) et d\'autres en LMNP (avec amortissement).',
        'Le déficit foncier a un impact sur le calcul de l\'IFI : le déficit imputé sur le revenu global réduit le revenu imposable, mais n\'a pas d\'effet direct sur l\'assiette de l\'IFI (qui dépend de la valeur du patrimoine immobilier, pas des revenus).',
        'Enfin, le déficit foncier peut être utilisé dans le cadre d\'une stratégie de cessation d\'activité ou de départ à la retraite, pour réduire l\'impôt sur le revenu des dernières années d\'activité, souvent caractérisées par une TMI élevée.',
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes avec le déficit foncier',
      level: 'h2',
      type: 'list',
      content: [
        'Plusieurs erreurs sont régulièrement constatées dans l\'utilisation du déficit foncier. Les éviter permet de maximiser l\'optimisation et d\'écarter tout risque de redressement.',
      ],
      listItems: [
        'Confondre travaux déductibles et travaux non déductibles : les travaux de reconstruction ou d\'agrandissement ne sont pas déductibles des revenus fonciers. Une erreur de catégorisation expose à un redressement fiscal.',
        'Oublier que les intérêts d\'emprunt ne génèrent pas de déficit imputable sur le revenu global : ils s\'imputent sur les revenus fonciers sans limitation, mais ne contribuent pas au déficit foncier imputable de 10 700 €.',
        'Ne pas lisser les travaux sur plusieurs années : des travaux trop importants réalisés la même année dépasseront le plafond de 10 700 € sans possibilité d\'imputer le surplus sur le revenu global.',
        'Investir dans des travaux sans vérifier la réalité de la location : un bien qui n\'est pas effectivement loué (ou offert à la location dans des conditions normales) ne peut pas générer de déficit foncier.',
        'Négliger la distinction entre les régimes micro-foncier et réel : le déficit foncier n\'existe qu\'au régime réel. Un passage du micro au réel peut être opportun si des travaux sont prévus.',
        'Oublier que les charges de copropriété sont déductibles uniquement pour la part non récupérée sur le locataire. Les charges récupérables doivent être exclues des charges déduites.',
        'Ne pas conserver les justificatifs (factures, quittances, contrats) : en cas de contrôle fiscal, l\'administration peut remettre en cause les déductions si les justificatifs ne sont pas produits.',
        'Utiliser le déficit foncier sans vision patrimoniale globale : le dispositif est un outil d\'optimisation, pas une fin en soi. Il doit s\'intégrer dans une stratégie patrimoniale cohérente.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance pour le déficit foncier',
      level: 'h2',
      type: 'risk',
      content: [
        'Le déficit foncier est un dispositif puissant mais encadré. Voici les points de vigilance essentiels à prendre en compte pour une utilisation sécurisée.',
      ],
      listItems: [
        'L\'administration fiscale est particulièrement attentive à la nature des travaux déclarés. Les travaux d\'amélioration et d\'entretien doivent être clairement distingués des travaux de reconstruction ou d\'agrandissement. Un même chantier peut faire l\'objet d\'une requalification partielle.',
        'Le plafond de 10 700 € est un plafond d\'imputation sur le revenu global, pas un plafond de dépenses. Des travaux plus importants peuvent être réalisés, mais le surplus est reporté sur les revenus fonciers futurs.',
        'En cas de vente du bien avant l\'épuisement du report du déficit foncier, le solde non imputé est définitivement perdu. Il n\'est pas transférable à un autre bien.',
        'Les règles applicables aux déficits fonciers peuvent être modifiées par les lois de finances annuelles. Une veille fiscale est recommandée, notamment sur les plafonds et les conditions d\'éligibilité.',
        'Le déficit foncier n\'est pas cumulable avec les dispositifs de défiscalisation type Pinel ou Denormandie pour un même bien. Le choix entre les dispositifs doit être fait en fonction de la situation personnelle et des objectifs.',
        'Les loyers perçus entre deux travaux doivent être déclarés, même si le bien est en travaux. L\'absence de déclaration peut être considérée comme une omission et faire l\'objet d\'un redressement.',
        'Le recours à un expert-comptable ou à un conseiller en gestion de patrimoine est recommandé pour optimiser le dispositif et sécuriser les déclarations, en particulier pour les travaux importants ou les situations complexes.',
      ],
    },
    {
      id: 'methode-utilisation',
      title: 'Méthode Eric Bellaiche pour utiliser le déficit foncier',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour utiliser le déficit foncier dans le cadre d\'une stratégie patrimoniale, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 étapes. Aucune recommandation n\'est formulée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation fiscale personnelle', description: 'TMI, revenus existants, nombre de parts fiscales, exposition à l\'IFI : ces éléments déterminent l\'intérêt et le potentiel d\'optimisation du déficit foncier.' },
        { title: 'Identification du bien et des travaux éligibles', description: 'Analyse du bien locatif, planification des travaux nécessaires, devis détaillés par catégorie (entretien, amélioration, reconstruction), estimation des loyers futurs.' },
        { title: 'Simulation pluriannuelle du déficit foncier', description: 'Calcul du déficit prévisionnel sur 3 à 5 ans, intégrant les loyers, les intérêts d\'emprunt, les charges et les travaux, avec lissage pour optimiser le plafond annuel de 10 700 €.' },
        { title: 'Choix du régime fiscal et déclaration', description: 'Option pour le régime réel si nécessaire, déclaration des revenus fonciers en 2044, suivi des reports déficitaires, conservation des justificatifs.' },
        { title: 'Suivi annuel et réévaluation', description: 'Vérification annuelle du respect du plafond, suivi des reports, adaptation de la stratégie en fonction de l\'évolution de la situation fiscale et des objectifs patrimoniaux.' },
      ],
    },
  ],
  faq: [
    { question: 'Qu\'est-ce que le déficit foncier ?', answer: 'Le déficit foncier est la situation où les charges déductibles d\'un bien immobilier loué nu (travaux, taxe foncière, frais de gestion, assurances) dépassent les loyers perçus. Ce déficit peut être imputé sur le revenu global dans la limite de 10 700 € par an.' },
    { question: 'Quel est le plafond du déficit foncier en 2026 ?', answer: 'Le plafond d\'imputation sur le revenu global est de 10 700 € par an. Ce plafond est global pour l\'ensemble des revenus fonciers du foyer fiscal. Au-delà, le surplus est reportable sur les revenus fonciers des années suivantes pendant 10 ans.' },
    { question: 'Les intérêts d\'emprunt sont-ils pris en compte dans le déficit foncier ?', answer: 'Les intérêts d\'emprunt sont déductibles des revenus fonciers sans limitation, mais ils ne peuvent pas générer de déficit imputable sur le revenu global. Seuls les déficits provenant des autres charges (travaux, taxe foncière, etc.) sont imputables dans la limite de 10 700 €.' },
    { question: 'Quels travaux sont déductibles des revenus fonciers ?', answer: 'Les travaux d\'entretien, de réparation et d\'amélioration sont déductibles. Les travaux de reconstruction, d\'agrandissement ou de surélévation ne sont pas déductibles mais viennent augmenter le prix de revient du bien pour le calcul de la plus-value.' },
    { question: 'Le déficit foncier est-il cumulable avec le LMNP ?', answer: 'Non, pour un même bien : le déficit foncier concerne la location nue (revenus fonciers), le LMNP relève des BIC. En revanche, un même investisseur peut détenir des biens en location nue et d\'autres en LMNP.' },
    { question: 'Peut-on utiliser le déficit foncier en SCI ?', answer: 'Oui, en SCI à l\'IR, le déficit est réparti entre les associés qui peuvent l\'imputer sur leur revenu global. En SCI à l\'IS, le déficit est imputé au niveau de la société sans possibilité d\'imputation sur le revenu des associés.' },
    { question: 'Que se passe-t-il en cas de vente du bien avec un report de déficit ?', answer: 'Le solde du déficit foncier non encore imputé est définitivement perdu lors de la vente du bien. Il n\'est pas transférable à un autre bien ni au cédant pour d\'autres revenus.' },
    { question: 'Faut-il être au régime réel pour bénéficier du déficit foncier ?', answer: 'Oui, le déficit foncier n\'existe qu\'au régime réel d\'imposition des revenus fonciers. Le micro-foncier (abattement de 30 %) ne permet pas de déduire les charges réelles et ne génère donc pas de déficit foncier.' },
    { question: 'Comment déclarer le déficit foncier ?', answer: 'Le déficit foncier se déclare via le formulaire n° 2044 (déclaration détaillée des revenus fonciers) ou le formulaire n° 2044 spéciale pour les biens en SCI. Le montant imputé est reporté sur la déclaration d\'ensemble des revenus (n° 2042).' },
    { question: 'Le déficit foncier présente-t-il des risques fiscaux ?', answer: 'Le principal risque est la requalification des travaux déductibles en travaux non déductibles par l\'administration fiscale. Pour sécuriser sa position, il est recommandé de conserver tous les justificatifs et de se faire accompagner par un professionnel.' },
  ],
  ctaTitle: 'Vous souhaitez optimiser votre fiscalité avec le déficit foncier ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation et de définir une stratégie d\'optimisation adaptée à vos objectifs patrimoniaux.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/fiscalite-revenus-fonciers/', label: 'Fiscalité des revenus fonciers', position: 'inline' },
    { href: '/articles/immobilier-locatif-fiscalite/', label: 'Immobilier locatif et fiscalité', position: 'inline' },
    { href: '/articles/lmnp-ou-location-nue/', label: 'LMNP ou location nue : comparatif', position: 'inline' },
    { href: '/articles/reduire-impot-sans-risque-excessif/', label: 'Réduire ses impôts sans risque excessif', position: 'footer' },
  ],
  hasRisks: false,
};

export default article;
