import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'erreurs-gestion-patrimoine',
  category: 'patrimoine',
  title: 'Les erreurs fréquentes en gestion de patrimoine et comment les éviter',
  metaTitle: 'Les erreurs fréquentes en gestion de patrimoine et comment les éviter | Eric Bellaiche',
  metaDescription: "Découvrez les erreurs les plus fréquentes en gestion de patrimoine : fiscalité, placements, immobilier, épargne, prévoyance, transmission. Comment les éviter avec un CGP-CIF.",
  canonical: 'https://eric-bellaiche.fr/articles/erreurs-gestion-patrimoine/',
  badge: 'Gestion de patrimoine &bull; CGP-CIF &bull; ORIAS 13001580',
  intro: "La gestion de patrimoine est un domaine où les erreurs coûtent cher, parfois très cher. Une décision prise sans analyse préalable, un produit souscrit pour un avantage fiscal immédiat sans vision globale, une absence d'anticipation de la transmission : ces erreurs peuvent grever la performance d'un patrimoine sur des décennies. L'objectif de cet article est de recenser les erreurs les plus fréquentes en gestion de patrimoine, d'expliquer pourquoi elles sont préjudiciables et de donner des pistes pour les éviter. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, accompagne ses clients dans l'optimisation et la sécurisation de leur patrimoine.",
  shortAnswer: "Les erreurs les plus fréquentes en gestion de patrimoine sont : investir sans objectif clair ni horizon défini, négliger sa fiscalité personnelle (TMI, IFI, PS), concentrer son patrimoine sur une seule classe d'actifs (trop d'immobilier ou trop de liquidités), conserver des contrats d'assurance-vie avec des frais excessifs, ouvrir un PER sans anticiper la fiscalité de sortie, sous-estimer les frais de gestion, ignorer la prévoyance, ne pas diversifier ses placements, ne pas anticiper la transmission, et prendre des décisions sous le coup d'une émotion ou d'une opportunité sans analyse préalable. Pour éviter ces erreurs, il est recommandé de réaliser un audit patrimonial préalable, de se fixer des objectifs clairs, de diversifier ses actifs, de vérifier régulièrement ses contrats et d'être accompagné par un CGP-CIF.",
  summaryItems: [
    { label: "Pourquoi les erreurs de gestion sont fréquentes", anchor: 'pourquoi-erreurs' },
    { label: 'Erreur n°1 : investir sans objectif ni horizon', anchor: 'erreur-sans-objectif' },
    { label: 'Erreur n°2 : négliger sa fiscalité personnelle', anchor: 'erreur-fiscalite' },
    { label: 'Erreur n°3 : concentrer son patrimoine sur une seule classe d\'actifs', anchor: 'erreur-concentration' },
    { label: 'Erreur n°4 : sous-estimer l\'impact des frais', anchor: 'erreur-frais' },
    { label: 'Tableau récapitulatif des erreurs et de leurs conséquences', anchor: 'tableau-recapitulatif' },
    { label: 'Erreurs sur les enveloppes (PER, assurance-vie, SCPI)', anchor: 'erreurs-enveloppes' },
    { label: 'Exemple pédagogique : les conséquences des erreurs cumulées', anchor: 'exemple-pedagogique' },
    { label: "Méthode Eric Bellaiche pour éviter les erreurs", anchor: 'methode' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 20,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['erreurs', 'gestion patrimoine', 'placements', 'fiscalité', 'immobilier', 'prévoyance', 'CGP-CIF'],
  sections: [
    {
      id: 'pourquoi-erreurs',
      title: "Pourquoi les erreurs de gestion de patrimoine sont fréquentes",
      level: 'h2',
      type: 'normal',
      content: [
        "La gestion de patrimoine est un domaine complexe qui combine plusieurs disciplines : droit, fiscalité, finance, immobilier, assurance, retraite, succession. Peu d'épargnants maîtrisent l'ensemble de ces sujets, ce qui les rend vulnérables aux erreurs.",
        "Plusieurs facteurs expliquent la fréquence des erreurs :",
        "1. L'absence de vision globale : la plupart des épargnants prennent des décisions au coup par coup, en fonction d'une opportunité ou d'une sollicitation commerciale. Un PER souscrit pour la défiscalisation, une SCPI achetée pour le rendement affiché, une assurance-vie ouverte dans une banque sans comparaison des frais. Chaque décision prise isolément peut sembler pertinente, mais l'ensemble manque souvent de cohérence.",
        "2. La complexité fiscale : la fiscalité française est l'une des plus complexes d'Europe. Entre l'IR, l'IFI, les PS, le PFU, les abattements, les crédits d'impôt, il est facile de prendre une décision sans mesurer l'impact fiscal réel. Par exemple, acheter une SCPI en direct sans anticiper l'imposition des revenus fonciers à la TMI + PS peut réduire considérablement le rendement net.",
        "3. Les biais comportementaux : la peur de manquer une opportunité (FOMO), l'aversion aux pertes, le biais de confirmation (ne chercher que les informations qui confirment ses choix), la surconfiance après un premier investissement réussi, l'influence des proches ou des réseaux sociaux. Ces biais poussent à des décisions irrationnelles.",
        "4. La sollicitation commerciale : les banques, assurances et sociétés de gestion ont des objectifs de vente. Les produits proposés ne sont pas toujours ceux qui correspondent le mieux aux besoins du client, mais ceux qui génèrent le plus de commissions pour le distributeur.",
        "5. L'absence de suivi régulier : un patrimoine se gère dans la durée. Beaucoup d'épargnants ouvrent des contrats et ne les regardent plus pendant des années, passant à côté d'opportunités d'arbitrage ou de réduction de frais.",
        "La meilleure protection contre ces erreurs est une approche méthodique : définir ses objectifs, réaliser un audit préalable, diversifier ses placements, suivre régulièrement ses investissements et s'entourer de professionnels compétents.",
      ],
    },
    {
      id: 'erreur-sans-objectif',
      title: "Erreur n°1 : investir sans objectif clair ni horizon défini",
      level: 'h2',
      type: 'normal',
      content: [
        "C'est probablement l'erreur la plus fondamentale et la plus répandue. Beaucoup d'épargnants investissent sans se poser les questions essentielles : pourquoi j'investis ? Pour quel objectif ? Dans combien de temps aurai-je besoin de cet argent ?",
        "Investir sans objectif conduit à des choix inadaptés : placer sur un PER une épargne qui aurait dû être disponible à moyen terme (achat immobilier, études des enfants), ou au contraire laisser sur un livret A une épargne destinée à la retraite qui aurait dû être investie en actions ou en immobilier pour générer un meilleur rendement.",
        "Chaque objectif patrimonial a un horizon, une tolérance au risque et une enveloppe fiscale adaptée :",
        "- Épargne de précaution (0-3 ans) : livret A, LDD, LEP, fonds euros. Sécurité et disponibilité avant tout.",
        "- Projet à moyen terme (3-8 ans) : assurance-vie en unités de compte diversifiées, PEA, SCPI. Un risque mesuré pour un rendement supérieur à l'épargne réglementée.",
        "- Projet à long terme (8 ans et plus) : PER, PEA, assurance-vie en UC, immobilier locatif, SCPI. La prise de risque est justifiée par un horizon long qui permet de lisser les fluctuations.",
        "La solution : avant tout investissement, définissez précisément vos objectifs (quoi, combien, quand) et choisissez l'enveloppe et le niveau de risque en conséquence. Un audit patrimonial permet de formaliser ces objectifs et de les hiérarchiser.",
      ],
    },
    {
      id: 'erreur-fiscalite',
      title: "Erreur n°2 : négliger sa fiscalité personnelle",
      level: 'h2',
      type: 'normal',
      content: [
        'La fiscalité personnelle a un impact considérable sur le rendement net des investissements. Négliger sa TMI, son exposition à l\'IFI, ses prélèvements sociaux ou son quotient familial peut conduire à des décisions sous-optimales.',
        'Exemple concret : un investisseur en TMI 41 % qui achète une SCPI en direct avec un rendement brut de 6 %. Après imposition des revenus fonciers (TMI 41 % + PS 17,2 % = 58,2 %), le rendement net de fiscalité tombe à environ 2,5 %, sans compter les frais de souscription et de gestion. Le même investisseur aurait pu souscrire la même SCPI via un contrat d\'assurance-vie en unités de compte, où la fiscalité des revenus est différée et avantageuse après 8 ans (prélèvement forfaitaire libératoire de 7,5 % après abattement).',
        "Autre exemple : ouvrir un PER sans anticiper la TMI à la retraite. La déduction des versements est intéressante en TMI 41 %, mais si la TMI à la retraite reste à 30 % (cumul pension de retraite + rente PER), le gain net est moins important qu'espéré. Il faut également considérer l'effet de la décote sur les pensions qui peut maintenir une TMI relativement élevée à la retraite.",
        "L'IFI est également un paramètre souvent négligé. Un patrimoine immobilier net > 1,3 M€ est assujetti à l'IFI (0,5 % à 1,5 %). Les investisseurs immobiliers doivent intégrer ce coût dans leur calcul de rendement. Certaines stratégies (détention de SCPI en assurance-vie, arbitrage entre immobilier direct et financier) permettent de réduire ou d'éviter l'exposition à l'IFI.",
        "La solution : avant toute décision d'investissement, faites analyser votre situation fiscale complète. La fiscalité ne doit pas être le seul moteur de vos décisions, mais elle ne doit pas non plus être ignorée.",
      ],
    },
    {
      id: 'erreur-concentration',
      title: "Erreur n°3 : concentrer son patrimoine sur une seule classe d'actifs",
      level: 'h2',
      type: 'normal',
      content: [
        "La concentration du patrimoine sur une seule classe d'actifs est l'une des erreurs les plus répandues et les plus risquées. Les Français ont historiquement une préférence marquée pour l'immobilier, et beaucoup ont plus de 60 % ou 70 % de leur patrimoine investi dans ce seul secteur.",
        "Les risques de la concentration immobilière :",
        "- Illiquidité : l'immobilier ne se vend pas en quelques jours. En cas de besoin urgent de liquidité, la vente peut prendre plusieurs mois.",
        "- Risque de marché : une baisse du marché immobilier peut impacter significativement la valeur du patrimoine.",
        "- Risque locatif : vacance locative, impayés, travaux, contentieux avec les locataires.",
        "- Fiscalité : les revenus fonciers sont imposés à la TMI + PS, et l'immobilier est soumis à l'IFI au-delà de 1,3 M€.",
        "- Coûts de transaction : frais de notaire (7-8 %), frais d'agence, diagnostics, qui réduisent la rentabilité nette.",
        "À l'inverse, la concentration sur les actifs financiers uniquement expose à la volatilité des marchés et à l'absence de diversification sectorielle.",
        "La solution : diversifiez votre patrimoine entre plusieurs classes d'actifs (immobilier, actions, obligations, monétaire) et plusieurs secteurs (France, Europe, international, pays émergents). Une répartition équilibrée permet de réduire le risque global sans sacrifier le rendement potentiel. La diversification ne garantit pas un rendement, mais elle réduit la volatilité.",
      ],
    },
    {
      id: 'erreur-frais',
      title: "Erreur n°4 : sous-estimer l'impact des frais",
      level: 'h2',
      type: 'normal',
      content: [
        "Les frais sont l'ennemi silencieux de la performance patrimoniale. Un écart apparemment minime dans les frais de gestion peut représenter une différence considérable sur 20 ou 30 ans, en raison de l'effet cumulatif.",
        "Exemple : un contrat d'assurance-vie avec 0,5 % de frais de gestion annuels vs un contrat avec 0,9 %. Sur 100 000 € placés pendant 20 ans avec un rendement brut annuel de 4 %, la différence est d'environ 12 000 € en faveur du contrat le moins cher. Sur 30 ans, la différence dépasse 25 000 €.",
        "Les frais à surveiller :",
        "- Frais d'entrée : certains contrats d'assurance-vie ou SCPI prennent jusqu'à 5 % de frais d'entrée. Sur 100 000 €, cela représente 5 000 € immédiatement perdus.",
        "- Frais de gestion annuels : ils varient de 0 % (fonds euros de certaines assurances) à 1,5 % (certains contrats bancaires anciens).",
        "- Frais d'arbitrage : certains contrats facturent des frais à chaque modification de la répartition des supports.",
        "- Frais de sortie : rares mais existent sur certains contrats (rachat partiel avec pénalité).",
        "- Frais de souscription SCPI : de 6 à 12 % selon les sociétés de gestion, prélevés sur le montant investi.",
        "- Frais de gestion locative : si vous confiez la gestion de votre bien immobilier à une agence, comptez 6 à 10 % des loyers perçus.",
        "La solution : comparez systématiquement les frais avant d'investir. Privilégiez les contrats sans frais d'entrée, avec des frais de gestion inférieurs à 0,6 % pour les assurances-vie en UC, et vérifiez les frais d'arbitrage. Les contrats récents (contrats d'assurance-vie en ligne, PER sans frais d'entrée) sont souvent beaucoup moins chers que les contrats bancaires traditionnels.",
      ],
    },
    {
      id: 'tableau-recapitulatif',
      title: "Tableau récapitulatif des erreurs et de leurs conséquences",
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous récapitule les principales erreurs de gestion de patrimoine, leurs conséquences et les pistes pour les éviter.",
      ],
      table: {
        headers: ['Erreur', 'Conséquence', 'Comment l\'éviter'],
        rows: [
          ['Investir sans objectif', 'Placements inadaptés, fiscalité sous-optimale', 'Définir des objectifs chiffrés et datés avant tout investissement'],
          ['Négliger sa fiscalité', 'Rendement net réduit, IFI non anticipé', 'Faire analyser sa TMI, son IFI et ses PS avant d\'investir'],
          ['Concentration immobilière', 'Illiquidité, risque locatif, fiscalité lourde', 'Diversifier entre immobilier, actions, obligations et monétaire'],
          ['Multiplier les contrats', 'Doublons, frais excessifs, perte de lisibilité', 'Limiter le nombre de contrats et vérifier leur performance nette'],
          ['Ignorer les frais', 'Perte significative sur le long terme (effet cumulatif)', 'Comparer les frais avant toute souscription, privilégier les contrats sans frais d\'entrée'],
          ['PER sans stratégie de sortie', 'Fiscalité de sortie défavorable, blocage des fonds', 'Anticiper la TMI future et le besoin de liquidité avant d\'alimenter un PER'],
          ['Pas de prévoyance', 'Déséquilibre patrimonial en cas d\'accident de la vie', 'Souscrire une prévoyance adaptée (décès, invalidité, incapacité)'],
          ['Pas d\'anticipation transmission', 'Droits de succession élevés, conflits familiaux', 'Anticiper avec donation, assurance-vie, donation entre époux'],
          ['Décisions émotionnelles', 'Achat au sommet, vente au creux, produits inadaptés', 'S\'en tenir à sa stratégie, éviter les décisions sous pression'],
          ['Absence de suivi régulier', 'Contrats obsolètes, allocation déséquilibrée', 'Réviser son patrimoine au moins une fois par an'],
        ],
      },
    },
    {
      id: 'erreurs-enveloppes',
      title: "Erreurs sur les enveloppes (PER, assurance-vie, SCPI)",
      level: 'h2',
      type: 'list',
      content: [
        "Certaines erreurs sont spécifiques aux enveloppes et produits financiers les plus courants. Les voici :",
      ],
      listItems: [
        'PER : verser sans vérifier le plafond disponible et sans anticiper la fiscalité de sortie. Le PER est intéressant quand la TMI actuelle est élevée et la TMI future basse. Vérifiez également que les frais du contrat sont compétitifs.',
        'PER : ne pas diversifier les supports. Un PER investi à 100 % en fonds euros ne profite pas du potentiel de rendement des UC. Pour un horizon long (+15 ans), une part d\'UC (40-60 %) est généralement recommandée.',
        'Assurance-vie : conserver des contrats anciens avec des frais de gestion élevés (0,8 % à 1,2 %) alors que des contrats récents proposent des frais de gestion à 0,3-0,6 %. L\'arbitrage vers un contrat plus performant est souvent rentable.',
        'Assurance-vie : ne pas utiliser les UC pour investir en SCPI ou en immobilier. De nombreux contrats permettent d\'investir en SCPI en UC, ce qui offre les avantages de l\'immobilier avec la fiscalité de l\'assurance-vie.',
        'Assurance-vie : clause bénéficiaire non rédigée ou obsolète. Une clause \"mon conjoint\" peut devenir problématique après un divorce. Une clause \"mes héritiers\" fait entrer les capitaux dans la succession.',
        'SCPI : acheter sans vérifier le taux d\'endettement, le taux d\'occupation financier (TOF), la valeur de reconstitution, la durée de jouissance et la fiscalité applicable. Toutes les SCPI ne se valent pas.',
        'SCPI : acheter en direct sans comparer l\'option via assurance-vie. L\'assurance-vie permet d\'investir en SCPI avec une fiscalité différée et avantageuse, ce qui peut être plus intéressant que la détention en direct selon la TMI.',
        'PEA : ne pas utiliser le plafond disponible (150 000 €). Le PEA est l\'enveloppe la plus avantageuse pour investir en actions (exonération d\'IR après 5 ans).',
        'Immobilier locatif : acheter sans simuler le rendement net après fiscalité, frais de notaire, travaux, taxe foncière, vacance locative et gestion.',
        'SCI : créer une SCI sans objectif clair. Une SCI a un coût de fonctionnement (comptabilité, fiscalité, assemblées générales) qui n\'est pas toujours justifié par rapport à une détention en direct.',
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: "Exemple pédagogique : les conséquences des erreurs cumulées",
      level: 'h2',
      type: 'normal',
      content: [
        "Situation : un homme de 58 ans, cadre, divorcé, remarié, deux enfants majeurs du premier mariage. Revenus annuels : 110 000 €. TMI : 30 %. Patrimoine : résidence principale 400 000 € (propre, issu du divorce), deux studios locatifs (350 000 € chacun) acquis en direct, assurance-vie de 180 000 € sur un contrat bancaire ancien (frais de gestion 0,95 %), PER de 20 000 € ouvert il y a 3 ans (plafond disponible 25 000 €), épargne de précaution de 70 000 € sur livrets, pas de PEA.",
        "Les erreurs cumulées et leurs conséquences :",
        "1. Concentration immobilière excessive : 1 100 000 € d'immobilier (résidence + studios) pour un patrimoine total d'environ 1 370 000 €, soit plus de 80 % en immobilier. L'exposition à l'IFI est imminente. Illiquidité totale. Risque locatif concentré sur deux biens.",
        "2. Épargne de précaution trop élevée : 70 000 € pour des dépenses mensuelles de 4 000 €, soit 17 mois de dépenses. L'excédent (environ 45 000 €) dort sur des livrets au lieu d'être investi.",
        "3. Assurance-vie avec frais excessifs : 0,95 % de frais de gestion sur 180 000 €, soit 1 710 € par an. Un contrat récent à 0,5 % coûterait 900 € par an. Économie potentielle : 810 € par an, soit 8 100 € sur 10 ans capitalisés.",
        "4. Plafond PER non utilisé : 25 000 € de déduction fiscale non utilisée chaque année. À 30 % de TMI, cela représente 7 500 € d'économie d'impôt par an. En 3 ans, 22 500 € d'impôt payé en trop.",
        "5. Absence de diversification financière : pas de PEA, pas d'UC en assurance-vie (contrat en fonds euros exclusivement). Aucune exposition aux marchés actions, ce qui limite le potentiel de croissance.",
        "6. Absence d'anticipation de la transmission au conjoint : pas de donation entre époux, clause bénéficiaire obsolète. En cas de décès, les enfants du premier mariage et le conjoint actuel pourraient être en conflit.",
        "Coût estimé des erreurs : environ 15 000 à 20 000 € par an de manque à gagner (fiscalité excessive, frais trop élevés, épargne non investie, plafond PER non utilisé), sans compter les conséquences successorales potentielles.",
        "Cet exemple anonymisé ne constitue pas une recommandation personnalisée. Chaque situation nécessite une analyse spécifique.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour éviter les erreurs de gestion de patrimoine",
      level: 'h2',
      type: 'method-steps',
      content: [
        "Eric Bellaiche, CGP-CIF, applique une méthode structurée en 6 étapes pour aider ses clients à éviter les erreurs les plus fréquentes et optimiser leur gestion patrimoniale. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète de la situation, du profil investisseur, des objectifs, de l'horizon et de la capacité de perte.",
      ],
      methodSteps: [
        { title: 'Audit patrimonial complet', description: "Analyse exhaustive de votre situation : fiscalité, actifs, passifs, retraite, prévoyance, transmission, capacité d'épargne, tolérance au risque. Identification des forces, des faiblesses et des incohérences qui constituent des sources d'erreur potentielles." },
        { title: 'Définition d\'une stratégie écrite', description: "Formalisation d'une stratégie patrimoniale écrite, avec des objectifs clairs, une allocation cible, un plan d'actions hiérarchisé et des critères de suivi. Cette stratégie sert de cadre de référence pour toutes les décisions futures." },
        { title: 'Audit des contrats existants', description: "Analyse détaillée de chaque contrat (assurance-vie, PER, PEA, immobilier) : frais, performance nette, fiscalité, adéquation avec les objectifs. Identification des contrats à conserver, à arbitrer, à regrouper ou à fermer." },
        { title: 'Optimisation des frais et de la fiscalité', description: "Recommandation d'arbitrages pour réduire les frais excessifs, optimisation de l'utilisation des plafonds PER, vérification de la cohérence fiscale de chaque placement. Simulation de l'impact fiscal des décisions avant leur mise en œuvre." },
        { title: 'Mise en place d\'un plan de suivi', description: "Planification des rendez-vous de suivi (annuels ou semestriels) pour vérifier l'adéquation de la stratégie, procéder aux rééquilibrages nécessaires et ajuster les objectifs. Mise en place d'alertes sur les échéances importantes (abattements, clauses, plafonds)." },
        { title: 'Accompagnement dans la durée', description: "Suivi continu de l'évolution de votre situation personnelle, de la fiscalité et des marchés. Ajustement de la stratégie en fonction des changements (mariage, naissance, héritage, changement de TMI, départ en retraite, évolution des marchés)." },
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance',
      level: 'h2',
      type: 'normal',
      content: [
        "La gestion de patrimoine est un domaine où la prudence est de mise. Voici les points de vigilance essentiels à garder à l'esprit :",
        "- Aucun investissement n'est sans risque. Les performances passées ne préjugent pas des performances futures. Tout placement comporte un risque de perte en capital.",
        "- Les promesses de rendement sont interdites pour un CGP-CIF. Méfiez-vous des conseillers ou plateformes qui promettent des rendements garantis ou des gains sans risque.",
        '- La fiscalité est un paramètre important mais évolutif. Une optimisation fiscale valable aujourd\'hui peut ne plus l\'être demain si la législation change.',
        "- La diversification réduit le risque mais ne l'élimine pas. Un patrimoine diversifié peut perdre de la valeur en période de crise généralisée.",
        "- Les frais ne sont pas toujours visibles. Lisez attentivement les conditions générales des contrats et demandez une transparence totale sur les frais avant de souscrire.",
        "- La gestion de patrimoine ne se limite pas aux placements. La prévoyance, la protection juridique, la transmission et la retraite sont des dimensions essentielles souvent négligées.",
        "- Un conseil patrimonial personnalisé ne peut être donné sans analyse préalable complète de votre situation. Méfiez-vous des recommandations génériques ou des conseils reçus lors de séminaires commerciaux.",
        "- La complexité du droit successoral français nécessite une coordination entre le CGP et le notaire. Un conseil patrimonial ne remplace pas un conseil juridique pour les aspects successoraux.",
      ],
    },
  ],
  faq: [
    { question: "Quelles sont les erreurs les plus coûteuses en gestion de patrimoine ?", answer: "Les plus coûteuses sont : investir sans objectif (placements inadaptés), négliger sa fiscalité (rendement net réduit), concentrer son patrimoine (risque élevé), sous-estimer les frais (perte cumulée significative) et ne pas anticiper la transmission (droits de succession élevés, conflits)." },
    { question: "Comment savoir si mon patrimoine est bien géré ?", answer: "Un patrimoine bien géré se caractérise par : des objectifs clairs et une stratégie écrite, une diversification adaptée, des frais maîtrisés, une fiscalité optimisée, une prévoyance adaptée, une transmission anticipée, et un suivi régulier." },
    { question: "Est-ce grave d'avoir plusieurs contrats d'assurance-vie ?", answer: "Ce n'est pas grave en soi, mais cela peut générer des frais redondants, une perte de lisibilité et une gestion plus complexe. L'idéal est d'avoir 2 à 3 contrats performants plutôt que 5 à 6 contrats aux frais élevés." },
    { question: "Faut-il toujours chercher à réduire ses impôts ?", answer: "Non, l'optimisation fiscale ne doit pas être le seul moteur des décisions. Un investissement fiscalement avantageux mais risqué, illiquide ou inadapté à vos objectifs peut être contre-productif. L'objectif premier est la cohérence patrimoniale." },
    { question: "Quel est l'impact réel des frais de gestion sur mon épargne ?", answer: "Très important. Par exemple, 0,5 % de frais en plus sur 100 000 € placés à 4 % pendant 20 ans représente environ 12 000 € de différence. Sur 30 ans, plus de 25 000 €. Les frais doivent être un critère de choix essentiel." },
    { question: "Comment éviter les décisions émotionnelles en investissement ?", answer: "En ayant une stratégie écrite et en s'y tenant. Évitez les décisions sous le coup d'une actualité, d'une opportunité ou d'une pression commerciale. Prenez le temps de l'analyse et consultez un professionnel avant toute décision importante." },
    { question: "Faut-il vendre un bien immobilier pour diversifier son patrimoine ?", answer: "Cela dépend de votre situation. Si l'immobilier représente plus de 60-70 % de votre patrimoine et que vous manquez de liquidités, une vente partielle peut être pertinente. Mais chaque situation est différente et nécessite une analyse personnalisée." },
    { question: "À quelle fréquence faut-il vérifier ses placements ?", answer: "Idéalement une fois par an, ou à chaque changement significatif de situation. Vérifiez la performance nette, les frais, l'adéquation avec vos objectifs et procédez aux arbitrages nécessaires." },
    { question: "Qu'est-ce qu'un audit patrimonial et en quoi aide-t-il à éviter les erreurs ?", answer: "Un audit patrimonial est une analyse complète de votre situation qui permet d'identifier les incohérences, les frais excessifs, les déséquilibres et les opportunités d'optimisation. C'est le point de départ indispensable pour éviter les erreurs." },
    { question: "Les conseillers en ligne sont-ils fiables pour la gestion de patrimoine ?", answer: "Oui, un CGP-CIF en ligne est soumis à la même réglementation qu'un conseiller en cabinet. Vérifiez son inscription à l'ORIAS et assurez-vous qu'il réalise une analyse préalable complète avant toute recommandation." },
  ],
  ctaTitle: 'Vous souhaitez vérifier que vous ne commettez pas d\'erreurs dans la gestion de votre patrimoine ?',
  ctaText: 'Un premier échange gratuit permet de faire le point sur votre situation et d\'identifier les points d\'amélioration prioritaires. Aucun engagement, aucune recommandation personnalisée sans analyse préalable.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne : méthode et analyse', position: 'inline' },
    { href: '/articles/structurer-son-patrimoine/', label: 'Structurer son patrimoine', position: 'inline' },
    { href: '/articles/conseiller-patrimoine-en-ligne/', label: 'Conseiller en gestion de patrimoine en ligne', position: 'inline' },
    { href: '/articles/preparer-retraite-patrimoine/', label: 'Préparer sa retraite avec son patrimoine', position: 'inline' },
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie : quelle enveloppe choisir', position: 'inline' },
  ],
};

export default article;
