import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'fiscalite-revenus-fonciers',
  category: 'fiscalite',
  title: "Fiscalité des revenus fonciers : comprendre l'impact avant d'investir",
  metaTitle: "Fiscalité des revenus fonciers : comprendre l'impact avant d'investir",
  metaDescription: "La fiscalité des revenus fonciers dépend du TMI, des prélèvements sociaux, du régime choisi (micro-foncier ou réel), du déficit foncier et de la nature des revenus. Analyse complète par Eric Bellaiche, CGP-CIF.",
  canonical: 'https://eric-bellaiche.fr/articles/fiscalite-revenus-fonciers/',
  badge: 'Revenus fonciers &bull; Fiscalité &bull; TMI &bull; Prélèvements sociaux &bull; Déficit foncier &bull; CGP-CIF',
  intro: 'Investir dans l\'immobilier locatif sans comprendre la fiscalité des revenus fonciers expose à des surprises désagréables. Les loyers perçus ne sont pas un revenu net : ils sont soumis à l\'impôt sur le revenu (dans la catégorie des revenus fonciers) et aux prélèvements sociaux. Selon la TMI du contribuable, le taux d\'imposition combiné peut atteindre 62,2 %, réduisant considérablement la rentabilité nette de l\'investissement. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous présente en détail la fiscalité des revenus fonciers, les régimes d\'imposition, les options possibles et les stratégies pour optimiser votre investissement locatif.',
  shortAnswer: 'Les revenus fonciers sont les loyers perçus par un propriétaire bailleur. Ils sont imposés dans la catégorie des revenus fonciers de l\'impôt sur le revenu, selon le barème progressif (TMI de 0 % à 45 %), et sont soumis aux prélèvements sociaux de 17,2 %. Le taux d\'imposition combiné varie donc de 17,2 % à 62,2 % selon la TMI. Deux régimes d\'imposition existent : le micro-foncier (abattement forfaitaire de 30 % sur les loyers bruts, plafond de 15 000 € de loyers annuels) et le régime réel (déduction des charges et frais réels, option possible si les loyers dépassent 15 000 € ou si elle est plus avantageuse). Le déficit foncier permet d\'imputer le déficit sur le revenu global dans la limite de 10 700 € par an. Le choix du régime et la gestion des déficits sont des leviers essentiels pour optimiser la fiscalité des revenus fonciers.',
  summaryItems: [
    { label: 'Principe général : imposition des loyers perçus', anchor: 'principe-general' },
    { label: 'Régime micro-foncier : abattement forfaitaire de 30 %', anchor: 'micro-foncier' },
    { label: 'Régime réel : déduction des charges et frais', anchor: 'regime-reel' },
    { label: 'TMI et prélèvements sociaux : le taux combiné', anchor: 'tmi-prelevements' },
    { label: 'Déficit foncier : imputation sur le revenu global', anchor: 'deficit-foncier' },
    { label: 'Tableau comparatif micro-foncier vs régime réel', anchor: 'tableau-comparatif' },
    { label: 'Plus-values immobilières en cas de revente', anchor: 'plus-values' },
    { label: 'Exemple pédagogique : impact du régime sur le net', anchor: 'exemple-pedagogique' },
    { label: 'Erreurs fréquentes avec la fiscalité des revenus fonciers', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour analyser la fiscalité', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 20,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['revenus fonciers', 'fiscalité', 'TMI', 'prélèvements sociaux', 'déficit foncier', 'micro-foncier', 'régime réel', 'CGP-CIF'],
  sections: [
    {
      id: 'principe-general',
      title: 'Principe général : les loyers perçus sont imposables',
      level: 'h2',
      type: 'normal',
      content: [
        "Les revenus fonciers sont les loyers et les recettes accessoires perçus par un propriétaire qui donne un bien immobilier en location. Ils sont imposables dans la catégorie des revenus fonciers de l'impôt sur le revenu, conformément aux dispositions du Code général des impôts.",
        "Le calcul de l'impôt sur les revenus fonciers se fait en deux temps : d'abord, le revenu foncier net est déterminé (loyers bruts diminués des charges déductibles), puis ce revenu net est ajouté au revenu global du foyer fiscal et soumis au barème progressif de l'impôt sur le revenu (TMI).",
        "En plus de l'impôt sur le revenu, les revenus fonciers sont soumis aux prélèvements sociaux au taux de 17,2 % (CSG, CRDS, prélèvement de solidarité). La CSG est partiellement déductible du revenu imposable à hauteur de 6,8 %.",
        "Le taux d'imposition combiné (IR + PS) varie donc en fonction de la TMI du contribuable, ce qui signifie que deux propriétaires percevant les mêmes loyers peuvent être imposés très différemment.",
        "Les revenus fonciers sont à déclarer chaque année dans la déclaration de revenus, sur le formulaire 2044 (régime réel) ou dans la case prévue pour le micro-foncier. L'administration fiscale peut contrôler les déclarations et remettre en cause les charges déduites.",
      ],
    },
    {
      id: 'micro-foncier',
      title: 'Régime micro-foncier : abattement forfaitaire de 30 %',
      level: 'h2',
      type: 'normal',
      content: [
        "Le régime micro-foncier est un régime simplifié d'imposition des revenus fonciers. Il s'applique de plein droit lorsque le montant annuel des loyers perçus (tous biens confondus) ne dépasse pas 15 000 €.",
        "Dans ce régime, le propriétaire bénéficie d'un abattement forfaitaire de 30 % sur le montant des loyers perçus, qui couvre l'ensemble des charges et frais (taxe foncière, frais de gestion, travaux d'entretien). Le revenu foncier imposable est donc égal à 70 % des loyers perçus.",
        "Exemple : pour des loyers annuels de 12 000 €, le revenu foncier imposable est de 12 000 € × 70 % = 8 400 €. Si la TMI du contribuable est de 30 %, l'impôt sur le revenu est de 8 400 € × 30 % = 2 520 €, et les prélèvements sociaux de 8 400 € × 17,2 % = 1 444,80 €.",
        "Le principal avantage du micro-foncier est sa simplicité : pas de déclaration complexe, pas de justificatifs à fournir, abattement automatique. Il est particulièrement adapté aux propriétaires dont les charges réelles sont inférieures à 30 % des loyers.",
        "En revanche, si les charges réelles (taxe foncière, travaux, intérêts d'emprunt, frais de gestion) dépassent 30 % des loyers, le régime réel est plus avantageux car il permet de déduire le montant réel des charges, potentiellement supérieur à l'abattement forfaitaire.",
        "Il est possible d'opter pour le régime réel même si les loyers sont inférieurs à 15 000 €, si cette option est plus favorable. L'option est irrévocable pour une durée minimale de 3 ans.",
      ],
    },
    {
      id: 'regime-reel',
      title: 'Régime réel : déduction des charges et frais réels',
      level: 'h2',
      type: 'normal',
      content: [
        "Le régime réel d'imposition des revenus fonciers est obligatoire lorsque les loyers annuels perçus dépassent 15 000 € (tous biens confondus). Il peut également être choisi sur option si les loyers sont inférieurs à ce seuil.",
        "Dans ce régime, le propriétaire déduit du montant des loyers perçus l'ensemble des charges et frais réels supportés dans le cadre de la location. Les charges déductibles sont nombreuses et comprennent notamment :",
        "- La taxe foncière (hors taxe d'enlèvement des ordures ménagères pour certaines locations) ;",
        "- Les frais de gestion et de garde (agence immobilière, syndic) ;",
        "- Les intérêts d'emprunt (prêt immobilier contracté pour l'acquisition, la construction ou les travaux du bien) ;",
        "- Les primes d'assurance (assurance propriétaire non occupant, assurance loyers impayés) ;",
        "- Les frais de copropriété (charges récupérables ou non) ;",
        "- Les travaux de réparation, d'entretien et d'amélioration (hors travaux de construction ou d'agrandissement) ;",
        "- Les frais de procédure (contentieux locatifs, recouvrement de loyers impayés) ;",
        "- Les frais de déplacement et de gestion (sous conditions).",
        "Si le total des charges déductibles dépasse le montant des loyers perçus, le propriétaire est en situation de déficit foncier. Ce déficit peut être imputé sur le revenu global dans la limite de 10 700 € par an, ou reporté sur les revenus fonciers des années suivantes.",
        "Le régime réel nécessite une déclaration détaillée (formulaire 2044) avec le détail de chaque charge. Il est recommandé de conserver tous les justificatifs (factures, quittances, contrats) en cas de contrôle fiscal.",
      ],
    },
    {
      id: 'tmi-prelevements',
      title: 'TMI et prélèvements sociaux : le taux d\'imposition combiné',
      level: 'h2',
      type: 'normal',
      content: [
        "Le taux d'imposition effectif des revenus fonciers est la somme de la TMI du contribuable et des prélèvements sociaux (17,2 %), ce qui peut donner un taux combiné très élevé.",
        "Pour un contribuable non imposable (TMI 0 %), le taux d'imposition des revenus fonciers est de 17,2 % (prélèvements sociaux uniquement). Pour un contribuable à 11 % de TMI, le taux combiné est de 28,2 %. Pour une TMI de 30 %, le taux combiné est de 47,2 %. Pour une TMI de 41 %, il atteint 58,2 %. Pour une TMI de 45 %, le taux combiné est de 62,2 %.",
        "Ces taux élevés expliquent pourquoi la fiscalité des revenus fonciers peut considérablement réduire la rentabilité nette d'un investissement locatif. Un rendement brut de 5 % peut ainsi se transformer en rendement net de 2,5 % à 3 % après impôt pour un contribuable à TMI élevée.",
        "Plusieurs stratégies permettent de réduire l'impact fiscal :",
        "- Opter pour le régime réel si les charges déductibles sont élevées ;",
        "- Générer un déficit foncier pour imputer les travaux sur le revenu global ;",
        "- Investir via une SCI soumise à l'IS pour bénéficier d'un taux d'impôt sur les sociétés (15 % à 25 %) ;",
        "- Choisir des SCPI plutôt que de l'immobilier direct pour diversifier et optimiser.",
        "Il est essentiel de simuler l'impact fiscal avant d'investir, en tenant compte de sa TMI actuelle et des charges prévisibles, pour évaluer la rentabilité nette réelle de l'opération.",
      ],
    },
    {
      id: 'deficit-foncier',
      title: 'Déficit foncier : imputation sur le revenu global',
      level: 'h2',
      type: 'normal',
      content: [
        "Le déficit foncier est un mécanisme fiscal qui permet aux propriétaires bailleurs de déduire de leur revenu global le déficit généré par un bien locatif, dans la limite de 10 700 € par an.",
        "Le déficit apparaît lorsque le total des charges déductibles (intérêts d'emprunt, travaux, taxe foncière, frais de gestion) dépasse le montant des loyers perçus. La partie du déficit correspondant aux intérêts d'emprunt n'est imputable que sur les revenus fonciers des années suivantes (pas sur le revenu global).",
        "Le déficit foncier est un outil particulièrement intéressant pour les contribuables à TMI élevée qui réalisent des travaux importants dans un bien locatif. Exemple : un propriétaire à 41 % de TMI qui réalise 40 000 € de travaux sur un bien locatif peut imputer 10 700 € par an sur son revenu global pendant trois ans, générant une économie d'impôt de 10 700 € × 41 % = 4 387 € par an, soit 13 161 € au total.",
        "Au-delà de 10 700 €, le déficit excédentaire est reporté sur les revenus fonciers des années suivantes, sans limitation de durée. Cela permet de réduire, voire d'annuler, l'imposition des loyers perçus pendant plusieurs années.",
        "Le déficit foncier est soumis à des conditions strictes :",
        "- Les travaux doivent être des travaux de réparation, d'entretien ou d'amélioration (hors construction et agrandissement) ;",
        "- Le bien doit être loué (ou destiné à être loué) ;",
        "- Les charges doivent être justifiées par des factures ;",
        "- Le propriétaire doit opter pour le régime réel d'imposition.",
        "L'imputation du déficit sur le revenu global est un levier d'optimisation fiscale puissant, mais il nécessite une planification rigoureuse et une bonne connaissance des règles applicables.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif micro-foncier vs régime réel',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous compare le régime micro-foncier et le régime réel d\'imposition des revenus fonciers.',
      ],
      table: {
        headers: ['Critère', 'Micro-foncier', 'Régime réel'],
        rows: [
          ['Conditions d\'application', 'Loyers annuels ≤ 15 000 € (automatique)', 'Loyers > 15 000 € (obligatoire) ou sur option'],
          ['Abattement / Déduction', 'Abattement forfaitaire de 30 %', 'Déduction des charges réelles'],
          ['Complexité', 'Très simple (case à cocher)', 'Complexe (déclaration détaillée, justificatifs)'],
          ['Intérêts d\'emprunt', 'Non déductibles (inclus dans l\'abattement)', 'Déductibles des loyers'],
          ['Travaux', 'Non déductibles (inclus dans l\'abattement)', 'Déductibles selon leur nature'],
          ['Déficit foncier', 'Impossible (pas de déficit)', 'Possible (imputation sur revenu global 10 700 €/an)'],
          ['Option possible', 'Oui, option pour le réel', 'N/A (obligatoire ou sur option)'],
          ['Durée de l\'option', '3 ans irrévocables', 'N/A'],
          ['Recommandé pour', 'Charges < 30 % des loyers, biens sans crédit', 'Charges > 30 %, crédit en cours, travaux'],
        ],
      },
    },
    {
      id: 'plus-values',
      title: 'Plus-values immobilières en cas de revente',
      level: 'h2',
      type: 'normal',
      content: [
        "En cas de revente d'un bien immobilier locatif, la plus-value réalisée est soumise à l'impôt sur le revenu au taux de 19 % et aux prélèvements sociaux de 17,2 %, soit un taux combiné de 36,2 %. Des abattements pour durée de détention permettent de réduire, voire d'annuler, l'imposition.",
        "Les abattements pour durée de détention s'appliquent comme suit :",
        "- Pour l'impôt sur le revenu : 6 % par an de la 6e à la 21e année, puis 4 % pour la 22e année (exonération totale après 22 ans) ;",
        "- Pour les prélèvements sociaux : 1,65 % par an de la 6e à la 21e année (exonération totale après 30 ans).",
        "Des abattements exceptionnels peuvent s'appliquer pour certaines catégories de biens (logements sociaux, zones ANRU) ou pour les cessions aux organismes HLM.",
        "La plus-value imposable est calculée sur la différence entre le prix de cession et le prix d'acquisition (ou la valeur déclarée en cas de donation). Le prix d'acquisition peut être majoré des frais d'acquisition (7,5 % forfaitaires ou réels) et des travaux réalisés (sous conditions).",
        "La cession de la résidence principale est exonérée d'impôt sur les plus-values, ce qui n'est pas le cas des biens locatifs. C'est un point important à prendre en compte dans la stratégie patrimoniale.",
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : micro-foncier vs régime réel',
      level: 'h2',
      type: 'normal',
      content: [
        "Prenons l'exemple de Mme Moreau, TMI de 30 %, qui perçoit 12 000 € de loyers annuels d'un appartement acquis 200 000 € avec un crédit de 150 000 € à 3 % sur 20 ans. Ses charges annuelles sont de 5 000 € (taxe foncière : 1 200 €, intérêts d'emprunt : 4 200 €, assurance : 400 €, frais de gestion : 600 €). Elle se demande quel régime choisir.",
        "Régime micro-foncier :",
        "- Revenu imposable : 12 000 € × 70 % = 8 400 €",
        "- IR (30 %) : 8 400 € × 30 % = 2 520 €",
        "- PS (17,2 %) : 8 400 € × 17,2 % = 1 444,80 €",
        "- Impôt total : 3 964,80 €",
        "- Revenu net après impôt : 12 000 € - 3 964,80 € = 8 035,20 €",
        "Régime réel :",
        "- Revenu imposable : 12 000 € - 5 000 € = 7 000 €",
        "- IR (30 %) : 7 000 € × 30 % = 2 100 €",
        "- PS (17,2 %) : 7 000 € × 17,2 % = 1 204 €",
        "- Impôt total : 3 304 €",
        "- Revenu net après impôt : 12 000 € - 3 304 € = 8 696 €",
        "Le régime réel est plus avantageux de 660,80 € par an dans cette situation, car les charges réelles (5 000 €) dépassent l'abattement forfaitaire de 30 % (3 600 €). Si elle réalise en plus des travaux, l'écart serait encore plus favorable au régime réel (déficit foncier possible).",
        "Inversement, si les charges réelles sont inférieures à 3 600 €, le micro-foncier serait plus avantageux. Ces chiffres sont donnés à titre pédagogique et ne constituent pas un conseil personnalisé.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes avec la fiscalité des revenus fonciers',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que plusieurs erreurs reviennent régulièrement chez les propriétaires bailleurs :'],
      listItems: [
        'Opter pour le micro-foncier sans vérifier si le régime réel serait plus avantageux (charges réelles vs abattement de 30 %).',
        'Oublier de déduire les intérêts d\'emprunt dans le régime réel, ce qui peut représenter plusieurs milliers d\'euros de charges déductibles.',
        'Confondre revenu brut et revenu net de fiscalité : le taux d\'imposition combiné peut atteindre 62,2 % pour les TMI élevées.',
        'Ne pas déclarer les prélèvements sociaux sur les revenus fonciers : ils sont intégrés dans la déclaration de revenus.',
        'Négliger le déficit foncier : des travaux importants peuvent générer un déficit imputable sur le revenu global.',
        'Déclarer des travaux de construction ou d\'agrandissement comme des charges déductibles : seuls les travaux d\'entretien, de réparation et d\'amélioration sont déductibles.',
        'Oublier de conserver les justificatifs de charges (factures, quittances, contrats) en cas de contrôle fiscal.',
        'Ne pas déclarer les revenus fonciers étrangers (résidence à l\'étranger) qui sont également soumis à l\'impôt en France, sous réserve des conventions fiscales.',
        'Ignorer la déductibilité partielle de la CSG (6,8 %) qui réduit le revenu imposable l\'année suivante.',
        'Vendre un bien locatif sans anticiper l\'impôt sur les plus-values immobilières (19 % IR + 17,2 % PS).',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance sur la fiscalité des revenus fonciers',
      level: 'h2',
      type: 'risk',
      content: [
        'La fiscalité des revenus fonciers comporte des points de vigilance qu\'il est essentiel de connaître avant d\'investir dans l\'immobilier locatif.',
      ],
      listItems: [
        'Le taux d\'imposition combiné (TMI + PS) peut rendre un investissement locatif peu rentable pour les contribuables à TMI élevée. Une simulation préalable est indispensable.',
        'Le déficit foncier est plafonné à 10 700 € d\'imputation sur le revenu global par an. Au-delà, le déficit est reportable sur les revenus fonciers sans limitation de durée.',
        'Les intérêts d\'emprunt sont déductibles des revenus fonciers dans le régime réel, mais ne peuvent pas générer de déficit imputable sur le revenu global. Ils sont reportables sur les revenus fonciers.',
        'L\'option pour le régime réel est irrévocable pendant 3 ans. Il faut être certain que ce régime est plus avantageux avant d\'opter.',
        'La taxe foncière a augmenté significativement ces dernières années dans certaines communes. Cette charge récurrente doit être intégrée dans le calcul de rentabilité.',
        'Les revenus fonciers s\'ajoutent aux autres revenus du foyer et peuvent faire basculer le contribuable dans une tranche supérieure d\'imposition (TMI), augmentant l\'impôt sur l\'ensemble des revenus.',
        'La gestion locative comporte des risques (vacance locative, impayés, dégradations) qui peuvent transformer un investissement rentable en source de déficit non imputable.',
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour analyser la fiscalité des revenus fonciers',
      level: 'h2',
      type: 'method-steps',
      content: [
        "L'analyse de la fiscalité des revenus fonciers suit une méthode structurée en 6 étapes, dans le respect du cadre réglementaire des CGP-CIF.",
      ],
      methodSteps: [
        { title: 'Analyse de la TMI et de la situation fiscale', description: "Détermination précise de la TMI du foyer, des autres revenus imposables, et de l'impact potentiel des revenus fonciers sur la tranche d'imposition." },
        { title: 'Définition du projet immobilier', description: "Analyse du bien (type, localisation, prix), du mode d'acquisition (comptant ou crédit), du montant des travaux prévisibles et du rendement locatif attendu." },
        { title: 'Choix du régime d\'imposition', description: "Comparaison détaillée entre le micro-foncier et le régime réel, en fonction du montant des loyers, des charges prévisibles et des intérêts d'emprunt. Simulation de l'impôt dû dans chaque scénario." },
        { title: 'Optimisation du déficit foncier', description: "Analyse de l'opportunité de générer un déficit foncier par des travaux, dans la limite de 10 700 € par an, pour réduire l'impôt sur le revenu global." },
        { title: 'Évaluation de la rentabilité nette', description: "Calcul du rendement net après impôt, en intégrant la fiscalité, les charges, les frais et le coût du crédit. Comparaison avec les alternatives d'investissement." },
        { title: 'Suivi et déclaration', description: "Mise en place d'un suivi annuel des charges et des loyers, préparation de la déclaration fiscale, conservation des justificatifs. Révision périodique de la stratégie." },
      ],
    },
    {
      id: 'faq',
      title: 'Questions fréquentes sur la fiscalité des revenus fonciers',
      level: 'h2',
      type: 'faq',
      content: ['Retrouvez les réponses aux questions les plus fréquentes concernant la fiscalité des revenus fonciers.'],
      listItems: [
        'Quels sont les revenus fonciers imposables ?',
        'Quelle est la différence entre micro-foncier et régime réel ?',
        'Comment sont calculés les prélèvements sociaux sur les revenus fonciers ?',
        'Le déficit foncier est-il plafonné ?',
        'Les intérêts d\'emprunt sont-ils déductibles des revenus fonciers ?',
        'Quels travaux sont déductibles des revenus fonciers ?',
        'Faut-il déclarer les revenus fonciers chaque année ?',
        'Quel est l\'impôt sur les plus-values immobilières ?',
        'Le régime réel est-il obligatoire au-delà de 15 000 € de loyers ?',
        'Un investissement locatif est-il toujours rentable après impôt ?',
      ],
    },
  ],
  faq: [
    { question: 'Quels sont les revenus fonciers imposables ?', answer: 'Les revenus fonciers imposables sont les loyers perçus, les recettes accessoires (charges récupérées, produits de la location de meubles), et les revenus des SCPI. Les loyers perçus dans le cadre de la location meublée sont imposés dans la catégorie des BIC (LMNP/LMP), pas dans les revenus fonciers.' },
    { question: 'Quelle est la différence entre micro-foncier et régime réel ?', answer: 'Le micro-foncier applique un abattement forfaitaire de 30 % sur les loyers bruts, sans déduction des charges réelles. Le régime réel permet de déduire l\'ensemble des charges et frais réels (intérêts d\'emprunt, travaux, taxe foncière, frais de gestion).' },
    { question: 'Comment sont calculés les prélèvements sociaux sur les revenus fonciers ?', answer: 'Les prélèvements sociaux (17,2 %) sont calculés sur le revenu foncier net imposable (après abattement ou déduction des charges). La CSG (9,2 %) est partiellement déductible du revenu imposable à hauteur de 6,8 % l\'année suivante.' },
    { question: 'Le déficit foncier est-il plafonné ?', answer: 'Oui, le déficit foncier imputable sur le revenu global est plafonné à 10 700 € par an. La partie du déficit correspondant aux intérêts d\'emprunt est imputable uniquement sur les revenus fonciers des années suivantes.' },
    { question: 'Les intérêts d\'emprunt sont-ils déductibles des revenus fonciers ?', answer: 'Oui, dans le régime réel, les intérêts d\'emprunt sont déductibles des loyers perçus. Si les intérêts dépassent les loyers, le déficit correspondant est reportable sur les revenus fonciers des années suivantes.' },
    { question: 'Quels travaux sont déductibles des revenus fonciers ?', answer: 'Sont déductibles les travaux de réparation, d\'entretien et d\'amélioration (art. 31 du CGI). Les travaux de construction, reconstruction ou agrandissement ne sont pas déductibles. Les travaux d\'amélioration sont déductibles sous conditions (installation sanitaire, chauffage, etc.).' },
    { question: 'Faut-il déclarer les revenus fonciers chaque année ?', answer: 'Oui, les revenus fonciers doivent être déclarés chaque année dans la déclaration de revenus, sur le formulaire 2044 (régime réel) ou dans la case prévue pour le micro-foncier.' },
    { question: 'Quel est l\'impôt sur les plus-values immobilières ?', answer: 'Les plus-values immobilières sont imposées à 19 % (impôt sur le revenu) + 17,2 % (prélèvements sociaux) = 36,2 %. Des abattements pour durée de détention s\'appliquent : exonération totale d\'IR après 22 ans et de PS après 30 ans.' },
    { question: 'Le régime réel est-il obligatoire au-delà de 15 000 € de loyers ?', answer: 'Oui, le régime réel est obligatoire lorsque le montant annuel des loyers perçus (tous biens confondus) dépasse 15 000 €. En dessous de ce seuil, le micro-foncier s\'applique de plein droit mais l\'option pour le réel est possible.' },
    { question: 'Un investissement locatif est-il toujours rentable après impôt ?', answer: 'Non, la rentabilité après impôt dépend fortement de la TMI du contribuable, du montant des charges, du coût du crédit et de la fiscalité applicable. Une simulation préalable est indispensable pour évaluer la rentabilité nette réelle d\'un projet locatif.' },
  ],
  ctaTitle: 'Vous souhaitez analyser la fiscalité de votre investissement locatif ?',
  ctaText: 'Un échange personnalisé permet d\'évaluer l\'impact fiscal de votre projet immobilier et d\'optimiser votre stratégie patrimoniale. Eric Bellaiche, CGP-CIF, vous accompagne dans votre analyse.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/deficit-foncier/', label: 'Déficit foncier : fonctionnement et optimisation', position: 'inline' },
    { href: '/articles/lmnp-ou-location-nue/', label: 'LMNP ou location nue : comment choisir', position: 'inline' },
    { href: '/articles/immobilier-locatif-fiscalite/', label: 'Immobilier locatif et fiscalité', position: 'inline' },
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité', position: 'inline' },
  ],
  complianceNotes: [
    'Les simulations présentées sont basées sur des hypothèses fiscales en vigueur au 11 juin 2026 et ne préjugent pas des évolutions futures.',
    'Ce contenu est fourni à titre d\'information générale et ne constitue pas un conseil personnalisé.',
  ],
  hasRisks: false,
};

export default article;
