import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'immobilier-locatif-fiscalite',
  category: 'fiscalite',
  title: 'Immobilier locatif et fiscalité : ce qu\'il faut analyser avant d\'investir',
  metaTitle: 'Immobilier locatif et fiscalité : analyse complète avant d\'investir - CGP-CIF',
  metaDescription: 'Guide complet sur la fiscalité de l\'immobilier locatif : revenus fonciers, plus-values, IFI, durée de détention, LMNP, SCI, déficit foncier. Analyse et conseils par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/immobilier-locatif-fiscalite/',
  badge: 'Immobilier &bull; Fiscalité &bull; Revenus fonciers &bull; IFI &bull; Plus-values &bull; CGP-CIF',
  intro: 'Investir dans l\'immobilier locatif ne se limite pas à choisir un bien et un emplacement. La fiscalité qui entoure l\'investissement immobilier est complexe, multidimensionnelle et évolutive. Elle impacte directement la rentabilité nette, la trésorerie disponible, les conditions de revente et la transmission du patrimoine. Que l\'on opte pour la location nue, le meublé, une SCI ou un dispositif de défiscalisation, chaque choix fiscal a des implications profondes sur le rendement réel de l\'investissement. Avant d\'acquérir un bien locatif, il est essentiel de comprendre les mécanismes fiscaux qui s\'appliqueront pendant toute la durée de détention et au moment de la sortie. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous propose un tour d\'horizon complet des enjeux fiscaux de l\'immobilier locatif.',
  shortAnswer: 'La fiscalité de l\'immobilier locatif recouvre plusieurs dimensions : les revenus fonciers (imposition des loyers dans la catégorie des revenus fonciers ou des BIC), la fiscalité des plus-values à la revente (avec abattements pour durée de détention), l\'IFI (impôt sur la fortune immobilière pour les patrimoines supérieurs à 1,3 million d\'euros), et les dispositifs d\'optimisation (déficit foncier, amortissement LMNP, SCI). Le choix du régime fiscal (location nue ou meublée, SCI à l\'IR ou à l\'IS) détermine la rentabilité nette et la fiscalité de sortie. Une analyse préalable est indispensable pour adapter la structure à la situation personnelle, à l\'horizon de détention et aux objectifs patrimoniaux.',
  summaryItems: [
    { label: 'Revenus fonciers : régime micro-foncier et régime réel', anchor: 'revenus-fonciers-micro-reel' },
    { label: 'Location meublée (LMNP) : BIC et amortissement', anchor: 'location-meublee-bic' },
    { label: 'Fiscalité des plus-values immobilières', anchor: 'fiscalite-plus-values' },
    { label: 'IFI : impôt sur la fortune immobilière', anchor: 'ifi-impot-fortune' },
    { label: 'Déficit foncier : imputation et plafond', anchor: 'deficit-foncier-imputation' },
    { label: 'Tableau récapitulatif des régimes fiscaux', anchor: 'tableau-regimes-fiscaux' },
    { label: 'Impact de la durée de détention sur la fiscalité', anchor: 'duree-detention-impact' },
    { label: 'Exemple pédagogique : rentabilité nette selon le régime', anchor: 'exemple-rentabilite-nette' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour analyser la fiscalité', anchor: 'methode-analyse-fiscalite' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 22,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['immobilier locatif', 'fiscalité', 'revenus fonciers', 'IFI', 'plus-values', 'CGP-CIF'],
  sections: [
    {
      id: 'revenus-fonciers-micro-reel',
      title: 'Revenus fonciers : régime micro-foncier et régime réel',
      level: 'h2',
      type: 'normal',
      content: [
        'Les revenus tirés de la location d\'un bien immobilier non meublé sont imposés dans la catégorie des revenus fonciers, conformément à l\'article 14 du Code général des impôts. Deux régimes coexistent selon le montant des recettes et le choix de l\'investisseur.',
        'Le micro-foncier s\'applique automatiquement lorsque les revenus fonciers annuels sont inférieurs à 15 000 €. Il offre un abattement forfaitaire de 30 % sur les loyers bruts perçus. Cet abattement est censé couvrir l\'ensemble des charges : intérêts d\'emprunt, taxe foncière, travaux, frais de gestion, assurances. Aucune charge réelle ne peut être déduite en sus. Le micro-foncier est simple à déclarer mais peut s\'avérer moins avantageux que le régime réel si les charges sont élevées.',
        'Le régime réel est accessible sur option ou obligatoire lorsque les revenus fonciers dépassent 15 000 € par an. Il permet de déduire l\'intégralité des charges réelles supportées : intérêts d\'emprunt, taxe foncière, charges de copropriété, frais de gestion, assurances, travaux d\'entretien et de réparation. Les travaux de reconstruction, d\'agrandissement ou de surélévation ne sont pas déductibles mais viennent augmenter le prix de revient du bien (amortissable ou non selon le régime).',
        'Le choix entre micro-foncier et régime réel n\'est pas définitif. L\'option pour le régime réel est valable pour un an et se renouvelle tacitement. Il est possible de revenir au micro-foncier si les recettes redeviennent inférieures à 15 000 €, sous réserve de respecter les délais de renonciation à l\'option.',
        'Un point essentiel : le régime réel permet de générer un déficit foncier lorsque les charges déductibles dépassent les loyers perçus. Ce déficit peut être imputé sur le revenu global du contribuable dans la limite de 10 700 € par an, offrant ainsi une optimisation fiscale significative, notamment les premières années de détention lorsque les intérêts d\'emprunt sont élevés.',
      ],
    },
    {
      id: 'location-meublee-bic',
      title: 'Location meublée (LMNP) : BIC et amortissement',
      level: 'h2',
      type: 'normal',
      content: [
        'La location meublée relève d\'un régime fiscal distinct : les revenus sont imposés dans la catégorie des BIC (bénéfices industriels et commerciaux). Le statut de Loueur en Meublé Non Professionnel (LMNP) permet de bénéficier de l\'amortissement du bien immobilier (hors terrain) et du mobilier, ce qui constitue un avantage fiscal significatif par rapport à la location nue.',
        'En LMNP, deux régimes sont possibles. Le micro-BIC applique un abattement forfaitaire de 50 % sur les loyers bruts, avec un plafond de recettes de 77 700 € par an. Le régime réel permet de déduire l\'amortissement et l\'ensemble des charges réelles. Pour un bien immobilier de valeur significative, le régime réel est presque toujours plus avantageux, malgré la contrainte comptable qu\'il impose.',
        'L\'amortissement en LMNP permet de déduire chaque année une fraction de la valeur du bien (hors terrain) du résultat imposable. Sur une durée de 25 à 30 ans, l\'amortissement cumulé peut atteindre 60 à 70 % de la valeur du bien, réduisant à zéro l\'imposition des loyers pendant la majeure partie de la période de détention.',
        'Il est important de comprendre que l\'amortissement n\'est pas une charge décaissée : il réduit l\'impôt sans sortie de trésorerie. C\'est un différé d\'imposition, car à la revente, le prix d\'acquisition fiscal est réduit du montant des amortissements pratiqués, ce qui augmente la plus-value imposable. Toutefois, les abattements pour durée de détention atténuent cet effet pour les détentions longues.',
        'La location meublée permet également des locations saisonnières, ce qui offre une flexibilité accrue par rapport à la location nue. En contrepartie, la gestion est plus lourde, le turn-over locatif plus élevé et une comptabilité professionnelle est nécessaire.',
      ],
    },
    {
      id: 'fiscalite-plus-values',
      title: 'Fiscalité des plus-values immobilières',
      level: 'h2',
      type: 'normal',
      content: [
        'La vente d\'un bien immobilier locatif génère une plus-value imposable correspondant à la différence entre le prix de cession et le prix d\'acquisition (ou la valeur déclarée pour les biens reçus par donation ou succession).',
        'La plus-value brute est calculée en déduisant du prix de cession le prix d\'acquisition, auquel peuvent s\'ajouter certains frais (frais d\'acquisition, travaux) sous conditions. Le régime des plus-values immobilières s\'applique, avec un taux d\'imposition de 19 % pour l\'impôt sur le revenu et 17,2 % pour les prélèvements sociaux, soit un total de 36,2 %. Des prélèvements supplémentaires (taxe sur les plus-values élevées) peuvent s\'appliquer pour les plus-values supérieures à 50 000 €.',
        'Des abattements pour durée de détention réduisent l\'imposition au fil du temps. Pour l\'impôt sur le revenu, l\'abattement est de 6 % par an de la 6e à la 21e année de détention, puis 4 % la 22e année, conduisant à une exonération totale au bout de 22 ans. Pour les prélèvements sociaux, l\'abattement est de 1,65 % par an de la 6e à la 21e année, puis 1,60 % de la 22e à la 30e année, avec exonération totale après 30 ans.',
        'En cas de détention en LMNP (location meublée), le prix d\'acquisition fiscal est réduit du montant des amortissements pratiqués, ce qui augmente mécaniquement la plus-value imposable. C\'est la contrepartie de l\'avantage fiscal obtenu pendant la détention.',
        'La résidence principale est exonérée de plus-value, ce qui n\'est pas le cas des investissements locatifs. La vente d\'un bien locatif est donc presque toujours imposable, sauf à respecter certaines conditions (détention longue, cession à un prix inférieur au prix d\'acquisition).',
      ],
    },
    {
      id: 'ifi-impot-fortune',
      title: 'IFI : impôt sur la fortune immobilière',
      level: 'h2',
      type: 'normal',
      content: [
        'Depuis la réforme de 2018, l\'impôt sur la fortune immobilière (IFI) a remplacé l\'ISF en ne taxant que le patrimoine immobilier, à l\'exclusion des actifs financiers. Tout investisseur immobilier dont le patrimoine immobilier net taxable dépasse 1,3 million d\'euros est potentiellement redevable de l\'IFI.',
        'Le patrimoine pris en compte comprend l\'ensemble des biens et droits immobiliers détenus directement ou indirectement (via une SCI, une SCPI, ou des parts de fonds immobiliers). Les dettes afférentes aux biens immobiliers (emprunts en cours) sont déductibles pour le calcul de l\'assiette nette.',
        'Pour un investisseur locatif, l\'IFI s\'ajoute aux autres impôts (impôt sur le revenu, prélèvements sociaux) et peut réduire significativement la rentabilité nette. Il est essentiel d\'intégrer l\'IFI dans le calcul de rendement global, en particulier pour les patrimoines immobiliers importants.',
        'Plusieurs stratégies permettent de réduire l\'IFI : le recours à l\'emprunt (les dettes sont déductibles), l\'investissement via des contrats d\'assurance-vie en unités de compte (horsIFI si les supports ne sont pas immobiliers), la détention de parts de SCPI avec une part de dette, ou l\'arbitrage vers des actifs financiers non imposables à l\'IFI.',
        'L\'IFI ne concerne pas uniquement les patrimoines très importants : un investisseur ayant accumulé plusieurs biens locatifs sur 10 à 20 ans peut franchir le seuil des 1,3 million d\'euros sans s\'en rendre compte. Une estimation régulière du patrimoine immobilier net est recommandée.',
      ],
    },
    {
      id: 'deficit-foncier-imputation',
      title: 'Déficit foncier : imputation et plafond',
      level: 'h2',
      type: 'normal',
      content: [
        'Le régime du déficit foncier est l\'un des dispositifs d\'optimisation fiscale les plus puissants pour les investisseurs immobiliers en location nue. Il permet, sous conditions, d\'imputer le déficit généré par un bien locatif sur le revenu global du contribuable.',
        'Le mécanisme est simple : lorsque les charges déductibles (intérêts d\'emprunt, taxe foncière, travaux d\'entretien, frais de gestion, assurances) dépassent les loyers perçus, le déficit est imputable sur le revenu global du foyer fiscal dans la limite de 10 700 € par an. Au-delà de ce plafond, le surplus est reporté sur les revenus fonciers des années suivantes pendant 10 ans.',
        'Les intérêts d\'emprunt sont déductibles des revenus fonciers sans limitation, mais ils ne peuvent pas générer de déficit imputable sur le revenu global. Seuls les déficits issus des autres charges (travaux, taxe foncière, frais de gestion) sont imputables sur le revenu global, dans la limite du plafond de 10 700 €.',
        'Pour un investisseur avec une TMI de 30 %, un déficit foncier de 10 700 € permet d\'économiser environ 5 000 € d\'impôt sur le revenu par an (10 700 € x 47,2 % incluant les prélèvements sociaux). C\'est un levier d\'optimisation particulièrement efficace en début de détention, lorsque les travaux et les intérêts d\'emprunt sont élevés.',
        'Le déficit foncier nécessite d\'être au régime réel d\'imposition des revenus fonciers. Il est cumulable avec d\'autres dispositifs, mais ne concerne que la location nue (pas le LMNP). Le recours à un expert-comptable ou un conseiller en gestion de patrimoine est recommandé pour optimiser le dispositif.',
      ],
    },
    {
      id: 'tableau-regimes-fiscaux',
      title: 'Tableau récapitulatif des régimes fiscaux de l\'immobilier locatif',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous récapitule les principaux régimes fiscaux applicables à l\'immobilier locatif, leurs caractéristiques et leurs avantages respectifs.',
      ],
      table: {
        headers: ['Régime', 'Catégorie', 'Abattement / Déduction', 'Plafond micro', 'Amortissement'],
        rows: [
          ['Micro-foncier (location nue)', 'Revenus fonciers', 'Abattement forfaitaire 30 %', '15 000 €/an', 'Non'],
          ['Régime réel (location nue)', 'Revenus fonciers', 'Charges réelles déductibles', 'Sans objet', 'Non'],
          ['Micro-BIC (LMNP)', 'BIC', 'Abattement forfaitaire 50 %', '77 700 €/an', 'Non (micro)'],
          ['Régime réel (LMNP)', 'BIC', 'Amortissement + charges réelles', 'Sans objet', 'Oui (hors terrain)'],
          ['SCI à l\'IR', 'Revenus fonciers (ou BIC)', 'Transparence fiscale, charges réelles', 'Sans objet', 'Non'],
          ['SCI à l\'IS', 'IS', 'Amortissement + charges réelles (société)', 'Sans objet', 'Oui (hors terrain)'],
          ['Déficit foncier', 'Revenus fonciers (régime réel)', 'Imputation sur revenu global', '10 700 €/an', 'Non'],
        ],
      },
    },
    {
      id: 'duree-detention-impact',
      title: 'Impact de la durée de détention sur la fiscalité',
      level: 'h2',
      type: 'normal',
      content: [
        'La durée de détention est un paramètre essentiel de la stratégie fiscale immobilière. Elle influence à la fois la fiscalité des revenus pendant la détention et la fiscalité des plus-values à la sortie.',
        'À court terme (moins de 6 ans), le bien locatif est dans sa phase la moins optimisée fiscalement. Les intérêts d\'emprunt sont élevés (en début de crédit), les abattements pour durée de détention ne s\'appliquent pas encore sur la plus-value, et les éventuels amortissements LMNP commencent tout juste à produire leurs effets. Une revente précoce expose à une fiscalité élevée sur la plus-value (36,2 % sans abattement).',
        'À moyen terme (6 à 15 ans), les abattements pour durée de détention commencent à s\'appliquer sur la plus-value (6 % par an de la 6e à la 21e année pour l\'IR). Les intérêts d\'emprunt diminuent progressivement, améliorant le cash-flow. En LMNP, l\'amortissement continue de réduire l\'imposition des loyers. C\'est la phase de rentabilité nette optimale.',
        'À long terme (plus de 22 ans), la plus-value est totalement exonérée d\'impôt sur le revenu (mais pas des prélèvements sociaux, qui nécessitent 30 ans de détention). En LMNP, l\'amortissement du bien peut être épuisé, ce qui rend le passage à la location nue ou au micro-BIC potentiellement plus intéressant.',
        'La durée de détention impacte également l\'IFI : plus le patrimoine s\'accumule, plus le risque de franchir le seuil des 1,3 million d\'euros est élevé. Une revente stratégique peut permettre de réduire l\'assiette IFI tout en réalisant une plus-value partiellement exonérée.',
      ],
    },
    {
      id: 'exemple-rentabilite-nette',
      title: 'Exemple pédagogique : rentabilité nette selon le régime fiscal',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous compare la rentabilité nette d\'un même investissement locatif de 250 000 € (apport 75 000 €, emprunt 175 000 € sur 20 ans à 3,5 %) selon trois régimes fiscaux différents. Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement ni une performance passée.',
      ],
      table: {
        headers: ['Critère', 'Micro-foncier (location nue)', 'Régime réel LMNP', 'Régime réel (location nue avec travaux)'],
        rows: [
          ['Loyers bruts annuels', '12 000 €', '14 000 € (meublé, loyer plus élevé)', '12 000 €'],
          ['Abattement/Amortissement', '30 % (3 600 €)', 'Amortissement ~8 000 €/an', 'Charges réelles ~10 000 €/an'],
          ['Charges réelles déductibles', 'Non (abattement forfaitaire)', '6 000 € (intérêts, taxe, etc.)', '10 000 € (dont 4 000 € travaux)'],
          ['Revenu imposable', '8 400 €', '0 € (amortissement)', '2 000 €'],
          ['IR + PS annuel (TMI 30 %)', '~3 965 €', '0 €', '~944 €'],
          ['Revenu net après impôt', '~8 035 €', '~8 000 €', '~9 056 €'],
          ['Économie d\'impôt annuelle', 'Réf., comparaison', '~3 965 €', '~3 021 €'],
          ['Trésorerie cumulée sur 10 ans', '~80 350 €', '~80 000 €', '~90 560 €'],
          ['Plus-value à la revente (estimation à 300 000 €)', '50 000 € (brute)', '50 000 € + amortissements cumulés (majoration)', '50 000 € (brute)'],
          ['Avantage principal', 'Simplicité', 'Non-imposition des loyers', 'Optimisation via déficit foncier'],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes en matière de fiscalité immobilière',
      level: 'h2',
      type: 'list',
      content: [
        'De nombreuses erreurs sont commises par les investisseurs immobiliers en matière de fiscalité. Les connaître permet d\'optimiser sa stratégie et d\'éviter des redressements.',
      ],
      listItems: [
        'Ne pas anticiper l\'IFI : investir dans l\'immobilier locatif sans évaluer régulièrement son patrimoine immobilier net peut conduire à un franchissement non anticipé du seuil d\'imposition.',
        'Confondre micro-foncier et micro-BIC : l\'abattement n\'est pas le même (30 % pour le foncier, 50 % pour le BIC), et les plafonds diffèrent (15 000 € vs 77 700 €). Le choix du mauvais régime peut coûter cher.',
        'Oublier que les intérêts d\'emprunt ne génèrent pas de déficit foncier imputable sur le revenu global : seules les autres charges (travaux, taxe foncière) peuvent générer un déficit imputable dans la limite de 10 700 €.',
        'Investir en LMNP sans tenir compte de la majoration de la plus-value à la revente : l\'économie d\'impôt pendant la détention doit être mise en balance avec le surcoût fiscal potentiel à la revente.',
        'Sous-estimer l\'impact des prélèvements sociaux (17,2 %) sur les revenus fonciers et les plus-values : ils s\'ajoutent à l\'impôt sur le revenu et réduisent la rentabilité nette.',
        'Choisir un régime fiscal sans simulation personnalisée : chaque situation est unique (TMI, montant des loyers, charges, durée de détention, objectifs). Une simulation précise est indispensable.',
        'Négliger la fiscalité de la transmission : les droits de succession sur un patrimoine immobilier peuvent être élevés. L\'anticipation via une donation, une SCI ou une assurance-vie est essentielle.',
        'Confondre défiscalisation et optimisation : la défiscalisation vise à réduire l\'impôt, l\'optimisation vise à maximiser le patrimoine net après impôt. Ce sont deux objectifs différents qui nécessitent des stratégies distinctes.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance pour votre investissement locatif',
      level: 'h2',
      type: 'risk',
      content: [
        'Avant de finaliser un investissement locatif, plusieurs points de vigilance fiscaux méritent une attention particulière dans le cadre d\'une analyse patrimoniale rigoureuse.',
      ],
      listItems: [
        'La fiscalité immobilière évolue régulièrement : les taux d\'imposition, les abattements, les plafonds et les règles de calcul peuvent être modifiés par les lois de finances annuelles.',
        'Le choix du régime fiscal a un impact direct sur la rentabilité nette : une erreur de régime peut coûter plusieurs milliers d\'euros par an en impôt supplémentaire.',
        'Les avantages fiscaux ne doivent jamais primer sur la qualité de l\'investissement : un bien mal situé, mal construit ou mal géré ne sera pas rentable, quel que soit le régime fiscal choisi.',
        'La détention en direct ou en société (SCI) modifie profondément la fiscalité. Le choix de la structure doit être fait en amont, car les changements ultérieurs sont complexes et coûteux.',
        'L\'IFI s\'applique sur le patrimoine immobilier net, déduction faite des dettes. Une gestion fine des emprunts et de la trésorerie est nécessaire pour optimiser l\'assiette IFI.',
        'La location meublée (LMNP) nécessite une comptabilité professionnelle. Les frais d\'expert-comptable doivent être intégrés dans le calcul de rentabilité.',
        'En cas de detection en SCI, la responsabilité des associés est indéfinie et solidaire. Une assurance responsabilité civile professionnelle est recommandée.',
      ],
    },
    {
      id: 'methode-analyse-fiscalite',
      title: 'Méthode Eric Bellaiche pour analyser la fiscalité avant d\'investir',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour analyser la fiscalité d\'un investissement locatif avant d\'investir, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 étapes. Aucune recommandation n\'est formulée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation fiscale personnelle', description: 'TMI, prélèvements sociaux, IFI, revenus existants, nombre de parts fiscales : chaque élément détermine le régime le plus adapté.' },
        { title: 'Définition de l\'objectif patrimonial et de l\'horizon', description: 'Revenus complémentaires, constitution de capital, optimisation fiscale, transmission : l\'objectif oriente le choix du type de location et du cadre juridique.' },
        { title: 'Simulation de la rentabilité nette par régime', description: 'Calcul de la rentabilité nette après impôt pour chaque régime possible (micro-foncier, réel, LMNP micro-BIC, réel, SCI IR/IS), intégrant les charges, l\'amortissement et la fiscalité de sortie.' },
        { title: 'Évaluation de la cohérence patrimoniale globale', description: 'Vérification de la compatibilité de l\'investissement avec le patrimoine existant, l\'exposition à l\'IFI, les objectifs de diversification et la capacité d\'endettement.' },
        { title: 'Arbitrage et mise en place opérationnelle', description: 'Choix du régime fiscal, structuration juridique (direct, SCI), déclaration d\'adéquation le cas échéant, accompagnement pour les obligations déclaratives et comptables.' },
      ],
    },
  ],
  faq: [
    { question: 'Quels sont les principaux impôts applicables à un investissement locatif ?', answer: 'Les principaux impôts sont l\'impôt sur le revenu (sur les loyers), les prélèvements sociaux (17,2 %), la taxe foncière, et éventuellement l\'IFI (patrimoine immobilier > 1,3 M€) et l\'impôt sur les plus-values à la revente (19 % + 17,2 %).' },
    { question: 'Quelle est la différence entre micro-foncier et micro-BIC ?', answer: 'Le micro-foncier (abattement 30 %, plafond 15 000 €) concerne la location non meublée. Le micro-BIC (abattement 50 %, plafond 77 700 €) concerne la location meublée (LMNP). Les deux régimes sont exclusifs l\'un de l\'autre.' },
    { question: 'L\'IFI est-il dû sur les biens locatifs ?', answer: 'Oui, les biens immobiliers locatifs sont inclus dans l\'assiette de l\'IFI, déduction faite des dettes afférentes. Le seuil de déclenchement est de 1,3 million d\'euros de patrimoine immobilier net.' },
    { question: 'Qu\'est-ce que le déficit foncier et comment ça marche ?', answer: 'Le déficit foncier est la situation où les charges déductibles dépassent les loyers perçus. Ce déficit peut être imputé sur le revenu global dans la limite de 10 700 € par an, réduisant ainsi l\'impôt sur le revenu.' },
    { question: 'Faut-il payer des impôts sur la plus-value en cas de revente ?', answer: 'Oui, sauf si le bien est détenu depuis plus de 22 ans (exonération IR) ou 30 ans (exonération PS). Des abattements progressifs s\'appliquent à partir de la 6e année de détention.' },
    { question: 'Location meublée ou location nue : quel régime choisir ?', answer: 'La location meublée (LMNP) est généralement plus avantageuse fiscalement grâce à l\'amortissement, mais plus contraignante (comptabilité, gestion). La location nue est plus simple mais moins optimisée sur le plan fiscal.' },
    { question: 'Peut-on cumuler déficit foncier et LMNP ?', answer: 'Non, le déficit foncier ne concerne que la location nue au régime réel. Le LMNP relève des BIC, qui ont leurs propres règles de déficit (reportable sur les BIC des années suivantes).' },
    { question: 'Quel est l\'impact de la TMI sur le choix du régime fiscal ?', answer: 'Plus la TMI est élevée, plus l\'avantage fiscal des régimes optimisés (LMNP, déficit foncier) est important. Pour une TMI de 11 %, l\'écart entre les régimes est faible et la simplicité du micro-foncier ou du micro-BIC peut être privilégiée.' },
    { question: 'Les frais d\'expert-comptable sont-ils déductibles ?', answer: 'Oui, les frais d\'expert-comptable sont déductibles des revenus fonciers (régime réel) ou des BIC (LMNP réel), ce qui réduit leur coût net après économie d\'impôt.' },
    { question: 'Faut-il un conseiller en gestion de patrimoine pour investir dans l\'immobilier locatif ?', answer: 'Un CGP-CIF apporte une analyse globale de la situation fiscale et patrimoniale, simule les différents régimes, et recommande la solution la plus adaptée. Pour des investissements significatifs ou complexes, son accompagnement est précieux.' },
  ],
  ctaTitle: 'Vous souhaitez analyser la fiscalité de votre investissement locatif ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation fiscale et de déterminer la stratégie la plus adaptée à vos objectifs patrimoniaux.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/fiscalite-revenus-fonciers/', label: 'Fiscalité des revenus fonciers', position: 'inline' },
    { href: '/articles/deficit-foncier/', label: 'Déficit foncier : fonctionnement et fiscalité', position: 'inline' },
    { href: '/articles/lmnp-ou-location-nue/', label: 'LMNP ou location nue : comparatif', position: 'inline' },
    { href: '/articles/sci-ir-ou-sci-is/', label: 'SCI à l\'IR ou à l\'IS', position: 'inline' },
    { href: '/articles/investissement-locatif-retraite/', label: 'Investissement locatif pour la retraite', position: 'footer' },
  ],
  hasRisks: false,
};

export default article;
