import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'investissement-locatif-retraite',
  category: 'patrimoine',
  title: 'Investissement locatif pour préparer sa retraite : méthode et risques',
  metaTitle: 'Investissement locatif pour la retraite : méthode, fiscalité, LMNP, SCI, SCPI - CGP-CIF',
  metaDescription: 'Guide complet sur l\'investissement locatif pour préparer sa retraite : crédit immobilier, revenus locatifs, fiscalité LMNP/SCI/SCPI, offre de prêt, duration, rentabilité nette, risques. Analyse par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/investissement-locatif-retraite/',
  badge: 'Investissement locatif &bull; Retraite &bull; LMNP &bull; SCI &bull; SCPI &bull; CGP-CIF',
  intro: 'Préparer sa retraite ne se résume pas à cotiser à des régimes par répartition ou à capitaliser sur des supports financiers. L\'investissement locatif constitue une alternative patrimoniale puissante, capable de générer des revenus complémentaires réguliers, de constituer un capital transmissible et de bénéficier d\'une fiscalité optimisée. Mais il ne s\'improvise pas : choix du bien, mode de détention, financement, fiscalité, horizon, gestion locative et anticipation de la sortie sont autant de paramètres à maîtriser pour faire de l\'immobilier locatif un véritable levier de préparation à la retraite. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous propose une méthode structurée pour intégrer l\'immobilier locatif dans votre stratégie retraite.',
  shortAnswer: 'L\'investissement locatif pour la retraite repose sur un principe simple : acquérir un bien à crédit pendant la vie active pour le voir générer des revenus nets une fois le prêt remboursé. Le crédit constitue une épargne forcée, l\'amortissement du prêt améliore le cash-flow, et la fiscalité (notamment en LMNP ou via un déficit foncier) réduit l\'imposition pendant la phase de constitution. À la retraite, le bien peut être conservé pour générer des loyers, vendu pour dégager un capital, ou transmis. Les principales options sont la location nue, le LMNP, la SCI, la SCPI et le viager. Chaque option a ses avantages et ses risques : vacance locative, impayés, travaux, fiscalité, évolution des loyers et de la valeur du bien.',
  summaryItems: [
    { label: 'Pourquoi l\'immobilier locatif pour la retraite ?', anchor: 'pourquoi-immobilier-retraite' },
    { label: 'Les différentes stratégies immobilières pour la retraite', anchor: 'strategies-immobilieres-retraite' },
    { label: 'Financement et effet de levier du crédit', anchor: 'financement-levier-credit' },
    { label: 'Fiscalité selon le mode de détention', anchor: 'fiscalite-mode-detention' },
    { label: 'Tableau comparatif des stratégies', anchor: 'tableau-strategies' },
    { label: 'SCPI : alternative à la détention directe', anchor: 'scpi-alternative-directe' },
    { label: 'Exemple pédagogique : simulation sur 25 ans', anchor: 'exemple-25-ans' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour préparer sa retraite', anchor: 'methode-preparer-retraite' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 22,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['investissement locatif', 'retraite', 'immobilier', 'fiscalité', 'LMNP', 'SCI', 'CGP-CIF'],
  sections: [
    {
      id: 'pourquoi-immobilier-retraite',
      title: 'Pourquoi l\'immobilier locatif pour préparer sa retraite ?',
      level: 'h2',
      type: 'normal',
      content: [
        'L\'immobilier locatif présente plusieurs caractéristiques qui en font un outil de préparation à la retraite particulièrement adapté. Il permet de constituer un patrimoine tangible, générateur de revenus complémentaires, tout en bénéficiant d\'un effet de levier du crédit et d\'une fiscalité potentiellement optimisée.',
        'Le premier atout est l\'effet de levier du crédit. En empruntant pour acquérir un bien, vous constituez un patrimoine sans mobiliser la totalité du capital. Les loyers perçus remboursent tout ou partie des échéances, et à l\'issue du remboursement, le bien dégage des revenus nets supplémentaires. C\'est le principe de l\'épargne forcée : pendant 15 à 25 ans, vous remboursez un capital qui s\'accumule, et à la retraite, le bien devient une source de revenus.',
        'Le deuxième atout est la constitution d\'un capital transmissible. Contrairement à une pension de retraite par répartition qui s\'éteint au décès, un bien immobilier se transmet. Il peut être vendu pour dégager une plus-value, conservé pour générer des loyers, ou donné à ses héritiers avec une fiscalité potentiellement optimisée via une SCI ou une donation.',
        'Le troisième atout est la diversification patrimoniale. L\'immobilier locatif a une faible corrélation avec les marchés financiers. Il constitue une classe d\'actifs complémentaire à l\'assurance-vie, au PER, aux actions ou aux obligations, permettant de réduire la volatilité globale du patrimoine.',
        'Enfin, l\'immobilier locatif offre une certaine maîtrise sur son investissement : choix du bien, de l\'emplacement, du type de location, du niveau de loyer, de la gestion. Cette dimension concrète est appréciée des investisseurs qui souhaitent comprendre et contrôler leur patrimoine.',
      ],
    },
    {
      id: 'strategies-immobilieres-retraite',
      title: 'Les différentes stratégies immobilières pour la retraite',
      level: 'h2',
      type: 'normal',
      content: [
        'Plusieurs stratégies immobilières peuvent être mises en œuvre pour préparer sa retraite. Le choix dépend de l\'âge, de la capacité d\'épargne, de l\'horizon, de la tolérance au risque et des objectifs patrimoniaux.',
        'La location nue en direct est la stratégie la plus simple. L\'investisseur acquiert un bien, le loue nu, et perçoit des loyers imposés dans la catégorie des revenus fonciers. Pendant la phase de remboursement, les intérêts d\'emprunt sont déductibles. Après remboursement, le bien génère un revenu net (loyers - charges), imposé à la TMI. Cette stratégie est adaptée aux investisseurs qui recherchent la simplicité et qui n\'ont pas besoin d\'optimisation fiscale poussée.',
        'Le LMNP (Loueur en Meublé Non Professionnel) est la stratégie la plus populaire pour la retraite. L\'amortissement du bien permet de réduire à zéro l\'imposition des loyers pendant une grande partie de la détention. À la retraite, le bien peut être conservé, les amortissements étant épuisés, le bien génère alors des revenus imposables mais avec un effort fiscal limité. Le LMNP est particulièrement adapté aux investisseurs avec une TMI élevée en phase d\'activité.',
        'La SCI à l\'IR ou à l\'IS permet une gestion collective (plusieurs associés) et une optimisation de la transmission. La SCI à l\'IR est intéressante pour la donation progressive de parts aux enfants. La SCI à l\'IS permet l\'amortissement et la capitalisation dans la société, mais la fiscalité de sortie est plus lourde.',
        'La SCPI (Société Civile de Placement Immobilier) est une alternative à la détention directe. Elle permet d\'investir dans l\'immobilier locatif sans les contraintes de gestion, avec une mutualisation des risques locatifs et un accès à des biens de qualité (bureaux, commerces, santé). La SCPI peut être détenue en direct ou via un contrat d\'assurance-vie. Elle est particulièrement adaptée aux investisseurs qui ne souhaitent pas gérer un bien directement.',
        'Enfin, le viager peut être une stratégie complémentaire pour les investisseurs plus âgés, permettant d\'acquérir un bien à un prix réduit en échange d\'une rente viagère.',
      ],
    },
    {
      id: 'financement-levier-credit',
      title: 'Financement et effet de levier du crédit',
      level: 'h2',
      type: 'normal',
      content: [
        'L\'effet de levier du crédit est le mécanisme central de l\'investissement locatif pour la retraite. Il permet de multiplier la capacité d\'investissement et d\'accélérer la constitution du patrimoine.',
        'Le principe est le suivant : avec un apport de 100 000 €, un investisseur peut acquérir un bien de 300 000 € en empruntant 200 000 €. Si le bien prend ne serait-ce que 2 % par an, la plus-value de 6 000 € (2 % de 300 000 €) représente un rendement de 6 % sur l\'apport de 100 000 €, bien supérieur aux 2 % si le bien avait été acheté comptant.',
        'Pendant la phase de remboursement (15 à 25 ans), les loyers contribuent au remboursement des échéances. L\'idéal est que le bien soit autofinancé, c\'est-à-dire que les loyers couvrent au moins les échéances et les charges. En pratique, un autofinancement partiel (cash-flow légèrement négatif les premières années) est acceptable si l\'investisseur peut compenser la différence.',
        'Au fil du remboursement, la part des intérêts dans les échéances diminue et la part du capital remboursé augmente. Progressivement, le cash-flow s\'améliore. Une fois le prêt intégralement remboursé, le bien génère l\'intégralité des loyers nets des charges, ce qui constitue un complément de revenu pour la retraite.',
        'Plusieurs paramètres influencent l\'effet de levier : le taux d\'intérêt, la duration du prêt, le montant de l\'apport, le niveau des loyers et l\'évolution de la valeur du bien. Un taux d\'intérêt bas est favorable, mais même à 3-4 %, l\'effet de levier reste positif si la rentabilité locative est suffisante.',
        'Attention : l\'effet de levier amplifie les gains mais aussi les pertes. Si la valeur du bien baisse ou si les loyers diminuent, l\'investisseur peut se retrouver en situation de cash-flow négatif prolongé. Une marge de sécurité est indispensable.',
      ],
    },
    {
      id: 'fiscalite-mode-detention',
      title: 'Fiscalité selon le mode de détention',
      level: 'h2',
      type: 'normal',
      content: [
        'La fiscalité de l\'investissement locatif pour la retraite change selon le mode de détention et selon la phase : phase de constitution (avant la retraite) et phase de jouissance (pendant la retraite).',
        'En phase de constitution (vie active), l\'objectif est de maximiser l\'optimisation fiscale pour réduire le coût net de l\'investissement. Le LMNP au régime réel permet de déduire l\'amortissement, réduisant à zéro l\'imposition des loyers. Le déficit foncier (location nue au régime réel) permet d\'imputer jusqu\'à 10 700 € par an sur le revenu global. Les deux dispositifs sont particulièrement efficaces pour les TMI élevées.',
        'En phase de jouissance (retraite), l\'objectif est de maximiser le revenu net disponible. Si le LMNP a été utilisé pendant la phase de constitution, les amortissements peuvent être épuisés, et les loyers redeviennent imposables. Le passage au micro-BIC (abattement de 50 %) peut alors être plus intéressant que le maintien au régime réel. En location nue, le passage au micro-foncier (abattement de 30 %) peut également être envisagé si les charges sont faibles.',
        'La TMI est généralement plus faible à la retraite qu\'en activité, ce qui réduit l\'impact fiscal et rend la simplicité du micro-foncier ou du micro-BIC plus attractive. En revanche, l\'IFI peut devenir un enjeu si le patrimoine immobilier dépasse 1,3 million d\'euros.',
        'La SCPI détenue via un contrat d\'assurance-vie offre un cadre fiscal particulièrement avantageux à la retraite : les loyers sont capitalisés sans imposition immédiate, et les rachats après 8 ans bénéficient de l\'abattement annuel de 4 600 € (personne seule) ou 9 200 € (couple). C\'est une option intéressante pour les investisseurs qui souhaitent des revenus fiscalement optimisés à la retraite.',
      ],
    },
    {
      id: 'tableau-strategies',
      title: 'Tableau comparatif des stratégies immobilières pour la retraite',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous compare les principales stratégies immobilières pour préparer sa retraite, selon plusieurs critères clés.',
      ],
      table: {
        headers: ['Critère', 'Location nue', 'LMNP', 'SCI (IR ou IS)', 'SCPI en direct', 'SCPI via assurance-vie'],
        rows: [
          ['Complexité de gestion', 'Faible', 'Moyenne (comptabilité requise)', 'Élevée', 'Faible', 'Très faible'],
          ['Fiscalité en phase de constitution', 'Déficit foncier (10 700 €/an)', 'Amortissement (imposition réduite à zéro)', 'IR : transparence / IS : amortissement', 'Revenus fonciers (TMI + PS)', 'Capitalisation (pas d\'IR immédiat)'],
          ['Fiscalité en phase de retraite', 'Revenus fonciers (TMI)', 'BIC (TMI, souvent plus faible en retraite)', 'Dividendes ou loyers', 'Revenus fonciers', 'Abattement après 8 ans + PFU'],
          ['Effet de levier du crédit', 'Oui (intérêts déductibles)', 'Oui (intérêts déductibles)', 'Oui', 'Oui (intérêts déductibles)', 'Non (ou limité)'],
          ['Transmission', 'Droits de mutation', 'Droits de mutation + plus-values latentes', 'Favorable (donation de parts)', 'Droits de mutation', 'Très favorable (abattement successoral)'],
          ['Risque locatif', 'Porté par l\'investisseur', 'Porté par l\'investisseur', 'Porté par la société', 'Mutualisé', 'Mutualisé'],
          ['Liquidité', 'Faible', 'Faible', 'Très faible', 'Moyenne', 'Moyenne'],
          ['Horizon recommandé', '15-20 ans', '15-25 ans', '20-30 ans', '8-15 ans', '8-15 ans'],
        ],
      },
    },
    {
      id: 'scpi-alternative-directe',
      title: 'SCPI : une alternative à la détention directe',
      level: 'h2',
      type: 'normal',
      content: [
        'La SCPI (Société Civile de Placement Immobilier) constitue une alternative crédible à la détention directe pour préparer sa retraite, notamment pour les investisseurs qui ne souhaitent pas ou ne peuvent pas gérer un bien immobilier directement.',
        'Investir en SCPI permet d\'accéder à un parc immobilier diversifié (bureaux, commerces, santé, logistique, résidences gérées) avec une mutualisation des risques locatifs. La société de gestion se charge de la sélection des biens, de la gestion locative, des travaux et de la revente. L\'investisseur perçoit des loyers trimestriels, généralement stables et indexés.',
        'La SCPI peut être détenue en direct ou via un contrat d\'assurance-vie. En direct, les loyers sont imposés dans la catégorie des revenus fonciers, avec possibilité de déduire les intérêts d\'emprunt si l\'acquisition est financée à crédit. Via assurance-vie, les loyers sont capitalisés sans imposition immédiate, ce qui optimise la fiscalité pendant la phase de constitution.',
        'À la retraite, la SCPI en direct génère des revenus fonciers imposables, tandis que la SCPI via assurance-vie permet des rachats fiscalement optimisés après 8 ans. La SCPI est particulièrement adaptée aux investisseurs qui souhaitent un complément de revenu régulier sans contrainte de gestion.',
        'Les principaux inconvénients de la SCPI sont l\'absence de maîtrise sur le choix des biens, les frais de souscription (8 à 12 %), la liquidité variable selon la SCPI, et la dépendance à la qualité de la société de gestion. Le choix de la SCPI et de la société de gestion est donc crucial.',
      ],
    },
    {
      id: 'exemple-25-ans',
      title: 'Exemple pédagogique : simulation sur 25 ans',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous simule un investissement locatif en LMNP pour préparer la retraite, sur 25 ans. Le bien est acquis à 250 000 € avec un apport de 50 000 € et un emprunt de 200 000 € sur 20 ans à 3 %. Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement ni une performance passée.',
      ],
      table: {
        headers: ['Période', 'Âge approximatif', 'Loyers annuels', 'Charges + intérêts', 'Amortissement', 'Résultat imposable', 'IR + PS (TMI 30 %)', 'Cash-flow net', 'Capital restant dû'],
        rows: [
          ['Années 1-5', '40-45 ans', '13 000 €', '12 000 €', '~8 000 €', '-7 000 €', '0 €', '~1 000 €', '~160 000 €'],
          ['Années 6-10', '45-50 ans', '14 000 €', '11 000 €', '~8 000 €', '-5 000 €', '0 €', '~3 000 €', '~110 000 €'],
          ['Années 11-15', '50-55 ans', '15 000 €', '10 000 €', '~8 000 €', '-3 000 €', '0 €', '~5 000 €', '~55 000 €'],
          ['Années 16-20', '55-60 ans', '16 000 €', '9 000 €', '~8 000 €', '-1 000 €', '0 €', '~7 000 €', '0 € (remboursé)'],
          ['Années 21-25', '60-65 ans', '17 000 €', '5 000 €', '0 € (amorti)', '12 000 €', '~5 664 €', '~11 336 €', '0 €'],
          ['Cumul 25 ans', '', '~375 000 €', '~235 000 €', '~180 000 €', '', '~14 160 €', '~140 840 €', 'Bien + trésorerie'],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans l\'investissement locatif pour la retraite',
      level: 'h2',
      type: 'list',
      content: [
        'Plusieurs erreurs sont régulièrement commises par les investisseurs qui utilisent l\'immobilier locatif pour préparer leur retraite. Les connaître permet d\'éviter des déconvenues.',
      ],
      listItems: [
        'Sous-estimer la vacance locative et les impayés : un bien loué n\'est pas un bien toujours loué. Une période de vacance de 2 à 3 mois par an peut réduire significativement la rentabilité.',
        'Négliger les travaux et la vétusté : un bien locatif nécessite des travaux réguliers (ravalement, toiture, chauffage). Le coût des travaux sur 20 à 30 ans peut représenter 20 à 40 % de la valeur du bien.',
        'Investir trop tard : plus l\'investissement est réalisé tôt (dès 35-40 ans), plus l\'effet de levier du crédit et la capitalisation sont importants. Investir à 55 ans laisse peu de temps pour rembourser le prêt avant la retraite.',
        'Choisir un bien sans analyser le marché locatif local : un bien mal situé, dans une zone à faible demande locative, peut rester vacant plusieurs mois par an, affectant la rentabilité et le remboursement du prêt.',
        'Oublier l\'impact de la fiscalité à la retraite : une fois le prêt remboursé et les amortissements épuisés, les loyers deviennent imposables. La TMI de retraite est généralement plus faible, mais l\'impôt peut réduire le revenu disponible.',
        'Se focaliser uniquement sur la rentabilité brute sans considérer la rentabilité nette après impôt, charges et vacance : une rentabilité brute de 7 % peut devenir 3-4 % nette après tous prélèvements.',
        'Négliger la transmission : sans anticipation, la transmission d\'un bien locatif peut générer des droits de succession élevés. Une SCI, une donation ou une assurance-vie peuvent optimiser la transmission.',
        'Investir sans plan de sortie : que faire du bien à la retraite ? Le conserver, le vendre, le transmettre ? Chaque option a des implications fiscales et patrimoniales différentes.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance pour l\'investissement locatif retraite',
      level: 'h2',
      type: 'risk',
      content: [
        'L\'investissement locatif pour la retraite n\'est pas sans risques. Voici les points de vigilance essentiels à prendre en compte dans votre réflexion.',
      ],
      listItems: [
        'La rentabilité locative n\'est jamais garantie : elle dépend de l\'évolution du marché locatif local, de la conjoncture économique et de la qualité du bien. Une baisse des loyers ou une hausse de la vacance peut dégrader le cash-flow.',
        'L\'effet de levier du crédit amplifie les pertes en cas de baisse de la valeur du bien ou de hausse des taux. Un bien acheté avec un fort effet de levier peut se retrouver en situation de cash-flow négatif si les taux augmentent fortement lors du renégociation.',
        'La fiscalité immobilière évolue régulièrement : les régimes d\'imposition, les abattements, les plafonds et les taux peuvent être modifiés par les lois de finances. Une stratégie doit être régulièrement réévaluée.',
        'L\'IFI peut devenir un enjeu important si le patrimoine immobilier dépasse 1,3 million d\'euros. L\'investissement locatif contribue à l\'assiette IFI, ce qui peut réduire la rentabilité nette.',
        'La gestion locative est chronophage et peut peser lourd, surtout à un âge avancé. La délégation à un professionnel (agence immobilière) a un coût (6 à 10 % des loyers) mais peut être justifiée.',
        'La revente d\'un bien locatif peut prendre du temps et générer des frais (commissions d\'agence, fiscalité sur la plus-value). La liquidité n\'est pas garantie, sauf à vendre à un prix inférieur au marché.',
        'L\'investissement locatif ne doit pas être la seule composante de la préparation à la retraite. Il doit s\'intégrer dans une stratégie globale incluant d\'autres supports (PER, assurance-vie, épargne financière) pour diversifier les risques.',
      ],
    },
    {
      id: 'methode-preparer-retraite',
      title: 'Méthode Eric Bellaiche pour préparer sa retraite avec l\'immobilier locatif',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour construire une stratégie retraite intégrant l\'immobilier locatif, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 étapes. Aucune recommandation n\'est formulée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation personnelle et des objectifs', description: 'Âge, revenus, TMI, patrimoine existant, capacité d\'épargne, âge de départ à la retraite, revenu cible, exposition à l\'IFI : chaque élément détermine la stratégie adaptée.' },
        { title: 'Définition de l\'enveloppe et de la capacité d\'emprunt', description: 'Évaluation du budget disponible pour l\'investissement, simulation de la capacité d\'emprunt, détermination de l\'apport et du montant du prêt, calcul du cash-flow cible.' },
        { title: 'Choix du type de bien, du mode de détention et du régime fiscal', description: 'Analyse des options (location nue, LMNP, SCI, SCPI), sélection du régime fiscal (micro ou réel, IR ou IS), choix du bien ou de la SCPI en fonction du marché et de la rentabilité.' },
        { title: 'Simulation pluriannuelle et planification de la sortie', description: 'Calcul des flux nets année par année jusqu\'à la retraite, intégrant le remboursement du prêt, l\'amortissement, la fiscalité, la vacance et les travaux. Définition du scénario de sortie (conservation, vente, transmission).' },
        { title: 'Mise en œuvre, suivi et réévaluation périodique', description: 'Acquisition, mise en location, déclarations fiscales, suivi annuel de la rentabilité, réévaluation de la stratégie en fonction de l\'évolution de la situation personnelle, fiscale et du marché.' },
      ],
    },
  ],
  faq: [
    { question: 'Quel est le meilleur investissement locatif pour préparer sa retraite ?', answer: 'Il n\'y a pas de réponse universelle. Le LMNP est souvent plébiscité pour son optimisation fiscale via l\'amortissement. La SCPI est adaptée aux investisseurs qui ne souhaitent pas gérer directement. Le choix dépend de l\'âge, de la TMI, de l\'horizon et des objectifs.' },
    { question: 'À quel âge commencer un investissement locatif pour la retraite ?', answer: 'Idéalement entre 35 et 45 ans, pour avoir le temps de rembourser un prêt sur 15-20 ans avant la retraite. Plus tôt on commence, plus l\'effet de levier et la capitalisation sont importants.' },
    { question: 'Quel est le rôle du crédit dans l\'investissement locatif retraite ?', answer: 'Le crédit constitue une épargne forcée : les loyers remboursent les échéances, et le capital s\'accumule. À l\'issue du remboursement, le bien génère des revenus nets. L\'effet de levier amplifie la constitution de patrimoine.' },
    { question: 'Le LMNP est-il adapté à la préparation de la retraite ?', answer: 'Oui, le LMNP est particulièrement adapté : l\'amortissement réduit l\'imposition des loyers pendant la phase active. Une fois le prêt remboursé et les amortissements épuisés, le bien génère des revenus imposables mais avec un effort fiscal limité.' },
    { question: 'Quelle est la différence entre SCPI en direct et SCPI via assurance-vie pour la retraite ?', answer: 'En direct, les loyers sont imposés chaque année (revenus fonciers). Via assurance-vie, les loyers sont capitalisés sans imposition immédiate, et les rachats après 8 ans bénéficient d\'un abattement annuel. L\'assurance-vie offre également un cadre successoral avantageux.' },
    { question: 'Faut-il privilégier un bien avec un fort rendement ou une bonne localisation ?', answer: 'La localisation prime toujours. Un bien mal situé aura du mal à rester loué et à prendre de la valeur. Un rendement brut élevé dans une zone peu demandée est moins intéressant qu\'un rendement modéré dans une zone dynamique.' },
    { question: 'Quel est l\'impact des travaux sur la rentabilité locative ?', answer: 'Les travaux sont à prévoir régulièrement : entretien courant, remplacement du chauffage, ravalement, toiture. Ils peuvent représenter 20 à 40 % de la valeur du bien sur 20-30 ans. Il est essentiel de les anticiper dans le plan de financement.' },
    { question: 'Peut-on cumuler immobilier locatif et PER pour la retraite ?', answer: 'Oui, ces deux dispositifs sont complémentaires. Le PER offre un avantage fiscal immédiat et une sortie en capital ou en rente. L\'immobilier locatif constitue un patrimoine tangible générateur de revenus. Une stratégie globale peut combiner les deux.' },
    { question: 'Quels sont les principaux risques de l\'investissement locatif pour la retraite ?', answer: 'Les principaux risques sont : vacance locative, impayés, travaux imprévus, hausse des taux d\'intérêt, baisse de la valeur du bien, évolution défavorable de la fiscalité, et difficulté de revente au moment voulu.' },
    { question: 'Faut-il se faire accompagner par un CGP-CIF pour investir dans l\'immobilier locatif retraite ?', answer: 'Un CGP-CIF apporte une analyse globale de la situation, une simulation personnalisée, un éclairage sur les différentes options et un suivi dans la durée. Pour un investissement aussi structurant que la préparation de la retraite, son accompagnement est précieux.' },
  ],
  ctaTitle: 'Vous souhaitez préparer votre retraite avec l\'immobilier locatif ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation et de construire une stratégie patrimoniale adaptée à vos objectifs de retraite.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/lmnp-ou-location-nue/', label: 'LMNP ou location nue : comparatif', position: 'inline' },
    { href: '/articles/immobilier-locatif-fiscalite/', label: 'Immobilier locatif et fiscalité', position: 'inline' },
    { href: '/articles/preparer-retraite-patrimoine/', label: 'Préparer sa retraite avec son patrimoine', position: 'inline' },
    { href: '/articles/sci-ir-ou-sci-is/', label: 'SCI à l\'IR ou à l\'IS', position: 'inline' },
    { href: '/articles/scpi-retraite/', label: 'SCPI pour la retraite', position: 'footer' },
  ],
  hasRisks: false,
};

export default article;
