import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'lmnp-ou-location-nue',
  category: 'fiscalite',
  title: 'LMNP ou location nue : fiscalité, amortissement et stratégie patrimoniale',
  metaTitle: 'LMNP ou location nue : comparatif fiscalité, amortissement et stratégie CGP-CIF',
  metaDescription: 'Comparaison détaillée entre le statut LMNP et la location nue : amortissement, BIC vs revenus fonciers, micro-BIC, régime réel, TMI, fiscalité, récupération de la TVA. Analyse complète par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/lmnp-ou-location-nue/',
  badge: 'LMNP &bull; Location nue &bull; Fiscalité &bull; Amortissement &bull; CGP-CIF',
  intro: 'Louer un bien immobilier meublé ou nu ne relève pas du même cadre juridique, fiscal ou comptable. Le statut de Loueur en Meublé Non Professionnel (LMNP) et la location nue (relevant des revenus fonciers au sens de l\'article 14 du CGI) obéissent à des règles profondément différentes qui influencent directement la rentabilité nette, la capacité d\'optimisation et la stratégie patrimoniale globale. Le choix entre ces deux régimes constitue l\'une des décisions les plus structurantes pour un investisseur immobilier, car il détermine le traitement fiscal des revenus, la possibilité de déduire l\'amortissement, les modalités de déclaration et les perspectives de transmission. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous propose une analyse détaillée des deux options pour vous aider à déterminer celle qui correspond le mieux à votre situation patrimoniale.',
  shortAnswer: 'Le LMNP permet de déduire l\'amortissement du bien et du mobilier, ce qui peut réduire fortement, voire annuler, l\'imposition des loyers perçus pendant la durée de détention. Les revenus sont imposés dans la catégorie des BIC (bénéfices industriels et commerciaux), avec un choix possible entre le micro-BIC (abattement de 50 %) et le régime réel (amortissement déductible). La location nue relève des revenus fonciers, avec un abattement de 30 % au micro-foncier ou la déduction des charges et intérêts d\'emprunt au régime réel, mais sans possibilité d\'amortir le bien. Le LMNP est généralement plus avantageux pour les investisseurs souhaitant optimiser leur fiscalité locative à long terme, notamment pour les TMI élevées, tandis que la location nue conserve des avantages en matière de simplicité et de transmission.',
  summaryItems: [
    { label: 'LMNP : régime fiscal, conditions et fonctionnement', anchor: 'lmnp-regime-fiscal' },
    { label: 'Location nue : revenus fonciers et régime réel', anchor: 'location-nue-revenus-fonciers' },
    { label: 'Tableau comparatif complet LMNP vs location nue', anchor: 'tableau-comparatif-complet' },
    { label: 'L\'amortissement LMNP : levier fiscal clé', anchor: 'amortissement-lmnp-levier' },
    { label: 'Micro-BIC vs régime réel en LMNP', anchor: 'micro-bic-regime-reel' },
    { label: 'Fiscalité des plus-values à la revente', anchor: 'fiscalite-plus-values-revente' },
    { label: 'Exemple pédagogique : simulation sur 15 ans', anchor: 'exemple-pedagogique-simulation' },
    { label: 'Impact sur la transmission et la succession', anchor: 'impact-transmission-succession' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour choisir', anchor: 'methode-choix' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 22,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['LMNP', 'location nue', 'fiscalité', 'amortissement', 'BIC', 'immobilier', 'CGP-CIF'],
  sections: [
    {
      id: 'lmnp-regime-fiscal',
      title: 'LMNP : régime fiscal, conditions et fonctionnement détaillé',
      level: 'h2',
      type: 'normal',
      content: [
        'Le statut de Loueur en Meublé Non Professionnel (LMNP) permet de louer un bien immobilier meublé à titre non professionnel. Les revenus générés sont imposés dans la catégorie des BIC (bénéfices industriels et commerciaux), conformément à l\'article 35 du Code général des impôts.',
        'Pour bénéficier du statut LMNP, plusieurs conditions doivent être réunies. Le logement loué doit être meublé : le locataire doit disposer d\'un équipement suffisant pour vivre immédiatement (literie, électroménager, vaisselle, mobilier). La location peut être saisonnière ou à l\'année, mais le loueur ne doit pas être inscrit au Registre du Commerce et des Sociétés en tant que loueur professionnel (LMP) — les recettes annuelles doivent rester inférieures à 23 000 € ou représenter moins de 50 % des revenus globaux du foyer fiscal.',
        'Sur le plan comptable, le LMNP au régime réel impose la tenue d\'une comptabilité : bilan, compte de résultat, plan d\'amortissement du bien (hors terrain) et du mobilier. Cette contrainte est souvent perçue comme un inconvénient, mais elle constitue en réalité le principal avantage fiscal du dispositif grâce à la déduction de l\'amortissement.',
        'Le principal avantage du LMNP réside dans l\'amortissement : le bien immobilier (hors valeur du terrain) peut être amorti sur une durée de 25 à 30 ans environ, et le mobilier sur 5 à 10 ans. Cette dotation aux amortissements vient en déduction des loyers perçus, ce qui peut réduire à zéro le résultat imposable pendant de nombreuses années. Contrairement aux idées reçues, l\'amortissement n\'est pas une charge décaissée : c\'est une écriture comptable qui réduit le bénéfice imposable sans sortie de trésorerie.',
        'En contrepartie, la revente du bien peut entraîner une imposition sur la plus-value calculée à partir du prix d\'acquisition diminué des amortissements pratiqués, ce qui augmente la base imposable. Ce mécanisme est essentiel à comprendre pour arbitrer correctement entre LMNP et location nue.',
      ],
    },
    {
      id: 'location-nue-revenus-fonciers',
      title: 'Location nue : le régime des revenus fonciers',
      level: 'h2',
      type: 'normal',
      content: [
        'La location nue (logement loué non meublé) relève de la catégorie des revenus fonciers, définie par l\'article 14 du Code général des impôts. Les loyers perçus sont imposés au barème progressif de l\'impôt sur le revenu après application d\'un abattement ou déduction des charges.',
        'Deux régimes sont possibles. Le micro-foncier s\'applique automatiquement lorsque les revenus fonciers annuels n\'excèdent pas 15 000 €. Il offre un abattement forfaitaire de 30 % sur les loyers bruts, sans possibilité de déduire les charges réelles. Cet abattement est censé couvrir l\'ensemble des frais : travaux, intérêts d\'emprunt, taxe foncière, assurance, frais de gestion.',
        'Le régime réel est accessible sur option et devient obligatoire au-delà de 15 000 € de recettes annuelles. Il permet de déduire l\'intégralité des charges réelles : intérêts d\'emprunt, taxe foncière, charges de copropriété, frais de gestion, assurances, travaux d\'entretien et de réparation. Les travaux de reconstruction ou d\'agrandissement ne sont pas déductibles mais peuvent être intégrés au prix de revient du bien.',
        'Contrairement au LMNP, l\'amortissement du bien immobilier n\'est pas autorisé en location nue. C\'est la différence fondamentale entre les deux régimes : le propriétaire bailleur en location nue ne peut pas déduire la dépréciation théorique de son bien. En conséquence, le résultat imposable est généralement plus élevé en location nue qu\'en LMNP pour un même niveau de loyer, surtout dans les premières années où les intérêts d\'emprunt sont importants.',
        'La location nue conserve néanmoins des atouts : simplicité de gestion et de déclaration, pas de comptabilité obligatoire, pas de seuil de TVA à respecter, location à l\'année sans contrainte de meublement. Elle reste le régime de droit commun pour l\'immobilier locatif traditionnel.',
      ],
    },
    {
      id: 'tableau-comparatif-complet',
      title: 'Tableau comparatif complet LMNP vs location nue',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous synthétise l\'ensemble des critères différenciant le LMNP de la location nue. Ce comparatif permet d\'appréhender les implications pratiques et fiscales de chaque régime.',
      ],
      table: {
        headers: ['Critère', 'LMNP (meublé)', 'Location nue'],
        rows: [
          ['Catégorie fiscale', 'BIC (bénéfices industriels et commerciaux)', 'Revenus fonciers (article 14 CGI)'],
          ['Amortissement du bien', 'Oui (hors terrain, sur 25-30 ans)', 'Non'],
          ['Micro-régime', 'Micro-BIC : abattement 50 %', 'Micro-foncier : abattement 30 %'],
          ['Régime réel', 'Amortissement + charges réelles déductibles', 'Charges réelles déductibles, pas d\'amortissement'],
          ['Plafond micro-régime', '77 700 € de recettes annuelles', '15 000 € de recettes annuelles'],
          ['Comptabilité obligatoire', 'Oui au régime réel (bilan, compte de résultat)', 'Non (sauf option pour le réel)'],
          ['Déduction des intérêts d\'emprunt', 'Oui en régime réel', 'Oui en régime réel'],
          ['Taxe foncière déductible', 'Oui', 'Oui'],
          ['Travaux déductibles', 'Travaux d\'entretien et de réparation', 'Travaux d\'entretien et de réparation'],
          ['Plus-value à la revente', 'Calculée sur prix d\'acquisition - amortissements', 'Calculée sur prix d\'acquisition'],
          ['Récupération TVA', 'Possible sous conditions (meublé classé, LMNP)', 'Non'],
          ['Location saisonnière possible', 'Oui (meublé de tourisme)', 'Non (location nue à l\'année uniquement)'],
          ['Transmission', 'Plus-values latentes plus élevées (amortissements)', 'Plus-values latentes moins élevées'],
        ],
      },
    },
    {
      id: 'amortissement-lmnp-levier',
      title: 'L\'amortissement LMNP : le levier fiscal central',
      level: 'h2',
      type: 'normal',
      content: [
        'L\'amortissement constitue le principal avantage du statut LMNP par rapport à la location nue. Ce mécanisme comptable permet de déduire chaque année une fraction de la valeur du bien (hors terrain) et du mobilier de votre résultat imposable.',
        'Prenons un exemple concret. Un appartement acquis 300 000 €, dont 250 000 € de valeur du bâti (hors terrain estimé à 50 000 €) et 10 000 € de mobilier. L\'amortissement du bâti peut être calculé sur 30 ans, soit environ 8 333 € par an. Le mobilier est amorti sur 7 ans, soit environ 1 428 € par an. Soit un total de 9 761 € d\'amortissement annuel déductible des loyers.',
        'Si ce bien génère 15 000 € de loyers annuels et que les charges réelles déductibles (taxe foncière, assurance, frais de copropriété, intérêts d\'emprunt) s\'élèvent à 6 000 €, le résultat imposable sans amortissement serait de 9 000 €. Avec l\'amortissement de 9 761 €, le résultat devient déficitaire. Résultat : aucune imposition sur les revenus locatifs, et ce pendant environ 20 à 25 ans, jusqu\'à ce que le bien soit totalement amorti.',
        'Il est essentiel de comprendre que l\'amortissement n\'est pas une charge décaissée. L\'investisseur conserve la trésorerie correspondante dans son patrimoine. C\'est un différé d\'imposition et non une exonération définitive : à la revente, la plus-value imposable sera majorée du montant des amortissements pratiqués. Toutefois, cet effet est généralement compensé par la durée de détention et les abattements pour durée de détention applicables aux plus-values immobilières.',
        'Le choix du plan d\'amortissement est encadré : la durée d\'amortissement du bâti est libre mais doit être justifiée (généralement 25 à 40 ans selon la qualité de la construction). Le terrain n\'est jamais amortissable, car il est considéré comme non dépréciable.',
      ],
    },
    {
      id: 'micro-bic-regime-reel',
      title: 'Micro-BIC vs régime réel en LMNP',
      level: 'h2',
      type: 'normal',
      content: [
        'Le LMNP offre le choix entre deux régimes d\'imposition : le micro-BIC et le régime réel. Ce choix n\'est pas définitif et peut être révisé. Le micro-BIC s\'applique par défaut lorsque les recettes annuelles sont inférieures à 77 700 €. Il applique un abattement forfaitaire de 50 % sur les loyers bruts pour frais, sans possibilité de déduire l\'amortissement ni les charges réelles.',
        'Le micro-BIC présente un avantage de simplicité : aucune comptabilité n\'est requise, il suffit de déclarer le montant des recettes chaque année. L\'abattement de 50 % couvre forfaitairement toutes les charges, ce qui peut être avantageux pour les biens générant peu de charges réelles. En revanche, il ne permet pas de déduire l\'amortissement, ce qui écarte le principal avantage fiscal du LMNP.',
        'Le régime réel est généralement plus avantageux pour les biens amortissables significatifs. Il nécessite une comptabilité complète, tenue par un expert-comptable ou via un logiciel dédié. Les frais de comptabilité (500 à 1 500 € par an selon la complexité) sont déductibles. Le gain fiscal lié à l\'amortissement dépasse presque toujours le coût de la comptabilité, surtout pour les biens de valeur significative.',
        'Il est possible d\'opter pour le régime réel même si les recettes sont inférieures à 77 700 €. L\'option est irrévocable pendant deux ans. Passé ce délai, elle est reconductible tacitement. Un bilan comparatif annuel permet de vérifier que le régime réel reste le plus avantageux, notamment lorsque les amortissements commencent à s\'épuiser après 20 à 25 ans.',
      ],
    },
    {
      id: 'fiscalite-plus-values-revente',
      title: 'Fiscalité des plus-values à la revente en LMNP et location nue',
      level: 'h2',
      type: 'normal',
      content: [
        'La fiscalité applicable à la revente du bien diffère selon le régime sous lequel les loyers ont été imposés pendant la détention.',
        'En location nue, la plus-value est calculée classiquement : prix de cession diminué du prix d\'acquisition (et des travaux éventuellement capitalisés). La plus-value brute est ensuite réduite des abattements pour durée de détention : 6 % par an de la 6e à la 21e année, puis 4 % la 22e année, soit une exonération totale au bout de 22 ans pour l\'IR. Pour les prélèvements sociaux, l\'abattement est de 1,65 % par an de la 6e à la 21e année, puis 1,60 % de la 22e à la 30e année, avec exonération totale au bout de 30 ans.',
        'En LMNP, la plus-value imposable est calculée à partir du prix d\'acquisition diminué du montant cumulé des amortissements pratiqués pendant la détention. Concrètement, si vous avez amorti 150 000 € sur 15 ans, le prix d\'acquisition retenu pour le calcul de la plus-value est réduit de 150 000 €. La plus-value imposable est donc mécaniquement augmentée du même montant.',
        'Toutefois, ce mécanisme est moins pénalisant qu\'il n\'y paraît. Les abattements pour durée de détention s\'appliquent sur la plus-value ainsi majorée. En pratique, pour une détention longue (20 ans ou plus), l\'abattement pour durée de détention permet souvent d\'effacer tout ou partie de la majoration liée aux amortissements. Par ailleurs, la différence de trésorerie accumulée pendant la détention grâce à la non-imposition des loyers peut être placée et rapporter davantage que le surcoût fiscal à la revente.',
      ],
    },
    {
      id: 'exemple-pedagogique-simulation',
      title: 'Exemple pédagogique : simulation comparative sur 15 ans',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous compare un investissement immobilier de 300 000 € (apport 90 000 €, emprunt 210 000 € sur 15 ans à 3 %) entre le LMNP au régime réel et la location nue au régime réel. Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement ni une performance passée.',
      ],
      table: {
        headers: ['Critère', 'LMNP (régime réel)', 'Location nue (régime réel)'],
        rows: [
          ['Prix d\'acquisition', '300 000 €', '300 000 €'],
          ['Loyers bruts annuels', '15 000 €', '13 500 € (location nue, loyer généralement plus faible)'],
          ['Charges réelles annuelles (hors amortissement)', '6 000 €', '6 000 €'],
          ['Amortissement annuel moyen', '9 500 €', 'Non applicable'],
          ['Résultat imposable annuel', '0 € (déficit après amortissement)', '7 500 €'],
          ['IR + PS économisés par an (TMI 30 %)', '~3 540 €', '0 €'],
          ['Économie d\'impôt cumulée sur 15 ans', '~53 100 €', '0 €'],
          ['Trésorerie nette cumulée sur 15 ans (après IR)', '~135 000 €', '~112 500 €'],
          ['Plus-value à la revente (estimation à 350 000 €)', 'Majorée des amortissements (~142 500 €)', 'Calculée sur 350 000 €'],
          ['Fiscalité estimée à la revente (après 15 ans)', 'Abattement 54 % IR + PS', 'Abattement 54 % IR + PS'],
        ],
      },
    },
    {
      id: 'impact-transmission-succession',
      title: 'Impact sur la transmission et la succession',
      level: 'h2',
      type: 'normal',
      content: [
        'Le choix entre LMNP et location nue a également des implications en matière de transmission patrimoniale. Ces implications sont souvent sous-estimées dans les comparatifs.',
        'En LMNP, les amortissements pratiqués réduisent la valeur comptable du bien sans réduire sa valeur vénale réelle. En cas de transmission, la différence entre valeur vénale et valeur comptable constitue une plus-value latente qui sera imposable chez les héritiers en cas de revente ultérieure. Cette plus-value latente peut être substantielle après 15 à 20 ans de détention.',
        'En location nue, la base imposable en cas de revente est calculée à partir du prix d\'acquisition réel, sans minoration par les amortissements. La plus-value latente est donc généralement moins élevée qu\'en LMNP pour une même durée de détention.',
        'Plusieurs stratégies permettent d\'optimiser la transmission d\'un bien loué en LMNP : la cession du bien et le remploi dans un contrat d\'assurance-vie, la donation des parts de SCI si le bien est détenu via une société, ou l\'anticipation via un démembrement de propriété. Chaque stratégie doit être étudiée en fonction de la situation familiale et patrimoniale.',
        'Dans les deux cas, la détention via une SCI permet de faciliter la transmission des parts sociales plutôt que du bien lui-même, avec des droits de donation potentiellement réduits grâce aux abattements en vigueur.',
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans le choix entre LMNP et location nue',
      level: 'h2',
      type: 'list',
      content: [
        'Plusieurs erreurs reviennent régulièrement chez les investisseurs qui comparent le LMNP et la location nue. Les éviter permet de prendre une décision éclairée.',
      ],
      listItems: [
        'Croire que le LMNP est toujours plus avantageux : l\'amortissement est un différé d\'imposition, pas une exonération. Pour les petits budgets ou les biens peu amortissables, la location nue peut être plus simple et tout aussi efficace.',
        'Négliger le coût de la comptabilité en LMNP : frais d\'expert-comptable, temps passé à collecter les pièces justificatives, risque d\'erreur en cas d\'autodéclaration. Ces coûts doivent être intégrés dans le calcul de rentabilité.',
        'Oublier la majoration de la plus-value à la revente en LMNP : les amortissements pratiqués réduisent le prix d\'acquisition fiscal. L\'économie d\'IR pendant la détention doit être mise en balance avec le surcoût fiscal potentiel à la revente.',
        'Choisir le micro-BIC sans comparer avec le régime réel : pour un bien amortissable de valeur significative, le régime réel est presque toujours plus avantageux malgré la contrainte comptable.',
        'Confondre LMNP et LMP (Loueur en Meublé Professionnel) : les seuils et les implications fiscales (plus-values professionnelles, prélèvements sociaux) sont différents. La frontière est de 23 000 € de recettes ou 50 % des revenus du foyer.',
        'Investir en LMNP sans anticiper l\'impact sur l\'IFI : le bien est inclus dans l\'assiette de l\'IFI comme tout bien immobilier, qu\'il soit loué meublé ou nu.',
        'Sous-estimer la contrainte de la location meublée : turn-over plus élevé, gestion locative plus lourde, nécessité de maintenir le mobilier en bon état.',
        'Ne pas intégrer la fiscalité des plus-values dans l\'arbitrage : l\'avantage fiscal du LMNP en phase de détention peut être en partie rattrapé par la fiscalité à la revente si le bien est cédé avant que les abattements pour durée de détention ne jouent pleinement.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance pour votre arbitrage',
      level: 'h2',
      type: 'risk',
      content: [
        'Avant d\'arrêter votre choix entre LMNP et location nue, plusieurs points méritent une attention particulière dans le cadre d\'une analyse patrimoniale rigoureuse.',
      ],
      listItems: [
        'Le régime réel du LMNP nécessite une comptabilité professionnelle : les frais d\'expert-comptable (800 à 1 500 € par an) sont déductibles mais doivent être anticipés dans le plan de financement.',
        'La durée d\'amortissement doit être cohérente avec la nature du bien : une durée trop courte expose à un redressement fiscal, une durée trop longue réduit l\'avantage fiscal. L\'accompagnement d\'un expert-comptable spécialisé est recommandé.',
        'La revente avant la fin de l\'amortissement peut générer une plus-value imposable significative si le bien a pris de la valeur. Une simulation de sortie à 5, 10 et 15 ans est utile avant d\'investir.',
        'Le choix du régime fiscal doit être réévalué périodiquement : les amortissements s\'épuisent avec le temps, et le passage en location nue ou en micro-BIC peut devenir plus intéressant après 20 ans.',
        'Les règles applicables aux meublés de tourisme (Airbnb, location saisonnière) diffèrent de celles de la location meublée classique : seuils, obligations déclaratives, réglementation locale. Une analyse spécifique est nécessaire.',
        'En cas de détention en SCI, le choix entre LMNP et location nue interagit avec le régime fiscal de la société (IR ou IS). Ceci nécessite une analyse globale de la structuration patrimoniale.',
        'L\'administration fiscale peut remettre en cause le caractère non professionnel du LMNP si l\'activité locative meublée devient l\'activité principale ou génère des recettes très importantes. Le suivi des seuils est indispensable.',
      ],
    },
    {
      id: 'methode-choix',
      title: 'Méthode Eric Bellaiche pour choisir entre LMNP et location nue',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour arbitrer entre LMNP et location nue, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 étapes permettant d\'aboutir à une recommandation adaptée à chaque situation patrimoniale. Aucune recommandation n\'est formulée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation fiscale globale', description: 'TMI, prélèvements sociaux, IFI, revenus existants : chaque élément influence l\'avantage relatif du LMNP (amortissement) ou de la location nue (simplicité).' },
        { title: 'Définition des objectifs patrimoniaux', description: 'Recherche de revenus complémentaires, optimisation fiscale, transmission, revente à horizon donné : les objectifs orientent le choix du régime.' },
        { title: 'Évaluation de la capacité de gestion', description: 'Le LMNP exige une comptabilité et une gestion locative plus lourde. La capacité à assumer ces contraintes entre dans la décision.' },
        { title: 'Simulation comparative sur la durée de détention prévue', description: 'Calcul des flux nets de trésorerie année par année en LMNP (réel) et en location nue, intégrant l\'amortissement, les frais de comptabilité, la fiscalité d\'acquisition et de sortie.' },
        { title: 'Arbitrage et formalisation', description: 'Choix du régime le plus adapté, déclaration d\'adéquation le cas échéant, mise en place du plan d\'amortissement et des obligations déclaratives avec l\'expert-comptable.' },
      ],
    },
  ],
  faq: [
    { question: 'Quelle est la différence principale entre LMNP et location nue ?', answer: 'La différence principale réside dans la possibilité d\'amortir le bien en LMNP, ce qui peut réduire ou annuler l\'imposition des loyers. En location nue, les revenus sont imposés sans amortissement, ce qui génère un résultat imposable plus élevé pour un même niveau de loyer.' },
    { question: 'Le LMNP est-il toujours plus avantageux que la location nue ?', answer: 'Non. Le LMNP est généralement plus avantageux pour les investisseurs avec une TMI élevée (30 % ou plus) et un bien amortissable significatif. Pour les TMI faibles, les petits budgets ou les biens peu amortissables, la location nue peut être plus adaptée du fait de sa simplicité.' },
    { question: 'Quel abattement pour le micro-BIC en LMNP ?', answer: 'Le micro-BIC applique un abattement forfaitaire de 50 % sur les loyers bruts, avec un plafond de recettes de 77 700 € par an. Cet abattement couvre forfaitairement l\'ensemble des frais, mais ne permet pas de déduire l\'amortissement.' },
    { question: 'Quel abattement pour le micro-foncier en location nue ?', answer: 'Le micro-foncier applique un abattement forfaitaire de 30 % sur les loyers bruts, avec un plafond de 15 000 € de recettes annuelles. Au-delà, le régime réel est obligatoire.' },
    { question: 'L\'amortissement LMNP est-il récupéré à la revente ?', answer: 'Oui, les amortissements pratiqués viennent réduire le prix d\'acquisition fiscal pour le calcul de la plus-value. Cela augmente la plus-value imposable à la revente, mais les abattements pour durée de détention atténuent cet effet pour les détentions longues.' },
    { question: 'Peut-on passer du LMNP à la location nue ou inversement ?', answer: 'Oui, il est possible de changer de régime en fonction de l\'évolution de la situation. Le passage du LMNP à la location nue nécessite de démeubler le logement. Le passage inverse nécessite de le meubler. Les implications fiscales doivent être étudiées au préalable.' },
    { question: 'Faut-il un expert-comptable pour le LMNP au régime réel ?', answer: 'La loi n\'impose pas le recours à un expert-comptable, mais la tenue d\'une comptabilité complète (bilan, compte de résultat, plan d\'amortissement) est obligatoire. En pratique, l\'accompagnement d\'un professionnel est fortement recommandé pour éviter les erreurs.' },
    { question: 'La location meublée est-elle plus contraignante que la location nue ?', answer: 'Oui, la location meublée génère généralement plus de turn-over locatif, nécessite un entretien régulier du mobilier et une gestion administrative plus lourde. En contrepartie, les loyers sont souvent plus élevés et la fiscalité plus avantageuse.' },
    { question: 'Quel est l\'impact du LMNP sur l\'IFI ?', answer: 'Le bien est inclus dans l\'assiette de l\'IFI comme tout bien immobilier, quel que soit le régime locatif (meublé ou nu). La valeur retenue est la valeur vénale du bien, sans déduction des amortissements comptabilisés.' },
    { question: 'Peut-on investir en LMNP via une SCI ?', answer: 'Oui, il est possible de détenir un bien loué meublé via une SCI. Le choix du régime fiscal de la SCI (IR ou IS) et les interactions avec le statut LMNP nécessitent une analyse approfondie. La fiscalité des BIC s\'applique au niveau de la société si elle est à l\'IS, ou au niveau des associés si elle est à l\'IR.' },
  ],
  ctaTitle: 'Vous hésitez entre LMNP et location nue ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation fiscale et patrimoniale pour déterminer le régime locatif le plus adapté à vos objectifs.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/immobilier-locatif-fiscalite/', label: 'Immobilier locatif et fiscalité', position: 'inline' },
    { href: '/articles/fiscalite-revenus-fonciers/', label: 'Fiscalité des revenus fonciers', position: 'inline' },
    { href: '/articles/investissement-locatif-retraite/', label: 'Investissement locatif pour la retraite', position: 'inline' },
    { href: '/articles/deficit-foncier/', label: 'Déficit foncier : fonctionnement et fiscalité', position: 'footer' },
  ],
  hasRisks: false,
};

export default article;
