import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'per-fiscalite',
  category: 'retraite',
  title: 'Fiscalité du PER : déduction, sortie en capital, rente et points de vigilance',
  metaTitle: 'Fiscalité du PER : déduction, sortie en capital, rente et points de vigilance',
  metaDescription: 'La fiscalité du PER repose sur la déduction à l\'entrée et l\'imposition à la sortie. Sortie en capital, sortie en rente, TMI, plafond : analyse détaillée par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/per-fiscalite/',
  badge: 'PER &bull; Fiscalité &bull; CGP-CIF',
  intro: 'Le Plan d\'Épargne Retraite (PER) est souvent présenté comme l\'un des derniers dispositifs de défiscalisation accessibles aux épargnants français. Pourtant, sa fiscalité est plus nuancée qu\'il n\'y paraît : la déduction à l\'entrée n\'est avantageuse que si la TMI au moment du versement est supérieure à celle qui s\'appliquera au moment de la sortie. L\'arbitrage entre sortie en capital et sortie en rente modifie également l\'imposition applicable, tout comme l\'option pour le prélèvement forfaitaire unique (PFU) ou le barème progressif. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous présente les mécanismes fiscaux du PER, les points de vigilance à connaître et la méthode pour évaluer l\'intérêt réel de ce produit dans une stratégie patrimoniale globale.',
  shortAnswer: 'La fiscalité du PER repose sur un principe de déduction à l\'entrée et d\'imposition à la sortie. Les versements volontaires sont déductibles du revenu imposable dans la limite d\'un plafond annuel (10 % des revenus professionnels, plafonné, montant indiqué sur l\'avis d\'imposition). À la sortie, le capital est imposé selon les options choisies : en sortie en capital, la part correspondant aux versements déduits est imposée dans la catégorie des pensions (TMI + PS 17,2 %), tandis que la part de plus-values est soumise au PFU (12,8 % + PS) ou au barème progressif sur option. En sortie en rente, la rente est imposée comme une pension (TMI + PS après abattement de 10 %). L\'avantage fiscal effectif dépend de l\'écart entre la TMI au moment du versement et la TMI au moment de la sortie. Il est également possible de ne pas déduire les versements, ce qui permet une sortie en capital exonérée d\'impôt sur les versements (seules les plus-values sont taxées). Le plafond de déduction est individuel et figure sur l\'avis d\'imposition.',
  summaryItems: [
    { label: 'Principe général : déduction à l\'entrée, imposition à la sortie', anchor: 'principe-general' },
    { label: 'Plafond de déduction et calcul', anchor: 'plafond-deduction' },
    { label: 'Sortie en capital : fiscalité des versements et des plus-values', anchor: 'sortie-capital' },
    { label: 'Sortie en rente : imposition de la rente viagère', anchor: 'sortie-rente' },
    { label: 'PFU ou barème progressif : comment choisir à la sortie', anchor: 'pfu-barème' },
    { label: 'Tableau comparatif : déduction vs non-déduction', anchor: 'tableau-deduction' },
    { label: 'Exemple pédagogique : TMI 30 % aujourd\'hui, TMI 11 % à la retraite', anchor: 'exemple-pedagogique' },
    { label: 'Erreurs fréquentes avec la fiscalité du PER', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance sur le PER', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour évaluer l\'intérêt fiscal du PER', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 22,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['PER', 'fiscalité', 'déduction', 'retraite', 'TMI', 'capital', 'rente', 'CGP-CIF'],
  sections: [
    {
      id: 'principe-general',
      title: "Principe général du PER : déduction à l'entrée, imposition à la sortie",
      level: 'h2',
      type: 'normal',
      content: [
        "Le Plan d'Épargne Retraite (PER) individuel, créé par la loi Pacte en 2019, repose sur un principe fiscal simple en apparence : les versements volontaires sont déductibles du revenu imposable l'année du versement, et les sommes perçues à la sortie (capital ou rente) sont imposées.",
        "Ce mécanisme de report d'imposition est conçu pour inciter les épargnants à constituer une épargne retraite. L'idée sous-jacente est que la TMI (tranche marginale d'imposition) est généralement plus élevée pendant la vie active qu'à la retraite, ce qui rend le différé d'imposition fiscalement avantageux.",
        "En pratique, l'économie d'impôt réalisée à l'entrée dépend de la TMI au moment du versement. Un contribuable à 41 % de TMI qui verse 10 000 € sur son PER économise 4 100 € d'impôt sur le revenu immédiatement (hors prélèvements sociaux). À la sortie, les sommes retirées seront imposées, mais potentiellement à un taux plus faible si la TMI a baissé.",
        "Toutefois, ce principe général comporte des exceptions et des options importantes : la possibilité de ne pas déduire les versements, le choix entre sortie en capital et sortie en rente, l'option entre le PFU (prélèvement forfaitaire unique) et le barème progressif, et les différents régimes applicables selon la nature des sommes (versements, plus-values, abondement employeur).",
        "Un autre point fondamental est que le plafond de déduction est individuel et non transférable. Il est calculé chaque année en fonction des revenus professionnels et figure sur l'avis d'imposition. Contrairement à une idée reçue, il n'existe pas de plafond unique applicable à tous les contribuables.",
        "Enfin, il est essentiel de comprendre que l'avantage fiscal du PER n'est pas un cadeau fiscal pur : c'est un différé d'imposition qui peut être avantageux ou non selon l'évolution de la situation fiscale personnelle. Une analyse rigoureuse est nécessaire avant d'utiliser ce produit dans une stratégie patrimoniale.",
      ],
    },
    {
      id: 'plafond-deduction',
      title: 'Plafond de déduction des versements : calcul et règles',
      level: 'h2',
      type: 'normal',
      content: [
        "Le plafond de déduction des versements volontaires sur un PER est calculé selon des règles précises qui varient selon la situation professionnelle et la composition du foyer fiscal.",
        "Pour les salariés, le plafond est égal au plus élevé des deux montants suivants : 10 % des revenus professionnels nets de l'année précédente, plafonnés à un montant annuel variable (fixé par l'administration fiscale, par exemple 35 194 € pour 2025 sur la base des revenus 2024), ou 10 % du PASS (plafond annuel de la sécurité sociale), soit environ 4 399 €.",
        "Pour les travailleurs non-salariés (TNS), le plafond est calculé sur la base de 10 % des bénéfices imposables dans la limite du PASS, plus 15 % des bénéfices compris entre 1 et 8 PASS. Ce calcul permet aux TNS de bénéficier d'un plafond de déduction plus élevé que les salariés, en contrepartie d'une protection sociale moindre.",
        "Le plafond est individuel mais peut être mutualisé au sein du foyer fiscal. Les époux ou partenaires de Pacs peuvent se transférer les plafonds non utilisés, ce qui permet d'optimiser la déduction au niveau du foyer. Par exemple, si l'un des conjoints n'utilise pas la totalité de son plafond, l'excédent peut être utilisé par l'autre conjoint.",
        "Les plafonds non utilisés d'une année peuvent être reportés sur les trois années suivantes, ce qui offre une certaine souplesse pour les contribuables souhaitant effectuer des versements plus importants certaines années (par exemple, en cas de revenus exceptionnels ou de cession d'entreprise).",
        "Il est important de noter que l'abondement de l'employeur sur un PER d'entreprise (obligatoire ou collectif) n'est pas déductible par le salarié puisqu'il n'a pas été inclus dans son revenu imposable. De même, les versements obligatoires (PER d'entreprise obligatoire) sont déjà déduits du revenu imposable via le bulletin de paie.",
        "En pratique, le montant exact du plafond disponible figure sur l'avis d'imposition. Il est conseillé de vérifier ce montant avant d'effectuer un versement, car tout dépassement du plafond entraîne la réintégration des sommes excédentaires dans le revenu imposable, sans possibilité de déduction ultérieure.",
      ],
    },
    {
      id: 'sortie-capital',
      title: "Sortie en capital : fiscalité des versements et des plus-values",
      level: 'h2',
      type: 'normal',
      content: [
        "La sortie en capital du PER est possible lors du départ à la retraite ou dans les cas de déblocage anticipé (achat de la résidence principale, invalidité, décès, surendettement, cessation d'activité). La fiscalité applicable dépend de la nature des sommes retirées : versements déduits, versements non déduits, plus-values.",
        "Sur le plan fiscal, le capital est composé de trois catégories distinctes qui font l'objet de traitements fiscaux différents :",
        "- La part correspondant aux versements volontaires qui ont été déduits du revenu imposable : elle est imposée dans la catégorie des pensions (barème progressif de l'IR + prélèvements sociaux de 17,2 %) ;",
        "- La part correspondant aux versements volontaires qui n'ont PAS été déduits du revenu imposable : elle est exonérée d'impôt sur le revenu à la sortie (seuls les prélèvements sociaux peuvent s'appliquer sur les produits) ;",
        "- La part correspondant aux plus-values et intérêts générés par le contrat : elle est soumise au prélèvement forfaitaire unique (PFU) de 12,8 % + prélèvements sociaux de 17,2 %, soit un total de 30 %, ou sur option au barème progressif.",
        "Le choix de déduire ou non les versements est donc stratégique. Un contribuable qui anticipe une TMI plus élevée à la retraite qu'aujourd'hui (cas rare mais possible, par exemple en cas de revenus fonciers importants à la retraite) pourrait avoir intérêt à ne pas déduire ses versements pour bénéficier d'une sortie en capital exonérée d'IR sur les versements.",
        "En cas de sortie en capital échelonnée (plusieurs retraits), chaque retrait est imposé selon les mêmes règles, avec une répartition proportionnelle entre les trois catégories de sommes. Il est possible d'opter pour un retrait en capital unique ou fractionné selon les besoins.",
      ],
    },
    {
      id: 'sortie-rente',
      title: 'Sortie en rente : imposition de la rente viagère',
      level: 'h2',
      type: 'normal',
      content: [
        "La sortie en rente viagère est l'autre option offerte au titulaire d'un PER lors du départ à la retraite. La rente est calculée en fonction du capital accumulé, de l'espérance de vie (selon un taux de conversion déterminé par le contrat) et d'un éventuel réversion au profit du conjoint.",
        "Sur le plan fiscal, la rente viagère est imposée selon les mêmes règles qu'une pension de retraite : elle est soumise au barème progressif de l'impôt sur le revenu dans la catégorie des pensions, après application d'un abattement forfaitaire de 10 % (plafonné). Les prélèvements sociaux de 17,2 % s'appliquent également sur le montant de la rente avant abattement.",
        "Le taux d'imposition effectif de la rente dépend donc de l'ensemble des revenus du foyer fiscal à la retraite (pensions de retraite, rente du PER, revenus fonciers, revenus financiers). L'abattement de 10 % s'applique sur l'ensemble des pensions et rentes, ce qui réduit légèrement la base imposable.",
        "Un point important est que la rente du PER est composée d'une part de capital et d'une part d'intérêts. Contrairement à la sortie en capital où les plus-values sont identifiables et taxées distinctement, la rente est imposée globalement comme une pension, sans distinction entre le capital et les produits.",
        "L'avantage de la rente est de sécuriser un revenu viager, mais son inconvénient est fiscal : la totalité de la rente est imposée (y compris la part de capital), contrairement à la sortie en capital où seule la part correspondant aux versements déduits et aux plus-values est imposée.",
        "Le choix entre sortie en capital et sortie en rente dépend de plusieurs facteurs : le besoin de revenus réguliers, l'espérance de vie, la situation familiale (conjoint à protéger via la réversion), et l'optimisation fiscale globale. Une sortie en capital partielle suivie d'une mise en rente du solde est également possible selon les contrats.",
      ],
    },
    {
      id: 'pfu-barème',
      title: 'PFU ou barème progressif : comment choisir à la sortie',
      level: 'h2',
      type: 'normal',
      content: [
        "Lors de la sortie en capital du PER, les plus-values et les intérêts sont soumis de plein droit au prélèvement forfaitaire unique (PFU), dit \"flat tax\", au taux de 12,8 % (auxquels s'ajoutent les prélèvements sociaux de 17,2 %, soit un total de 30 %).",
        "Toutefois, le contribuable peut opter pour le barème progressif de l'impôt sur le revenu si cette option lui est plus favorable. L'option est globale : elle s'applique à l'ensemble des revenus de capitaux mobiliers et des plus-values de cession de valeurs mobilières pour l'année concernée.",
        "L'option pour le barème progressif est intéressante lorsque la TMI est basse (0 % ou 11 %), car le taux d'imposition effectif sur les plus-values peut être inférieur au PFU de 12,8 %. En revanche, pour une TMI de 30 % ou plus, le PFU est généralement plus avantageux.",
        "Il est important de noter que l'option pour le barème progressif ne modifie pas le traitement fiscal de la part de capital correspondant aux versements déduits, qui reste imposée dans la catégorie des pensions (TMI + PS). Seule la fiscalité des plus-values est concernée par cette option.",
        "En pratique, la décision d'opter ou non pour le barème progressif doit être prise en fonction de la situation fiscale globale de l'année de sortie. Il est recommandé de simuler l'impôt dû dans les deux scénarios avant d'effectuer le retrait.",
      ],
    },
    {
      id: 'tableau-deduction',
      title: 'Tableau comparatif : déduction vs non-déduction des versements',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous compare les deux options possibles concernant la déduction des versements sur un PER, selon la TMI à l\'entrée et la TMI estimée à la sortie.',
      ],
      table: {
        headers: ['Scénario', 'Avantage fiscal à l\'entrée', 'Imposition à la sortie (capital)', 'Intérêt fiscal global'],
        rows: [
          ['Déduction + TMI élevée à l\'entrée (41 %), TMI faible à la sortie (11 %)', 'Économie d\'impôt de 41 % sur le versement', 'Imposition à 11 % (TMI) + 17,2 % (PS) sur les versements déduits', 'Très favorable : gain net d\'environ 30 points d\'écart'],
          ['Déduction + TMI identique à l\'entrée et à la sortie (30 %)', 'Économie d\'impôt de 30 % sur le versement', 'Imposition à 30 % (TMI) + 17,2 % (PS) sur les versements déduits', 'Neutre (hors effet de trésorerie et PS)'],
          ['Déduction + TMI plus faible à l\'entrée (11 %) qu\'à la sortie (30 %)', 'Économie d\'impôt de 11 % sur le versement', 'Imposition à 30 % (TMI) + 17,2 % (PS) sur les versements déduits', 'Défavorable : perte nette d\'environ 19 points'],
          ['Non-déduction', 'Pas d\'économie d\'impôt immédiate', 'Exonération d\'IR sur les versements, PFU sur les plus-values', 'Intéressant si TMI future estimée élevée'],
        ],
      },
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : TMI 30 % aujourd\'hui, TMI 11 % à la retraite',
      level: 'h2',
      type: 'normal',
      content: [
        'Prenons l\'exemple d\'un contribuable âgé de 45 ans, TMI actuelle de 30 %, qui verse 10 000 € par an sur son PER pendant 15 ans, soit un total de 150 000 € de versements.',
        'À l\'entrée, il économise 30 % d\'impôt sur chaque versement, soit 3 000 € par an et 45 000 € au total. Le coût net de son épargne après économie d\'impôt est donc de 105 000 € pour 150 000 € investis.',
        'Supposons que son contrat génère un rendement annuel moyen de 3 % (ce chiffre est donné à titre pédagogique et ne constitue pas une promesse de rendement). Au bout de 15 ans, son capital accumulé est d\'environ 195 000 €, dont environ 150 000 € de versements et 45 000 € de plus-values.',
        'À la retraite, sa TMI est de 11 %. Il opte pour une sortie en capital unique. La fiscalité à la sortie est la suivante :',
        '- Sur les 150 000 € de versements déduits : imposition à 11 % (TMI) + 17,2 % (PS) = 28,2 %, soit 42 300 € d\'impôt ;',
        '- Sur les 45 000 € de plus-values : imposition au PFU à 12,8 % + 17,2 % (PS) = 30 %, soit 13 500 € d\'impôt ;',
        '- Total de l\'impôt à la sortie : 55 800 €.',
        'Bilan net de l\'opération : 195 000 € - 55 800 € = 139 200 € net après impôt, pour un coût net de 105 000 € après déduction. Le gain net est d\'environ 34 200 €.',
        'Cet exemple montre que le PER est fiscalement avantageux lorsque la TMI baisse entre l\'entrée et la sortie. Dans le cas inverse (TMI qui augmente), l\'avantage fiscal disparaît, voire devient négatif. Ces chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement. Chaque situation est unique et doit faire l\'objet d\'une analyse personnalisée.',
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes avec la fiscalité du PER',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que plusieurs erreurs reviennent régulièrement concernant la fiscalité du PER :'],
      listItems: [
        'Croire que la déduction à l\'entrée est toujours avantageuse : elle ne l\'est que si la TMI à la sortie est inférieure à la TMI à l\'entrée.',
        'Confondre le plafond de déduction du PER avec un plafond unique : chaque contribuable a un plafond individuel qui figure sur son avis d\'imposition.',
        'Oublier que les prélèvements sociaux de 17,2 % s\'appliquent à la sortie sur les versements déduits, en plus de l\'impôt sur le revenu.',
        'Penser que la sortie en capital est totalement exonérée : seuls les versements non déduits bénéficient de l\'exonération d\'IR à la sortie.',
        'Négliger l\'option PFU/barème progressif : le choix peut avoir un impact significatif sur le montant net perçu.',
        'Ignorer la possibilité de ne pas déduire les versements : cette option peut être pertinente pour les contribuables anticipant une TMI stable ou plus élevée à la retraite.',
        'Utiliser le PER sans avoir simulé l\'impact fiscal global, en tenant compte de l\'ensemble des revenus de retraite (pensions, revenus fonciers, revenus financiers).',
        'Oublier que le PER n\'est pas un produit de défiscalisation pure : c\'est un différé d\'imposition, pas une exonération.',
        'Ne pas vérifier le plafond de déduction disponible avant d\'effectuer un versement, ce qui peut entraîner une réintégration des sommes excédentaires.',
        'Confondre les règles fiscales du PER individuel avec celles des PER d\'entreprise (obligatoire ou collectif), qui ont des régimes spécifiques.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance sur la fiscalité du PER',
      level: 'h2',
      type: 'risk',
      content: [
        'La fiscalité du PER comporte des points de vigilance qu\'il est essentiel de connaître avant de souscrire ou d\'effectuer des versements. Ces éléments ne constituent pas des contre-indications absolues mais des paramètres à intégrer dans l\'analyse.',
      ],
      listItems: [
        'Le blocage des fonds jusqu\'à la retraite est une contrainte forte : en cas de besoin de liquidité imprévu, seuls les cas de déblocage anticipé prévus par la loi permettent d\'accéder à l\'épargne. Un imprévu non couvert (chômage hors cessation d\'activité, maladie hors invalidité, travaux) ne permet pas le déblocage.',
        'La fiscalité à la sortie peut être plus élevée que prévu si la TMI ne baisse pas à la retraite, notamment en présence de revenus fonciers importants, de rentes ou de pensions élevées.',
        'Les frais de gestion et d\'arbitrage du PER réduisent le rendement net et doivent être intégrés dans la simulation fiscale globale. Un PER avec des frais élevés peut annuler tout ou partie de l\'avantage fiscal.',
        'Le taux de conversion de la rente (pour une sortie en rente) est déterminé par le contrat et peut être peu favorable selon les conditions de marché et l\'âge de conversion.',
        'La déduction des versements est plafonnée : un versement excédant le plafond disponible est réintégré au revenu imposable sans possibilité de déduction ultérieure.',
        'Les règles fiscales du PER peuvent évoluer : une réforme de la fiscalité de l\'épargne retraite pourrait modifier les conditions actuelles. Il convient de suivre les évolutions législatives.',
        'L\'arbitrage entre PER et assurance-vie pour la préparation de la retraite est un choix patrimonial structurant qui mérite une analyse complète de la situation personnelle.',
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour évaluer l\'intérêt fiscal du PER',
      level: 'h2',
      type: 'method-steps',
      content: [
        'L\'évaluation de l\'intérêt fiscal du PER suit une méthode structurée en 6 étapes, dans le respect du cadre réglementaire des CGP-CIF. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable complète de la situation du client.',
      ],
      methodSteps: [
        { title: 'Analyse de la TMI actuelle', description: 'Détermination précise de la TMI du foyer fiscal, des revenus imposables, des éventuels revenus exceptionnels et de la capacité d\'épargne disponible après impôt.' },
        { title: 'Estimation de la TMI future à la retraite', description: 'Projection des revenus de retraite (pensions de base, complémentaires, autres revenus) pour estimer la TMI probable à la sortie. Cette étape est cruciale pour évaluer l\'avantage fiscal du différé d\'imposition.' },
        { title: 'Calcul du plafond de déduction disponible', description: 'Vérification du plafond de déduction sur l\'avis d\'imposition, prise en compte des plafonds non utilisés des années antérieures reportables, et mutualisation possible au sein du foyer fiscal.' },
        { title: 'Simulation des scénarios de sortie', description: 'Comparaison des options de sortie en capital (unique ou fractionnée) et en rente, avec simulation de l\'impôt dû selon la TMI estimée et l\'option PFU ou barème progressif.' },
        { title: 'Comparaison avec les alternatives', description: 'Mise en perspective du PER avec d\'autres enveloppes (assurance-vie, PEA, immobilier) pour déterminer la solution la plus adaptée à la stratégie patrimoniale globale.' },
        { title: 'Formalisation et documentation', description: 'Déclaration d\'adéquation formelle si une recommandation est formulée, documentation complète des simulations, suivi périodique et actualisation en fonction des évolutions fiscales et patrimoniales.' },
      ],
    },
    {
      id: 'faq',
      title: 'Questions fréquentes sur la fiscalité du PER',
      level: 'h2',
      type: 'faq',
      content: ['Retrouvez les réponses aux questions les plus fréquentes concernant la fiscalité du Plan d\'Épargne Retraite.'],
      listItems: [
        'Quel est l\'avantage fiscal principal du PER ?',
        'Comment est calculé le plafond de déduction du PER ?',
        'La sortie en capital du PER est-elle imposable ?',
        'Quelle est la différence fiscale entre sortie en capital et sortie en rente ?',
        'Peut-on ne pas déduire ses versements sur un PER ?',
        'Quels sont les cas de déblocage anticipé du PER ?',
        'Comment sont imposées les plus-values du PER à la sortie ?',
        'Le PER est-il intéressant pour un non-imposable ?',
        'Peut-on cumuler PER et assurance-vie pour la retraite ?',
        'Les règles fiscales du PER peuvent-elles changer ?',
      ],
    },
  ],
  faq: [
    { question: 'Quel est l\'avantage fiscal principal du PER ?', answer: 'L\'avantage fiscal principal du PER est la déduction des versements volontaires du revenu imposable dans la limite d\'un plafond annuel. Cette déduction permet de réduire l\'impôt sur le revenu immédiatement. L\'économie d\'impôt réalisée dépend de la TMI : un contribuable à 41 % de TMI qui verse 10 000 € économise 4 100 € d\'impôt.' },
    { question: 'Comment est calculé le plafond de déduction du PER ?', answer: 'Le plafond est égal au plus élevé entre 10 % des revenus professionnels nets plafonnés (montant variable, environ 35 194 € pour 2025) et 10 % du PASS (environ 4 399 €). Pour les travailleurs non-salariés, des règles spécifiques permettent un plafond plus élevé. Le montant exact figure sur l\'avis d\'imposition.' },
    { question: 'La sortie en capital du PER est-elle imposable ?', answer: 'Oui, sauf pour les versements qui n\'ont pas été déduits. Les versements déduits sont imposés dans la catégorie des pensions (TMI + PS 17,2 %). Les plus-values sont soumises au PFU (12,8 % + 17,2 %) ou au barème progressif sur option.' },
    { question: 'Quelle est la différence fiscale entre sortie en capital et sortie en rente ?', answer: 'En sortie en capital, seuls les versements déduits et les plus-values sont imposés. En sortie en rente, la totalité de la rente est imposée comme une pension (TMI + PS), sans distinction entre capital et produits. La rente bénéficie toutefois de l\'abattement de 10 % sur les pensions.' },
    { question: 'Peut-on ne pas déduire ses versements sur un PER ?', answer: 'Oui, il est possible d\'effectuer des versements non déduits sur un PER. Dans ce cas, la sortie en capital est exonérée d\'impôt sur le revenu sur la part des versements. Seules les plus-values sont imposées au PFU. Cette option est intéressante si la TMI future estimée est élevée.' },
    { question: 'Quels sont les cas de déblocage anticipé du PER ?', answer: 'Les cas de déblocage anticipé prévus par la loi sont : l\'achat de la résidence principale, le décès du titulaire, l\'invalidité (titulaire, conjoint ou enfants), le surendettement, la cessation d\'activité non salariée suite à liquidation judiciaire, et l\'expiration des droits aux allocations chômage.' },
    { question: 'Comment sont imposées les plus-values du PER à la sortie ?', answer: 'Les plus-values et intérêts générés par le contrat sont soumis au prélèvement forfaitaire unique (PFU) de 12,8 % (auxquels s\'ajoutent les 17,2 % de prélèvements sociaux, soit 30 % au total). Le contribuable peut opter pour le barème progressif si cela lui est plus favorable.' },
    { question: 'Le PER est-il intéressant pour un non-imposable ?', answer: 'Pour un non-imposable ou un contribuable à TMI très basse (0 % ou 11 %), l\'intérêt fiscal du PER est limité puisque la déduction des versements ne procure pas d\'économie d\'impôt significative. L\'assurance-vie peut être plus adaptée dans ce cas, sauf si l\'objectif est uniquement la constitution d\'une épargne retraite bloquée.' },
    { question: 'Peut-on cumuler PER et assurance-vie pour la retraite ?', answer: 'Oui, PER et assurance-vie sont complémentaires. Le PER est dédié à la retraite avec un avantage fiscal à l\'entrée, tandis que l\'assurance-vie offre plus de souplesse et un cadre successoral avantageux. Une stratégie patrimoniale peut combiner les deux enveloppes en fonction des objectifs.' },
    { question: 'Les règles fiscales du PER peuvent-elles changer ?', answer: 'Oui, les règles fiscales du PER peuvent évoluer en fonction des réformes législatives. Il est recommandé de suivre les évolutions et de réévaluer périodiquement sa stratégie patrimoniale avec un conseiller en gestion de patrimoine.' },
  ],
  ctaTitle: 'Vous souhaitez analyser l\'intérêt fiscal d\'un PER dans votre situation ?',
  ctaText: 'Un échange personnalisé permet d\'évaluer votre situation fiscale et patrimoniale, votre TMI actuelle et future estimée, et de déterminer si le PER est adapté à vos objectifs. Eric Bellaiche, CGP-CIF, vous accompagne dans cette analyse.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie : comment choisir', position: 'inline' },
    { href: '/articles/assurance-vie-fiscalite/', label: 'Fiscalité de l\'assurance-vie', position: 'inline' },
    { href: '/articles/preparer-retraite-patrimoine/', label: 'Préparer sa retraite avec son patrimoine', position: 'inline' },
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne', position: 'inline' },
  ],
  complianceNotes: [
    'Les rendements mentionnés sont donnés à titre purement pédagogique et ne constituent pas une promesse de rendement.',
    'Les simulations présentées sont basées sur des hypothèses fiscales en vigueur au 11 juin 2026 et ne préjugent pas des évolutions futures.',
    'Ce contenu est fourni à titre d\'information générale et ne constitue pas un conseil personnalisé.',
  ],
  hasRisks: false,
};

export default article;
