import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'per-ou-assurance-vie',
  category: 'retraite',
  title: 'PER ou assurance-vie : quelle enveloppe pour préparer sa retraite ?',
  metaTitle: 'PER ou assurance-vie : quelle enveloppe pour préparer sa retraite ?',
  metaDescription: 'Comparaison détaillée entre PER (Plan d\'Épargne Retraite) et assurance-vie pour la préparation retraite : disponibilité, fiscalité à l\'entrée et à la sortie, TMI actuelle et future, horizon, transmission, souplesse. Analyse CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/per-ou-assurance-vie/',
  badge: 'Comparatif &bull; Retraite &bull; Fiscalité &bull; CGP-CIF',
  intro: 'PER ou assurance-vie pour préparer sa retraite ? Ces deux enveloppes répondent à des logiques différentes et peuvent être complémentaires. Le PER est dédié à la retraite avec un avantage fiscal immédiat à l\'entrée, tandis que l\'assurance-vie offre plus de souplesse, une fiscalité allégée après 8 ans et un cadre successoral optimisé. Le choix ne se résume pas à un produit contre un autre : il dépend de la TMI actuelle, de la TMI future estimée, de l\'horizon, du besoin de liquidité et des objectifs de transmission. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous aide à comprendre leurs spécificités.',
  shortAnswer: 'Le PER est conçu spécifiquement pour la retraite : l\'épargne est bloquée jusqu\'à la retraite (sauf exceptions légales), mais les versements sont déductibles du revenu imposable dans la limite d\'un plafond (10 % des revenus professionnels, montant variable selon l\'année, indiqué sur l\'avis d\'imposition). L\'assurance-vie offre plus de souplesse avec des rachats possibles à tout moment, une fiscalité allégée après 8 ans (abattement annuel de 4 600/9 200 €) et un cadre successoral très avantageux (abattement de 152 500 € par bénéficiaire avant 70 ans). Ces deux enveloppes peuvent être complémentaires.',
  summaryItems: [
    { label: 'PER : logique retraite, déduction fiscale et blocage', anchor: 'per-logique-retraite' },
    { label: 'Assurance-vie : souplesse, rachats, fiscalité et transmission', anchor: 'assurance-vie-souplesse' },
    { label: 'Tableau comparatif complet', anchor: 'tableau-comparatif' },
    { label: 'TMI actuelle vs TMI future à la retraite', anchor: 'tmi-actuelle-vs-future' },
    { label: 'Liquidité : un point clé', anchor: 'liquidite-point-cle' },
    { label: 'Transmission : avant et après 70 ans', anchor: 'transmission' },
    { label: 'Complémentarité PER + assurance-vie', anchor: 'complementarite' },
    { label: 'Exemples pédagogiques', anchor: 'exemples-pedagogiques' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Méthode Eric Bellaiche en 5 filtres', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 16,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['PER', 'assurance-vie', 'retraite', 'épargne', 'fiscalité', 'TMI', 'transmission', 'CGP-CIF', 'complémentarité'],
  sections: [
    {
      id: 'per-logique-retraite',
      title: 'PER : logique retraite, déduction fiscale et blocage',
      level: 'h2',
      type: 'normal',
      content: [
        "Le Plan d'Épargne Retraite (PER) est un produit d'épargne dédié à la retraite, réformé par la loi Pacte en 2019. Il existe sous trois formes : PER individuel (successeur du PERP et du contrat Madelin), PER d'entreprise collectif (ex-PERCO) et PER d'entreprise obligatoire.",
        "L'avantage principal du PER est la déduction fiscale des versements volontaires du revenu imposable, dans la limite d'un plafond. Ce plafond est calculé chaque année en fonction des revenus professionnels (10 % des revenus, plafonné à un montant variable selon les années). Il n'existe pas de plafond fixe applicable à tous : le montant exact du plafond disponible figure sur l'avis d'imposition de chaque contribuable.",
        "En contrepartie de cet avantage fiscal, les fonds sont bloqués jusqu'à l'âge légal de départ à la retraite, sauf cas de déblocage anticipé prévus par la loi : achat de la résidence principale, décès, invalidité, surendettement, cessation d'activité. Ces motifs sont limitatifs et ne couvrent pas un besoin de trésorerie classique.",
        "À la sortie, le capital est imposé selon l'option choisie par l'épargnant :",
        "- Sortie en capital : le capital est soumis à l'impôt sur le revenu (sauf la part correspondant aux versements obligatoires) ;",
        "- Sortie en rente : la rente est soumise à l'impôt sur le revenu dans la catégorie des pensions ;",
        "- Sortie mixte : une partie en capital, une partie en rente.",
        "L'avantage fiscal dépend donc de l'écart entre la TMI au moment du versement et la TMI au moment de la sortie. Plus cet écart est important, plus le PER est intéressant.",
      ],
    },
    {
      id: 'assurance-vie-souplesse',
      title: 'Assurance-vie : souplesse, rachats, fiscalité et transmission',
      level: 'h2',
      type: 'normal',
      content: [
        "L'assurance-vie est une enveloppe plus polyvalente que le PER. Elle permet d'épargner sur du moyen à long terme sans objectif exclusif de retraite. Contrairement au PER, elle autorise des rachats à tout moment, pour tout motif, sans condition.",
        "Sur le plan fiscal :",
        "- Les versements ne sont pas déductibles du revenu imposable (sauf contrats Madelin ou contrats collectifs spécifiques).",
        "- Les gains (plus-values) sont imposés uniquement lors d'un rachat, pas pendant la phase d'épargne.",
        "- Après 8 ans de détention, un abattement annuel de 4 600 € (personne seule) ou 9 200 € (couple) s'applique sur les gains pour l'impôt sur le revenu. Au-delà de cet abattement, les gains sont imposés à 7,5 % (ou au barème progressif sur option). Les prélèvements sociaux (17,2 %) sont dus sur la totalité des gains.",
        "En matière de transmission, l'assurance-vie offre un cadre très avantageux :",
        "- Les sommes versées avant 70 ans bénéficient d'un abattement de 152 500 € par bénéficiaire désigné.",
        "- Au-delà de cet abattement, un prélèvement forfaitaire de 20 % s'applique jusqu'à 700 000 €, puis 31,25 % au-delà.",
        "- Les sommes versées après 70 ans bénéficient d'un abattement global de 30 500 € sur l'ensemble des bénéficiaires.",
        "L'assurance-vie est donc particulièrement adaptée aux épargnants qui souhaitent conserver une certaine souplesse et optimiser la transmission de leur patrimoine.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif complet',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous compare les deux enveloppes sur l\'ensemble des critères pertinents pour la préparation retraite.',
      ],
      table: {
        headers: ['Critère', 'PER', 'Assurance-vie'],
        rows: [
          ['Objectif principal', 'Préparation retraite dédiée', 'Épargne polyvalente, retraite, transmission'],
          ['Disponibilité des fonds', 'Bloqué jusqu\'à la retraite (sauf exceptions légales)', 'Rachats possibles à tout moment, sans motif'],
          ["Fiscalité à l'entrée", 'Versements déductibles du revenu imposable (plafonné, variable selon année)', "Versements non déductibles (sauf Madelin, contrats collectifs)"],
          ['Fiscalité des gains en cours', 'Capitalisation sans imposition', 'Capitalisation sans imposition'],
          ["Fiscalité à la sortie (capital)", 'Capital soumis à l\'IR (sauf fraction des versements obligatoires)', 'Gains soumis à l\'IR via abattement après 8 ans (4 600/9 200 €)'],
          ["Fiscalité à la sortie (rente)", 'Rente imposée dans la catégorie des pensions', 'Rente imposée avec un abattement selon l\'âge'],
          ['Plafond de versement', 'Plafond annuel (10 % des revenus, variable selon année et revenus)', 'Pas de plafond annuel (limite des primes selon âge pour l\'assurabilité)'],
          ['Transmission', 'Capital transmis : droits de mutation, abattement selon lien de parenté', 'Cadre très avantageux : abattement 152 500 €/bénéficiaire avant 70 ans'],
          ['Souplesse de gestion', 'Faible (blocage jusqu\'à la retraite, arbitrages possibles)', 'Élevée (rachats, arbitrages, gestion pilotée, avances)'],
          ['Horizon conseillé', 'Jusqu\'à la retraite (peut être 20-40 ans)', 'Moyen à long terme (8+ ans), souple'],
          ['Frais', "Frais d'entrée possibles, frais de gestion annuels", "Frais d'entrée possibles, frais de gestion annuels"],
          ['Motifs de déblocage anticipé', 'Achat RP, décès, invalidité, surendettement, cessation activité', 'Tous motifs (aucune condition)'],
        ],
      },
    },
    {
      id: 'tmi-actuelle-vs-future',
      title: 'TMI actuelle vs TMI future à la retraite : le levier fiscal',
      level: 'h2',
      type: 'normal',
      content: [
        'Le principal avantage du PER repose sur l\'écart entre la TMI actuelle (pendant la vie active) et la TMI estimée à la retraite. Plus cet écart est important, plus le PER est intéressant sur le plan fiscal.',
        "Mécanisme : un épargnant qui verse 10 000 € sur son PER et dont la TMI est de 41 % économise 4 100 € d'impôt immédiatement. À la retraite, s'il est dans une TMI de 11 %, il paiera environ 1 100 € d'impôt sur ce même capital (hors prélèvements sociaux). L'économie fiscale nette est d'environ 3 000 €.",
        "Si un épargnant bénéficie d'une TMI de 41 % aujourd'hui et estime sa TMI à 11 % à la retraite, l'économie d'impôt réalisée grâce à la déduction est significative. Le PER permet alors de différer l'imposition à un moment où le taux est moins élevé.",
        "En revanche, pour un épargnant dont la TMI actuelle est déjà faible (11 % ou 0 %), l'avantage fiscal du PER est limité, voire nul. Dans ce cas, l'assurance-vie peut être plus adaptée.",
        "Points d'attention importants :",
        "- La TMI future n'est pas connue avec certitude : elle dépend de la législation fiscale future, des autres revenus à la retraite (retraite de base, complémentaire, revenus fonciers, placements).",
        "- Une estimation prudente est recommandée, sans pari fiscal agressif.",
        "- Le PER peut être intéressant même avec un écart de TMI modéré, dans une logique de diversification et de complément retraite.",
      ],
    },
    {
      id: 'liquidite-point-cle',
      title: 'Liquidité : un point clé dans le choix',
      level: 'h2',
      type: 'normal',
      content: [
        'La liquidité est l\'un des critères les plus différenciants entre le PER et l\'assurance-vie. Ce critère est souvent sous-estimé lors de la souscription.',
        'Avec le PER, les fonds sont bloqués jusqu\'à la retraite, sauf cas de déblocage anticipé limités (achat résidence principale, décès, invalidité, surendettement, cessation d\'activité). L\'épargnant ne peut pas accéder à son épargne pour d\'autres projets (études des enfants, événement familial, opportunité d\'investissement).',
        "Avec l'assurance-vie, les rachats sont possibles à tout moment, pour tout motif, sans condition. Cette souplesse permet de faire face à un imprévu, de financer un projet familial ou de saisir une opportunité. C'est un atout considérable pour les épargnants qui ne souhaitent pas immobiliser leur épargne jusqu'à un âge éloigné.",
        "Le choix dépend donc de la capacité de l'épargnant à immobiliser son épargne jusqu'à la retraite. Pour quelqu'un qui dispose déjà d'une épargne de précaution suffisante et d'une capacité d'épargne confortable, le PER peut être adapté. Pour quelqu'un qui anticipe un besoin de liquidité ou qui souhaite conserver une flexibilité, l'assurance-vie est plus appropriée.",
        "Une solution intermédiaire consiste à utiliser les deux enveloppes : le PER pour la part d'épargne dédiée à la retraite, l'assurance-vie pour l'épargne plus flexible.",
      ],
    },
    {
      id: 'transmission',
      title: 'Transmission : avant et après 70 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "La transmission est l'un des domaines où les différences entre PER et assurance-vie sont les plus marquées.",
        "Assurance-vie :",
        "- Versements avant 70 ans : abattement de 152 500 € par bénéficiaire désigné. Au-delà, prélèvement de 20 % jusqu'à 700 000 €, puis 31,25 %. C'est un avantage successoral considérable, car les capitaux décès échappent en grande partie aux droits de succession.",
        "- Versements après 70 ans : abattement global de 30 500 € sur l'ensemble des bénéficiaires. Au-delà, les capitaux sont soumis aux droits de succession. Il est donc stratégique d'effectuer les versements importants avant 70 ans.",
        "PER :",
        "- Le capital transmis est soumis aux droits de succession classiques, avec les abattements selon le lien de parenté (100 000 € pour un enfant, etc.).",
        "- Le PER n'offre pas d'avantage successoral spécifique comparable à l'assurance-vie.",
        "Pour un objectif de transmission, l'assurance-vie est généralement beaucoup plus avantageuse. À l'inverse, si la transmission n'est pas une priorité et que l'optimisation fiscale à l'entrée (déduction) l'est, le PER peut être privilégié.",
      ],
    },
    {
      id: 'complementarite',
      title: 'Complémentarité PER + assurance-vie',
      level: 'h2',
      type: 'normal',
      content: [
        "PER et assurance-vie ne sont pas exclusifs. Au contraire, ils sont souvent complémentaires dans une stratégie patrimoniale bien construite.",
        "Le PER est idéal pour :",
        "- Bénéficier d'une déduction fiscale immédiate sur les versements (pour les TMI élevées).",
        "- Se constituer un complément de retraite dédié, avec une épargne bloquée jusqu'à la retraite.",
        "- Diversifier les sources de revenus à la retraite.",
        "L'assurance-vie est idéale pour :",
        "- Conserver une souplesse d'accès à l'épargne (rachats possibles à tout moment).",
        "- Bénéficier d'un cadre successoral avantageux (transmission optimisée).",
        "- Constituer une épargne de long terme sans objectif exclusif de retraite.",
        "Exemple de stratégie combinée : un épargnant avec une TMI élevée (41 %) verse sur son PER pour bénéficier de la déduction fiscale immédiate, tout en alimentant une assurance-vie pour se constituer une épargne disponible et optimiser sa transmission. À la retraite, il peut utiliser le PER pour un complément de revenu et l'assurance-vie pour des besoins ponctuels ou la transmission.",
        "Cette complémentarité permet de bénéficier des avantages de chaque enveloppe : déduction fiscale du PER, souplesse et transmission de l'assurance-vie.",
      ],
    },
    {
      id: 'exemples-pedagogiques',
      title: 'Exemples pédagogiques',
      level: 'h2',
      type: 'table',
      content: [
        'Les exemples ci-dessous illustrent des situations types. Ils sont donnés à titre pédagogique et ne constituent pas des recommandations personnalisées.',
      ],
      table: {
        headers: ['Profil', 'Situation', 'Enveloppe potentiellement adaptée', 'Raison principale'],
        rows: [
          ['Jeune cadre TMI 41 %', 'Revenus élevés, objectif retraite, pas de besoin de liquidité immédiate', 'PER', 'Déduction fiscale élevée, TMI future estimée plus basse'],
          ['Professionnel libéral TMI 30 %', 'Revenus stables, objectif transmission importante', 'Assurance-vie', 'Cadre successoral avantageux, souplesse des rachats'],
          ['Épargnant TMI 11 %', 'Revenus modestes, besoin de souplesse', 'Assurance-vie', 'Avantage fiscal du PER limité, liquidité nécessaire'],
          ['Couple avec enfants', 'Objectif retraite + transmission', 'PER + assurance-vie', 'Complémentarité : PER pour la déduction, AV pour la transmission'],
          ['Investisseur TMI 30 %', 'Patrimoine déjà constitué, objectif diversification', 'PER et/ou assurance-vie', "Selon l'horizon et les objectifs spécifiques"],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans le choix entre PER et assurance-vie',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que plusieurs erreurs reviennent régulièrement dans le choix entre PER et assurance-vie :'],
      listItems: [
        'Choisir le PER uniquement pour la déduction fiscale sans anticiper la fiscalité de sortie ni le blocage des fonds.',
        "Fixer un plafond PER comme une vérité permanente et unique : le plafond dépend des revenus professionnels et de l'année, et est indiqué sur l'avis d'imposition.",
        "Sous-estimer l'importance de la liquidité : le blocage du PER jusqu'à la retraite peut poser problème en cas d'imprévu.",
        "Négliger l'avantage successoral de l'assurance-vie, surtout pour les versements effectués avant 70 ans.",
        'Ouvrir un PER sans avoir constitué une épargne de précaution suffisante (3 à 6 mois de revenus).',
        "Penser que l'assurance-vie est toujours moins avantageuse fiscalement que le PER.",
        "Choisir une enveloppe sans analyser la TMI actuelle et la TMI future estimée à la retraite.",
        'Investir sans objectif clair : retraite, transmission, souplesse, ou combinaison des trois.',
        "Ne pas considérer la complémentarité des deux enveloppes, qui peut être plus efficace que le choix exclusif de l'une.",
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour choisir entre PER et assurance-vie',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour orienter le choix entre PER et assurance-vie, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 filtres. Aucune recommandation personnalisée n\'est formulée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Filtre fiscal', description: "Analyse de la TMI actuelle et estimation de la TMI future à la retraite. Plus l'écart est important, plus le PER est pertinent." },
        { title: 'Filtre liquidité', description: "Évaluation du besoin d'accès à l'épargne avant la retraite. Si un besoin existe, l'assurance-vie est plus adaptée." },
        { title: 'Filtre transmission', description: "Analyse des objectifs successoraux. Si la transmission est prioritaire, l'assurance-vie offre un cadre beaucoup plus avantageux." },
        { title: 'Filtre complémentarité', description: "Vérification de la possibilité de cumuler les deux enveloppes pour bénéficier de leurs avantages respectifs (déduction + souplesse)." },
        { title: 'Filtre cohérence globale', description: "Intégration dans la stratégie patrimoniale globale, en tenant compte des autres placements, de l'immobilier, de la prévoyance et des objectifs personnels." },
      ],
    },
  ],
  faq: [
    { question: 'Quelle différence entre PER et assurance-vie ?', answer: "Le PER est conçu pour la retraite : l'épargne est bloquée jusqu'à la retraite (sauf exceptions). L'assurance-vie offre plus de souplesse avec des rachats possibles à tout moment. La fiscalité diffère : déduction à l'entrée pour le PER, abattement après 8 ans pour l'assurance-vie." },
    { question: 'Quelle enveloppe est la plus avantageuse fiscalement ?', answer: "Le PER permet de déduire les versements du revenu imposable, intéressant pour les TMI élevées. L'assurance-vie offre un abattement annuel après 8 ans sur les gains. Le choix dépend de la TMI actuelle et de la TMI future estimée à la retraite." },
    { question: 'Peut-on cumuler PER et assurance-vie ?', answer: "Oui, ces deux enveloppes sont complémentaires. Le PER pour la déduction fiscale et la constitution d'une épargne retraite dédiée, l'assurance-vie pour la souplesse et la transmission." },
    { question: 'Quel est le plafond de déduction du PER ?', answer: "Le plafond dépend des revenus professionnels (10 % des revenus, plafonné à un montant variable selon l'année). Le montant exact du plafond disponible figure sur l'avis d'imposition. Il n'existe pas de plafond fixe applicable à tous." },
    { question: 'Peut-on sortir en capital du PER ?', answer: "Oui, la sortie en capital est possible depuis la loi Pacte (2019). L'épargnant peut choisir entre sortie en capital, en rente, ou mixte. Le capital est soumis à l'impôt sur le revenu lors du retrait." },
    { question: "L'assurance-vie est-elle vraiment avantageuse pour la transmission ?", answer: "Oui, pour les versements effectués avant 70 ans, chaque bénéficiaire désigné bénéficie d'un abattement de 152 500 €. C'est un avantage très significatif par rapport aux droits de succession classiques." },
    { question: 'Le PER est-il adapté à une personne non imposable ?', answer: "Si la TMI est de 0 %, l'avantage fiscal du PER est nul. L'assurance-vie peut être plus adaptée, sous réserve de l'horizon et des objectifs." },
    { question: "Quels sont les cas de déblocage anticipé du PER ?", answer: "Achat de la résidence principale, décès, invalidité, surendettement, cessation d'activité. Les motifs sont limités par la loi et ne couvrent pas les besoins courants." },
    { question: "L'assurance-vie a-t-elle un plafond de versement ?", answer: "Il n'y a pas de plafond annuel de versement, mais les versements importants après 70 ans réduisent l'avantage successoral. Des contraintes techniques existent selon les contrats (limite des primes selon l'âge)." },
    { question: 'Une recommandation peut-elle être faite sans analyse préalable ?', answer: 'Non. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse de la situation, des objectifs, de la TMI actuelle et future, de l\'horizon et de la capacité d\'épargne.' },
  ],
  ctaTitle: 'Vous souhaitez structurer votre stratégie retraite ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation et d\'identifier l\'enveloppe la mieux adaptée à vos objectifs patrimoniaux.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne', position: 'inline' },
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI', position: 'inline' },
  ],
};

export default article;
