import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'preparer-retraite-patrimoine',
  category: 'retraite',
  title: 'Préparer sa retraite avec son patrimoine : placements, immobilier et fiscalité',
  metaTitle: 'Préparer sa retraite avec son patrimoine : placements, immobilier et fiscalité | Eric Bellaiche',
  metaDescription: "Préparer sa retraite avec son patrimoine : stratégie globale combinant PER, assurance-vie, immobilier locatif, SCPI, épargne et optimisation fiscale. Méthode et conseils d'un CGP-CIF.",
  canonical: 'https://eric-bellaiche.fr/articles/preparer-retraite-patrimoine/',
  badge: 'Préparation retraite &bull; CGP-CIF &bull; ORIAS 13001580',
  intro: "La retraite est l'un des enjeux patrimoniaux les plus importants pour les actifs français. Avec un système de retraite par répartition dont le taux de remplacement diminue tendanciellement, la constitution d'un patrimoine dédié à la retraite est devenue une nécessité pour maintenir son niveau de vie. Préparer sa retraite avec son patrimoine, c'est mettre en place une stratégie globale qui combine plusieurs leviers : l'épargne dans des enveloppes fiscales adaptées (PER, assurance-vie), l'investissement immobilier (locatif, SCPI), et une gestion optimisée de la fiscalité. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, accompagne ses clients dans la construction et le pilotage de leur stratégie retraite.",
  shortAnswer: "Préparer sa retraite avec son patrimoine consiste à construire une stratégie d'épargne et d'investissement sur le long terme pour compléter les pensions de retraite obligatoires. Les principaux leviers sont : le PER (déduction fiscale des versements, sortie en capital ou rente), l'assurance-vie (fiscalité avantageuse après 8 ans, disponibilité des fonds), l'immobilier locatif (revenus complémentaires, constitution d'un patrimoine), les SCPI (diversification immobilière, revenus réguliers), et l'épargne investie en actions via PEA ou assurance-vie UC. La stratégie doit tenir compte de l'horizon, de la TMI, de l'âge, des objectifs de revenus futurs et de la tolérance au risque. L'optimisation fiscale des versements, la diversification des supports et l'anticipation de la fiscalité de sortie sont les clés d'une préparation réussie.",
  summaryItems: [
    { label: 'Pourquoi préparer sa retraite avec son patrimoine ?', anchor: 'pourquoi-preparer-retraite' },
    { label: 'Les piliers de la stratégie retraite patrimoniale', anchor: 'piliers-strategie' },
    { label: 'PER, assurance-vie, immobilier : quel rôle pour chaque enveloppe ?', anchor: 'role-enveloppes' },
    { label: 'Tableau comparatif des enveloppes retraite', anchor: 'tableau-comparatif' },
    { label: 'Stratégie fiscale pour la retraite', anchor: 'strategie-fiscale' },
    { label: 'Erreurs fréquentes dans la préparation retraite', anchor: 'erreurs-frequentes' },
    { label: 'Exemple pédagogique anonymisé', anchor: 'exemple-pedagogique' },
    { label: "Méthode Eric Bellaiche pour préparer sa retraite", anchor: 'methode' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 20,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['retraite', 'patrimoine', 'placements', 'immobilier', 'fiscalité', 'PER', 'assurance-vie', 'CGP-CIF'],
  sections: [
    {
      id: 'pourquoi-preparer-retraite',
      title: 'Pourquoi préparer sa retraite avec son patrimoine ?',
      level: 'h2',
      type: 'normal',
      content: [
        "La retraite par répartition, pilier du système français, permet de bénéficier d'une pension calculée sur la base des revenus d'activité. Cependant, le taux de remplacement (rapport entre la pension et le dernier revenu d'activité) tend à diminuer depuis plusieurs années, sous l'effet de l'allongement de la durée de cotisation, de la désindexation partielle des pensions et de l'évolution démographique.",
        "Pour un cadre ayant cotisé au plafond de la Sécurité sociale, le taux de remplacement net est estimé entre 60 et 75 % du dernier revenu net, selon le régime complémentaire et la durée de carrière. Pour les revenus supérieurs au plafond (3 864 € par mois en 2024), la part non couverte par la retraite obligatoire est encore plus importante.",
        "Préparer sa retraite avec son patrimoine permet de combler cet écart en constituant des revenus complémentaires. L'objectif n'est pas seulement d'accumuler un capital, mais de générer des flux de revenus réguliers, fiscalement optimisés, qui viendront s'ajouter aux pensions de retraite.",
        "Les avantages d'une préparation patrimoniale de la retraite sont multiples :",
        "- Constitution d'un capital qui peut être transformé en rente ou en revenus réguliers (loyers, dividendes, intérêts).",
        "- Optimisation fiscale pendant la phase d'épargne (déduction des versements PER, fiscalité allégée de l'assurance-vie).",
        "- Diversification des sources de revenus à la retraite (pension de retraite, rente PER, revenus de l'assurance-vie, loyers, dividendes).",
        "- Flexibilité : possibilité d'adapter le rythme de prélèvement en fonction des besoins.",
        "- Transmission : le capital non consommé à la retraite peut être transmis dans des conditions fiscales avantageuses (assurance-vie notamment).",
        "Plus tôt la stratégie est mise en place, plus l'effet de la capitalisation et des intérêts composés joue en faveur de l'épargnant.",
      ],
    },
    {
      id: 'piliers-strategie',
      title: 'Les piliers de la stratégie retraite patrimoniale',
      level: 'h2',
      type: 'list',
      content: [
        "Une stratégie retraite complète repose sur plusieurs piliers, qui doivent être combinés en fonction de l'âge, des revenus, de la fiscalité et des objectifs :",
      ],
      listItems: [
        "L'épargne salariale et l'abondement employeur : PER d'entreprise, PEE, PERCO. C'est souvent le premier levier à actionner car il bénéficie d'un abondement employeur qui constitue un rendement immédiat et sans risque.",
        "Le PER individuel : enveloppe dédiée à la retraite, avec déduction fiscale des versements dans la limite du plafond (10 % des revenus professionnels, maximum 35 194 € en 2024). Sortie possible en capital (100 %) ou en rente, au choix. Fiscalité de sortie : le capital est imposé à l'IR (hors montant correspondant aux versements déduits).",
        "L'assurance-vie : enveloppe polyvalente qui permet d'épargner pour la retraite tout en conservant une disponibilité (rachat partiel possible). Fiscalité avantageuse après 8 ans (abattement annuel de 4 600 € sur les plus-values). Utilisation possible en complément de revenu par des rachats programmés.",
        "L'immobilier locatif : investissement dans un bien locatif qui génère des loyers à la retraite. Avantage : effet de levier du crédit pendant la phase d'activité, constitution d'un patrimoine, revenus complémentaires. Inconvénient : gestion locative, fiscalité des revenus fonciers, illiquidité.",
        'Les SCPI : société civile de placement immobilier qui permet d\'investir dans l\'immobilier sans les contraintes de gestion locative. Les SCPI distribuent des revenus trimestriels ou semestriels, ce qui en fait un outil adapté à la recherche de revenus complémentaires à la retraite.',
        "Les actions et ETF via PEA ou assurance-vie : investissement en actions pour bénéficier de la croissance économique sur le long terme. Le PEA est exonéré d'IR après 5 ans (PS 17,2 % dus). Les UC en assurance-vie bénéficient de la fiscalité avantageuse de l'enveloppe.",
      ],
    },
    {
      id: 'role-enveloppes',
      title: 'PER, assurance-vie, immobilier : quel rôle pour chaque enveloppe ?',
      level: 'h2',
      type: 'normal',
      content: [
        "Chaque enveloppe a un rôle spécifique dans une stratégie retraite globale. Le choix et la pondération de chaque enveloppe dépendent de plusieurs facteurs : l'âge, la TMI, l'horizon, la capacité d'épargne, la tolérance au risque et les objectifs de revenus futurs.",
        "Le PER est l'outil le plus spécifiquement dédié à la retraite. Son avantage principal est la déduction fiscale des versements : chaque euro versé est déduit du revenu imposable, ce qui génère une économie d'impôt immédiate égale à la TMI multipliée par le montant versé. Pour un TMI à 41 %, verser 10 000 € sur un PER coûte en réalité 5 900 € après économie d'impôt. L'inconvénient est le blocage des fonds jusqu'à la retraite (sauf exceptions) et la fiscalité de sortie : le capital retiré (hors plus-values) est imposé à l'IR dans la catégorie des rentes viagères à titre onéreux. Le PER est donc particulièrement intéressant quand la TMI actuelle est élevée et que la TMI future estimée sera plus basse.",
        "L'assurance-vie est plus polyvalente. Elle ne donne pas droit à une déduction fiscale des versements, mais elle offre une grande flexibilité : les fonds sont disponibles à tout moment (rachat partiel ou total), la fiscalité des plus-values est avantageuse après 8 ans (prélèvement forfaitaire libératoire de 7,5 % au-delà de l'abattement, ou PFU 30 %), et l'assurance-vie permet d'investir dans une large gamme de supports (fonds euros, UC, SCPI, ETF, obligations). À la retraite, l'assurance-vie peut être utilisée pour générer des revenus réguliers via des rachats programmés.",
        "L'immobilier locatif et les SCPI constituent un troisième pilier. Ils génèrent des revenus sous forme de loyers, qui s'ajoutent aux pensions de retraite. L'immobilier offre une protection contre l'inflation et permet de diversifier les sources de revenus. Les SCPI présentent l'avantage de la mutualisation (diversification sur plusieurs immeubles et plusieurs secteurs) et de l'absence de gestion locative directe.",
        "La clé d'une stratégie retraite réussie est la complémentarité entre ces enveloppes, en fonction de l'âge, de la situation fiscale et des objectifs. Par exemple, un jeune cadre de 35 ans aura intérêt à combiner un PER (pour la déduction fiscale et le long terme) et une assurance-vie (pour la flexibilité), puis à ajouter des SCPI ou de l'immobilier locatif à mesure que son patrimoine se constitue.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif des enveloppes pour la retraite',
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous compare les principales caractéristiques des enveloppes utilisées dans une stratégie retraite patrimoniale. Il vous aidera à comprendre les avantages et contraintes de chaque outil.",
      ],
      table: {
        headers: ['Critère', 'PER individuel', 'Assurance-vie', 'SCPI', 'Immobilier locatif direct', 'PEA'],
        rows: [
          ['Avantage fiscal à l\'entrée', 'Déduction des versements du RFR', 'Aucun', 'Aucun (sauf Pinel)', 'Aucun (sauf dispositifs)', 'Aucun'],
          ['Fiscalité des gains', 'Rente imposée à l\'IR. Capital (hors versements déduits) imposé au PFU 7,5 %', 'PFU 30 % ou IR après 8 ans (abattement 4 600 €)', 'RF imposés à la TMI + PS 17,2 %', 'RF imposés à la TMI + PS 17,2 %', 'Exonération IR après 5 ans (PS 17,2 %)'],
          ['Disponibilité avant retraite', 'Blocage (sauf exceptions)', 'Disponible à tout moment', 'Peu liquide', 'Peu liquide', 'Disponible après 5 ans'],
          ['Risque', 'Fonds euros : faible. UC : variable', 'Fonds euros : faible. UC : variable', 'Moyen (marché immo, vacance)', 'Moyen à élevé', 'Élevé (volatilité actions)'],
          ['Frais', 'Frais d\'entrée, de gestion, d\'arbitrage', 'Frais de gestion, d\'arbitrage', 'Frais de souscription, de gestion', 'Frais de notaire, de gestion locative', 'Frais de courtage, de garde'],
          ['Transmission', 'Capital transmis, fiscalité selon l\'âge', 'Très avantageuse (hors PS)', 'Transmission via succession', 'Transmission via succession', 'Transmission normale'],
          ['Gouvernance', 'Simple (contrat individuel)', 'Simple (contrat individuel)', 'Simple (copropriété)', 'Complexe (gestion locative)', 'Simple (compte titres)'],
          ['Revenus à la retraite', 'Rente ou capital échelonné', 'Rachats programmés', 'Dividendes trimestriels', 'Loyers mensuels', 'Dividendes ou vente'],
        ],
      },
    },
    {
      id: 'strategie-fiscale',
      title: 'Stratégie fiscale pour la retraite',
      level: 'h2',
      type: 'normal',
      content: [
        "L'optimisation fiscale est un élément central de la préparation retraite. L'enjeu est de maximiser l'effet de levier fiscal pendant la phase d'épargne tout en minimisant l'imposition au moment de la phase de consommation du capital.",
        "Pendant la phase d'activité : le PER est l'outil le plus efficace pour réduire l'impôt sur le revenu. Les versements sont déductibles dans la limite d'un plafond annuel. Pour un TMI à 41 %, chaque tranche de 1 000 € versée sur un PER génère 410 € d'économie d'impôt. Il est stratégique d'utiliser son plafond PER chaque année, surtout dans les années à forte TMI. L'assurance-vie ne permet pas de déduction, mais elle offre une croissance des capitaux dans un cadre fiscal avantageux. L'investissement en SCPI peut être réalisé via l'assurance-vie pour bénéficier de la fiscalité de l'enveloppe.",
        "À l'approche de la retraite : il est recommandé de sécuriser progressivement son épargne en réduisant la part d'actifs risqués (UC actions) au profit d'actifs plus sécurisés (fonds euros, obligations, SCPI de rendement). Cette phase de sécurisation s'étale généralement sur les 5 à 10 ans précédant le départ en retraite.",
        "À la retraite : la gestion du patrimoine doit viser à générer des revenus réguliers tout en optimisant la fiscalité. Les stratégies possibles incluent : les rachats programmés sur l'assurance-vie (abattement annuel de 4 600 € sur les plus-values), la perception des loyers ou des dividendes de SCPI, le retrait partiel du PER (le capital est alors imposé, mais si la TMI est plus basse qu'en activité, l'opération est favorable).",
        "Il est important de noter que la fiscalité est un paramètre évolutif. Les règles peuvent changer en cours de route, et une stratégie optimale aujourd'hui peut ne plus l'être demain. C'est pourquoi un suivi périodique avec un CGP-CIF est recommandé.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans la préparation de la retraite',
      level: 'h2',
      type: 'list',
      content: [
        'La préparation de la retraite est un exercice complexe où les erreurs peuvent avoir des conséquences importantes. Voici les plus fréquentes :',
      ],
      listItems: [
        'Commencer trop tard : plus on commence tôt, plus l\'effet des intérêts composés est puissant. Commencer à 50 ans pour une retraite à 62-67 ans laisse peu de temps pour constituer un capital significatif.',
        'Sous-estimer le besoin de revenus futurs : beaucoup de futurs retraités surestiment leur pension et sous-estiment les dépenses post-activité (santé, dépendance, loisirs, voyages).',
        'Surinvestir dans le PER sans anticiper la fiscalité de sortie : verser sur un PER quand on est en TMI 30 % est pertinent, mais il faut vérifier que la TMI future ne sera pas trop élevée (notamment si le PER génère une rente importante cumulée avec la pension de retraite).',
        'Négliger l\'assurance-vie dans la stratégie retraite : l\'assurance-vie offre une flexibilité que le PER n\'a pas. Beaucoup d\'épargnants mettent tout sur le PER et aucun sur l\'assurance-vie, ce qui les prive de souplesse.',
        'Investir uniquement en fonds euros pour la retraite : un horizon long (15-30 ans) permet de prendre un risque mesuré en actions ou en immobilier pour obtenir un meilleur rendement espéré. Un fonds euros seul risque de ne pas générer suffisamment de capital.',
        'Oublier l\'inflation : une pension fixe perd du pouvoir d\'achat avec l\'inflation. Les placements immobiliers (loyers indexés) et actions offrent une meilleure protection contre l\'inflation.',
        'Ne pas diversifier ses sources de revenus : dépendre d\'une seule source (la pension de retraite + un seul placement) est risqué. Mieux vaut combiner retraite obligatoire, PER, assurance-vie, immobilier et SCPI.',
        'Négliger l\'impact des frais : des frais de gestion élevés peuvent réduire significativement le capital accumulé sur 20 ou 30 ans. Comparez les frais avant de choisir un contrat.',
        'Ne pas réviser sa stratégie régulièrement : un plan établi à 35 ans n\'est plus adapté à 55 ans. La stratégie doit être ajustée à chaque étape de la vie.',
        'Confondre épargne retraite et défiscalisation : investir dans un produit uniquement parce qu\'il est défiscalisant, sans vérifier sa cohérence avec la stratégie retraite globale.',
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique anonymisé',
      level: 'h2',
      type: 'normal',
      content: [
        "Situation : un homme de 48 ans, cadre supérieur, marié, deux enfants de 14 et 16 ans. Revenus annuels : 140 000 €. TMI : 41 %. Résidence principale : 600 000 €, crédit en cours 100 000 € à 1,1 % sur 7 ans. Assurance-vie : 150 000 € sur deux contrats (dont 80 000 € de fonds euros et 70 000 € d'UC diversifiées). PER : 40 000 €, plafond disponible 25 000 €. PEA : 30 000 € (ETF monde). Épargne de précaution : 35 000 €. Pas d'immobilier locatif ni de SCPI. Objectif : retraite à 63-65 ans, maintenir un niveau de vie équivalent à 80 % du revenu actuel.",
        "Estimation du besoin : la pension de retraite estimée est de 48 000 € par an (taux de remplacement estimé à 55 % du revenu net). Le besoin de revenus complémentaires est d'environ 30 000 € par an, soit 2500 € par mois.",
        "Stratégie proposée après analyse :",
        "1. Utilisation du plafond PER disponible (25 000 €) pendant 3 ans. Économie d'impôt immédiate : 25 000 € × 41 % = 10 250 € par an. Au total, 75 000 € versés sur 3 ans avec une économie d'impôt de 30 750 €.",
        "2. Augmentation des versements sur l'assurance-vie : 10 000 € par an supplémentaires en UC diversifiées (ETF monde, SCPI via assurance-vie). Objectif : constituer un capital de 200 000 € à 250 000 € d'ici la retraite, permettant des rachats programmés de 8 000 à 10 000 € par an.",
        "3. Investissement en SCPI via l'assurance-vie : 50 000 € en une fois, pour générer des revenus complémentaires (rendement estimé 4,5 à 5,5 % brut, soit environ 2 500 € par an de revenus locatifs, fiscalité allégée par l'enveloppe assurance-vie).",
        "4. À 58-60 ans, sécurisation progressive : arbitrage des UC actions vers des supports plus sécurisés (fonds euros, obligations). À 63 ans, le capital est majoritairement en actifs sécurisés.",
        "Cet exemple anonymisé ne constitue pas une recommandation personnalisée. Chaque situation nécessite une analyse spécifique préalable.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour préparer sa retraite avec son patrimoine",
      level: 'h2',
      type: 'method-steps',
      content: [
        "Eric Bellaiche, CGP-CIF, applique une méthode structurée en 6 étapes pour préparer la retraite de ses clients. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète de la situation, du profil investisseur, des objectifs, de l'horizon et de la capacité de perte.",
      ],
      methodSteps: [
        { title: 'Analyse de la situation et estimation des droits', description: "Recueil des documents : relevé de carrière, estimation des droits retraite (régime général, complémentaire Agirc-Arrco, régimes spéciaux), situation fiscale, patrimoine existant, capacité d'épargne mensuelle. Estimation du taux de remplacement et du besoin de complément de revenu." },
        { title: 'Définition des objectifs de revenus', description: "Détermination du niveau de vie souhaité à la retraite, des dépenses prévisibles, des projets (voyages, logement, santé), de l'âge de départ souhaité. Chiffrage de l'objectif : montant annuel de revenus complémentaires nécessaire." },
        { title: "Choix de la répartition entre enveloppes", description: "Proposition d'une allocation entre PER (déduction fiscale), assurance-vie (flexibilité, fiscalité de sortie), immobilier/SCPI (revenus réguliers) et PEA (croissance long terme). Pondération en fonction de l'âge, de la TMI et de l'horizon." },
        { title: 'Mise en place du plan d\'épargne', description: "Définition d'un plan d'épargne mensuel ou annuel, avec répartition entre les enveloppes. Optimisation de l'utilisation du plafond PER chaque année. Mise en place de versements programmés sur l'assurance-vie. Planification des investissements immobiliers ou SCPI." },
        { title: 'Gestion de la phase de sécurisation', description: "À l'approche de la retraite (5 à 10 ans avant), sécurisation progressive du patrimoine : réduction de la part d'UC actions, renforcement du fonds euros et des SCPI de rendement, anticipation de la fiscalité de sortie du PER." },
        { title: 'Suivi et ajustement annuel', description: "Suivi annuel de la stratégie : révision des objectifs, ajustement de l'allocation, rééquilibrage des enveloppes. Prise en compte des évolutions de la fiscalité, des marchés et de la situation personnelle." },
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance sur la préparation retraite',
      level: 'h2',
      type: 'normal',
      content: [
        "La préparation de la retraite est un enjeu de long terme qui nécessite rigueur et méthode. Plusieurs points méritent une attention particulière :",
        "- Les estimations de pension de retraite sont sujettes à des réformes. Les paramètres (âge légal, durée de cotisation, taux de liquidation) peuvent évoluer. Il faut donc réviser régulièrement ses projections.",
        "- Aucun placement ne garantit un rendement fixe sur 20 ou 30 ans. Les performances passées ne préjugent pas des performances futures.",
        "- La fiscalité de la retraite est complexe et peut évoluer. Les règles de déduction du PER, de taxation des rentes et d'abattement de l'assurance-vie peuvent être modifiées par le législateur.",
        "- Le PER est un outil puissant mais rigide. Les fonds sont bloqués jusqu'à la retraite (sauf quelques exceptions : achat de la résidence principale, décès, invalidité). Il faut donc conserver une épargne disponible par ailleurs.",
        "- L'immobilier locatif à la retraite peut être source de revenus, mais aussi de contraintes : gestion locative, travaux, vacance locative. Les SCPI permettent d'éviter ces contraintes mais présentent un risque de marché et d'illiquidité.",
        "- La transmission du patrimoine retraite est un sujet à anticiper. L'assurance-vie offre des avantages successoraux significatifs par rapport au PER.",
        "Ces points ne remettent pas en cause l'importance de préparer sa retraite avec son patrimoine, mais soulignent la nécessité d'une approche diversifiée, révisable et accompagnée.",
      ],
    },
  ],
  faq: [
    { question: "Quel est le bon âge pour commencer à préparer sa retraite ?", answer: "Idéalement dès les premiers revenus professionnels, car l'effet de la capitalisation est d'autant plus puissant que l'horizon est long. Mais il n'est jamais trop tard : même à 50 ans, une stratégie bien conçue peut faire une différence significative." },
    { question: "Quelle est la différence entre le PER et l'assurance-vie pour la retraite ?", answer: "Le PER permet une déduction fiscale des versements mais bloque les fonds jusqu'à la retraite. L'assurance-vie ne donne pas droit à déduction mais offre une disponibilité permanente et une fiscalité de sortie souvent plus avantageuse après 8 ans." },
    { question: "Est-il possible de cumuler PER et assurance-vie pour la retraite ?", answer: "Oui, c'est même recommandé. Le PER est utilisé pour la déduction fiscale et l'épargne bloquée jusqu'à la retraite. L'assurance-vie apporte flexibilité, disponibilité et avantages successoraux." },
    { question: "Quel montant épargner chaque mois pour une retraite confortable ?", answer: "Cela dépend de votre âge, de vos revenus, de votre pension estimée et de vos objectifs. Une règle courante est d'épargner 10 à 15 % de ses revenus, mais seule une analyse personnalisée permet de déterminer le montant adapté." },
    { question: "Les SCPI sont-elles adaptées à la préparation de la retraite ?", answer: "Oui, les SCPI sont particulièrement adaptées car elles génèrent des revenus réguliers (dividendes trimestriels) sans contrainte de gestion locative. Elles peuvent être détenues en direct ou via une assurance-vie." },
    { question: "Faut-il rembourser son crédit immobilier avant la retraite ?", answer: "Généralement oui, pour réduire ses charges fixes à la retraite. Mais dans certains cas (taux très bas, investissement locatif), il peut être stratégique de conserver un crédit. Cela dépend de chaque situation." },
    { question: "Quel est l'impact de la retraite sur ma TMI ?", answer: "La retraite fait généralement baisser les revenus, donc la TMI. C'est pourquoi le PER est intéressant : vous déduisez les versements à une TMI élevée en activité et vous êtes imposé à une TMI plus basse à la retraite." },
    { question: "Puis-je utiliser mon PER pour acheter ma résidence principale ?", answer: "Oui, la loi autorise le déblocage anticipé du PER pour l'achat de la résidence principale. C'est une exception au principe de blocage jusqu'à la retraite." },
    { question: "Quelle est la meilleure stratégie pour les travailleurs non-salariés (TNS) ?", answer: "Les TNS bénéficient de plafonds PER spécifiques souvent plus élevés. Le PER Madelin (pour les TNS) et le PER obligatoire sont des outils puissants. L'assurance-vie et l'immobilier complètent la stratégie." },
    { question: "Dois-je privilégier la rente ou le capital pour mon PER à la retraite ?", answer: "Le choix dépend de vos besoins. Le capital offre plus de flexibilité (vous gérez vous-même vos prélèvements). La rente offre un revenu garanti à vie mais est moins flexible et fiscalement moins avantageuse. La sortie en capital (100 %) est souvent préférée." },
  ],
  ctaTitle: 'Vous souhaitez préparer votre retraite avec une stratégie patrimoniale ?',
  ctaText: 'Un premier échange gratuit permet d\'estimer votre situation, vos droits et le chemin à parcourir. Aucun engagement, aucune recommandation personnalisée sans analyse préalable complète.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie : quelle enveloppe choisir', position: 'inline' },
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne', position: 'inline' },
    { href: '/articles/structurer-son-patrimoine/', label: 'Structurer son patrimoine', position: 'inline' },
    { href: '/articles/erreurs-gestion-patrimoine/', label: 'Les erreurs fréquentes en gestion de patrimoine', position: 'inline' },
  ],
};

export default article;
