import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'sci-ir-ou-sci-is',
  category: 'fiscalite',
  title: 'SCI à l\'IR ou SCI à l\'IS : fiscalité, transmission et arbitrage patrimonial',
  metaTitle: 'SCI à l\'IR ou à l\'IS : comparatif fiscalité, transmission, dividendes, plus-values - CGP-CIF',
  metaDescription: 'Comparaison détaillée entre SCI soumise à l\'IR et SCI soumise à l\'IS : fiscalité des loyers, dividendes, plus-values, transmission patrimoniale, frais de structure, amortissement, TMI. Analyse complète par Eric Bellaiche, CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/sci-ir-ou-sci-is/',
  badge: 'SCI &bull; IR &bull; IS &bull; Fiscalité &bull; Transmission &bull; CGP-CIF',
  intro: 'Le choix du régime fiscal d\'une Société Civile Immobilière constitue l\'une des décisions les plus structurantes pour un investisseur immobilier. Soumettre la SCI à l\'impôt sur le revenu (IR) ou à l\'impôt sur les sociétés (IS) n\'est pas une simple formalité administrative : ce choix détermine la fiscalité des loyers perçus, le traitement des plus-values, la possibilité d\'amortir le bien, la politique de distribution des dividendes et, in fine, l\'efficacité patrimoniale de la structure. Chaque régime présente des avantages et des inconvénients qui s\'apprécient différemment selon la situation personnelle des associés, leurs objectifs de revenus, leur horizon de détention et leur stratégie de transmission. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous propose une analyse approfondie des implications fiscales et patrimoniales de chaque option.',
  shortAnswer: 'La SCI à l\'IR est le régime de droit commun, fiscalement transparent : les associés déclarent leur quote-part de résultat dans leur déclaration de revenus, dans la catégorie des revenus fonciers ou BIC. La SCI à l\'IS est une option qui transforme la société en personne morale imposable sur son résultat : elle ouvre droit à l\'amortissement du bien (comme en LMNP), mais double la fiscalité (IS sur le bénéfice + IR sur les dividendes). La SCI à l\'IR est généralement plus adaptée pour la détention longue, la transmission progressive et les associés avec une TMI modérée. La SCI à l\'IS convient aux associés à TMI élevée souhaitant capitaliser dans la société tout en amortissant le bien. L\'arbitrage dépend de la situation patrimoniale globale.',
  summaryItems: [
    { label: 'SCI à l\'IR : fonctionnement, fiscalité et avantages', anchor: 'sci-ir-fonctionnement' },
    { label: 'SCI à l\'IS : fonctionnement, fiscalité et contraintes', anchor: 'sci-is-fonctionnement' },
    { label: 'Tableau comparatif SCI IR vs SCI IS', anchor: 'tableau-comparatif' },
    { label: 'L\'amortissement en SCI à l\'IS : levier fiscal', anchor: 'amortissement-sci-is' },
    { label: 'Fiscalité des plus-values à la sortie', anchor: 'fiscalite-plus-values-sortie' },
    { label: 'Impact sur la transmission et la donation de parts', anchor: 'impact-transmission-donation' },
    { label: 'Exemple pédagogique : simulation sur 20 ans', anchor: 'exemple-pedagogique-simulation' },
    { label: 'Frais de structure et coûts de fonctionnement', anchor: 'frais-structure-fonctionnement' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Méthode Eric Bellaiche pour arbitrer', anchor: 'methode-arbitrage' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 22,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCI', 'IR', 'IS', 'fiscalité', 'transmission', 'immobilier', 'CGP-CIF'],
  sections: [
    {
      id: 'sci-ir-fonctionnement',
      title: 'SCI à l\'IR : fonctionnement, fiscalité et avantages',
      level: 'h2',
      type: 'normal',
      content: [
        'La SCI soumise à l\'impôt sur le revenu (IR) constitue le régime de droit commun des sociétés civiles immobilières. Par défaut, une SCI est soumise à l\'IR conformément à l\'article 8 du Code général des impôts. Ce régime se caractérise par sa transparence fiscale : la société n\'est pas imposée sur son résultat ; ce sont les associés qui déclarent chacun leur quote-part de résultat dans leur déclaration de revenus personnelle.',
        'En SCI à l\'IR, le résultat de la société (loyers perçus diminués des charges déductibles) est imposé dans la catégorie des revenus fonciers pour chaque associé, proportionnellement à sa participation au capital. Les associés peuvent déduire leur quote-part des intérêts d\'emprunt, de la taxe foncière, des charges de copropriété, des frais de gestion et des travaux d\'entretien. En revanche, l\'amortissement du bien immobilier n\'est pas autorisé.',
        'Le principal avantage de la SCI à l\'IR est sa simplicité fiscale et sa transparence. Chaque associé est imposé selon sa propre TMI, ce qui permet une certaine souplesse si les associés ont des situations fiscales différentes. En cas de déficit foncier, chaque associé peut imputer sa quote-part de déficit sur son revenu global dans la limite de 10 700 € par an (régime du déficit foncier).',
        'Pour la transmission, la SCI à l\'IR présente un avantage majeur : les parts sociales peuvent être transmises progressivement par donation, avec les abattements applicables entre vifs (100 000 € par enfant tous les 15 ans). La valeur des parts est déterminée à partir de la valeur vénale du bien, sans minoration liée à des amortissements comptabilisés, ce qui peut être favorable pour la transmission. En contrepartie, en cas de cession des parts, la plus-value est calculée sur la différence entre le prix de cession et le prix d\'acquisition des parts, et imposée comme une plus-value immobilière.',
      ],
    },
    {
      id: 'sci-is-fonctionnement',
      title: 'SCI à l\'IS : fonctionnement, fiscalité et contraintes spécifiques',
      level: 'h2',
      type: 'normal',
      content: [
        'L\'option pour l\'impôt sur les sociétés (IS) transforme profondément le fonctionnement fiscal de la SCI. La société devient une personne morale imposable sur son bénéfice au taux de l\'IS (15 % jusqu\'à 42 500 € de bénéfice pour les PME, puis 25 % au-delà). Les associés ne sont plus imposés directement sur les loyers, mais uniquement sur les dividendes qui leur sont distribués par la société.',
        'L\'avantage principal de la SCI à l\'IS réside dans la possibilité d\'amortir le bien immobilier (hors terrain). Comme en LMNP, l\'amortissement réduit le résultat imposable de la société, ce qui peut permettre de ne payer que peu ou pas d\'IS pendant la période d\'amortissement. Cet amortissement n\'est pas une charge décaissée : la trésorerie correspondante reste dans la société et peut être réinvestie.',
        'La contrepartie est le mécanisme de double imposition. Lorsque la société distribue des dividendes aux associés, ceux-ci sont imposés à l\'IR dans la catégorie des revenus de capitaux mobiliers (PFU de 30 % ou option pour le barème progressif). Les prélèvements sociaux (17,2 %) s\'appliquent également. Au total, les revenus distribués supportent l\'IS (15-25 %) puis l\'IR (jusqu\'à 30 % au PFU), ce qui peut représenter une charge fiscale globale significative.',
        'La SCI à l\'IS entraîne également des contraintes de gestion plus lourdes : tenue d\'une comptabilité complète (bilan, compte de résultat, annexes), établissement de liasses fiscales, assemblées générales annuelles, nomination d\'un commissaire aux comptes sous certaines conditions. Les frais de fonctionnement (expert-comptable, formalités juridiques) sont généralement plus élevés qu\'en SCI à l\'IR.',
        'Enfin, le régime de l\'IS modifie les règles de plus-value : la cession du bien par la SCI est imposée au taux de l\'IS (25 %), sans abattement pour durée de détention. La cession des parts par les associés est imposée comme une plus-value sur valeurs mobilières (PFU de 30 %), avec abattement pour durée de détention uniquement si l\'option pour le barème progressif est retenue.',
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif complet : SCI IR vs SCI IS',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous synthétise les principales différences entre SCI à l\'IR et SCI à l\'IS, critère par critère.',
      ],
      table: {
        headers: ['Critère', 'SCI à l\'IR', 'SCI à l\'IS'],
        rows: [
          ['Régime de droit commun', 'Oui (par défaut)', 'Non (option à exercer)'],
          ['Personne morale imposable', 'Non (transparence fiscale)', 'Oui (imposition au niveau de la société)'],
          ['Imposition des loyers', 'Revenus fonciers chez chaque associé (TMI + PS)', 'IS au niveau de la société (15-25 %)'],
          ['Amortissement du bien', 'Non autorisé', 'Oui (hors terrain, sur 25-30 ans)'],
          ['Déduction des intérêts d\'emprunt', 'Oui (quote-part chez chaque associé)', 'Oui (au niveau de la société)'],
          ['Imposition des dividendes', 'Non applicable', 'PFU 30 % ou barème progressif pour les associés'],
          ['Plus-value sur cession du bien', 'Imposée chez les associés (plus-value immobilière)', 'IS 25 % au niveau de la société'],
          ['Plus-value sur cession de parts', 'Plus-value immobilière (abattement durée détention)', 'Plus-value sur valeurs mobilières (PFU 30 %)'],
          ['Déficit foncier imputable', 'Oui (limite 10 700 € par associé)', 'Non (déficit reportable sur la société)'],
          ['Transmission par donation', 'Favorable (valeur vénale, abattements classiques)', 'Moins favorable (valeur comptable après amortissements)'],
          ['Comptabilité obligatoire', 'Simplifiée (option pour le réel simplifié)', 'Complète (bilan, compte de résultat, liasses fiscales)'],
          ['Frais de gestion annuels', 'Faibles à modérés', 'Plus élevés (expert-comptable, formalités)'],
          ['Adapté aux TMI élevées', 'Oui, si déficit foncier ou TMI modérée', 'Oui, pour capitalisation avec amortissement'],
        ],
      },
    },
    {
      id: 'amortissement-sci-is',
      title: 'L\'amortissement en SCI à l\'IS : le levier fiscal clé',
      level: 'h2',
      type: 'normal',
      content: [
        'L\'amortissement constitue le principal avantage de l\'option pour l\'IS. Il permet à la société de déduire chaque année une fraction de la valeur du bien (hors terrain) de son résultat imposable, réduisant d\'autant l\'IS dû.',
        'Prenons un exemple concret. Une SCI à l\'IS acquiert un immeuble de 500 000 €, dont 80 000 € de terrain (non amortissable) et 420 000 € de construction. Avec un amortissement sur 30 ans en linéaire, la dotation annuelle est de 14 000 €. Si les loyers annuels sont de 30 000 € et les charges de 10 000 € (intérêts d\'emprunt, taxe foncière, assurance, frais de gestion), le bénéfice avant amortissement est de 20 000 €. Après amortissement de 14 000 €, le bénéfice imposable tombe à 6 000 €, soit un IS de seulement 900 € (au taux de 15 %). Sans amortissement, l\'IS aurait été de 3 000 €.',
        'L\'économie d\'IS réalisée grâce à l\'amortissement s\'accumule dans la société sous forme de trésorerie disponible. Cette trésorerie peut être utilisée pour rembourser l\'emprunt, financer des travaux, réaliser de nouveaux investissements ou être distribuée sous forme de dividendes (avec la fiscalité afférente).',
        'Attention : l\'amortissement réduit la valeur comptable du bien dans les comptes de la société. En cas de revente, la plus-value comptable (prix de cession - valeur nette comptable) sera plus élevée et imposée à l\'IS sans abattement pour durée de détention. C\'est le même mécanisme de différé d\'imposition qu\'en LMNP.',
        'Le plan d\'amortissement doit être établi avec soin : durée cohérente avec la nature du bien, méthode linéaire ou dégressive le cas échéant, distinction entre composants (gros œuvre, second œuvre, installations techniques). L\'accompagnement d\'un expert-comptable spécialisé est indispensable.',
      ],
    },
    {
      id: 'fiscalite-plus-values-sortie',
      title: 'Fiscalité des plus-values à la sortie',
      level: 'h2',
      type: 'normal',
      content: [
        'La sortie de l\'investissement (cession du bien ou cession des parts) n\'est pas fiscalement traitée de la même manière selon le régime de la SCI. Cette différence est cruciale dans l\'arbitrage IR vs IS.',
        'En SCI à l\'IR, la cession du bien immobilier est transparente : la plus-value est calculée au niveau de chaque associé comme une plus-value immobilière. Elle bénéficie des abattements pour durée de détention (exonération totale après 22 ans pour l\'IR et 30 ans pour les prélèvements sociaux). En cas de cession des parts de la SCI, la plus-value est également imposée comme une plus-value immobilière avec les mêmes abattements.',
        'En SCI à l\'IS, la cession du bien par la société génère une plus-value imposée à l\'IS au taux en vigueur (25 %), sans aucun abattement pour durée de détention. C\'est un inconvénient majeur par rapport à l\'IR. Si la société est ensuite liquidée, le produit de la cession (après IS) est distribué aux associés et imposé au PFU de 30 % (ou au barème), ajoutant une seconde couche d\'imposition.',
        'La cession des parts d\'une SCI à l\'IS est traitée comme une cession de valeurs mobilières : la plus-value est imposée au PFU de 30 % (12,8 % d\'IR + 17,2 % de PS), avec un abattement pour durée de détention si l\'associé opte pour le barème progressif (50 % après 2 ans, 65 % après 8 ans pour l\'IR). Les prélèvements sociaux restent dus sans abattement.',
        'Ces différences rendent la SCI à l\'IS moins adaptée pour les détentions très longues (au-delà de 20 ans) ou pour les associés qui envisagent de céder le bien à un horizon connu. En revanche, si l\'objectif est de conserver le bien indéfiniment et de transmettre les parts, la SCI à l\'IS peut rester pertinente malgré la fiscalité de sortie.',
      ],
    },
    {
      id: 'impact-transmission-donation',
      title: 'Impact sur la transmission et la donation de parts',
      level: 'h2',
      type: 'normal',
      content: [
        'La transmission du patrimoine immobilier détenu en SCI diffère sensiblement selon le régime fiscal choisi. Cette dimension est souvent déterminante dans l\'arbitrage pour les investisseurs ayant un objectif de transmission patrimoniale.',
        'En SCI à l\'IR, la valeur des parts est déterminée à partir de la valeur vénale du bien immobilier détenu. Les amortissements ne viennent pas réduire cette valeur. La donation de parts peut être réalisée progressivement, en utilisant les abattements personnels (100 000 € par enfant tous les 15 ans, 31 865 € pour les petits-enfants, etc.). Le démembrement de parts (usufruit temporaire ou viager) permet de transmettre la nue-propriété à moindre coût fiscal.',
        'En SCI à l\'IS, la valeur des parts est calculée à partir de la situation nette comptable de la société (actif - passif), qui intègre les amortissements pratiqués. Si le bien a été amorti sur 20 ans, la valeur comptable peut être très inférieure à la valeur vénale. Pour la donation, c\'est la valeur réelle des parts (valeur vénale) qui est retenue par l\'administration fiscale, et non la valeur comptable. Cependant, la donation de parts d\'une SCI à l\'IS peut entraîner une imposition au titre des plus-values latentes si la donation est réalisée à titre onéreux. En donation pure et simple, la plus-value latente est transmise avec les parts — elle sera imposée chez le donataire lors de la cession future.',
        'Le démembrement de parts en SCI à l\'IS est plus complexe qu\'en SCI à l\'IR. Il nécessite une analyse juridique et fiscale approfondie pour éviter les écueils. En pratique, la SCI à l\'IR est souvent privilégiée pour les stratégies de transmission patrimoniale.',
        'Dans les deux cas, une convention de blocage des parts (agrément des cessions) est recommandée pour contrôler l\'entrée de nouveaux associés. Les statuts de la SCI doivent également prévoir les modalités de sortie et de valorisation des parts.',
      ],
    },
    {
      id: 'exemple-pedagogique-simulation',
      title: 'Exemple pédagogique : simulation comparative sur 20 ans',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous compare un même investissement immobilier en SCI à l\'IR et en SCI à l\'IS. Le bien est acquis 500 000 € avec un apport de 150 000 € et un emprunt de 350 000 € sur 20 ans à 3 %. Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement ni une performance passée.',
      ],
      table: {
        headers: ['Critère', 'SCI à l\'IR', 'SCI à l\'IS'],
        rows: [
          ['Prix d\'acquisition', '500 000 €', '500 000 € (dont 420 000 € amortissable)'],
          ['Loyers bruts annuels', '30 000 €', '30 000 €'],
          ['Charges annuelles (intérêts, taxe foncière, etc.)', '12 000 €', '12 000 €'],
          ['Amortissement annuel', 'Non applicable', '14 000 € (30 ans, linéaire)'],
          ['Bénéfice annuel avant impôt', '18 000 €', '4 000 €'],
          ['Impôt annuel (TMI 30 % ou IS 15 %)', '~5 400 € (IR + PS)', '~600 € (IS à 15 %)'],
          ['Économie d\'impôt annuelle', 'Réf., comparaison', '~4 800 €'],
          ['Trésorerie nette annuelle disponible', '~12 600 €', '~17 400 € (dans la société)'],
          ['Trésorerie cumulée sur 20 ans', '~252 000 €', '~348 000 € (dans la société)'],
          ['Plus-value à la revente (bien cédé 600 000 €)', 'Plus-value imposable : 100 000 €', 'Plus-value imposable : ~220 000 € (valeur nette)'],
          ['Fiscalité estimée à la revente', 'Abattement durée de détention (exonération totale IR après 22 ans)', 'IS 25 % sur la plus-value (~55 000 €) + PFU si distribution'],
          ['Transmission des parts', 'Valorisation vénale, donation facilitée', 'Valorisation ajustée, donation plus complexe'],
        ],
      },
    },
    {
      id: 'frais-structure-fonctionnement',
      title: 'Frais de structure et coûts de fonctionnement',
      level: 'h2',
      type: 'normal',
      content: [
        'Les coûts de fonctionnement d\'une SCI diffèrent sensiblement selon le régime fiscal choisi. Ces coûts doivent être anticipés et intégrés dans le calcul de rentabilité global.',
        'Pour une SCI à l\'IR, les obligations comptables sont allégées. Si la société relève du régime réel simplifié, une comptabilité de trésorerie et une déclaration annuelle de résultat (n° 2072) suffisent. Les frais d\'expert-comptable sont généralement compris entre 500 et 1 200 € par an selon la complexité. Les frais juridiques (assemblées générales, formalités) sont modestes.',
        'Pour une SCI à l\'IS, les obligations sont plus lourdes. La société doit établir un bilan, un compte de résultat et des annexes, déposer une liasse fiscale complète (n° 2065 et liasses n° 2050 à 2059). Les frais d\'expert-comptable sont plus élevés, généralement entre 1 500 et 3 000 € par an. Des frais supplémentaires peuvent s\'ajouter pour l\'établissement du plan d\'amortissement, la gestion des immobilisations et le suivi des reports déficitaires.',
        'Les frais de constitution de la SCI (rédaction des statuts, enregistrement, publication légale, immatriculation) sont sensiblement les mêmes quel que soit le régime, soit environ 1 500 à 3 000 € selon la complexité. En revanche, en cas d\'option pour l\'IS, des frais supplémentaires peuvent être nécessaires pour adapter les statuts et informer l\'administration fiscale.',
        'Il est important de noter que les frais de fonctionnement (expert-comptable, frais juridiques, frais de tenue de compte) sont déductibles du résultat de la société, quel que soit le régime. Le coût net après économie d\'impôt est donc réduit d\'autant.',
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans le choix du régime fiscal de la SCI',
      level: 'h2',
      type: 'list',
      content: [
        'Plusieurs erreurs sont couramment commises lors du choix entre SCI à l\'IR et SCI à l\'IS. Les connaître permet d\'éviter des décisions préjudiciables.',
      ],
      listItems: [
        'Croire que l\'IS est toujours plus avantageux grâce à l\'amortissement : l\'économie d\'impôt en phase de détention peut être annulée par la double imposition à la sortie (IS sur la plus-value + PFU sur les dividendes).',
        'Opter pour l\'IS sans anticiper la fiscalité de sortie : la cession du bien après IS est bien plus lourde qu\'en IR, surtout pour les détentions de plus de 15 à 20 ans.',
        'Négliger l\'impact de l\'IS sur la transmission : la donation de parts d\'une SCI à l\'IS est plus complexe et potentiellement moins favorable qu\'en IR, en raison des plus-values latentes.',
        'Confondre les règles de plus-value sur cession de parts : en SCI à l\'IR, c\'est une plus-value immobilière (abattement durée de détention) ; en SCI à l\'IS, c\'est une plus-value sur valeurs mobilières (PFU ou barème progressif).',
        'Oublier les frais de structure supplémentaires en IS : comptabilité complète, expert-comptable spécialisé, formalités annuelles. Ces frais réduisent la rentabilité nette.',
        'Choisir l\'IS uniquement pour des raisons fiscales sans considérer la situation personnelle des associés : l\'IS est contre-performant pour les associés ayant une TMI faible ou modérée.',
        'Ne pas prévoir de stratégie de sortie : l\'IS est particulièrement pénalisant si le bien doit être revendu à court ou moyen terme (10-15 ans). Une détention de 20 ans minimum est recommandée en IS.',
        'Investir en SCI à l\'IS sans simulation personnalisée : les paramètres sont nombreux (TMI, loyer, durée, taux d\'emprunt, plus-value attendue) et seule une simulation précise permet de comparer les deux options.',
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance pour votre arbitrage',
      level: 'h2',
      type: 'risk',
      content: [
        'Le choix entre SCI à l\'IR et SCI à l\'IS mérite une analyse rigoureuse. Voici les points de vigilance essentiels à prendre en compte.',
      ],
      listItems: [
        'L\'option pour l\'IS est irrévocable à certains égards : une fois exercée, le retour à l\'IR est soumis à des conditions strictes et peut entraîner des coûts fiscaux importants (imposition des réserves).',
        'En SCI à l\'IS, les loyers inférieurs à la valeur locative réelle (location à un associé, par exemple) peuvent être requalifiés par l\'administration fiscale comme un acte anormal de gestion, entraînant un redressement.',
        'La déduction des intérêts d\'emprunt en SCI à l\'IS est plafonnée dans certaines conditions (règles de sous-capitalisation). Une vigilance particulière est nécessaire en cas de financement majoritaire par emprunt.',
        'La transmission des parts de SCI à l\'IS doit être anticipée : la clause d\'agrément des statuts doit prévoir les modalités d\'évaluation des parts et les conditions de sortie des associés.',
        'En cas d\'associés multiples, leurs situations fiscales personnelles (TMI, patrimoine, objectifs) peuvent diverger. Le choix du régime doit être cohérent avec l\'ensemble des associés, pas seulement le plus imposé.',
        'Les règles de l\'IS évoluent régulièrement (taux, seuils, régime des plus-values). Une veille fiscale et un suivi par un professionnel sont nécessaires pour anticiper les changements.',
        'En SCI à l\'IS, la distribution de dividendes est soumise au PFU (30 %) ou au barème progressif. Cette fiscalité s\'ajoute à l\'IS déjà acquitté, ce qui peut représenter une charge fiscale globale de 40 à 50 % sur les bénéfices distribués.',
      ],
    },
    {
      id: 'methode-arbitrage',
      title: 'Méthode Eric Bellaiche pour arbitrer entre SCI IR et SCI IS',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour déterminer le régime fiscal le plus adapté à votre SCI, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 étapes. Aucune recommandation n\'est formulée sans analyse préalable de la situation globale.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation fiscale des associés', description: 'TMI de chaque associé, prélèvements sociaux, IFI, revenus existants : ces éléments déterminent l\'avantage comparatif de l\'IR (transparence) ou de l\'IS (capitalisation).' },
        { title: 'Définition de l\'horizon de détention et des objectifs', description: 'Horizon de placement, objectif de revenus (distribution vs capitalisation), stratégie de transmission : chaque paramètre oriente le choix du régime.' },
        { title: 'Simulation comparative personnalisée', description: 'Calcul des flux nets de trésorerie année par année en IR et en IS, intégrant l\'amortissement, la fiscalité des dividendes, les frais de structure et la fiscalité de sortie à l\'horizon prévu.' },
        { title: 'Analyse de la stratégie de transmission', description: 'Évaluation de l\'impact sur la donation de parts, les droits de succession, le démembrement de propriété et la valorisation des parts à transmettre.' },
        { title: 'Arbitrage et mise en place opérationnelle', description: 'Choix du régime, rédaction ou adaptation des statuts, exercice de l\'option fiscale le cas échéant, mise en place de la comptabilité et des obligations déclaratives avec l\'expert-comptable.' },
      ],
    },
  ],
  faq: [
    { question: 'Quelle est la différence fondamentale entre une SCI à l\'IR et une SCI à l\'IS ?', answer: 'La différence fondamentale est le régime d\'imposition : en IR, la société est fiscalement transparente et le résultat est imposé directement chez les associés. En IS, la société est imposée sur son bénéfice, et les dividendes distribués sont imposés une seconde fois chez les associés.' },
    { question: 'La SCI à l\'IS permet-elle d\'amortir le bien immobilier ?', answer: 'Oui, l\'amortissement du bien (hors terrain) est autorisé en SCI à l\'IS, ce qui constitue le principal avantage de ce régime par rapport à la SCI à l\'IR où l\'amortissement n\'est pas possible.' },
    { question: 'Quel régime fiscal choisir pour transmettre son patrimoine ?', answer: 'La SCI à l\'IR est généralement plus adaptée pour la transmission : valorisation des parts à la valeur vénale, donation facilitée, abattements classiques. La SCI à l\'IS est plus complexe pour la transmission en raison des plus-values latentes liées aux amortissements.' },
    { question: 'Peut-on passer d\'une SCI à l\'IR à une SCI à l\'IS ?', answer: 'Oui, l\'option pour l\'IS est possible sur simple demande auprès de l\'administration fiscale. En revanche, le retour de l\'IS vers l\'IR est beaucoup plus complexe et peut entraîner une imposition des réserves.' },
    { question: 'Quels sont les frais de comptabilité d\'une SCI à l\'IS ?', answer: 'Les frais d\'expert-comptable pour une SCI à l\'IS sont généralement compris entre 1 500 et 3 000 € par an, contre 500 à 1 200 € pour une SCI à l\'IR, en raison des obligations comptables plus lourdes.' },
    { question: 'La double imposition en SCI à l\'IS est-elle rédhibitoire ?', answer: 'Pas nécessairement. L\'amortissement permet de réduire fortement l\'IS pendant les 20-25 premières années. La double imposition devient pénalisante si les bénéfices sont distribués ou si le bien est cédé avec une forte plus-value. Tout dépend de la stratégie de capitalisation et de l\'horizon.' },
    { question: 'Quel est le traitement des plus-values en SCI à l\'IS ?', answer: 'La plus-value sur cession du bien est imposée à l\'IS (25 %), sans abattement pour durée de détention. La plus-value sur cession de parts est imposée au PFU (30 %) ou au barème progressif avec abattement pour durée de détention sur option.' },
    { question: 'La SCI à l\'IS est-elle adaptée aux petits budgets ?', answer: 'Généralement non, car les frais de structure (expert-comptable, comptabilité) sont élevés par rapport au gain fiscal potentiel. La SCI à l\'IS est plus pertinente pour des investissements significatifs, généralement supérieurs à 300 000-400 000 €.' },
    { question: 'Faut-il une SCI pour investir dans l\'immobilier locatif ?', answer: 'Non, la SCI n\'est pas obligatoire. Elle est utile pour faciliter la détention à plusieurs, organiser la transmission, ou opter pour l\'IS et bénéficier de l\'amortissement. Pour un investisseur seul, la détention en direct (LMNP ou location nue) est souvent plus simple et moins coûteuse.' },
    { question: 'Quel est le rôle du CGP-CIF dans le choix du régime fiscal de la SCI ?', answer: 'Le CGP-CIF (Conseiller en Gestion de Patrimoine) analyse la situation globale du ou des associés, simule les deux régimes, évalue l\'impact sur la fiscalité, la transmission et la rentabilité, et recommande la solution la plus adaptée. Il oriente également vers les professionnels compétents (expert-comptable, notaire) pour la mise en place.' },
  ],
  ctaTitle: 'Vous vous interrogez sur le régime fiscal de votre SCI ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation patrimoniale et de déterminer le régime fiscal le plus adapté à vos objectifs.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/immobilier-locatif-fiscalite/', label: 'Immobilier locatif et fiscalité', position: 'inline' },
    { href: '/articles/fiscalite-revenus-fonciers/', label: 'Fiscalité des revenus fonciers', position: 'inline' },
    { href: '/articles/transmission-patrimoine-famille-recomposee/', label: 'Transmission du patrimoine en famille recomposée', position: 'inline' },
    { href: '/articles/structurer-son-patrimoine/', label: 'Structurer son patrimoine', position: 'footer' },
  ],
  hasRisks: false,
};

export default article;
