import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'scpi-assurance-vie-ou-direct',
  category: 'scpi',
  title: 'SCPI en direct ou via assurance-vie : comment comparer et choisir ?',
  metaTitle: 'SCPI en direct ou via assurance-vie : comment comparer et choisir ?',
  metaDescription: 'Comparaison détaillée entre détention directe de SCPI et investissement via assurance-vie : frais, fiscalité, liquidité, choix des SCPI, rendement net, horizon, transmission, succession. Analyse CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/scpi-assurance-vie-ou-direct/',
  badge: 'SCPI &bull; Assurance-vie &bull; Comparatif CGP-CIF',
  intro: 'Investir en SCPI en direct ou via un contrat d\'assurance-vie ? Ce choix revient fréquemment chez les investisseurs patrimoniaux et il n\'existe pas de réponse universelle. Chaque option présente des avantages et des limites spécifiques en matière de fiscalité, de frais, de liquidité, de choix des supports et de transmission. Le bon choix dépend de la situation personnelle, des objectifs patrimoniaux et de l\'horizon de placement. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous aide à comprendre les différences pour éclairer votre décision.',
  shortAnswer: 'La détention directe offre un choix plus large de SCPI, une gestion directe et une simplicité de souscription, mais avec une fiscalité élevée sur les revenus (IR + PS) et les plus-values, et une transmission soumise aux droits de mutation. L\'assurance-vie offre un cadre fiscal différé et un abattement annuel après 8 ans (4 600/9 200 €), ainsi qu\'un cadre successoral avantageux avec abattement de 152 500 € par bénéficiaire avant 70 ans. En contrepartie, le choix des SCPI est limité, des frais supplémentaires s\'ajoutent, et la quote-part de loyers reversée peut être réduite. Le choix dépend de la situation personnelle.',
  summaryItems: [
    { label: 'SCPI en direct : fonctionnement, fiscalité et limites', anchor: 'scpi-direct-fonctionnement' },
    { label: 'SCPI via assurance-vie : fonctionnement et fiscalité des rachats', anchor: 'scpi-assurance-vie-fonctionnement' },
    { label: 'Tableau comparatif complet', anchor: 'tableau-comparatif' },
    { label: 'Impact fiscal selon le profil', anchor: 'impact-fiscal-profil' },
    { label: 'Impact sur la liquidité', anchor: 'impact-liquidite' },
    { label: 'Impact sur la transmission', anchor: 'impact-transmission' },
    { label: 'Impact sur le choix des SCPI disponibles', anchor: 'impact-choix-scpi' },
    { label: 'Frais et quote-part de loyers reversée', anchor: 'frais-quote-part' },
    { label: 'Exemple pédagogique : simulation sur 10 ans', anchor: 'exemple-pedagogique' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Méthode Eric Bellaiche pour comparer les options', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 18,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'assurance-vie', 'détention directe', 'comparatif', 'fiscalité', 'transmission', 'liquidité', 'CGP-CIF', 'frais'],
  sections: [
    {
      id: 'scpi-direct-fonctionnement',
      title: 'SCPI en direct : fonctionnement, fiscalité, avantages et limites',
      level: 'h2',
      type: 'normal',
      content: [
        "Investir en SCPI en direct signifie acquérir des parts de société civile de placement immobilier directement auprès de la société de gestion ou via un intermédiaire (banque, conseiller en gestion de patrimoine). L'investisseur perçoit les loyers distribués au prorata de ses parts et supporte la fiscalité afférente.",
        "Sur le plan fiscal, les revenus sont imposés dans la catégorie des revenus fonciers, soumis à la TMI et aux prélèvements sociaux (17,2 %). Les plus-values de cession sont imposées comme des plus-values immobilières (19 % d'IR + 17,2 % de PS, soit 36,2 %), avec des abattements pour durée de détention.",
        "Principaux avantages de la détention directe :",
        '- Choix large : toutes les SCPI du marché sont accessibles, sans restriction.',
        "- Simplicité de détention : l'investisseur est directement propriétaire des parts.",
        '- Pas d\'intermédiaire financier supplémentaire : les frais se limitent aux frais de souscription et de gestion de la SCPI.',
        '- Possibilité de déduire les intérêts d\'emprunt si acquisition à crédit.',
        '- Perception directe des revenus : les loyers sont versés directement sur le compte de l\'investisseur.',
        "Principales limites :",
        "- Fiscalité élevée pour les TMI supérieures à 30 %, réduisant fortement le rendement net.",
        "- Liquidité dépendante du marché secondaire de la SCPI (délai de revente variable).",
        "- Transmission soumise aux droits de mutation classiques.",
        "- Pas d'abattement fiscal spécifique pour les plus-values à long terme.",
      ],
    },
    {
      id: 'scpi-assurance-vie-fonctionnement',
      title: 'SCPI via assurance-vie : fonctionnement et fiscalité des rachats',
      level: 'h2',
      type: 'normal',
      content: [
        "Dans un contrat d'assurance-vie, les parts de SCPI sont logées en unités de compte (UC). L'investisseur ne détient pas directement les parts de SCPI, mais des parts du contrat adossées à ces parts. C'est une différence fondamentale qui modifie la fiscalité, la liquidité et la transmission.",
        "Sur le plan fiscal, les revenus des SCPI sont capitalisés dans le contrat sans imposition immédiate. C'est uniquement au moment du rachat que la fiscalité s'applique, et uniquement sur les gains (plus-values), pas sur le capital.",
        "En cas de rachat après 8 ans de détention, les gains bénéficient d'un abattement annuel sur l'impôt sur le revenu : 4 600 € pour une personne seule, 9 200 € pour un couple. Au-delà de cet abattement, les gains sont imposés au taux forfaitaire de 7,5 % (ou au barème progressif sur option). Les prélèvements sociaux (17,2 %) restent dus sur la totalité des gains, sans abattement.",
        "Principaux avantages de l'assurance-vie :",
        "- Fiscalité différée et abattement annuel après 8 ans.",
        "- Cadre successoral particulièrement avantageux (abattement de 152 500 € par bénéficiaire désigné pour les versements avant 70 ans).",
        '- Possibilité d\'arbitrer entre différents supports sans fiscalité immédiate.',
        "- Pas d'IFI sur les unités de compte.",
        "Principales limites :",
        "- Choix des SCPI limité à celles éligibles au contrat, négociées par l'assureur.",
        "- Frais supplémentaires : frais d'entrée du contrat, frais de gestion des UC.",
        "- La quote-part de loyers reversée par la SCPI via l'assureur peut être inférieure à celle de la détention directe.",
        "- L'abattement annuel après 8 ans n'est pas une exonération totale : il est limité à 4 600/9 200 € par an.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif complet',
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous compare l'ensemble des critères différenciant la détention directe de la détention via assurance-vie.",
      ],
      table: {
        headers: ['Critère', 'SCPI en direct', 'SCPI via assurance-vie'],
        rows: [
          ["Frais d'entrée", "8 à 12 % (frais de souscription SCPI)", "Frais d'entrée du contrat (0 à 5 %) + frais sur UC"],
          ['Frais de gestion annuels', '8 à 12 % des loyers perçus (société de gestion)', 'Frais de gestion du contrat (0,5 à 1 %) + frais de gestion SCPI'],
          ['Quote-part de loyers reversée', '100 % des loyers distribués (après frais de gestion)', 'Quote-part réduite (frais assureur : estimation 85-95 %)'],
          ['Fiscalité des revenus (pendant la détention)', 'IR (TMI) + PS 17,2 % chaque année', 'Capitalisation : aucune imposition immédiate'],
          ['Fiscalité en sortie', 'IR + PS sur les plus-values immobilières', 'Abattement après 8 ans, puis 7,5 % + PS sur les gains'],
          ['Liquidité', 'Marché secondaire de la SCPI (délai variable de quelques semaines à années)', 'Rachat du contrat (délai variable selon l\'assureur)'],
          ['Choix des SCPI', 'Large (toutes les SCPI du marché)', 'Limité aux SCPI éligibles au contrat'],
          ['Horizon recommandé', '8 à 10 ans minimum', '8 ans minimum (optimisation fiscale)'],
          ['Transmission / succession', 'Droits de mutation', 'Cadre successoral avantageux (hors succession)'],
          ['IFI', 'Inclus dans le patrimoine immobilier', 'Pas d\'IFI (UC)'],
          ['Possibilité de crédit', 'Oui, intérêts déductibles', 'Non (sauf contrats spécifiques)'],
          ['Gestion pilotée', 'Non (choix libre de l\'investisseur)', 'Oui, possible'],
          ['Arbitrage entre supports', 'Non applicable (une seule SCPI)', 'Oui, possible sans fiscalité immédiate'],
        ],
      },
    },
    {
      id: 'impact-fiscal-profil',
      title: 'Impact fiscal selon le profil de l\'investisseur',
      level: 'h2',
      type: 'normal',
      content: [
        'L\'avantage fiscal de l\'assurance-vie par rapport à la détention directe dépend fortement de la TMI et de l\'horizon de placement.',
        'Pour un investisseur avec une TMI de 30 % ou plus, l\'assurance-vie offre un avantage fiscal significatif sur le long terme. En direct, le rendement net peut être réduit de près de moitié par la fiscalité (par exemple, un TD de 6 % devient ~3,2 % net pour une TMI à 30 %). Via l\'assurance-vie, ce même rendement brut peut être conservé presque intégralement grâce à la capitalisation et à l\'abattement après 8 ans.',
        "Pour un investisseur avec une TMI faible (11 % ou 0 %), l'écart est moins marqué. La détention directe peut être plus avantageuse, notamment si l'investisseur souhaite percevoir des revenus réguliers immédiats et bénéficier d'un choix large de SCPI.",
        "Attention : l'avantage fiscal de l'assurance-vie doit être mis en balance avec les frais supplémentaires et la quote-part de loyers reversée par l'assureur, qui peuvent réduire le rendement brut avant même la fiscalité. Un contrat d'assurance-vie avec des frais élevés peut annuler tout ou partie de l'avantage fiscal.",
      ],
    },
    {
      id: 'impact-liquidite',
      title: 'Impact sur la liquidité',
      level: 'h2',
      type: 'normal',
      content: [
        'La liquidité diffère sensiblement selon le mode de détention, même si elle n\'est jamais garantie dans les deux cas.',
        'En direct : la revente des parts dépend du marché secondaire de la SCPI, géré par la société de gestion. Certaines SCPI très capitalisées (plus d\'un milliard d\'euros) offrent une liquidité correcte avec des délais de revente de quelques semaines. Les SCPI de taille modeste (moins de 200 millions d\'euros) peuvent nécessiter plusieurs mois, voire années, pour trouver un acheteur.',
        "Via assurance-vie : le rachat de parts du contrat dépend des conditions générales de l'assureur. Certains contrats imposent un délai de rachat (30 à 60 jours). L'assureur peut être contraint de vendre les parts de SCPI sur le marché secondaire pour exécuter le rachat, ce qui peut prendre du temps supplémentaire.",
        "Dans les deux cas, la liquidité n'est pas garantie. Un horizon de 8 à 10 ans est recommandé quel que soit le mode de détention. Il est déconseillé d'investir en SCPI si un besoin de liquidité est prévisible à court ou moyen terme.",
      ],
    },
    {
      id: 'impact-transmission',
      title: 'Impact sur la transmission',
      level: 'h2',
      type: 'normal',
      content: [
        "La transmission est l'un des critères les plus différenciants entre les deux modes de détention.",
        "En direct : le décès entraîne la transmission des parts aux héritiers dans le cadre de la succession. Les parts sont soumises aux droits de mutation, avec des abattements selon le lien de parenté (100 000 € pour un enfant, 15 932 € pour un frère/sœur, etc.). Au-delà, les droits peuvent atteindre 45 % pour la tranche la plus élevée.",
        "Via assurance-vie : le capital transmis bénéficie d'un cadre fiscal spécifique très avantageux. Les sommes versées avant 70 ans bénéficient d'un abattement de 152 500 € par bénéficiaire désigné. Au-delà, un prélèvement de 20 % s'applique jusqu'à 700 000 €, puis 31,25 % au-delà. Les sommes versées après 70 ans bénéficient d'un abattement global de 30 500 € sur l'ensemble des bénéficiaires.",
        "Pour un objectif de transmission patrimoniale, l'assurance-vie est généralement beaucoup plus avantageuse, sous réserve de respecter les plafonds et les conditions liées à l'âge lors des versements.",
      ],
    },
    {
      id: 'impact-choix-scpi',
      title: 'Impact sur le choix des SCPI disponibles',
      level: 'h2',
      type: 'normal',
      content: [
        'Le choix des SCPI est l\'un des critères pratiques les plus importants dans la comparaison.',
        'En direct, toutes les SCPI du marché sont accessibles : SCPI de rendement diversifiées, SCPI spécialisées (bureaux, santé, logistique), SCPI fiscales (déficit foncier, Malraux), SCPI européennes. L\'investisseur peut construire un portefeuille sur mesure en sélectionnant les véhicules les plus adaptés à ses objectifs.',
        "Via assurance-vie, le choix est limité aux SCPI éligibles au contrat. Chaque assureur négocie une sélection de SCPI avec les sociétés de gestion. L'investisseur ne peut investir que dans cette sélection. Certains contrats proposent une large gamme (50 à 80 SCPI), d'autres se limitent à une dizaine.",
        'Points d\'attention :',
        "- Vérifier la diversité des SCPI proposées dans le contrat (secteurs, pays, capitalisations).",
        "- Certaines SCPI de qualité (bonne capitalisation, TOF élevé, diversification solide) peuvent ne pas être accessibles via l'assurance-vie.",
        "- Les conditions de changement de support (arbitrage) varient selon les contrats : certains sont gratuits, d'autres facturés.",
      ],
    },
    {
      id: 'frais-quote-part',
      title: 'Frais et quote-part de loyers reversée',
      level: 'h2',
      type: 'normal',
      content: [
        "L'un des points les moins visibles mais les plus importants dans la comparaison est la quote-part de loyers reversée par l'assureur.",
        "En direct, les frais se limitent à ceux de la SCPI : frais de souscription (8 à 12 %), frais de gestion (8 à 12 % des loyers). L'investisseur perçoit l'intégralité des loyers nets de ces frais.",
        "Via assurance-vie, des frais supplémentaires s'ajoutent :",
        "- Frais d'entrée du contrat : 0 à 5 % selon les contrats.",
        "- Frais de gestion des unités de compte : 0,5 à 1 % par an.",
        "- Quote-part de loyers prélevée par l'assureur : l'assureur peut conserver une fraction des loyers (estimée entre 5 et 15 %) avant de les capitaliser dans le contrat. Cela signifie que le rendement brut des SCPI est réduit avant même la capitalisation.",
        "Conséquence : un TD de 6 % en direct peut se traduire par une quote-part reversée de 5,1 à 5,4 % seulement via assurance-vie. Sur 10 ans, cette différence peut représenter plusieurs milliers d'euros sur un investissement conséquent.",
        "Il est essentiel de comparer non seulement le rendement affiché, mais aussi le rendement net après tous frais et quote-part, pour chaque option.",
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : simulation sur 10 ans',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous compare un investissement de 100 000 € dans une SCPI affichant un TD brut de 6 %, selon le mode de détention (direct vs assurance-vie). Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement.',
      ],
      table: {
        headers: ['Critère', 'SCPI en direct', 'SCPI via assurance-vie'],
        rows: [
          ['Capital investi', '100 000 €', '100 000 €'],
          ["Frais d'entrée estimés", '10 000 € (10 %)', '3 000 € (3 %) + frais UC'],
          ['Capital net investi', '90 000 €', '97 000 €'],
          ['TD brut annuel', '6,0 %', '6,0 % brut, quote-part reversée ~5,4 %'],
          ['Revenu annuel brut', '~5 400 € (sur 90 000 € nets investis)', '~5 238 € capitalisés (sur 97 000 € nets)'],
          ['Fiscalité annuelle (TMI 30 %)', 'IR + PS = 47,2 % = ~2 549 €', 'Aucune (capitalisation)'],
          ['Revenu net annuel perçu', '~2 851 €', '0 € (capitalisé dans le contrat)'],
          ['Revenus nets cumulés sur 10 ans', '~28 510 €', '0 € perçus, capital dans le contrat'],
          ['Valeur du capital après 10 ans', '90 000 € + 28 510 € = ~118 510 €', '97 000 € + ~52 380 € = ~149 380 €'],
          ['Fiscalité en sortie (rachat après 8 ans)', 'IR + PS sur plus-values', 'Abattement annuel, puis 7,5 % + PS'],
          ['Rendement net estimé après 10 ans', 'Variable selon fiscalité de revente', 'Variable selon abattement disponible'],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans le choix entre SCPI en direct et assurance-vie',
      level: 'h2',
      type: 'list',
      content: ['Plusieurs erreurs reviennent régulièrement lors de la comparaison entre les deux modes de détention :'],
      listItems: [
        "Croire que l'assurance-vie exonère totalement d'impôt : l'abattement annuel est limité (4 600 € / 9 200 €) et les prélèvements sociaux (17,2 %) restent dus sur la totalité des gains.",
        "Négliger les frais de l'assurance-vie : frais d'entrée, frais de gestion des UC, quote-part prélevée par l'assureur.",
        'Choisir l\'assurance-vie uniquement pour la fiscalité sans vérifier la quote-part de loyers reversée.',
        'Investir en direct sans anticiper la fiscalité, qui peut diviser le rendement par deux pour une TMI élevée.',
        "Ne pas vérifier la qualité ni la diversité des SCPI proposées dans le contrat d'assurance-vie.",
        "Oublier que la liquidité en assurance-vie dépend de l'assureur et du marché secondaire des SCPI.",
        "Choisir la détention directe sans prendre en compte les droits de succession, potentiellement élevés.",
        'Investir sans analyser la cohérence avec le patrimoine global et les objectifs personnels.',
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour comparer les options',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour choisir entre SCPI en direct et via assurance-vie, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 étapes. Aucune recommandation n\'est formulée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation fiscale', description: "TMI, prélèvements sociaux, IFI : chaque élément influence l'avantage relatif de chaque mode de détention." },
        { title: 'Définition de l\'horizon', description: "L'horizon conditionne la pertinence de l'assurance-vie (optimale après 8 ans) ou de la détention directe." },
        { title: 'Évaluation des objectifs patrimoniaux', description: 'Revenus immédiats, capitalisation, transmission : chaque objectif oriente le choix vers un mode de détention spécifique.' },
        { title: 'Comparaison des offres disponibles', description: 'Analyse des SCPI accessibles et des contrats d\'assurance-vie : frais, quote-part, qualité des supports, diversité, liquidité.' },
        { title: 'Simulation personnalisée et arbitrage', description: 'Calcul précis du rendement net estimé selon la situation (fiscalité, frais, horizon), formalisation et déclaration d\'adéquation le cas échéant.' },
      ],
    },
  ],
  faq: [
    { question: 'Quelle différence entre SCPI en direct et via assurance-vie ?', answer: "En direct, vous achetez des parts de SCPI directement. Via assurance-vie, les parts sont logées dans un contrat d'assurance-vie en unités de compte. Chaque mode a des implications différentes en termes de frais, fiscalité, liquidité et succession." },
    { question: 'Quel mode de détention est le plus avantageux fiscalement ?', answer: "Cela dépend de la TMI et de l'horizon. Pour une TMI de 30 % ou plus, l'assurance-vie offre un avantage fiscal significatif. Pour une TMI faible, la détention directe peut être plus adaptée, notamment pour des revenus immédiats." },
    { question: 'Peut-on investir dans toutes les SCPI via assurance-vie ?', answer: 'Non, seules les SCPI éligibles aux contrats d\'assurance-vie sont accessibles. Le choix est plus large en direct, avec accès à toutes les SCPI du marché.' },
    { question: "L'assurance-vie exonère-t-elle totalement d'impôt les plus-values après 8 ans ?", answer: "Non. Après 8 ans, un abattement annuel s'applique (4 600 € pour une personne seule, 9 200 € pour un couple). Au-delà, les gains sont imposés à 7,5 % (ou au barème). Les prélèvements sociaux (17,2 %) restent dus sur la totalité des gains." },
    { question: 'La détention directe est-elle toujours moins avantageuse pour la transmission ?', answer: "Généralement, l'assurance-vie offre un cadre successoral plus avantageux que la détention directe, mais le choix dépend des montants, de l'âge au moment du versement et de la situation familiale." },
    { question: 'Quels sont les frais supplémentaires en assurance-vie ?', answer: "Frais d'entrée du contrat (0 à 5 %), frais de gestion annuels des UC (0,5 à 1 %), et la quote-part de loyers prélevée par l'assureur (estimée entre 5 et 15 % des loyers)." },
    { question: 'Peut-on sortir facilement d\'une SCPI en assurance-vie ?', answer: "Le rachat du contrat dépend des conditions de l'assureur. L'assureur peut vendre les parts de SCPI sur le marché secondaire, ce qui peut prendre du temps. La liquidité n'est pas garantie." },
    { question: 'Faut-il privilégier un mode de détention selon sa TMI ?', answer: "Pour une TMI élevée (30 % ou plus), l'assurance-vie est souvent plus avantageuse grâce à la capitalisation et à l'abattement. Pour une TMI faible, la détention directe peut être pertinente." },
    { question: 'Peut-on diversifier entre direct et assurance-vie ?', answer: 'Oui, il est possible d\'investir à la fois en direct et via assurance-vie pour combiner les avantages des deux modes. Une analyse globale est recommandée.' },
    { question: 'Une recommandation peut-elle être faite sans analyse préalable ?', answer: 'Non. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse de la situation, du profil investisseur, des objectifs, de l\'horizon et de la capacité de perte.' },
  ],
  ctaTitle: 'Vous hésitez entre SCPI en direct et assurance-vie ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation et de comparer les options adaptées à vos objectifs patrimoniaux.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité', position: 'inline' },
  ],
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
