import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'scpi-fiscalite',
  category: 'scpi',
  title: 'SCPI et fiscalité : comprendre l\'impact fiscal avant d\'investir',
  metaTitle: 'SCPI et fiscalité : comprendre l\'impact fiscal avant d\'investir',
  metaDescription: 'La fiscalité des SCPI dépend du mode de détention, de la TMI, des prélèvements sociaux, des revenus étrangers, de l\'assurance-vie, du démembrement ou d\'une SCI. Analyse des points à vérifier avant une souscription.',
  canonical: 'https://eric-bellaiche.fr/articles/scpi-fiscalite/',
  badge: 'Fiscalité SCPI &bull; Analyse CGP-CIF &bull; ORIAS 13001580',
  intro: 'Investir en SCPI sans analyser préalablement l\'impact fiscal peut réduire significativement le rendement net attendu. Selon la tranche marginale d\'imposition (TMI), le mode de détention et la situation personnelle, un même taux de distribution peut produire des résultats nets très différents. Par exemple, un TD brut de 6 % peut se traduire par un rendement net de 2,5 % pour un contribuable à 41 % de TMI, ou de 5 % pour un non-imposable. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous aide à comprendre les implications fiscales avant toute souscription.',
  shortAnswer: 'La fiscalité des SCPI dépend de plusieurs facteurs : le mode de détention (direct, assurance-vie, crédit, démembrement, SCI), la TMI de l\'investisseur (0 %, 11 %, 30 %, 41 % ou 45 %), les prélèvements sociaux (17,2 %), l\'IFI, et le type de SCPI (française, européenne, fiscale). Le rendement net de fiscalité peut être significativement inférieur au taux de distribution affiché. Par exemple, pour un investisseur à 30 % de TMI détenant une SCPI en direct, le taux d\'imposition combiné est de 47,2 %. Une analyse personnalisée est indispensable avant toute souscription.',
  summaryItems: [
    { label: 'Pourquoi la fiscalité peut changer fortement le rendement net', anchor: 'pourquoi-fiscalite-change-rendement' },
    { label: 'SCPI en direct : revenus fonciers, TMI, prélèvements sociaux', anchor: 'scpi-direct-revenus-fonciers' },
    { label: 'SCPI européennes : conventions fiscales et vigilance', anchor: 'scpi-europeennes' },
    { label: 'SCPI en assurance-vie : fiscalité différée et abattement', anchor: 'scpi-assurance-vie' },
    { label: 'SCPI à crédit : intérêts d\'emprunt et fiscalité', anchor: 'scpi-credit' },
    { label: 'SCPI en démembrement : fiscalité pendant la période', anchor: 'scpi-demembrement' },
    { label: 'SCPI via SCI à l\'IR ou à l\'IS', anchor: 'scpi-sci' },
    { label: 'SCPI fiscales : déficit foncier, Malraux, Pinel', anchor: 'scpi-fiscales' },
    { label: 'Tableau comparatif des modes de détention', anchor: 'tableau-comparatif' },
    { label: 'Exemple pédagogique : impact de la TMI sur le rendement net', anchor: 'exemple-pedagogique' },
    { label: 'Erreurs fréquentes en matière de fiscalité SCPI', anchor: 'erreurs-frequentes' },
    { label: 'Méthode Eric Bellaiche pour analyser la fiscalité SCPI', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 18,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'fiscalité', 'impôt sur le revenu', 'TMI', 'prélèvements sociaux', 'assurance-vie', 'démembrement', 'SCI', 'CGP-CIF', 'IFI'],
  sections: [
    {
      id: 'pourquoi-fiscalite-change-rendement',
      title: 'Pourquoi la fiscalité peut changer fortement le rendement net d\'une SCPI',
      level: 'h2',
      type: 'normal',
      content: [
        'Le taux de distribution (TD) est le premier indicateur mis en avant par les sociétés de gestion. Pourtant, ce chiffre ne tient pas compte de la situation fiscale personnelle de l\'investisseur. Un TD de 6 % brut peut se transformer en 3,5 % net après impôt pour un contribuable soumis à une TMI de 30 %, ou en 2,5 % pour une TMI de 41 %. L\'écart est considérable et peut modifier la pertinence même de l\'investissement.',
        'La fiscalité applicable dépend de plusieurs paramètres cumulatifs qui doivent être analysés ensemble :',
        "- la nature des revenus distribués (revenus fonciers, plus-values, revenus étrangers) ;",
        '- la TMI de l\'investisseur (0 %, 11 %, 30 %, 41 % ou 45 %) ;',
        "- les prélèvements sociaux (17,2 %) qui s'appliquent systématiquement ;",
        "- l'IFI, si le patrimoine immobilier total dépasse 1,3 million d'euros ;",
        '- le mode de détention (direct, assurance-vie, crédit, démembrement, SCI) ;',
        "- l'origine géographique des actifs (France, Union européenne, hors UE) ;",
        '- le type de SCPI (de rendement, fiscale, européenne).',
        'Ces paramètres peuvent faire varier le rendement net de manière considérable. Un même investissement peut être intéressant pour un non-imposable et peu rentable pour un contribuable à forte TMI. D\'où l\'importance d\'une analyse préalable structurée avant toute souscription.',
      ],
    },
    {
      id: 'scpi-direct-revenus-fonciers',
      title: 'SCPI en direct : revenus fonciers, TMI et prélèvements sociaux',
      level: 'h2',
      type: 'normal',
      content: [
        "Les revenus distribués par les SCPI détenues en direct sont imposés dans la catégorie des revenus fonciers. Ils s'ajoutent aux autres revenus du foyer fiscal et sont soumis au barème progressif de l'impôt sur le revenu (TMI). Cela signifie que le taux d'imposition effectif dépend de l'ensemble des revenus du foyer.",
        "En pratique, le calcul est le suivant : le montant des revenus perçus est ajouté au revenu global imposable. Le taux d'imposition effectif dépend de la tranche dans laquelle se situe le foyer. À cela s'ajoutent les prélèvements sociaux au taux de 17,2 %, qui sont prélevés directement par l'établissement payeur ou déclarés par l'investisseur.",
        "Exemple concret : pour un investisseur dont la TMI est de 30 %, le taux d'imposition combiné sur les revenus SCPI est de 47,2 % (30 % + 17,2 %) avant prise en compte d'éventuels abattements ou frais déductibles. Cela signifie que sur 1 000 € de revenus SCPI perçus, l'investisseur conserve environ 528 € après impôt.",
        "Il est important de noter que les frais de gestion prélevés par la société de gestion (généralement 8 à 12 % des loyers encaissés) sont déjà déduits avant distribution. En revanche, les intérêts d'emprunt contracté pour acquérir les parts sont déductibles des revenus fonciers, ce qui peut réduire, voire annuler, l'impôt dû pendant la durée du crédit.",
        "En matière de plus-values, la cession de parts de SCPI en direct est soumise au régime des plus-values immobilières : 19 % d'impôt sur le revenu, auxquels s'ajoutent 17,2 % de prélèvements sociaux, soit un taux total de 36,2 %. Des abattements pour durée de détention s'appliquent (6 % par an de la 6e à la 21e année pour l'IR, 1,65 % par an pour les PS).",
      ],
    },
    {
      id: 'scpi-europeennes',
      title: 'SCPI européennes : conventions fiscales et vigilance pays par pays',
      level: 'h2',
      type: 'normal',
      content: [
        "Les SCPI dites européennes (ou diversifiées) investissent dans plusieurs pays de l'Union européenne. Chaque pays applique ses propres règles fiscales sur les loyers perçus localement. Des conventions fiscales bilatérales existent entre la France et chaque État pour éviter la double imposition.",
        "Le mécanisme est le suivant : les loyers perçus dans un pays étranger sont soumis à l'impôt local (souvent une retenue à la source, qui peut varier de 0 % à 30 % selon les pays). L'investisseur peut ensuite bénéficier d'un crédit d'impôt en France pour éviter d'être imposé deux fois sur les mêmes revenus.",
        "Points de vigilance importants :",
        "- Le taux effectif d'imposition varie selon les pays : certains prélèvent 0 % (Pays-Bas sous conditions), d'autres jusqu'à 30 % (Allemagne, Espagne).",
        "- Le crédit d'impôt est limité à l'impôt français correspondant : si l'impôt local est plus élevé que l'impôt français, la différence n'est pas remboursée.",
        "- Tous les pays européens n'offrent pas la même transparence fiscale ni la même fiabilité dans l'application des conventions.",
        "- La complexité déclarative augmente avec le nombre de pays d'investissement : chaque pays nécessite une déclaration spécifique.",
        'Les SCPI européennes ne sont pas automatiquement plus avantageuses d\'un point de vue fiscal. L\'impact dépend des conventions fiscales applicables, de la répartition des actifs entre pays et de la situation personnelle du contribuable.',
      ],
    },
    {
      id: 'scpi-assurance-vie',
      title: 'SCPI en assurance-vie : fiscalité différée et abattement après 8 ans',
      level: 'h2',
      type: 'normal',
      content: [
        "Lorsque des parts de SCPI sont détenues en unités de compte dans un contrat d'assurance-vie, le régime fiscal applicable est celui de l'assurance-vie, et non celui des revenus fonciers. Cette différence est fondamentale.",
        'Pendant la phase d\'épargne, les revenus des SCPI sont capitalisés dans le contrat, sans imposition immédiate. La fiscalité intervient uniquement au moment du rachat, uniquement sur les gains (plus-values).',
        "En cas de rachat après 8 ans de détention, les gains bénéficient d'un abattement annuel sur l'impôt sur le revenu : 4 600 € pour une personne seule, 9 200 € pour un couple. Au-delà de cet abattement, les gains sont imposés au taux forfaitaire de 7,5 % (ou au barème progressif sur option). Les prélèvements sociaux (17,2 %) restent dus sur la totalité des gains, sans abattement.",
        "Attention : l'avantage fiscal n'est pas une exonération totale mais un abattement annuel sur les gains dans certaines limites. Pour un célibataire disposant de 50 000 € de gains lors d'un rachat après 8 ans, seuls 4 600 € seront exonérés d'IR ; les 45 400 € restants seront imposés à 7,5 %.",
        "Points d'attention supplémentaires :",
        "- Toutes les SCPI ne sont pas éligibles aux contrats d'assurance-vie : seules celles sélectionnées par l'assureur sont accessibles.",
        "- Des frais supplémentaires s'ajoutent (frais d'entrée du contrat, frais de gestion des UC).",
        "- La quote-part de loyers reversée par la SCPI au contrat peut être réduite par rapport à une détention directe, en raison des frais prélevés par l'assureur.",
        "- L'avantage fiscal de l'assurance-vie doit être mis en balance avec ces frais et cette quote-part réduite.",
      ],
    },
    {
      id: 'scpi-credit',
      title: 'SCPI à crédit : intérêts d\'emprunt et fiscalité',
      level: 'h2',
      type: 'normal',
      content: [
        "L'acquisition de parts de SCPI à crédit permet de déduire les intérêts d'emprunt des revenus fonciers perçus. Cette déduction peut réduire, voire annuler, l'impôt sur les revenus SCPI pendant la durée du crédit, améliorant ainsi le rendement net de l'opération.",
        "L'effet de levier peut être intéressant si le taux d'emprunt est inférieur au taux de distribution net de fiscalité. Par exemple, avec un crédit à 3 % et un TD net estimé à 4 %, l'écart positif de 1 % vient améliorer le rendement du capital investi. En revanche, cet effet de levier amplifie également le risque en cas de baisse des distributions ou de hausse des taux.",
        "Points de vigilance :",
        "- L'assurance emprunteur obligatoire s'ajoute au coût total du crédit et peut représenter une part significative du coût global.",
        "- Le remboursement du capital de l'emprunt n'est pas déductible : seuls les intérêts le sont.",
        "- À l'issue du crédit, l'ensemble des revenus redevient imposable sans déduction d'intérêts.",
        "- Un crédit immobilier classique peut ne pas être compatible avec l'achat de parts de SCPI. Il est recommandé de vérifier l'affectation du prêt auprès de la banque.",
        "- En cas de baisse des distributions, le crédit reste dû, ce qui peut créer une tension de trésorerie.",
      ],
    },
    {
      id: 'scpi-demembrement',
      title: 'SCPI en démembrement : fiscalité pendant la période de nue-propriété',
      level: 'h2',
      type: 'normal',
      content: [
        "Le démembrement de parts de SCPI consiste à séparer la nue-propriété (détenue par l'investisseur) de l'usufruit (détenu par une autre personne, souvent un investisseur institutionnel). Pendant la période de démembrement, les revenus sont perçus par l'usufruitier. Le nu-propriétaire ne perçoit pas de revenus et n'est donc pas imposé.",
        "À l'issue du démembrement (généralement 10 à 15 ans), le nu-propriétaire récupère la pleine propriété sans fiscalité sur la reconstitution de la valeur. Ce mécanisme peut être intéressant dans une logique de transmission ou d'optimisation fiscale à long terme, notamment pour des investisseurs souhaitant se constituer un patrimoine sans fiscalité immédiate.",
        'Points d\'attention :',
        "- Pendant le démembrement, le nu-propriétaire ne bénéficie d'aucun revenu : ce mécanisme n'est pas adapté aux objectifs de revenus immédiats.",
        "- Le démembrement n'est pas adapté aux profils recherchant des revenus réguliers et immédiats.",
        "- La durée du démembrement (10 à 15 ans) doit être cohérente avec l'horizon de placement de l'investisseur.",
        "- Le prix d'acquisition en nue-propriété est inférieur au prix de la pleine propriété (généralement 60 à 80 % selon la durée), ce qui réduit l'investissement initial.",
      ],
    },
    {
      id: 'scpi-sci',
      title: 'SCPI via SCI à l\'IR ou à l\'IS',
      level: 'h2',
      type: 'normal',
      content: [
        'Les parts de SCPI peuvent être détenues via une société civile immobilière (SCI) soumise à l\'impôt sur le revenu (IR) ou à l\'impôt sur les sociétés (IS). Chaque régime a des implications fiscales distinctes qui doivent être analysées en fonction de la situation.',
        "SCI à l'IR : les revenus remontent directement chez les associés, imposés dans la catégorie des revenus fonciers, au même titre qu'une détention directe. L'intérêt principal est la gestion collective au sein d'une famille ou d'un groupe d'associés, avec une transmission facilitée des parts sociales.",
        "SCI à l'IS : la société est imposée sur ses bénéfices au taux de l'IS (15 % jusqu'à 42 000 € de bénéfice, puis 25 %). Les associés ne sont imposés que sur les dividendes distribués. Ce régime peut être intéressant pour des investisseurs souhaitant réinvestir les bénéfices sans fiscalité immédiate. En revanche, les plus-values de cession des parts sont imposées à l'IS, puis une nouvelle fois à l'IR lors de la distribution, créant une double imposition potentielle.",
        'Points d\'attention :',
        "- Une SCI à l'IS ne permet pas de déduire les déficits fonciers du revenu global des associés.",
        "- La création d'une SCI uniquement pour détenir des SCPI peut ne pas être justifiée sur le plan économique (frais de structure, comptabilité, fiscalité).",
        "- Les frais de structure (comptabilité, frais juridiques, fiscalité) réduisent le rendement net et doivent être mis en balance avec les avantages escomptés.",
      ],
    },
    {
      id: 'scpi-fiscales',
      title: 'SCPI fiscales : déficit foncier, Malraux, Pinel',
      level: 'h2',
      type: 'normal',
      content: [
        "Certaines SCPI sont spécifiquement conçues pour offrir des avantages fiscaux, en contrepartie de contraintes et de risques spécifiques.",
        "Les SCPI de déficit foncier : elles investissent dans des biens immobiliers nécessitant des travaux, générant un déficit foncier imputable sur le revenu global (dans la limite de 10 700 € par an). Au-delà, le déficit est imputable sur les revenus fonciers des années suivantes. L'objectif est de réduire l'impôt sur le revenu tout en constituant un patrimoine.",
        "Les SCPI Malraux : elles permettent une réduction d'impôt en contrepartie de travaux de restauration sur des immeubles situés dans des secteurs protégés. Le taux de réduction varie selon la localisation du bien (22 % dans les sites patrimoniaux remarquables, 30 % dans les quartiers anciens dégradés). La réduction est plafonnée à 100 000 € ou 400 000 € de travaux selon le dispositif.",
        "Les SCPI Pinel : elles ouvrent droit à une réduction d'impôt en contrepartie d'un investissement locatif dans le neuf. Le dispositif a été prolongé jusqu'en 2024 mais ses conditions et ses taux de réduction évoluent. La réduction dépend de la durée d'engagement (12, 15 ou 18 ans).",
        "Points de vigilance communs aux SCPI fiscales :",
        "- L'avantage fiscal est encadré par des plafonds et des conditions strictes (respect des engagements, des plafonds de loyer et de ressources).",
        "- La durée de détention est généralement longue (9 à 15 ans minimum).",
        "- Le rendement locatif des SCPI fiscales est souvent inférieur à celui des SCPI de rendement classiques.",
        "- En cas de non-respect des conditions (location, plafonds, durée), l'avantage fiscal peut être remis en cause avec des pénalités.",
        "- Les SCPI fiscales ne sont pas adaptées à tous les profils : elles s'adressent principalement aux contribuables fortement imposés avec un horizon long terme.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif des modes de détention',
      level: 'h2',
      type: 'table',
      content: [
        'Le tableau ci-dessous compare les principaux modes de détention de parts de SCPI sur le plan fiscal, patrimonial et pratique.',
      ],
      table: {
        headers: ['Mode de détention', 'Fiscalité des revenus', 'Fiscalité des plus-values', 'Avantage principal', 'Limite principale', 'Profil type'],
        rows: [
          ['Direct', 'IR (TMI + PS 17,2 %) en revenus fonciers', 'IR + PS sur plus-values immobilières', 'Choix large de SCPI, simplicité', 'Fiscalité élevée selon TMI', 'Investisseur cherchant la simplicité et le choix'],
          ['Assurance-vie', 'Capitalisation : fiscalité différée', 'Abattement annuel après 8 ans (4 600/9 200 €)', 'Fiscalité allégée long terme', 'Choix limité de SCPI, quote-part réduite', 'Objectif transmission ou long terme'],
          ['Crédit', 'Intérêts déductibles des revenus fonciers', 'Idem direct + imposition de la plus-value', 'Effet de levier potentiel', 'Risque amplifié, coût du crédit', 'TMI élevée + capacité d\'endettement'],
          ['Démembrement', 'Pas de revenus (perçus par usufruitier)', 'Pas d\'imposition à la réunification', 'Optimisation transmission', 'Absence de revenus pendant la période', 'Transmission patrimoniale'],
          ['SCI IR', 'IR (TMI + PS) via transparence fiscale', 'IR + PS chez les associés', 'Gestion collective et transmission', 'Complexité juridique, frais de structure', 'Famille ou groupe d\'associés'],
          ['SCI IS', 'IS (15-25 %) sur bénéfices', 'IS puis IR sur dividendes', 'Réinvestissement des bénéfices', 'Double imposition possible', 'Vision long terme avec réinvestissement'],
        ],
      },
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : impact de la TMI sur le rendement net',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous illustre l\'impact de la TMI sur le rendement net d\'une SCPI détenue en direct, pour un taux de distribution brut de 6 %. Les chiffres sont donnés à titre pédagogique et ne constituent en aucun cas une promesse de rendement. Le calcul ne tient pas compte des frais de souscription ni du délai de jouissance, qui réduiraient davantage le rendement effectif.',
      ],
      table: {
        headers: ['Profil', 'TMI', 'Prélèvements sociaux', 'Taux d\'imposition total', 'Rendement brut', 'Rendement net estimé'],
        rows: [
          ['Non imposable', '0 %', '17,2 %', '17,2 %', '6,0 %', '~4,97 %'],
          ['TMI modérée', '11 %', '17,2 %', '28,2 %', '6,0 %', '~4,31 %'],
          ['TMI moyenne', '30 %', '17,2 %', '47,2 %', '6,0 %', '~3,17 %'],
          ['TMI élevée', '41 %', '17,2 %', '58,2 %', '6,0 %', '~2,51 %'],
          ['TMI très élevée', '45 %', '17,2 %', '62,2 %', '6,0 %', '~2,27 %'],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes en matière de fiscalité SCPI',
      level: 'h2',
      type: 'list',
      content: ['L\'expérience montre que plusieurs erreurs reviennent régulièrement chez les investisseurs débutants comme plus expérimentés :'],
      listItems: [
        'Regarder uniquement le rendement brut sans calculer l\'impact fiscal personnel.',
        'Oublier les prélèvements sociaux de 17,2 % qui s\'appliquent quels que soient les revenus.',
        'Négliger sa TMI : un même TD peut produire des résultats très différents selon la tranche d\'imposition (de 2,27 % à 4,97 % net).',
        'Confondre SCPI européennes et absence totale d\'impôt : la fiscalité dépend des conventions bilatérales et n\'est jamais nulle.',
        "Choisir l'assurance-vie sans regarder les frais supplémentaires et la quote-part de loyers reversée, qui peut être inférieure à celle d'une détention directe.",
        "Créer une SCI uniquement pour détenir des SCPI sans évaluer les coûts de structure et la complexité administrative.",
        'Investir dans une SCPI fiscale sans vérifier sa compatibilité avec la situation globale et les plafonds applicables.',
        'Souscrire à crédit sans simuler l\'impact d\'une hausse des taux ou d\'une baisse des distributions.',
        'Ne pas vérifier si les SCPI sont soumises à l\'IFI et comment elles doivent être déclarées.',
        "Oublier la déclaration fiscale spécifique aux revenus étrangers pour les SCPI diversifiées, qui peut être complexe.",
        'Investir sans avoir simulé le rendement net de fiscalité pour sa propre situation.',
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour analyser la fiscalité SCPI',
      level: 'h2',
      type: 'method-steps',
      content: [
        "L'analyse de la fiscalité d'un projet SCPI suit une méthode structurée en 6 étapes, dans le respect du cadre réglementaire des CGP-CIF. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable complète de la situation du client.",
      ],
      methodSteps: [
        { title: 'Recueil de la situation fiscale', description: "Analyse complète de la TMI, des prélèvements sociaux, de l'IFI, des revenus, du patrimoine existant et des déficits éventuels." },
        { title: 'Définition des objectifs patrimoniaux', description: "Revenus complémentaires, capitalisation, optimisation fiscale, transmission. Chaque objectif oriente le choix du mode de détention et du type de SCPI." },
        { title: 'Analyse des modes de détention possibles', description: "Comparaison détaillée de l'impact fiscal selon que les SCPI sont détenues en direct, via assurance-vie, à crédit, en démembrement ou via une SCI." },
        { title: 'Simulation du rendement net de fiscalité', description: "Calcul précis du rendement estimé après prise en compte de l'impôt sur le revenu, des prélèvements sociaux, des frais et de l'IFI éventuel." },
        { title: 'Vérification de la cohérence avec le profil investisseur', description: "Adéquation avec les connaissances, l'expérience en investissement immobilier, la capacité de perte et l'horizon de placement." },
        { title: 'Formalisation et documentation', description: "Déclaration d'adéquation formelle si une recommandation est formulée, documentation complète des analyses, suivi périodique et actualisation." },
      ],
    },
  ],
  faq: [
    { question: 'Comment sont imposés les revenus des SCPI détenues en direct ?', answer: "Les revenus des SCPI en direct sont imposés dans la catégorie des revenus fonciers, soumis au barème progressif de l'impôt sur le revenu (TMI) et aux prélèvements sociaux de 17,2 %. Le taux combiné varie de 17,2 % à 62,2 % selon la TMI." },
    { question: 'Les SCPI européennes sont-elles fiscalement intéressantes ?', answer: "Les SCPI européennes peuvent offrir des opportunités, mais leur fiscalité dépend des conventions fiscales entre la France et chaque pays d'investissement. Elles ne sont pas automatiquement plus avantageuses que les SCPI françaises." },
    { question: "Quel est l'avantage fiscal des SCPI en assurance-vie ?", answer: "Dans un contrat d'assurance-vie, les revenus sont capitalisés sans imposition immédiate. Lors du rachat après 8 ans, les gains bénéficient d'un abattement annuel sur l'impôt (4 600 € pour une personne seule, 9 200 € pour un couple), au-delà duquel ils sont imposés à 7,5 % (hors prélèvements sociaux)." },
    { question: "Peut-on déduire les intérêts d'emprunt pour l'achat de parts de SCPI ?", answer: "Oui, les intérêts d'emprunt sont déductibles des revenus fonciers générés par les SCPI détenues en direct ou via une SCI à l'IR. Cette déduction peut réduire, voire annuler, l'impôt dû pendant la durée du crédit." },
    { question: "Le démembrement de SCPI est-il fiscalement avantageux ?", answer: "Pendant le démembrement, le nu-propriétaire ne perçoit pas de revenus et n'est pas imposé. À l'issue, la réunification de la pleine propriété n'entraîne pas d'imposition. Le démembrement peut être intéressant dans une optique de transmission." },
    { question: 'Quelle différence entre une SCI à l\'IR et une SCI à l\'IS pour détenir des SCPI ?', answer: "La SCI à l'IR est transparente fiscalement : les revenus remontent chez les associés (revenus fonciers). La SCI à l'IS est imposée sur ses bénéfices (15-25 %), et seuls les dividendes distribués sont imposés chez les associés. Chaque régime a des implications différentes." },
    { question: "Qu'est-ce qu'une SCPI de déficit foncier ?", answer: "Une SCPI de déficit foncier investit dans des biens nécessitant des travaux, générant un déficit imputable sur le revenu global (limité à 10 700 € par an). Elle vise à réduire l'impôt tout en constituant un patrimoine." },
    { question: "Les SCPI sont-elles soumises à l'IFI ?", answer: "Les parts de SCPI détenues en direct sont incluses dans le patrimoine immobilier pour le calcul de l'IFI. Le mode de détention influence le traitement : en assurance-vie, les parts ne sont généralement pas soumises à l'IFI." },
    { question: "Faut-il déclarer les revenus de SCPI européennes différemment ?", answer: "Oui, les revenus perçus par l'intermédiaire de SCPI investissant à l'étranger peuvent nécessiter des déclarations spécifiques et l'application de crédits d'impôt selon les conventions fiscales bilatérales." },
    { question: "Un conseil fiscal personnalisé est-il obligatoire avant d'investir en SCPI ?", answer: "Il est fortement recommandé. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, analyse systématiquement la situation fiscale et patrimoniale avant toute recommandation. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète." },
  ],
  ctaTitle: "Vous souhaitez analyser l'impact fiscal d'un projet SCPI ?",
  ctaText: "Un échange permet d'évaluer votre situation fiscale et patrimoniale avant toute souscription. Eric Bellaiche, CGP-CIF, vous accompagne dans l'analyse de votre projet.",
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
    { href: '/articles/scpi-assurance-vie-ou-direct/', label: 'SCPI en direct ou via assurance-vie', position: 'inline' },
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne', position: 'inline' },
  ],
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
