import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'scpi-demembrement',
  category: 'scpi',
  title: "SCPI en démembrement : nue-propriété, usufruit et stratégie patrimoniale",
  metaTitle: "SCPI en démembrement : nue-propriété, usufruit et stratégie patrimoniale",
  metaDescription: "Investir en SCPI via le démembrement de propriété (nue-propriété / usufruit) permet d'optimiser la transmission et la fiscalité. Analyse complète du mécanisme, des avantages et des points de vigilance par Eric Bellaiche, CGP-CIF ORIAS 13001580.",
  canonical: 'https://eric-bellaiche.fr/articles/scpi-demembrement/',
  badge: "SCPI &bull; Démembrement &bull; CGP-CIF &bull; ORIAS 13001580",
  intro: "Le démembrement de propriété est une technique juridique qui consiste à séparer la nue-propriété de l'usufruit d'un bien. Appliqué aux SCPI, ce mécanisme permet à un investisseur d'acquérir des parts à un prix réduit (généralement 60 à 80 % de la valeur en pleine propriété) tout en différant la perception des revenus et en optimisant la transmission. Cette stratégie patrimoniale séduit de plus en plus d'investisseurs, mais elle comporte des spécificités et des contraintes qu'il convient de maîtriser avant de s'engager. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous guide dans la compréhension du démembrement de SCPI et de ses applications patrimoniales.",
  shortAnswer: "Le démembrement de parts de SCPI consiste à séparer la nue-propriété (détenue par l'investisseur) de l'usufruit (détenu par un tiers, souvent un investisseur institutionnel). Pendant la période de démembrement (généralement 10 à 15 ans), les revenus locatifs sont perçus par l'usufruitier, tandis que le nu-propriétaire ne perçoit aucun revenu et n'est donc pas imposé. À l'issue du démembrement, le nu-propriétaire récupère automatiquement la pleine propriété des parts, sans fiscalité sur cette reconstitution de valeur. L'acquisition en nue-propriété se fait à un prix réduit (par exemple 65 % de la valeur en pleine propriété pour un démembrement de 15 ans). Ce mécanisme est particulièrement intéressant pour les investisseurs souhaitant se constituer un patrimoine à long terme sans fiscalité immédiate, ou pour optimiser la transmission de leur patrimoine. Il peut également être combiné avec un crédit pour financer l'acquisition.",
  summaryItems: [
    { label: "Qu'est-ce que le démembrement de propriété appliqué aux SCPI ?", anchor: 'definition-demembrement' },
    { label: "Les différents types de démembrement : temporaire, viager, successoral", anchor: 'types-demembrement' },
    { label: "Pourquoi investir en SCPI en démembrement ?", anchor: 'pourquoi-demembrement' },
    { label: "Fiscalité de la SCPI en démembrement", anchor: 'fiscalite-demembrement' },
    { label: "Quel prix d'acquisition en nue-propriété de SCPI ?", anchor: 'prix-acquisition' },
    { label: "Le démembrement comme outil de transmission patrimoniale", anchor: 'transmission-demembrement' },
    { label: "SCPI en démembrement et crédit : est-ce compatible ?", anchor: 'demembrement-credit' },
    { label: "Tableau comparatif : pleine propriété vs démembrement", anchor: 'tableau-comparatif' },
    { label: "Exemple pédagogique : acquisition en nue-propriété sur 15 ans", anchor: 'exemple-pedagogique' },
    { label: "Risques et points de vigilance du démembrement", anchor: 'points-vigilance' },
    { label: "Erreurs fréquentes dans l'investissement en SCPI démembrée", anchor: 'erreurs-frequentes' },
    { label: "Méthode Eric Bellaiche pour analyser un projet de SCPI en démembrement", anchor: 'methode' },
    { label: "Questions fréquentes", anchor: 'faq' },
  ],
  readingTime: 21,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'démembrement', 'nue-propriété', 'usufruit', 'transmission', 'fiscalité', 'patrimoine', 'succession', 'investissement', 'CGP-CIF'],
  sections: [
    {
      id: 'definition-demembrement',
      title: "Qu'est-ce que le démembrement de propriété appliqué aux SCPI ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Le démembrement de propriété est une technique juridique issue du droit civil français qui permet de séparer les deux attributs essentiels du droit de propriété : l'usufruit (le droit d'utiliser le bien et d'en percevoir les revenus) et la nue-propriété (le droit de disposer du bien à terme, c'est-à-dire d'en être le propriétaire sans en percevoir les fruits immédiats).",
        "Appliqué aux SCPI, le démembrement fonctionne de la manière suivante : un investisseur acquiert la nue-propriété de parts de SCPI, tandis qu'un autre investisseur (souvent un institutionnel comme une compagnie d'assurance ou un fonds de pension) acquiert l'usufruit pour une durée déterminée, généralement comprise entre 10 et 15 ans.",
        "Pendant la période de démembrement, l'usufruitier perçoit l'intégralité des revenus distribués par la SCPI (loyers). Le nu-propriétaire ne perçoit rien et n'a donc aucun revenu imposable lié à ces parts. À l'issue de la période de démembrement, la pleine propriété est reconstituée automatiquement au profit du nu-propriétaire, sans fiscalité sur cette réunification.",
        "Le prix d'acquisition en nue-propriété est inférieur à celui de la pleine propriété, car il reflète l'absence de perception des revenus pendant la durée du démembrement. La décote est fonction de la durée du démembrement et du rendement attendu de la SCPI.",
      ],
    },
    {
      id: 'types-demembrement',
      title: "Les différents types de démembrement : temporaire, viager, successoral",
      level: 'h2',
      type: 'normal',
      content: [
        "Il existe plusieurs formes de démembrement de parts de SCPI, qui répondent à des objectifs patrimoniaux distincts.",
        "Le démembrement temporaire est la forme la plus courante dans le cadre d'un investissement en SCPI. L'usufruit est accordé pour une durée déterminée (généralement 10, 15 ou 20 ans). À l'issue de cette période, la pleine propriété est automatiquement reconstituée. Ce type de démembrement est particulièrement adapté aux investisseurs qui souhaitent se constituer un patrimoine à long terme sans fiscalité immédiate, ou qui préparent leur retraite.",
        "Le démembrement viager est plus rare dans le cadre des SCPI. L'usufruit est accordé pour la durée de vie d'une personne (l'usufruitier). La pleine propriété est reconstituée au décès de l'usufruitier. Ce montage est principalement utilisé dans une logique de transmission familiale.",
        "Le démembrement successoral résulte d'une succession : lorsqu'un conjoint survivant hérite de l'usufruit d'un bien et que les enfants héritent de la nue-propriété. Ce démembrement est subi, non choisi, mais il peut être organisé en amont via des donations de parts de SCPI avec réserve d'usufruit.",
        "Dans le cadre d'un investissement en SCPI, le démembrement temporaire est le plus fréquent car il offre une vision claire de l'horizon de placement et des conditions financières.",
      ],
    },
    {
      id: 'pourquoi-demembrement',
      title: "Pourquoi investir en SCPI en démembrement ?",
      level: 'h2',
      type: 'normal',
      content: [
        "L'investissement en SCPI en démembrement présente plusieurs avantages stratégiques qui peuvent correspondre à différents profils d'investisseurs.",
        "Le premier avantage est l'absence de fiscalité pendant la période de démembrement. Le nu-propriétaire ne percevant pas de revenus, il n'est pas imposé au titre des loyers distribués. Cela peut être particulièrement intéressant pour les contribuables fortement imposés qui souhaitent différer leur imposition à une période où leur TMI sera potentiellement plus faible (par exemple après la retraite).",
        "Le deuxième avantage est le prix d'acquisition réduit. En acquérant la nue-propriété, l'investisseur bénéficie d'une décote sur le prix de souscription. Cette décote, qui peut atteindre 30 à 40 % pour un démembrement de 15 ans, permet d'acquérir un patrimoine plus important pour un même montant investi.",
        "Le troisième avantage est la reconstitution automatique de la pleine propriété sans fiscalité. À l'issue du démembrement, le nu-propriétaire redevient plein propriétaire sans avoir à payer d'impôt sur la valeur reconstituée. Ce mécanisme est fiscalement neutre.",
        "Le quatrième avantage est la simplicité de gestion. Contrairement à un bien immobilier physique dont le démembrement implique des questions d'entretien, de réparations et de gestion locative, le démembrement de parts de SCPI est géré par la société de gestion, sans contrainte pour le nu-propriétaire.",
        "Enfin, le démembrement de SCPI peut constituer un outil efficace de transmission patrimoniale, comme nous le verrons dans une section dédiée.",
      ],
    },
    {
      id: 'fiscalite-demembrement',
      title: "Fiscalité de la SCPI en démembrement",
      level: 'h2',
      type: 'normal',
      content: [
        "La fiscalité du démembrement de parts de SCPI est l'un de ses principaux attraits. Pendant la période de démembrement, le nu-propriétaire ne perçoit aucun revenu et n'est donc soumis à aucune imposition sur les loyers distribués par la SCPI. Cette absence d'imposition est totale : ni impôt sur le revenu, ni prélèvements sociaux, ni IFI sur les parts démembrées.",
        "L'usufruitier, quant à lui, perçoit les loyers et est imposé sur ces revenus selon son régime fiscal propre. Si l'usufruitier est une personne morale (compagnie d'assurance, fonds), la fiscalité s'applique au niveau de cette entité.",
        "À l'issue du démembrement, la réunification de la pleine propriété est fiscalement neutre. Le nu-propriétaire redevient plein propriétaire sans avoir à payer d'impôt sur la différence entre la valeur de la pleine propriété reconstituée et le prix d'acquisition de la nue-propriété. Cette absence de fiscalité à la sortie est un avantage considérable par rapport à d'autres placements.",
        "En matière d'IFI, les parts de SCPI détenues en nue-propriété sont généralement considérées comme faisant partie du patrimoine immobilier du nu-propriétaire pour leur valeur en pleine propriété, ce qui peut avoir un impact si le patrimoine total dépasse 1,3 million d'euros.",
        "En cas de cession des parts avant la fin du démembrement, la plus-value est calculée sur la différence entre le prix de cession et le prix d'acquisition de la nue-propriété. La fiscalité applicable est celle des plus-values immobilières (19 % + 17,2 % de prélèvements sociaux), avec les abattements pour durée de détention.",
      ],
    },
    {
      id: 'prix-acquisition',
      title: "Quel prix d'acquisition en nue-propriété de SCPI ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Le prix d'acquisition en nue-propriété est déterminé en fonction de la valeur en pleine propriété des parts, diminuée de la valeur de l'usufruit. Cette décote est calculée selon un barème fiscal (article 669 du Code général des impôts) qui tient compte de la durée du démembrement ou de l'âge de l'usufruitier.",
        "Pour un démembrement temporaire, la valeur de l'usufruit est calculée en fonction de la durée : 23 % de la valeur en pleine propriété pour 10 ans, 31 % pour 15 ans, 38 % pour 20 ans. En pratique, la décote sur le prix de la nue-propriété est donc d'autant plus importante que la durée du démembrement est longue.",
        "Pour un démembrement viager, la valeur de l'usufruit dépend de l'âge de l'usufruitier : plus l'usufruitier est âgé, moins l'usufruit a de valeur (car sa durée probable est plus courte). Par exemple, pour un usufruitier de 50 ans, l'usufruit est évalué à 50 % de la valeur en pleine propriété ; pour un usufruitier de 80 ans, il est évalué à 20 %.",
        "En pratique, pour une SCPI dont la valeur de souscription est de 1 000 € par part en pleine propriété, le prix d'acquisition en nue-propriété pour un démembrement de 15 ans sera d'environ 650 à 700 € par part. Cette décote de 30 à 35 % reflète les loyers qui seront perçus par l'usufruitier pendant 15 ans.",
        "À l'issue du démembrement, la valeur des parts peut avoir évolué, et le nu-propriétaire récupère des parts dont la valeur peut être supérieure ou inférieure à celle de la pleine propriété au moment de l'acquisition.",
      ],
    },
    {
      id: 'transmission-demembrement',
      title: "Le démembrement comme outil de transmission patrimoniale",
      level: 'h2',
      type: 'normal',
      content: [
        "Le démembrement de parts de SCPI est un outil particulièrement efficace dans une stratégie de transmission patrimoniale. En donnant la nue-propriété de parts de SCPI à ses enfants tout en conservant l'usufruit, le donateur peut transmettre son patrimoine tout en continuant à percevoir les revenus.",
        "Le mécanisme est le suivant : un parent achète des parts de SCPI en pleine propriété, puis donne la nue-propriété à ses enfants tout en conservant l'usufruit. Les droits de donation sont calculés sur la valeur de la nue-propriété uniquement (qui est inférieure à la valeur en pleine propriété), ce qui réduit l'assiette taxable.",
        "Au décès du donateur (usufruitier), les enfants récupèrent automatiquement la pleine propriété sans droits de succession supplémentaires sur la part d'usufruit qui s'éteint. Ce mécanisme permet de transmettre un patrimoine immobilier à moindre coût fiscal.",
        "Une autre stratégie consiste à acquérir directement des parts en nue-propriété pour le compte de ses enfants, avec un démembrement temporaire. À l'issue du démembrement, les enfants récupèrent la pleine propriété des parts, sans fiscalité sur cette reconstitution. Cette approche est particulièrement adaptée pour préparer la transmission à long terme.",
        "Points d'attention dans le cadre d'une transmission :",
        "- L'abusus (droit de disposer du bien) appartient au nu-propriétaire : les enfants peuvent vendre leurs parts avec l'accord de l'usufruitier.",
        "- En cas de donation avec réserve d'usufruit, le donateur reste imposable sur les revenus des parts (sauf option pour l'imposition du donataire).",
        "- Les droits de donation bénéficient d'abattements (100 000 € par parent et par enfant tous les 15 ans) qui peuvent réduire significativement le coût de la transmission.",
        "- Eric Bellaiche, CGP-CIF, recommande une analyse préalable complète avant d'engager une stratégie de transmission via le démembrement de SCPI.",
      ],
    },
    {
      id: 'demembrement-credit',
      title: "SCPI en démembrement et crédit : est-ce compatible ?",
      level: 'h2',
      type: 'normal',
      content: [
        "La question de la compatibilité entre le démembrement et le crédit se pose fréquemment. En théorie, il est possible d'acquérir des parts de SCPI en nue-propriété à crédit, mais cette configuration présente des spécificités qu'il convient d'analyser.",
        "La difficulté principale réside dans l'absence de revenus pendant la période de démembrement. Le nu-propriétaire ne percevant pas de loyers, il ne peut pas utiliser les revenus de la SCPI pour rembourser le crédit. Le remboursement doit donc être assuré par d'autres revenus (salaires, autres revenus fonciers, épargne).",
        "Certaines banques peuvent être réticentes à financer une acquisition en nue-propriété sans revenus associés. En revanche, pour les profils disposant de revenus suffisants, ce montage peut être intéressant car l'absence de fiscalité pendant la période de démembrement améliore la capacité de remboursement.",
        "L'acquisition en nue-propriété à crédit peut être pertinente dans les cas suivants :",
        "- L'investisseur dispose de revenus suffisants pour rembourser le crédit sans avoir besoin des loyers.",
        "- L'objectif est de se constituer un patrimoine à long terme avec un effet de levier, sans contrainte de revenus immédiats.",
        "- L'investisseur souhaite bénéficier de la décote sur le prix d'acquisition tout en étalant le paiement via le crédit.",
        "Il est recommandé de vérifier auprès de sa banque la compatibilité du financement avec une acquisition en nue-propriété avant de s'engager.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: "Tableau comparatif : pleine propriété vs démembrement",
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous compare l'investissement en SCPI en pleine propriété et en nue-propriété (démembrement temporaire de 15 ans). Les chiffres sont donnés à titre indicatif et ne constituent pas une promesse de rendement.",
      ],
      table: {
        headers: ['Critère', 'Pleine propriété', 'Nue-propriété (démembrement 15 ans)'],
        rows: [
          ['Investissement', '100 000 €', '~65 000 € (décote ~35 %)'],
          ['Revenus pendant la période', 'Perçus immédiatement (loyers)', 'Aucun revenu (perçu par usufruitier)'],
          ['Fiscalité pendant la période', 'IR + PS sur les loyers perçus', 'Aucune (pas de revenus)'],
          ['À l\'issue des 15 ans', 'Parts conservées, loyers inchangés', 'Pleine propriété reconstituée sans fiscalité'],
          ['Valeur des parts à terme', 'Valeur en pleine propriété', 'Valeur en pleine propriété (identique)'],
          ['Objectif principal', 'Revenus immédiats', 'Constitution patrimoine long terme / transmission'],
          ['Liquidité', 'Revente possible avec fiscalité', 'Revente possible (plus-values immobilières)'],
          ['Crédit possible', 'Oui, avec loyers pour rembourser', 'Oui, sans loyers (autres revenus nécessaires)'],
        ],
      },
    },
    {
      id: 'exemple-pedagogique',
      title: "Exemple pédagogique : acquisition en nue-propriété sur 15 ans",
      level: 'h2',
      type: 'table',
      content: [
        "Prenons l'exemple d'un investisseur de 50 ans, TMI à 41 %, qui souhaite acquérir des parts de SCPI en nue-propriété pour préparer sa retraite. Cet exemple est donné à titre purement pédagogique et ne constitue en aucun cas une promesse de rendement.",
      ],
      table: {
        headers: ['Poste', 'Pleine propriété', 'Nue-propriété (15 ans)'],
        rows: [
          ['Valeur des parts acquises', '100 000 €', '100 000 € (en équivalent PP)'],
          ['Capital investi', '100 000 €', '65 000 € (décote 35 %)'],
          ['Économie sur l\'investissement', '0 €', '35 000 €'],
          ['Revenus annuels perçus', '5 500 € (TD 5,5 %)', '0 €'],
          ['Impôt annuel (TMI 41 % + PS 17,2 %)', '~3 201 € (58,2 % de 5 500 €)', '0 €'],
          ['Revenu net annuel', '~2 299 €', '0 €'],
          ['Revenus nets cumulés sur 15 ans', '~34 485 €', '0 €'],
          ['À l\'issue des 15 ans', 'Parts valant 100 000 €', 'Pleine propriété, parts valant 100 000 €'],
          ['Patrimoine total après 15 ans (hors revalo)', '~134 485 €', '100 000 € (parts) + 35 000 € (économie) = 135 000 €'],
          ['Avantage clé', 'Revenus immédiats', 'Absence de fiscalité + décote à l\'entrée'],
        ],
      },
    },
    {
      id: 'points-vigilance',
      title: "Risques et points de vigilance du démembrement",
      level: 'h2',
      type: 'risk',
      content: [
        "L'investissement en SCPI en démembrement comporte des risques et des contraintes spécifiques qui doivent être identifiés avant toute souscription.",
        "Absence de revenus pendant la durée du démembrement : c'est la contrainte principale. Pendant 10 à 15 ans, le nu-propriétaire ne perçoit aucun revenu des parts. Ce mécanisme n'est pas adapté aux investisseurs recherchant des revenus complémentaires immédiats.",
        "Risque de performance : à l'issue du démembrement, la valeur de reconstitution des parts dépend de la performance de la SCPI. Si la valeur des parts a baissé, le nu-propriétaire récupère des parts d'une valeur inférieure à l'investissement initial.",
        "Risque de liquidité : en cas de besoin de trésorerie pendant la durée du démembrement, la revente de parts en nue-propriété peut être difficile. Le marché secondaire des parts démembrées est moins liquide que celui des parts en pleine propriété.",
        "Risque de changement de législation : une modification des règles fiscales applicables au démembrement (barème de l'usufruit, traitement fiscal de la réunification, IFI) peut modifier l'équilibre économique de l'opération.",
        "Points de vigilance spécifiques :",
        "- La durée du démembrement (10 à 15 ans) doit être compatible avec l'horizon de placement et l'âge de l'investisseur.",
        "- La qualité de la SCPI et de sa société de gestion est déterminante : une SCPI avec un mauvais historique de distribution ou une gestion hasardeuse présente un risque accru.",
        "- Les frais de souscription (8 à 12 %) sont prélevés sur le montant de la souscription en nue-propriété, ce qui réduit la décote effective.",
        "- Certaines offres de démembrement sur le marché peuvent comporter des conditions particulières (usufruitier imposant des contraintes) qui réduisent l'attractivité du montage.",
        "- En cas de décès du nu-propriétaire pendant la période de démembrement, la transmission des parts à ses héritiers peut être complexe.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: "Erreurs fréquentes dans l'investissement en SCPI démembrée",
      level: 'h2',
      type: 'list',
      content: [
        "L'expérience montre que plusieurs erreurs sont commises par les investisseurs qui se tournent vers le démembrement de SCPI sans analyse préalable suffisante :",
      ],
      listItems: [
        "Confondre décote et réduction de prix : la décote sur la nue-propriété n'est pas une réduction mais la contrepartie de l'absence de revenus pendant la durée du démembrement.",
        "Investir en démembrement sans horizon long terme : un démembrement de 10 à 15 ans n'est pas compatible avec un objectif de placement à court terme.",
        "Négliger la qualité de la SCPI sous prétexte que l'on n'en perçoit pas les revenus immédiats : la performance future des parts dépend de la qualité de la SCPI et de sa gestion.",
        "Oublier que les frais de souscription (8-12 %) réduisent la décote effective et doivent être intégrés dans le calcul de rentabilité.",
        "Ne pas anticiper le traitement IFI des parts démembrées, qui peut impacter la situation patrimoniale globale.",
        "Choisir un démembrement trop long (20 ans) sans être certain de pouvoir conserver les parts jusqu'à son terme.",
        "Investir sans avoir simulé la valeur de reconstitution potentielle à l'issue du démembrement, en intégrant les hypothèses de revalorisation et de distribution.",
        "Ne pas vérifier les conditions de sortie anticipée : frais de cession, délais de revente sur le marché secondaire, fiscalité applicable.",
        "Investir en démembrement pour des objectifs de revenus immédiats : c'est une contradiction fondamentale avec le mécanisme.",
        "S'engager sans avoir consulté un CGP-CIF comme Eric Bellaiche, inscrit ORIAS n°13001580, pour valider la cohérence du projet avec sa situation personnelle et ses objectifs patrimoniaux.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour analyser un projet de SCPI en démembrement",
      level: 'h2',
      type: 'method-steps',
      content: [
        "L'analyse d'un projet d'investissement en SCPI en démembrement suit une méthode structurée en 6 étapes, dans le respect du cadre réglementaire des CGP-CIF. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable complète de la situation du client.",
      ],
      methodSteps: [
        { title: "Analyse de la situation patrimoniale et des objectifs", description: "Recueil complet de la situation personnelle, professionnelle, fiscale et patrimoniale. Identification des objectifs : constitution de patrimoine, préparation retraite, transmission, optimisation fiscale." },
        { title: "Vérification de l'adéquation du démembrement au profil", description: "Le démembrement implique une absence de revenus pendant 10 à 15 ans. Il est impératif de vérifier que cette contrainte est compatible avec la situation financière et les objectifs de l'investisseur." },
        { title: "Analyse des offres de démembrement disponibles", description: "Comparaison des conditions proposées par les différentes sociétés de gestion : durée du démembrement, décote appliquée, qualité de l'usufruitier, frais de souscription, historique de la SCPI." },
        { title: "Simulation financière et fiscale", description: "Calcul de la valeur de reconstitution estimée à l'issue du démembrement, intégration de la fiscalité (IFI, plus-values en cas de cession anticipée), comparaison avec un investissement en pleine propriété." },
        { title: "Analyse des scénarios de sortie", description: "Évaluation des conditions de sortie anticipée, des délais de cession, des frais applicables et de l'impact fiscal d'une revente avant le terme du démembrement." },
        { title: "Formalisation et suivi périodique", description: "Si une recommandation est formulée, établissement d'une déclaration d'adéquation, documentation des analyses et mise en place d'un suivi annuel pour vérifier la bonne exécution du projet." },
      ],
    },
    {
      id: 'demembrement-usufruitier',
      title: "Qui est l'usufruitier dans le cadre d'une SCPI démembrée ?",
      level: 'h3',
      type: 'normal',
      content: [
        "Dans le cadre d'une offre de démembrement de SCPI, l'usufruitier est généralement un investisseur institutionnel : compagnie d'assurance, fonds de pension, mutuelle ou caisse de retraite. Ces acteurs recherchent des revenus réguliers et prévisibles sur une durée déterminée, ce qui correspond aux loyers distribués par les SCPI.",
        "La présence d'un usufruitier institutionnel présente des avantages pour le nu-propriétaire : elle garantit la stabilité du montage et évite les complications liées à un usufruitier personne physique (décès, changement de situation, conflit).",
        "Il est important de noter que l'usufruitier n'intervient pas dans la gestion de la SCPI, qui reste assurée par la société de gestion. Les relations entre nu-propriétaire et usufruitier sont régies par le contrat de démembrement, qui précise les droits et obligations de chaque partie.",
        "Dans le cadre d'une transmission familiale, l'usufruitier peut être un membre de la famille (conjoint, parent). Dans ce cas, le montage est généralement organisé via une donation avec réserve d'usufruit.",
      ],
    },
  ],
  faq: [
    { question: "Qu'est-ce que le démembrement de parts de SCPI ?", answer: "Le démembrement consiste à séparer la nue-propriété (le droit de disposer du bien à terme) de l'usufruit (le droit de percevoir les revenus). Pendant la période de démembrement, l'usufruitier perçoit les loyers, le nu-propriétaire ne perçoit rien. À l'issue, la pleine propriété est reconstituée automatiquement." },
    { question: "Quel est l'avantage fiscal du démembrement de SCPI ?", answer: "Le nu-propriétaire n'est pas imposé pendant la période de démembrement (pas de revenus). À l'issue, la réunification de la pleine propriété est fiscalement neutre. Cet avantage est particulièrement intéressant pour les contribuables fortement imposés." },
    { question: "Quelle décote pour l'achat en nue-propriété de SCPI ?", answer: "La décote dépend de la durée du démembrement. Pour 10 ans : environ 23 % de décote. Pour 15 ans : environ 31 à 35 %. Pour 20 ans : environ 38 %. Le prix d'acquisition est d'autant plus réduit que la durée est longue." },
    { question: "Puis-je revendre mes parts de SCPI avant la fin du démembrement ?", answer: "Oui, la revente est possible sur le marché secondaire. La plus-value est calculée sur la différence entre le prix de cession et le prix d'acquisition de la nue-propriété. La fiscalité applicable est celle des plus-values immobilières." },
    { question: "Le démembrement de SCPI est-il adapté à la préparation de la retraite ?", answer: "Oui, c'est l'une des utilisations les plus courantes. Un investisseur de 50-55 ans acquiert des parts en nue-propriété pour 10-15 ans. À l'issue, à l'âge de la retraite, il récupère la pleine propriété et perçoit les loyers pour compléter ses revenus." },
    { question: "Peut-on acheter des SCPI en démembrement à crédit ?", answer: "Oui, c'est possible mais plus contraignant car aucun revenu locatif ne vient rembourser le crédit. Le remboursement doit être assuré par d'autres revenus. Certaines banques peuvent être réticentes à financer ce type d'acquisition." },
    { question: "Quels sont les risques du démembrement de SCPI ?", answer: "Les principaux risques sont : absence de revenus pendant la période, risque de baisse de la valeur des parts, liquidité réduite, changement de législation fiscale, et risque de défaillance de l'usufruitier (rare pour les institutionnels)." },
    { question: "Le démembrement est-il intéressant pour la transmission ?", answer: "Oui, c'est un outil efficace. En donnant la nue-propriété à ses enfants tout en conservant l'usufruit, on réduit l'assiette des droits de donation (calculés sur la nue-propriété seulement). Au décès, les enfants récupèrent la pleine propriété sans droits supplémentaires." },
    { question: "Quelle différence entre démembrement temporaire et viager ?", answer: "Le démembrement temporaire a une durée fixe (10, 15 ou 20 ans). Le démembrement viager dure jusqu'au décès de l'usufruitier. Le temporaire est plus adapté à un investissement structuré avec un horizon connu." },
    { question: "Les frais de souscription s'appliquent-ils sur la nue-propriété ?", answer: "Oui, les frais de souscription (8 à 12 %) sont prélevés sur le montant de la souscription en nue-propriété. Ils réduisent la décote effective et doivent être intégrés dans le calcul de rentabilité." },
    { question: "Comment sont traités les parts de SCPI en démembrement pour l'IFI ?", answer: "Les parts de SCPI détenues en nue-propriété sont généralement incluses dans le patrimoine immobilier du nu-propriétaire pour leur valeur en pleine propriété. Il est recommandé de vérifier le traitement applicable avec un conseil." },
    { question: "Un CGP-CIF est-il recommandé pour un investissement en SCPI démembrée ?", answer: "Oui, fortement recommandé. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, analyse la cohérence du démembrement avec votre situation personnelle, vos objectifs et votre horizon de placement avant toute souscription." },
  ],
  ctaTitle: "Vous souhaitez étudier un projet de SCPI en démembrement ?",
  ctaText: "Un échange permet d'évaluer si le démembrement est adapté à votre situation patrimoniale et à vos objectifs. Eric Bellaiche, CGP-CIF, vous accompagne dans l'analyse de votre projet.",
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité : impact fiscal avant d\'investir', position: 'inline' },
    { href: '/articles/scpi-succession-transmission/', label: 'SCPI et succession : transmission et fiscalité', position: 'inline' },
    { href: '/articles/scpi-revenus-complementaires/', label: 'SCPI pour revenus complémentaires', position: 'inline' },
  ],
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
