import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'scpi-succession-transmission',
  category: 'scpi',
  title: "SCPI et succession : transmission, fiscalité et modes de détention",
  metaTitle: "SCPI et succession : transmission, fiscalité et modes de détention",
  metaDescription: "Transmettre des parts de SCPI dans le cadre d'une succession : droits de succession, donation, démembrement, assurance-vie. Guide complet des stratégies de transmission patrimoniale par Eric Bellaiche, CGP-CIF ORIAS 13001580.",
  canonical: 'https://eric-bellaiche.fr/articles/scpi-succession-transmission/',
  badge: "SCPI &bull; Succession &bull; CGP-CIF &bull; ORIAS 13001580",
  intro: "La transmission du patrimoine est une préoccupation majeure pour de nombreux investisseurs en SCPI. Les parts de SCPI, comme tout actif immobilier, sont intégrées dans le patrimoine successoral et peuvent être soumises aux droits de succession. Selon le mode de détention choisi (direct, assurance-vie, démembrement, SCI), la fiscalité applicable à la transmission peut varier considérablement. Une stratégie de transmission bien conçue permet de réduire significativement le coût fiscal tout en assurant une transmission efficace à ses héritiers. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous guide dans la compréhension des mécanismes de transmission des parts de SCPI et des stratégies d'optimisation.",
  shortAnswer: "Les parts de SCPI sont transmises selon les règles du droit successoral français, avec un abattement de 100 000 € par parent et par enfant (renouvelable tous les 15 ans) et un barème progressif des droits de donation allant de 5 % à 45 %. Le mode de détention influence fortement la fiscalité de transmission : en direct, les parts sont intégrées dans l'actif successoral et soumises aux droits de succession ; en assurance-vie, les capitaux transmis bénéficient d'une fiscalité allégée (abattement de 152 500 € par bénéficiaire) ; en démembrement, la donation de la nue-propriété seule réduit l'assiette taxable (la valeur de l'usufruit étant déterminée selon l'âge du donateur). La donation anticipée des parts avec réserve d'usufruit est l'une des stratégies les plus efficaces pour transmettre son patrimoine en SCPI à moindre coût fiscal. En l'absence d'anticipation, les droits de succession peuvent atteindre 45 % pour les tranches les plus élevées.",
  summaryItems: [
    { label: "Comment sont transmises les parts de SCPI en cas de succession ?", anchor: 'transmission-successorale' },
    { label: "Fiscalité des droits de succession sur les parts de SCPI", anchor: 'droits-succession' },
    { label: "La donation de parts de SCPI : abattements et barème", anchor: 'donation-scpi' },
    { label: "Donation avec réserve d'usufruit : une stratégie efficace", anchor: 'donation-reserve-usufruit' },
    { label: "SCPI en assurance-vie : transmission allégée", anchor: 'assurance-vie-transmission' },
    { label: "Transmission via une SCI détenant des SCPI", anchor: 'sci-transmission' },
    { label: "Le démembrement comme outil de transmission", anchor: 'demembrement-transmission' },
    { label: "Tableau comparatif des modes de transmission", anchor: 'tableau-comparatif' },
    { label: "Exemple pédagogique : transmission de 200 000 € de parts de SCPI", anchor: 'exemple-pedagogique' },
    { label: "Risques et points de vigilance pour la transmission de SCPI", anchor: 'points-vigilance' },
    { label: "Erreurs fréquentes dans la transmission de SCPI", anchor: 'erreurs-frequentes' },
    { label: "Méthode Eric Bellaiche pour optimiser la transmission de SCPI", anchor: 'methode' },
    { label: "Questions fréquentes", anchor: 'faq' },
  ],
  readingTime: 22,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'succession', 'transmission', 'fiscalité', 'démembrement', 'donation', 'assurance-vie', 'droits de succession', 'SCI', 'CGP-CIF'],
  sections: [
    {
      id: 'transmission-successorale',
      title: "Comment sont transmises les parts de SCPI en cas de succession ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Les parts de SCPI détenues en direct font partie de l'actif successoral du défunt, au même titre que les autres biens immobiliers. Elles sont donc intégrées dans la masse successorale et soumises aux droits de succession selon les règles en vigueur.",
        "La valeur retenue pour le calcul des droits est la valeur vénale des parts au jour du décès, c'est-à-dire le prix de retrait (valeur de part hors frais de souscription). Cette valeur est généralement inférieure au prix de souscription, ce qui peut réduire légèrement l'assiette taxable.",
        "Les héritiers reçoivent les parts de SCPI dans le cadre du partage successoral. Ils peuvent choisir de les conserver (et percevoir les loyers correspondants) ou de les vendre pour répartir le produit de la vente. En cas de vente, la plus-value est calculée à partir de la valeur au jour du décès (effet de purge de la plus-value).",
        "Pour les couples mariés ou pacsés, le conjoint survivant bénéficie d'une exonération totale de droits de succession (depuis la loi TEPA de 2007). Il peut donc hériter des parts de SCPI sans aucun droit à payer.",
        "Pour les enfants et autres héritiers, des abattements et un barème progressif s'appliquent. Il est essentiel d'anticiper cette fiscalité pour éviter que les héritiers ne soient contraints de vendre les parts pour payer les droits.",
      ],
    },
    {
      id: 'droits-succession',
      title: "Fiscalité des droits de succession sur les parts de SCPI",
      level: 'h2',
      type: 'normal',
      content: [
        "La fiscalité applicable à la transmission de parts de SCPI par succession suit le barème général des droits de succession. Ce barème est progressif et varie selon le lien de parenté avec le défunt.",
        "Pour les enfants (en ligne directe) :",
        "- Abattement de 100 000 € par enfant sur la part lui revenant.",
        "- Barème progressif après abattement : 5 % jusqu'à 8 072 €, 10 % jusqu'à 12 109 €, 15 % jusqu'à 15 932 €, 20 % jusqu'à 552 324 €, 30 % jusqu'à 902 838 €, 40 % jusqu'à 1 805 677 €, 45 % au-delà.",
        "Pour le conjoint survivant : exonération totale de droits de succession depuis 2007.",
        "Pour les frères et sœurs : abattement de 15 932 €, puis taux de 35 % jusqu'à 24 430 € et 45 % au-delà.",
        "Pour les neveux et nièces : abattement de 7 967 €, puis taux de 55 %.",
        "Pour les autres héritiers (non-parents) : abattement de 1 594 €, puis taux de 60 %.",
        "En l'absence d'anticipation, les droits de succession peuvent donc représenter une charge significative. Par exemple, pour un patrimoine en SCPI de 300 000 € transmis à un enfant unique, les droits de succession seront calculés sur 200 000 € (300 000 € - 100 000 € d'abattement), soit environ 33 000 € de droits à payer.",
        "Ces chiffres montrent l'importance d'anticiper la transmission pour réduire le coût fiscal et éviter de contraindre les héritiers à vendre les parts.",
      ],
    },
    {
      id: 'donation-scpi',
      title: "La donation de parts de SCPI : abattements et barème",
      level: 'h2',
      type: 'normal',
      content: [
        "La donation de parts de SCPI de son vivant est l'une des stratégies les plus efficaces pour organiser sa transmission à moindre coût fiscal. Elle permet de bénéficier des abattements en vigueur et de figer la valeur des parts au jour de la donation.",
        "Les abattements applicables aux donations sont les mêmes qu'aux successions : 100 000 € par parent et par enfant, renouvelables tous les 15 ans. Cela signifie qu'un couple peut transmettre jusqu'à 200 000 € à chaque enfant sans droits de donation, tous les 15 ans.",
        "Au-delà de l'abattement, le barème des droits de donation est identique à celui des droits de succession (de 5 % à 45 % selon le montant et le lien de parenté).",
        "Des abattements supplémentaires existent pour les donations consenties avant 80 ans (donation aux enfants : abattement de 100 000 €) et avant 70 ans pour les donations aux petits-enfants (abattement de 31 865 € par petit-enfant).",
        "La donation de parts de SCPI peut être faite en pleine propriété ou en nue-propriété (avec réserve d'usufruit). Dans ce second cas, seul le montant de la nue-propriété est soumis aux droits de donation, ce qui réduit encore l'assiette taxable.",
        "Points d'attention pour une donation de parts de SCPI :",
        "- La donation doit être faite par acte notarié pour être valable et opposable.",
        "- Les frais de notaire (environ 1,5 à 2 % de la valeur donnée) s'ajoutent aux éventuels droits de donation.",
        "- La donation peut être organisée de manière progressive (dons de parts sur plusieurs années) pour optimiser les abattements.",
        "- Un CGP-CIF comme Eric Bellaiche peut vous aider à structurer votre stratégie de donation.",
      ],
    },
    {
      id: 'donation-reserve-usufruit',
      title: "Donation avec réserve d'usufruit : une stratégie efficace",
      level: 'h2',
      type: 'normal',
      content: [
        "La donation avec réserve d'usufruit est l'une des stratégies les plus utilisées pour transmettre des parts de SCPI à moindre coût fiscal. Le donateur conserve l'usufruit des parts (et donc les revenus) tandis que les enfants reçoivent la nue-propriété.",
        "Le mécanisme est le suivant : le parent donateur donne la nue-propriété des parts de SCPI à ses enfants, tout en conservant l'usufruit (le droit de percevoir les loyers). Les droits de donation sont calculés sur la seule valeur de la nue-propriété, qui est inférieure à la valeur en pleine propriété.",
        "La valeur de l'usufruit est déterminée selon un barème fiscal (article 669 du Code général des impôts) basé sur l'âge du donateur :",
        "- Moins de 21 ans : usufruit = 90 % de la valeur, nue-propriété = 10 %.",
        "- 21 à 30 ans : usufruit = 80 %, nue-propriété = 20 %.",
        "- 31 à 40 ans : usufruit = 70 %, nue-propriété = 30 %.",
        "- 41 à 50 ans : usufruit = 60 %, nue-propriété = 40 %.",
        "- 51 à 60 ans : usufruit = 50 %, nue-propriété = 50 %.",
        "- 61 à 70 ans : usufruit = 40 %, nue-propriété = 60 %.",
        "- 71 à 80 ans : usufruit = 30 %, nue-propriété = 70 %.",
        "- 81 à 90 ans : usufruit = 20 %, nue-propriété = 80 %.",
        "- Plus de 91 ans : usufruit = 10 %, nue-propriété = 90 %.",
        "Par exemple, pour un donateur de 60 ans donnant 200 000 € de parts de SCPI en nue-propriété, la valeur taxable est de 100 000 € (50 %). Avec l'abattement de 100 000 € par enfant, aucun droit de donation n'est dû.",
        "Au décès du donateur, l'usufruit s'éteint et les enfants récupèrent automatiquement la pleine propriété, sans droits de succession supplémentaires sur cette part.",
        "Cette stratégie est particulièrement intéressante pour les investisseurs qui n'ont pas besoin des revenus des SCPI pour vivre et qui souhaitent transmettre leur patrimoine à moindre coût.",
      ],
    },
    {
      id: 'assurance-vie-transmission',
      title: "SCPI en assurance-vie : transmission allégée",
      level: 'h2',
      type: 'normal',
      content: [
        "Lorsque des parts de SCPI sont détenues en unités de compte dans un contrat d'assurance-vie, les règles de transmission sont celles de l'assurance-vie, et non celles du droit successoral général. Cette différence est fondamentale et peut offrir des avantages fiscaux significatifs.",
        "En cas de décès du souscripteur, les capitaux transmis au bénéficiaire désigné bénéficient des règles suivantes :",
        "- Pour les versements effectués avant 70 ans : abattement de 152 500 € par bénéficiaire sur la part des gains (plus-values). Au-delà, taxation à 20 % jusqu'à 700 000 € et à 31,25 % au-delà.",
        "- Pour les versements effectués après 70 ans : abattement global de 30 500 € sur l'ensemble des bénéficiaires (tous contrats confondus), puis droits de succession selon le lien de parenté.",
        "L'avantage principal de l'assurance-vie réside dans la désignation bénéficiaire, qui permet de transmettre les capitaux en dehors du cadre successoral. Le bénéficiaire désigné (conjoint, enfant, tiers) reçoit les fonds directement, sans passer par la succession.",
        "Cet avantage est particulièrement intéressant pour :",
        "- Transmettre à un bénéficiaire non héritier (concubin, ami, association).",
        "- Transmettre à un enfant avec une fiscalité réduite (abattement de 152 500 € sur les gains).",
        "- Organiser sa transmission en complément d'une donation ou d'un testament.",
        "Points d'attention pour la transmission de SCPI en assurance-vie :",
        "- Toutes les SCPI ne sont pas éligibles aux contrats d'assurance-vie.",
        "- Les frais du contrat réduisent le rendement net par rapport à une détention directe.",
        "- La quote-part de loyers reversée peut être inférieure à celle d'une détention directe.",
        "- Il est recommandé de désigner clairement le bénéficiaire dans la clause bénéficiaire du contrat.",
      ],
    },
    {
      id: 'sci-transmission',
      title: "Transmission via une SCI détenant des SCPI",
      level: 'h2',
      type: 'normal',
      content: [
        "La détention de parts de SCPI via une société civile immobilière (SCI) offre des possibilités de transmission spécifiques, différentes de la détention directe.",
        "Dans une SCI, ce sont les parts sociales de la société qui sont transmises, et non les parts de SCPI elles-mêmes. La transmission des parts sociales est soumise au droit d'apport (droit d'enregistrement) pour les donations, et aux droits de succession pour les transmissions à titre gratuit.",
        "L'avantage principal de la SCI pour la transmission est la possibilité de donner des parts sociales à plusieurs personnes (conjoint, enfants) tout en conservant le contrôle de la gestion via la gérance. Le donateur peut rester gérant de la SCI et continuer à gérer le patrimoine immobilier.",
        "La donation de parts de SCI peut être organisée progressivement, en donnant des parts chaque année dans la limite des abattements. Cette stratégie permet d'optimiser la transmission sur plusieurs années.",
        "Points d'attention pour la transmission de SCPI via une SCI :",
        "- Les frais de structure de la SCI (comptabilité, frais juridiques) réduisent le rendement net.",
        "- La valeur des parts sociales (et donc l'assiette des droits de donation) doit être régulièrement actualisée.",
        "- La transmission de parts de SCI peut être plus complexe que la transmission directe de parts de SCPI.",
        "- En cas de donation de parts de SCI avec réserve d'usufruit, le donateur peut conserver les revenus tout en transmettant le patrimoine.",
        "- Il est recommandé de consulter un notaire et un CGP-CIF pour organiser la transmission via une SCI.",
      ],
    },
    {
      id: 'demembrement-transmission',
      title: "Le démembrement comme outil de transmission",
      level: 'h2',
      type: 'normal',
      content: [
        "Le démembrement de parts de SCPI est un outil particulièrement efficace dans une stratégie de transmission. Il permet de séparer la propriété des parts en deux composantes : l'usufruit (revenus) et la nue-propriété (capital), qui peuvent être transmises à des personnes différentes.",
        "La stratégie classique est la donation avec réserve d'usufruit, déjà évoquée, mais le démembrement peut également être utilisé de manière plus sophistiquée.",
        "Une autre stratégie consiste à acquérir directement des parts en démembrement temporaire pour le compte de ses enfants. Le parent acquiert la nue-propriété pour ses enfants, avec un démembrement temporaire de 10 à 15 ans. Pendant cette période, un investisseur institutionnel perçoit les loyers (usufruit). À l'issue, les enfants récupèrent la pleine propriété, sans fiscalité sur la reconstitution.",
        "Le démembrement croisé est une technique qui consiste à démembrer les parts entre plusieurs membres d'une famille : par exemple, le parent conserve l'usufruit, un enfant reçoit la nue-propriété d'une partie des parts, un autre enfant reçoit la nue-propriété d'une autre partie. Cette technique permet d'optimiser les abattements et de répartir le patrimoine selon les besoins de chacun.",
        "Points d'attention :",
        "- Le démembrement est un outil de transmission efficace mais qui nécessite une analyse juridique et fiscale approfondie.",
        "- Les frais de mise en place du démembrement (frais de notaire, frais de structure) doivent être intégrés dans l'analyse de rentabilité.",
        "- La situation personnelle et familiale évolue dans le temps : un démembrement mis en place aujourd'hui peut ne plus être adapté dans 10 ans.",
        "- Eric Bellaiche, CGP-CIF, recommande une analyse préalable complète avant de mettre en place une stratégie de démembrement à visée successorale.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: "Tableau comparatif des modes de transmission",
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous compare les différents modes de transmission de parts de SCPI, en fonction de leur efficacité fiscale et de leur complexité.",
      ],
      table: {
        headers: ['Mode de transmission', 'Fiscalité', 'Abattement applicable', 'Avantage principal', 'Inconvénient principal', 'Profil recommandé'],
        rows: [
          ['Succession (détention directe)', 'Barème successoral (5-45 %)', '100 000 € par enfant', 'Simplicité (aucune action préalable)', 'Droits élevés en l\'absence d\'anticipation', 'Petit patrimoine (< 100 000 € par enfant)'],
          ['Donation pleine propriété', 'Barème donation (5-45 %)', '100 000 € par enfant / 15 ans', 'Anticipation, gel de la valeur', 'Perte des revenus pour le donateur', 'Donateur n\'ayant pas besoin des revenus'],
          ['Donation avec réserve d\'usufruit', 'Sur la seule nue-propriété', '100 000 € par enfant / 15 ans', 'Transmission à coût réduit + conservation des revenus', 'Complexité juridique', 'Donateur souhaitant conserver les revenus'],
          ['Assurance-vie', 'Régime propre (abattement 152 500 €)', '152 500 € par bénéficiaire (versements avant 70 ans)', 'Fiscalité allégée + désignation libre', 'Frais du contrat, choix limité de SCPI', 'Transmission hors cadre successoral'],
          ['SCI', 'Droits d\'enregistrement + barème', '100 000 € par enfant / 15 ans', 'Gestion collective, transmission progressive', 'Frais de structure, complexité', 'Patrimoine important, famille nombreuse'],
          ['Démembrement temporaire', 'Néant (acquisition directe en NP)', 'Abattements sur donation si donation', 'Pas de fiscalité à la sortie', 'Absence de revenus pendant la période', 'Transmission programmée à long terme'],
        ],
      },
    },
    {
      id: 'exemple-pedagogique',
      title: "Exemple pédagogique : transmission de 200 000 € de parts de SCPI",
      level: 'h2',
      type: 'table',
      content: [
        "Prenons l'exemple d'un investisseur de 60 ans, veuf, qui souhaite transmettre 200 000 € de parts de SCPI à son enfant unique. Comparons les différentes stratégies possibles. Cet exemple est donné à titre purement pédagogique et ne constitue pas un conseil fiscal personnalisé.",
      ],
      table: {
        headers: ['Stratégie', 'Assiette taxable', 'Abattement', 'Montant taxable', 'Droits estimés', 'Revenus conservés par le donateur'],
        rows: [
          ["Succession (décès sans anticipation)", "200 000 €", "100 000 €", "100 000 €", "~11 500 €", "N/A (décès)"],
          ["Donation en pleine propriété (60 ans)", "200 000 €", "100 000 €", "100 000 €", "~11 500 €", "Non (plus de revenus)"],
          ["Donation avec réserve d'usufruit (60 ans, usufruit 50 %)", "100 000 € (NP = 50 %)", "100 000 €", "0 €", "0 €", "Oui (loyers conservés)"],
          ["Assurance-vie (versements avant 70 ans, bénéficiaire unique)", "Gains uniquement", "152 500 € sur gains", "0 € (si gains < 152 500 €)", "0 €", "Oui (capitalisation)"],
          ["Donation progressive (2 x 100 000 € à 15 ans d'intervalle)", "200 000 €", "2 x 100 000 €", "0 €", "0 €", "Oui si donation NP"],
        ],
      },
    },
    {
      id: 'points-vigilance',
      title: "Risques et points de vigilance pour la transmission de SCPI",
      level: 'h2',
      type: 'risk',
      content: [
        "La transmission de parts de SCPI comporte des risques et des points de vigilance qui doivent être anticipés pour éviter des conséquences fiscales ou patrimoniales défavorables.",
        "Risque de mésentente familiale : en cas de donation démembrée ou de transmission via SCI, des conflits peuvent survenir entre l'usufruitier et les nus-propriétaires, notamment sur les décisions de gestion ou de vente des parts.",
        "Risque de changement de législation : les règles fiscales applicables aux successions, donations et assurances-vie peuvent être modifiées par le législateur. Une stratégie mise en place aujourd'hui peut perdre une partie de son efficacité demain.",
        "Risque de liquidité : si les héritiers doivent payer des droits de succession et ne disposent pas de la trésorerie nécessaire, ils peuvent être contraints de vendre les parts de SCPI, parfois à des conditions défavorables.",
        "Risque de valorisation : la valeur des parts de SCPI peut fluctuer. Une donation fige la valeur au jour de l'acte, ce qui peut être avantageux ou désavantageux selon l'évolution future.",
        "Risque de dépendance : le donateur qui conserve l'usufruit dépend des loyers perçus. Si les distributions baissent, ses revenus diminuent.",
        "Points de vigilance spécifiques :",
        "- L'abus de jouissance (usufruitier qui perçoit des revenus excessifs) peut être requalifié par l'administration fiscale.",
        "- La donation de parts de SCPI doit être faite par acte notarié pour être opposable.",
        "- En cas de donation avec réserve d'usufruit, les nus-propriétaires ne peuvent pas vendre les parts sans l'accord de l'usufruitier.",
        "- L'assurance-vie doit être correctement structurée (clause bénéficiaire rédigée avec soin) pour éviter les contestations.",
        "- Il est recommandé de réviser sa stratégie de transmission tous les 5 ans ou à chaque changement significatif de situation (mariage, divorce, naissance, décès).",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: "Erreurs fréquentes dans la transmission de SCPI",
      level: 'h2',
      type: 'list',
      content: [
        "L'expérience montre que plusieurs erreurs sont commises par les investisseurs dans la transmission de leurs parts de SCPI :",
      ],
      listItems: [
        "Ne pas anticiper la transmission : attendre le décès pour transmettre expose à des droits de succession qui auraient pu être réduits par une donation anticipée.",
        "Confondre donation et succession sur le plan fiscal : les barèmes sont identiques, mais les abattements se renouvellent tous les 15 ans pour les donations, ce qui permet d'optimiser.",
        "Oublier de désigner un bénéficiaire précis dans son assurance-vie : une clause bénéficiaire mal rédigée peut entraîner des contestations et un traitement fiscal défavorable.",
        "Donner ses parts sans conserver d'usufruit si les loyers sont nécessaires à son train de vie : la donation en pleine propriété prive le donateur des revenus.",
        "Ne pas tenir compte de l'évolution des abattements : les règles fiscales évoluent, et ce qui était optimal il y a 10 ans peut ne plus l'être aujourd'hui.",
        "Transmettre des parts de SCPI à des héritiers mineurs sans organiser la gestion des parts (administration légale, tutorat).",
        "Ne pas informer ses héritiers de l'existence des parts de SCPI et de leur mode de détention : en cas de décès, des parts peuvent rester non déclarées.",
        "Sous-estimer les frais de notaire dans le cadre d'une donation : ces frais (environ 1,5 à 2 %) s'ajoutent aux éventuels droits de donation.",
        "Négliger l'aspect international : pour les héritiers résidant à l'étranger, la fiscalité peut être différente et des conventions internationales peuvent s'appliquer.",
        "Ne pas consulter de professionnels (CGP-CIF, notaire) pour organiser sa transmission : Eric Bellaiche, inscrit ORIAS n°13001580, recommande une approche pluridisciplinaire associant conseil en gestion de patrimoine et expertise notariale.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour optimiser la transmission de SCPI",
      level: 'h2',
      type: 'method-steps',
      content: [
        "L'optimisation de la transmission de parts de SCPI suit une méthode structurée en 7 étapes, dans le respect du cadre réglementaire des CGP-CIF. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable complète de la situation du client.",
      ],
      methodSteps: [
        { title: "Recueil de la situation familiale et patrimoniale", description: "Analyse complète de la composition familiale (conjoint, enfants, petits-enfants, héritiers potentiels), du patrimoine existant (SCPI, immobilier direct, financier) et des objectifs de chacun." },
        { title: "Identification des objectifs de transmission", description: "Définition des souhaits du client : à qui transmettre, sous quelle forme, avec quelle fiscalité cible, et avec quelle conservation de revenus éventuelle." },
        { title: "Analyse des modes de détention existants", description: "Vérification du mode de détention actuel des SCPI (direct, assurance-vie, SCI, démembrement) et identification des possibilités d'optimisation." },
        { title: "Proposition de stratégie de transmission", description: "Recommandation de la stratégie la plus adaptée : donation avec réserve d'usufruit, donation en pleine propriété, arbitrage vers l'assurance-vie, démembrement, ou combinaison de plusieurs solutions." },
        { title: "Simulation fiscale comparative", description: "Calcul précis des droits de donation ou de succession selon chaque stratégie, intégration des abattements disponibles, simulation de l'impact sur les revenus du donateur." },
        { title: "Mise en œuvre avec les professionnels adaptés", description: "Coordination avec le notaire pour la rédaction des actes de donation, avec l'assureur pour la mise à jour des clauses bénéficiaires, et avec le conseiller fiscal pour la déclaration." },
        { title: "Suivi et révision périodique", description: "Révision de la stratégie tous les 5 ans ou à chaque événement familial significatif (mariage, divorce, naissance, décès). Actualisation des abattements et adaptation aux évolutions législatives." },
      ],
    },
    {
      id: 'strategie-anticipation',
      title: "L'importance de l'anticipation dans la transmission de SCPI",
      level: 'h3',
      type: 'normal',
      content: [
        "L'anticipation est le maître-mot de toute stratégie de transmission de parts de SCPI. Plus la transmission est organisée tôt, plus les possibilités d'optimisation sont importantes.",
        "Une donation réalisée à 50-60 ans permet de bénéficier pleinement des abattements (100 000 € par enfant tous les 15 ans) et de la décote liée à la réserve d'usufruit (la nue-propriété à 50 ans ne représente que 40 % de la valeur des parts), tout en conservant les revenus via l'usufruit.",
        "Une donation effectuée tardivement (après 70-80 ans) limite les possibilités de réitération (l'abattement ne se renouvelle que tous les 15 ans) et réduit la décote sur la nue-propriété.",
        "Les abattements sont personnels et se renouvellent : un couple peut transmettre 200 000 € à chaque enfant tous les 15 ans, soit potentiellement 400 000 € sur 30 ans (en deux donations espacées de 15 ans), sans aucun droit de donation.",
        "L'anticipation permet également de lisser la transmission dans le temps : donner des parts progressivement, en fonction de sa capacité à se séparer des revenus, et en profitant des évolutions du marché immobilier.",
        "En conclusion, plus tôt la réflexion sur la transmission est engagée, plus les leviers d'optimisation sont nombreux et efficaces.",
      ],
    },
  ],
  faq: [
    { question: "Comment sont imposées les parts de SCPI en cas de succession ?", answer: "Les parts de SCPI sont intégrées dans l'actif successoral et soumises aux droits de succession selon le barème progressif (5 à 45 %). Le conjoint survivant est exonéré de droits. Chaque enfant bénéficie d'un abattement de 100 000 €." },
    { question: "Quel est l'avantage de la donation avec réserve d'usufruit ?", answer: "Les droits de donation sont calculés sur la seule valeur de la nue-propriété (réduite selon l'âge du donateur), ce qui permet de transmettre à moindre coût tout en conservant les revenus des parts. Au décès, l'usufruit s'éteint sans droits supplémentaires." },
    { question: "Est-il préférable de transmettre ses SCPI par donation ou par assurance-vie ?", answer: "Les deux outils sont complémentaires. La donation permet une transmission en ligne directe avec abattement. L'assurance-vie offre une fiscalité spécifique (abattement de 152 500 € par bénéficiaire) et permet de désigner librement ses bénéficiaires." },
    { question: "Quels sont les abattements applicables aux donations de parts de SCPI ?", answer: "L'abattement principal est de 100 000 € par parent et par enfant, renouvelable tous les 15 ans. Pour les petits-enfants, l'abattement est de 31 865 € par grand-parent." },
    { question: "Peut-on donner des parts de SCPI à ses enfants sans payer de droits ?", answer: "Oui, dans la limite des abattements. Par exemple, avec la donation avec réserve d'usufruit, un parent de 60 ans peut donner jusqu'à 200 000 € de parts de SCPI à son enfant sans droits (usufruit 50 %, soit 100 000 € taxables - 100 000 € d'abattement = 0 €)." },
    { question: "Quelle est la fiscalité des SCPI en assurance-vie au décès ?", answer: "Pour les versements avant 70 ans : abattement de 152 500 € par bénéficiaire sur les gains, puis taxation à 20 % jusqu'à 700 000 € et 31,25 % au-delà. Pour les versements après 70 ans : abattement global de 30 500 € sur l'ensemble des bénéficiaires." },
    { question: "Les parts de SCPI en SCI sont-elles transmises différemment ?", answer: "Oui, ce sont les parts de la SCI qui sont transmises, soumises aux droits d'enregistrement et aux droits de donation. La SCI permet une transmission progressive et une gestion collective du patrimoine." },
    { question: "Faut-il un notaire pour une donation de parts de SCPI ?", answer: "Oui, la donation de parts de SCPI doit obligatoirement être faite par acte notarié pour être valable et opposable aux tiers. Les frais de notaire sont d'environ 1,5 à 2 % de la valeur donnée." },
    { question: "Peut-on transmettre des SCPI à ses petits-enfants ?", answer: "Oui, avec un abattement de 31 865 € par grand-parent et par petit-enfant. La donation peut être démembrée (usufruit conservé par les grands-parents, nue-propriété transmise) pour optimiser la transmission." },
    { question: "Quel est l'impact de l'IFI sur la transmission de SCPI ?", answer: "Les parts de SCPI sont incluses dans l'assiette de l'IFI pour leur valeur vénale. En cas de donation avec réserve d'usufruit, l'usufruitier déclare la valeur en pleine propriété. Il est recommandé d'intégrer l'IFI dans la stratégie de transmission." },
    { question: "Peut-on revenir sur une donation de parts de SCPI ?", answer: "Non, une donation est en principe irrévocable une fois acceptée par le donataire. Il est donc essentiel de bien réfléchir avant de s'engager et de ne donner que ce dont on peut se passer." },
    { question: "Un CGP-CIF est-il utile pour organiser la transmission de SCPI ?", answer: "Oui, un CGP-CIF comme Eric Bellaiche, inscrit ORIAS n°13001580, vous aide à analyser votre situation, choisir la stratégie de transmission la plus adaptée et coordonner les professionnels (notaire, assureur, conseiller fiscal)." },
  ],
  ctaTitle: "Vous souhaitez organiser la transmission de vos parts de SCPI ?",
  ctaText: "Un échange permet d'analyser votre situation familiale et patrimoniale et de définir la stratégie de transmission la plus adaptée. Eric Bellaiche, CGP-CIF, vous accompagne dans l'optimisation de votre transmission.",
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
    { href: '/articles/scpi-demembrement/', label: 'SCPI en démembrement : nue-propriété et usufruit', position: 'inline' },
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité : impact fiscal avant d\'investir', position: 'inline' },
    { href: '/articles/scpi-assurance-vie-ou-direct/', label: 'SCPI en direct ou via assurance-vie', position: 'inline' },
  ],
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
