import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'scpi-assurance-vie-ou-direct',
  category: 'scpi',
  title: 'SCPI en direct ou via assurance-vie : comment comparer et choisir ?',
  metaTitle: 'SCPI en direct ou via assurance-vie : comment comparer et choisir ?',
  metaDescription: 'Comparaison détaillée entre détention directe de SCPI et investissement via assurance-vie : frais, fiscalité, liquidité, choix des SCPI, rendement net, horizon, transmission, succession. Analyse CGP-CIF.',
  canonical: 'https://eric-bellaiche.fr/articles/scpi-assurance-vie-ou-direct/',
  badge: 'SCPI &bull; Assurance-vie &bull; Comparatif CGP-CIF',
  intro: 'Investir en SCPI en direct ou via un contrat d\'assurance-vie ? Ce choix revient fréquemment chez les investisseurs patrimoniaux. Chaque option présente des avantages et des limites spécifiques en matière de fiscalité, de frais, de liquidité, de choix des supports et de transmission. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous aide à comprendre les différences pour éclairer votre décision.',
  shortAnswer: 'La détention directe offre un choix plus large de SCPI, une gestion directe et une simplicité de souscription, mais avec une fiscalité plus élevée sur les revenus et les plus-values. L\'assurance-vie offre un cadre fiscal différé et un abattement après 8 ans, ainsi qu\'un cadre successoral avantageux, mais limite le choix des SCPI disponibles et ajoute des frais supplémentaires. Le choix dépend de la situation personnelle.',
  summaryItems: [
    { label: 'SCPI en direct : fonctionnement et fiscalité', anchor: 'scpi-direct-fonctionnement' },
    { label: 'SCPI via assurance-vie : fonctionnement et fiscalité des rachats', anchor: 'scpi-assurance-vie-fonctionnement' },
    { label: 'Tableau comparatif complet', anchor: 'tableau-comparatif' },
    { label: 'Impact fiscal selon le profil', anchor: 'impact-fiscal-profil' },
    { label: 'Impact sur la liquidité', anchor: 'impact-liquidite' },
    { label: 'Impact sur la transmission', anchor: 'impact-transmission' },
    { label: 'Impact sur le choix des SCPI disponibles', anchor: 'impact-choix-scpi' },
    { label: 'Exemple pédagogique : simulation sur 10 ans', anchor: 'exemple-pedagogique' },
    { label: 'Erreurs fréquentes', anchor: 'erreurs-frequentes' },
    { label: 'Méthode Eric Bellaiche pour comparer les options', anchor: 'methode' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 15,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'assurance-vie', 'détention directe', 'comparatif', 'fiscalité', 'transmission', 'liquidité', 'CGP-CIF'],
  sections: [
    {
      id: 'scpi-direct-fonctionnement',
      title: 'SCPI en direct : fonctionnement, fiscalité, avantages et limites',
      level: 'h2',
      type: 'normal',
      content: [
        "Investir en SCPI en direct signifie acquérir des parts directement auprès de la société de gestion ou via un intermédiaire. L'investisseur perçoit les loyers distribués et supporte la fiscalité afférente.",
        "Sur le plan fiscal, les revenus sont imposés dans la catégorie des revenus fonciers, soumis à la TMI et aux prélèvements sociaux (17,2 %). Les plus-values de cession sont imposées comme des plus-values immobilières (19 % + PS 17,2 %).",
        'Principaux avantages :',
        '- Choix large : toutes les SCPI du marché sont accessibles.',
        "- Simplicité : l'investisseur est directement propriétaire des parts.",
        '- Pas d\'intermédiaire financier supplémentaire entre l\'investisseur et la SCPI.',
        '- Déduction possible des intérêts d\'emprunt si acquisition à crédit.',
        'Principales limites :',
        "- Fiscalité élevée pour les TMI supérieures à 30 %.",
        "- Liquidité dépendante du marché secondaire de la SCPI.",
        "- Transmission soumise aux droits de mutation classiques.",
      ],
    },
    {
      id: 'scpi-assurance-vie-fonctionnement',
      title: 'SCPI via assurance-vie : fonctionnement et fiscalité des rachats',
      level: 'h2',
      type: 'normal',
      content: [
        "Dans un contrat d'assurance-vie, les parts de SCPI sont logées en unités de compte (UC). L'investisseur ne détient pas directement les parts mais des parts du contrat adossées à la SCPI.",
        "Sur le plan fiscal, les revenus des SCPI sont capitalisés dans le contrat sans imposition immédiate. C'est au moment du rachat que la fiscalité s'applique, uniquement sur les gains (plus-values).",
        "En cas de rachat après 8 ans, les gains bénéficient d'un abattement annuel sur l'impôt sur le revenu : 4 600 € pour une personne seule, 9 200 € pour un couple. Au-delà, les gains sont imposés au taux forfaitaire de 7,5 % (ou au barème progressif sur option). Les prélèvements sociaux (17,2 %) restent dus.",
        'Principaux avantages :',
        "- Fiscalité différée et abattement annuel après 8 ans.",
        "- Cadre successoral particulièrement avantageux (hors succession, abattement de 152 500 € par bénéficiaire).",
        '- Possibilité d\'arbitrer entre différents supports.',
        '- Pas d\'IFI sur les UC.',
        "Principales limites :",
        "- Choix des SCPI limité à celles éligibles au contrat.",
        "- Frais supplémentaires (frais d'entrée du contrat, frais de gestion des UC).",
        "- La quote-part de loyers reversée par la SCPI peut être inférieure à celle de la détention directe (frais prélevés par l'assureur).",
        "- L'abattement n'est pas une exonération totale : il s'applique dans la limite des plafonds annuels.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: 'Tableau comparatif complet',
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous compare l'ensemble des critères différenciant la détention directe de la détention via assurance-vie.",
      ],
      table: {
        headers: ['Critère', 'SCPI en direct', 'SCPI via assurance-vie'],
        rows: [
          ["Frais d'entrée", "8 à 12 % (frais de souscription SCPI)", "Frais d'entrée du contrat (0 à 5 %) + frais sur UC"],
          ['Frais de gestion annuels', '8 à 12 % des loyers perçus (société de gestion)', 'Frais de gestion du contrat (0,5 à 1 %) + frais de gestion SCPI'],
          ['Fiscalité des revenus (pendant la détention)', 'IR (TMI) + PS 17,2 % chaque année', 'Capitalisation : aucune imposition immédiate'],
          ['Fiscalité en sortie', 'IR + PS sur les plus-values', 'Abattement après 8 ans, puis 7,5 % + PS sur les gains'],
          ['Liquidité', 'Marché secondaire de la SCPI (délai variable)', 'Rachat du contrat (délai variable selon l\'assureur)'],
          ['Choix des SCPI', 'Large (toutes les SCPI du marché)', 'Limité aux SCPI éligibles au contrat'],
          ['Horizon recommandé', '8 à 10 ans minimum', '8 ans minimum (optimisation fiscale)'],
          ['Transmission / succession', 'Droits de mutation', 'Cadre successoral avantageux (hors succession)'],
          ['IFI', 'Inclus dans le patrimoine immobilier', 'Pas d\'IFI (UC)'],
          ['Possibilité de crédit', 'Oui, intérêts déductibles', 'Non (sauf contrats spécifiques)'],
          ['Gestion pilotée', 'Non (choix libre)', 'Oui, possible'],
        ],
      },
    },
    {
      id: 'impact-fiscal-profil',
      title: 'Impact fiscal selon le profil de l\'investisseur',
      level: 'h2',
      type: 'normal',
      content: [
        'L\'avantage fiscal de l\'assurance-vie par rapport à la détention directe dépend fortement de la TMI et de l\'horizon de placement.',
        'Pour un investisseur avec une TMI de 30 % ou plus, l\'assurance-vie offre un avantage fiscal significatif sur le long terme grâce à la capitalisation et à l\'abattement après 8 ans. En direct, le rendement net peut être réduit de près de moitié par la fiscalité.',
        "Pour un investisseur avec une TMI faible, l'écart est moins marqué. La détention directe peut être plus avantageuse si l'investisseur souhaite un revenu régulier immédiat et un choix large de SCPI.",
        "Attention : l'avantage fiscal de l'assurance-vie doit être mis en balance avec les frais supplémentaires et la quote-part de loyers reversée, qui peuvent réduire le rendement brut avant même la fiscalité.",
      ],
    },
    {
      id: 'impact-liquidite',
      title: 'Impact sur la liquidité',
      level: 'h2',
      type: 'normal',
      content: [
        'La liquidité diffère selon le mode de détention :',
        'En direct : la revente des parts dépend du marché secondaire de la SCPI. Certaines SCPI très capitalisées (plus d\'un milliard d\'euros) offrent une liquidité correcte, tandis que des SCPI de taille modeste peuvent nécessiter plusieurs mois, voire années, pour trouver un acheteur.',
        "Via assurance-vie : le rachat de parts du contrat dépend des conditions générales de l'assureur. Certains contrats imposent un délai de rachat, et l'assureur peut être contraint de vendre les parts de SCPI sur le marché secondaire pour exécuter le rachat, ce qui peut prendre du temps.",
        "Dans les deux cas, la liquidité n'est pas garantie. Un horizon de 8 à 10 ans est recommandé quel que soit le mode de détention.",
      ],
    },
    {
      id: 'impact-transmission',
      title: 'Impact sur la transmission',
      level: 'h2',
      type: 'normal',
      content: [
        "La transmission est l'un des critères les plus différenciants entre les deux modes de détention.",
        "En direct : le décès entraîne la transmission des parts aux héritiers, soumise aux droits de mutation successifs. L'abattement dépend du lien de parenté (100 000 € pour un enfant, etc.). Au-delà, les droits peuvent être élevés.",
        "Via assurance-vie : le capital transmis bénéficie d'un cadre fiscal spécifique. Les sommes versées avant 70 ans bénéficient d'un abattement de 152 500 € par bénéficiaire. Au-delà, un prélèvement de 20 % jusqu'à 700 000 €, puis 31,25 % au-dessus. Les sommes versées après 70 ans bénéficient d'un abattement global de 30 500 €.",
        "Pour un objectif de transmission patrimoniale, l'assurance-vie est généralement plus avantageuse, sous réserve de respecter les plafonds et les conditions.",
      ],
    },
    {
      id: 'impact-choix-scpi',
      title: 'Impact sur le choix des SCPI disponibles',
      level: 'h2',
      type: 'normal',
      content: [
        'Le choix des SCPI est l\'un des critères pratiques les plus importants.',
        'En direct, toutes les SCPI du marché sont accessibles : SCPI de rendement, SCPI fiscales, SCPI européennes. L\'investisseur peut construire un portefeuille diversifié en sélectionnant les véhicules les plus adaptés à ses objectifs.',
        "Via assurance-vie, le choix est limité aux SCPI éligibles au contrat. Chaque assureur négocie une sélection de SCPI avec les sociétés de gestion. L'investisseur ne peut investir que dans cette sélection. Certains contrats proposent une cinquantaine de SCPI, d'autres moins d'une dizaine.",
        'Points d\'attention :',
        "- Vérifier la diversité des SCPI proposées dans le contrat.",
        "- Certaines SCPI de qualité peuvent ne pas être accessibles via l'assurance-vie.",
        "- Les conditions de sortie et de change de SCPI varient selon les contrats.",
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique : simulation sur 10 ans',
      level: 'h2',
      type: 'table',
      content: [
        'L\'exemple ci-dessous compare un investissement de 100 000 € dans une SCPI affichant un TD brut de 6 %, selon le mode de détention. Les chiffres sont donnés à titre pédagogique et ne constituent pas une promesse de rendement.',
      ],
      table: {
        headers: ['Critère', 'SCPI en direct', 'SCPI via assurance-vie'],
        rows: [
          ['Capital investi', '100 000 €', '100 000 €'],
          ['Frais d\'entrée estimés', '10 000 € (10 %)', '3 000 € (3 %) + frais UC'],
          ['TD brut annuel', '6,0 %', '6,0 % brut, quote-part reversée ~5,4 %'],
          ['Revenu annuel brut', '~6 000 €', '~5 400 € capitalisés'],
          ['Fiscalité annuelle (TMI 30 %)', 'IR + PS = 47,2 %', 'Aucune (capitalisation)'],
          ['Revenu net annuel perçu', '~3 168 €', '0 € (capitalisé dans le contrat)'],
          ['Valeur après 10 ans (brute avant fiscalité de sortie)', '100 000 € + 60 000 € de revenus bruts', '100 000 € + ~54 000 € capitalisés'],
          ['Fiscalité en sortie (rachat après 8 ans, TMI 30 %)', 'IR + PS sur plus-values', 'Abattement annuel puis 7,5 % + PS'],
          ['Rendement net estimé après 10 ans', 'Variable selon TMI et revente', 'Variable selon abattement et quote-part'],
        ],
      },
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans le choix entre SCPI en direct et assurance-vie',
      level: 'h2',
      type: 'list',
      content: ['Plusieurs erreurs reviennent régulièrement lors de la comparaison :'],
      listItems: [
        "Croire que l'assurance-vie exonère totalement d'impôt : l'abattement annuel est limité (4 600 € / 9 200 €) et les prélèvements sociaux restent dus.",
        "Négliger les frais de l'assurance-vie : frais d'entrée, frais de gestion des UC, quote-part prélevée par l'assureur.",
        'Choisir l\'assurance-vie uniquement pour la fiscalité sans vérifier la quote-part de loyers reversée.',
        'Investir en direct sans anticiper la fiscalité, qui peut diviser le rendement par deux.',
        "Ne pas vérifier la qualité des SCPI proposées dans le contrat d'assurance-vie.",
        "Oublier que la liquidité en assurance-vie dépend de l'assureur et du marché secondaire.",
        "Choisir la détention directe sans prendre en compte les droits de succession.",
        'Investir sans analyser la cohérence avec le patrimoine global et les objectifs personnels.',
      ],
    },
    {
      id: 'methode',
      title: 'Méthode Eric Bellaiche pour comparer les options',
      level: 'h2',
      type: 'method-steps',
      content: [
        'Pour choisir entre SCPI en direct et via assurance-vie, Eric Bellaiche, CGP-CIF, applique une méthode structurée en 5 étapes. Aucune recommandation n\'est formulée sans analyse préalable.',
      ],
      methodSteps: [
        { title: 'Analyse de la situation fiscale', description: "TMI, prélèvements sociaux, IFI : chaque élément influence l'avantage relatif de chaque mode." },
        { title: 'Définition de l\'horizon', description: "L'horizon conditionne la pertinence de l'assurance-vie (optimale après 8 ans) ou de la détention directe." },
        { title: 'Évaluation des objectifs patrimoniaux', description: 'Revenus immédiats, capitalisation, transmission : chaque objectif oriente vers un mode de détention.' },
        { title: 'Comparaison des offres disponibles', description: 'Analyse des SCPI accessibles et des contrats d\'assurance-vie, frais, quote-part, qualité des supports.' },
        { title: 'Simulation personnalisée et arbitrage', description: 'Calcul du rendement net estimé selon la situation, formalisation et déclaration d\'adéquation le cas échéant.' },
      ],
    },
  ],
  faq: [
    { question: 'Quelle différence entre SCPI en direct et via assurance-vie ?', answer: "En direct, vous achetez des parts de SCPI directement. Via assurance-vie, les parts sont logées dans un contrat d'assurance-vie en unités de compte. Chaque mode a des implications différentes en termes de frais, fiscalité, liquidité et succession." },
    { question: 'Quel mode de détention est le plus avantageux fiscalement ?', answer: "Cela dépend de la situation personnelle. La détention en assurance-vie offre une fiscalité différée et un abattement après 8 ans. La détention directe peut être plus adaptée selon les objectifs et l'horizon du client." },
    { question: 'Peut-on investir dans toutes les SCPI via assurance-vie ?', answer: 'Non, seules les SCPI éligibles aux contrats d\'assurance-vie sont accessibles. Le choix est plus large en direct.' },
    { question: "L'assurance-vie exonère-t-elle totalement d'impôt les plus-values après 8 ans ?", answer: "Non. Après 8 ans, un abattement annuel s'applique (4 600 € pour une personne seule, 9 200 € pour un couple). Au-delà, les gains sont imposés à 7,5 % (ou au barème). Les prélèvements sociaux restent dus." },
    { question: 'La détention directe est-elle toujours moins avantageuse pour la transmission ?', answer: "Généralement, l'assurance-vie offre un cadre successoral plus avantageux que la détention directe, mais le choix dépend des montants, de l'âge au moment du versement et de la situation familiale." },
    { question: 'Quels sont les frais supplémentaires en assurance-vie ?', answer: "Frais d'entrée du contrat (0 à 5 %), frais de gestion annuels des UC (0,5 à 1 %), et la quote-part de loyers prélevée par l'assureur, qui réduit le rendement brut des SCPI." },
    { question: 'Peut-on sortir facilement d\'une SCPI en assurance-vie ?', answer: "Le rachat du contrat dépend des conditions de l'assureur. L'assureur peut vendre les parts de SCPI sur le marché secondaire, ce qui peut prendre du temps. La liquidité n'est pas garantie." },
    { question: 'Faut-il privilégier un mode de détention selon sa TMI ?', answer: "Pour une TMI élevée (30 % ou plus), l'assurance-vie est souvent plus avantageuse. Pour une TMI faible, la détention directe peut être pertinente, notamment pour des revenus immédiats." },
    { question: 'Peut-on diversifier entre direct et assurance-vie ?', answer: 'Oui, il est possible d\'investir à la fois en direct et via assurance-vie pour combiner les avantages des deux modes. Une analyse globale est recommandée.' },
    { question: 'Une recommandation peut-elle être faite sans analyse préalable ?', answer: 'Non. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse de la situation, du profil investisseur, des objectifs, de l\'horizon et de la capacité de perte.' },
  ],
  ctaTitle: 'Vous hésitez entre SCPI en direct et assurance-vie ?',
  ctaText: 'Un échange avec Eric Bellaiche, CGP-CIF, permet d\'analyser votre situation et de comparer les options adaptées à vos objectifs patrimoniaux.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité', position: 'inline' },
  ],
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
