import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'scpi-retraite',
  category: 'scpi',
  title: "SCPI et retraite : revenus complémentaires, fiscalité et horizon de placement",
  metaTitle: "SCPI et retraite : revenus complémentaires, fiscalité et horizon de placement",
  metaDescription: "Les SCPI peuvent constituer un complément de retraite efficace grâce à des revenus réguliers et une valorisation du capital. Analyse des stratégies de placement, de la fiscalité et de l'horizon recommandé par Eric Bellaiche, CGP-CIF ORIAS 13001580.",
  canonical: 'https://eric-bellaiche.fr/articles/scpi-retraite/',
  badge: "SCPI &bull; Retraite &bull; CGP-CIF &bull; ORIAS 13001580",
  intro: "La préparation de la retraite est l'un des objectifs patrimoniaux les plus courants chez les investisseurs français. Face à la baisse annoncée des taux de remplacement des régimes de retraite par répartition, la constitution d'un complément de revenus est devenue une nécessité pour de nombreux épargnants. Les SCPI, en offrant des revenus locatifs réguliers et une potentielle valorisation du capital à long terme, constituent une solution de plus en plus plébiscitée. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous aide à comprendre comment intégrer les SCPI dans votre stratégie de préparation à la retraite, en fonction de votre horizon de placement, de votre fiscalité et de vos objectifs.",
  shortAnswer: "Les SCPI permettent de se constituer un complément de retraite de deux manières principales : par les revenus distribués (loyers perçus régulièrement) et par la valorisation du capital à long terme. Avec un taux de distribution moyen de 4 à 6 % par an, un investissement de 100 000 € en SCPI peut générer un revenu annuel de 4 000 à 6 000 €, soit 330 à 500 € par mois. Pour un investisseur de 45 ans, un investissement programmé sur 15 à 20 ans permet de cumuler un capital significatif au moment de la retraite, grâce à l'effet de capitalisation (réinvestissement des loyers) et à l'éventuelle revalorisation des parts. La fiscalité applicable dépend du mode de détention : en direct (revenus fonciers imposés à la TMI + PS), via une assurance-vie (fiscalité différée, abattement après 8 ans), ou en nue-propriété (absence d'imposition pendant la période de démembrement avec récupération des loyers à l'issue). L'horizon de placement recommandé est de 10 à 20 ans minimum.",
  summaryItems: [
    { label: "Pourquoi les SCPI sont adaptées à la préparation de la retraite", anchor: 'pourquoi-scpi-retraite' },
    { label: "SCPI à capitalisation ou SCPI de distribution : quelle stratégie ?", anchor: 'capitalisation-ou-distribution' },
    { label: "Investissement programmé en SCPI pour la retraite", anchor: 'investissement-programme' },
    { label: "SCPI en nue-propriété pour préparer sa retraite", anchor: 'nue-propriete-retraite' },
    { label: "SCPI en assurance-vie pour la retraite", anchor: 'assurance-vie-retraite' },
    { label: "SCPI vs PER : comparaison pour la préparation retraite", anchor: 'scpi-vs-per' },
    { label: "Fiscalité des revenus SCPI à la retraite", anchor: 'fiscalite-retraite' },
    { label: "Tableau comparatif des stratégies SCPI pour la retraite", anchor: 'tableau-comparatif' },
    { label: "Exemple pédagogique : constitution d'un complément de retraite sur 15 ans", anchor: 'exemple-pedagogique' },
    { label: "Risques et points de vigilance pour un objectif retraite", anchor: 'points-vigilance' },
    { label: "Erreurs fréquentes dans la préparation retraite avec des SCPI", anchor: 'erreurs-frequentes' },
    { label: "Méthode Eric Bellaiche pour constituer un complément retraite avec des SCPI", anchor: 'methode' },
    { label: "Questions fréquentes", anchor: 'faq' },
  ],
  readingTime: 22,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['SCPI', 'retraite', 'revenus complémentaires', 'fiscalité', 'capitalisation', 'PER', 'assurance-vie', 'nue-propriété', 'horizon de placement', 'CGP-CIF'],
  sections: [
    {
      id: 'pourquoi-scpi-retraite',
      title: "Pourquoi les SCPI sont adaptées à la préparation de la retraite",
      level: 'h2',
      type: 'normal',
      content: [
        "Les SCPI présentent plusieurs caractéristiques qui les rendent particulièrement adaptées à un objectif de constitution d'un complément de retraite.",
        "La première est la régularité des revenus distribués. Les SCPI de rendement distribuent généralement des loyers chaque trimestre ou chaque semestre, avec un taux de distribution qui peut varier de 4 à 6 % selon la SCPI et les conditions de marché. Cette régularité est un atout majeur pour un retraité qui cherche à compléter ses revenus de manière prévisible.",
        "La deuxième est le potentiel de valorisation du capital à long terme. Historiquement, les parts de SCPI ont tendance à s'apprécier sur le long terme, sous l'effet de la revalorisation du parc immobilier et du réinvestissement des bénéfices. Cette double source de rendement (revenus + valorisation) est favorable à une stratégie de long terme.",
        "La troisième est la diversification. Une SCPI investit généralement dans un parc immobilier diversifié (bureaux, commerces, logistique, santé) sur plusieurs zones géographiques, ce qui réduit le risque par rapport à un investissement locatif direct.",
        "La quatrième est la souplesse dans le choix du mode de détention. Selon son âge, sa TMI et ses objectifs, l'investisseur peut choisir entre la détention directe (simplicité, revenus immédiats), la nue-propriété (absence de fiscalité, récupération à la retraite), l'assurance-vie (fiscalité différée, transmission), ou l'investissement programmé (effet de capitalisation).",
        "Enfin, la mutualisation des risques locatifs est un avantage : contrairement à un investissement locatif direct, la vacance locative d'un seul bien n'impacte que marginalement les revenus d'une SCPI, grâce à la diversification du parc.",
      ],
    },
    {
      id: 'capitalisation-ou-distribution',
      title: "SCPI à capitalisation ou SCPI de distribution : quelle stratégie ?",
      level: 'h2',
      type: 'normal',
      content: [
        "Il existe deux grandes familles de SCPI qui répondent à des objectifs différents dans le cadre de la préparation de la retraite.",
        "Les SCPI de distribution (les plus courantes) : elles redistribuent la quasi-totalité des loyers perçus aux associés, généralement chaque trimestre. Le taux de distribution (TD) est le principal indicateur de performance. Ces SCPI conviennent aux investisseurs qui souhaitent percevoir des revenus réguliers pendant la phase d'épargne, par exemple pour réinvestir les loyers perçus (effet de capitalisation).",
        "Les SCPI à capitalisation : elles conservent tout ou partie des loyers perçus pour les réinvestir dans le parc immobilier (acquisition de nouveaux biens, travaux). La valeur de la part tend à augmenter plus rapidement que dans une SCPI de distribution, mais l'associé ne perçoit pas de revenus réguliers. Ces SCPI conviennent aux investisseurs qui n'ont pas besoin de revenus immédiats et qui privilégient la valorisation du capital à long terme.",
        "Le choix entre les deux dépend de l'horizon de placement et des besoins de revenus de l'investisseur. Pour un investisseur de 40 à 50 ans qui prépare sa retraite sur 15 à 20 ans, une combinaison des deux peut être pertinente : SCPI de distribution avec réinvestissement des loyers pour bénéficier de l'effet de capitalisation, complétée par une SCPI à capitalisation pour accélérer la croissance du patrimoine.",
        "À l'approche de la retraite (55-65 ans), l'investisseur peut progressivement basculer vers des SCPI de distribution pour sécuriser des revenus réguliers.",
      ],
    },
    {
      id: 'investissement-programme',
      title: "Investissement programmé en SCPI pour la retraite",
      level: 'h2',
      type: 'normal',
      content: [
        "L'investissement programmé en SCPI est une stratégie qui consiste à acquérir des parts de manière régulière (chaque mois ou chaque trimestre) sur une longue période, plutôt que d'investir une somme unique. Cette approche présente plusieurs avantages pour la préparation de la retraite.",
        "Le premier avantage est l'effet de capitalisation : en réinvestissant systématiquement les loyers perçus, le nombre de parts détenues augmente progressivement, ce qui accroît les revenus futurs. Sur 15 à 20 ans, cet effet peut être significatif.",
        "Le deuxième avantage est le lissage du prix d'acquisition (effet de dollar cost averaging). En investissant régulièrement, l'investisseur achète des parts à différents niveaux de prix, ce qui réduit l'impact des fluctuations du marché.",
        "Le troisième avantage est la discipline d'épargne. Un investissement programmé permet de constituer un patrimoine de manière régulière et automatique, sans avoir à mobiliser une somme importante en une seule fois.",
        "Concrètement, un investisseur de 45 ans qui investit 300 € par mois en SCPI avec un rendement moyen de 5 % peut accumuler, après 20 ans (à 65 ans), un capital d'environ 120 000 € (hors revalorisation des parts), générant des revenus annuels de 6 000 € (500 € par mois). Cet exemple est donné à titre pédagogique et ne constitue pas une promesse de rendement.",
        "L'investissement programmé peut être mis en place dans le cadre d'un contrat d'assurance-vie en unités de compte, ou en direct via un compte-titres. Le choix du support dépend de la fiscalité souhaitée et de l'objectif de transmission.",
      ],
    },
    {
      id: 'nue-propriete-retraite',
      title: "SCPI en nue-propriété pour préparer sa retraite",
      level: 'h2',
      type: 'normal',
      content: [
        "La SCPI en nue-propriété est une stratégie particulièrement adaptée à la préparation de la retraite, notamment pour les investisseurs âgés de 50 à 55 ans qui disposent d'une capacité d'épargne et qui souhaitent se constituer un complément de revenus pour leur retraite dans 10 à 15 ans.",
        "Le mécanisme est simple : l'investisseur acquiert des parts de SCPI en nue-propriété avec une décote de 30 à 40 % par rapport à la valeur en pleine propriété. Pendant la période de démembrement (10 à 15 ans), il ne perçoit pas de loyers et n'est pas imposé. À l'issue, au moment de la retraite, il récupère la pleine propriété des parts et commence à percevoir les loyers.",
        "Cette stratégie présente plusieurs avantages pour la retraite :",
        "- L'absence de fiscalité pendant la phase de constitution (pas d'IR ni de PS sur des revenus non perçus).",
        "- La décote à l'entrée permet d'acquérir un patrimoine plus important pour un même investissement.",
        "- La récupération des loyers intervient au moment où l'investisseur en a le plus besoin (baisse des revenus professionnels, fin des remboursements de crédit).",
        "- La fiscalité à la retraite est potentiellement plus favorable (TMI plus faible après la cessation d'activité).",
        "Cette approche est particulièrement pertinente pour les investisseurs à TMI élevée (30 %, 41 % ou 45 %) qui souhaitent optimiser leur fiscalité pendant leur phase d'activité et se constituer un complément de revenus pour leur retraite.",
      ],
    },
    {
      id: 'assurance-vie-retraite',
      title: "SCPI en assurance-vie pour la retraite",
      level: 'h2',
      type: 'normal',
      content: [
        "Détenir des SCPI en unités de compte dans un contrat d'assurance-vie est une autre stratégie courante pour préparer sa retraite. Ce mode de détention présente des avantages fiscaux spécifiques.",
        "Pendant la phase d'épargne, les loyers des SCPI sont capitalisés dans le contrat, sans imposition immédiate. Cette capitalisation permet de bénéficier de l'effet de composition sans le frein de la fiscalité annuelle. Les loyers réinvestis achètent automatiquement de nouvelles parts, ce qui accélère la croissance du patrimoine.",
        "À la retraite, l'investisseur peut effectuer des rachats programmés pour compléter ses revenus. Après 8 ans de détention, les gains bénéficient d'un abattement annuel sur l'impôt sur le revenu : 4 600 € par an pour une personne seule, 9 200 € pour un couple. Au-delà de cet abattement, les gains sont imposés au taux forfaitaire de 7,5 % (hors prélèvements sociaux de 17,2 %).",
        "L'assurance-vie offre également des avantages en matière de transmission, qui peuvent être intégrés dans une stratégie patrimoniale globale incluant la préparation de la retraite.",
        "Points d'attention pour la détention de SCPI en assurance-vie dans un objectif retraite :",
        "- Toutes les SCPI ne sont pas éligibles aux contrats d'assurance-vie : le choix est limité à celles sélectionnées par l'assureur.",
        "- Les frais du contrat (frais d'entrée, frais de gestion des UC, frais d'arbitrage) réduisent le rendement net.",
        "- La quote-part de loyers reversée peut être inférieure à celle d'une détention directe.",
        "- L'assurance-vie est un outil de long terme, cohérent avec un objectif retraite.",
      ],
    },
    {
      id: 'scpi-vs-per',
      title: "SCPI vs PER : comparaison pour la préparation retraite",
      level: 'h2',
      type: 'normal',
      content: [
        "Le Plan d'Épargne Retraite (PER) est l'autre grand outil de préparation de la retraite. Comparer SCPI et PER permet de mieux comprendre leur complémentarité.",
        "Le PER offre un avantage fiscal immédiat : les versements sont déductibles du revenu imposable, dans la limite des plafonds réglementaires. Cet avantage est particulièrement intéressant pour les contribuables à TMI élevée. En revanche, les sommes sont bloquées jusqu'à la retraite (sauf cas de déblocage anticipé), et la sortie en capital est imposée dans les conditions des rentes.",
        "Les SCPI, selon le mode de détention, n'offrent pas de déduction fiscale à l'entrée mais permettent une plus grande flexibilité : possibilité de sortie anticipée, transmission facilitée, absence de blocage des fonds. Les revenus sont perçus en direct, ce qui peut être utile pour des besoins de trésorerie.",
        "La complémentarité entre les deux outils est évidente :",
        "- Le PER est privilégié pour l'optimisation fiscale immédiate (déduction des versements).",
        "- Les SCPI en nue-propriété sont adaptées pour préparer des revenus futurs sans fiscalité immédiate.",
        "- Les SCPI en assurance-vie sont un bon compromis entre flexibilité et performance.",
        "- Les SCPI en direct conviennent pour des revenus immédiats (pré-retraite, retraite déjà commencée).",
        "Une stratégie patrimoniale complète peut combiner plusieurs de ces outils pour diversifier les sources de revenus à la retraite.",
      ],
    },
    {
      id: 'fiscalite-retraite',
      title: "Fiscalité des revenus SCPI à la retraite",
      level: 'h2',
      type: 'normal',
      content: [
        "La fiscalité applicable aux revenus des SCPI perçus pendant la retraite dépend du mode de détention choisi et de la situation fiscale du retraité.",
        "En détention directe, les loyers perçus sont imposés dans la catégorie des revenus fonciers, soumis au barème progressif de l'impôt sur le revenu (TMI) et aux prélèvements sociaux de 17,2 %. À la retraite, la TMI est souvent plus faible que pendant l'activité, ce qui réduit l'imposition effective. Par exemple, un retraité avec une TMI de 11 % subira un taux combiné de 28,2 %, contre 47,2 % pour un actif à 30 % de TMI.",
        "En assurance-vie, les rachats après 8 ans bénéficient de l'abattement annuel et du taux réduit de 7,5 % sur les gains. Ce régime est particulièrement avantageux pour les retraités dont les revenus globaux restent dans des tranches modestes.",
        "En nue-propriété, la fiscalité est différée : pendant la phase de constitution, rien n'est imposé. À la retraite, lorsque la pleine propriété est reconstituée, les loyers sont imposés comme en direct.",
        "L'IFI peut également concerner les retraités disposant d'un patrimoine immobilier net supérieur à 1,3 million d'euros. Les parts de SCPI sont incluses dans le calcul de l'assiette IFI.",
        "Points d'attention sur la fiscalité des SCPI à la retraite :",
        "- La baisse de TMI à la retraite peut rendre la détention directe plus attractive fiscalement.",
        "- Les prélèvements sociaux (17,2 %) s'appliquent quelle que soit la TMI, même à 0 %.",
        "- Les revenus des SCPI s'ajoutent aux pensions de retraite et peuvent faire basculer le contribuable dans une tranche supérieure.",
        "- Il est recommandé de simuler l'impact fiscal des revenus SCPI sur la retraite avant d'investir.",
      ],
    },
    {
      id: 'tableau-comparatif',
      title: "Tableau comparatif des stratégies SCPI pour la retraite",
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous compare les principales stratégies d'investissement en SCPI pour la préparation de la retraite, en fonction du profil et de l'horizon de l'investisseur.",
      ],
      table: {
        headers: ['Stratégie', 'Profil', 'Âge recommandé', 'Horizon', 'Avantage principal', 'Inconvénient principal'],
        rows: [
          ['SCPI en direct (distribution)', 'Revenus immédiats', '55-70 ans', '5-10 ans', 'Revenus réguliers perçus dès le début', 'Fiscalité élevée si TMI haute'],
          ['SCPI en nue-propriété', 'Préparation sans fiscalité', '45-55 ans', '10-15 ans', 'Décote à l\'entrée + fiscalité différée', 'Aucun revenu pendant la période'],
          ['SCPI en assurance-vie', 'Capitalisation + transmission', '40-60 ans', '10-20 ans', 'Fiscalité différée + abattement après 8 ans', 'Frais du contrat, choix limité de SCPI'],
          ['Investissement programmé', 'Épargne mensuelle régulière', '35-50 ans', '15-25 ans', 'Effet capitalisation + lissage du prix', 'Nécessite une discipline d\'épargne'],
          ['SCPI à capitalisation', 'Valorisation du capital', '40-50 ans', '15-20 ans', 'Croissance accélérée du capital', 'Aucun revenu immédiat'],
          ['Mixte (PL + AV + NP)', 'Stratégie diversifiée', '40-55 ans', '15-20 ans', 'Optimisation fiscale + diversification', 'Complexité de gestion'],
        ],
      },
    },
    {
      id: 'exemple-pedagogique',
      title: "Exemple pédagogique : constitution d'un complément de retraite sur 15 ans",
      level: 'h2',
      type: 'table',
      content: [
        "Prenons l'exemple d'un investisseur de 50 ans, TMI à 30 %, qui souhaite se constituer un complément de retraite de 500 € par mois (6 000 € par an) à l'âge de 65 ans. Il opte pour une stratégie d'investissement programmé en SCPI de distribution. Cet exemple est donné à titre purement pédagogique et ne constitue en aucun cas une promesse de rendement.",
      ],
      table: {
        headers: ['Poste', 'Valeur'],
        rows: [
          ['Âge au début de l\'investissement', '50 ans'],
          ['Âge de la retraite visé', '65 ans'],
          ['Durée de constitution', '15 ans'],
          ['Investissement mensuel', '500 €'],
          ['Total investi sur 15 ans', '90 000 €'],
          ['Taux de distribution moyen hypothèse', '5,0 % brut'],
          ['Réinvestissement des loyers', 'Oui (capitalisation)'],
          ['Capital estimé à 65 ans (hypothèse stable)', '~113 000 €'],
          ['Revenu annuel estimé à 65 ans (5 %)', '~5 650 € par an (~470 €/mois)'],
          ['Revenu fiscalité déduite (TMI 11 % retraite)', '~4 400 € par an (~367 €/mois)'],
          ['Capital total (parts + loyers capitalisés)', '~113 000 €'],
          ['Possibilité de vente partielle pour complément', 'Oui, selon besoins'],
        ],
      },
    },
    {
      id: 'points-vigilance',
      title: "Risques et points de vigilance pour un objectif retraite",
      level: 'h2',
      type: 'risk',
      content: [
        "Investir en SCPI pour préparer sa retraite comporte des risques qui doivent être anticipés, d'autant que l'horizon de placement est long et que les conséquences d'une contre-performance peuvent être significatives.",
        "Risque de baisse des distributions : le taux de distribution peut baisser au fil du temps, en fonction de l'évolution du marché immobilier et de la qualité de gestion de la SCPI. Une baisse du TD de 5 % à 4 % réduit les revenus attendus de 20 %.",
        "Risque de perte en capital : la valeur des parts de SCPI n'est pas garantie. En cas de revente au moment de la retraite, si la valeur a baissé, le capital disponible est réduit.",
        "Risque de liquidité : la revente de parts peut prendre plusieurs mois, ce qui peut être problématique si les besoins de trésorerie sont urgents au moment de la retraite.",
        "Risque de durée : si l'investisseur commence trop tard (après 60 ans), l'horizon de placement (5 à 10 ans) peut être insuffisant pour bénéficier pleinement de l'effet de capitalisation et lisser les fluctuations du marché.",
        "Risque fiscal : une modification de la législation fiscale (hausse des prélèvements sociaux, modification du régime d'imposition des revenus fonciers, réforme de l'IFI) peut réduire le rendement net attendu.",
        "Points de vigilance spécifiques :",
        "- Le choix de la SCPI est déterminant : une SCPI avec un historique solide et une gestion de qualité est préférable à une SCPI au rendement plus élevé mais plus risquée.",
        "- La diversification entre plusieurs SCPI (différents secteurs, différentes sociétés de gestion) réduit le risque spécifique.",
        "- L'investissement programmé doit être maintenu dans la durée : une interruption peut compromettre l'objectif de capital.",
        "- Il est recommandé de prévoir une marge de sécurité dans le calcul des revenus attendus (scénario prudent).",
        "- La stratégie doit être régulièrement révisée (tous les 2-3 ans) pour vérifier l'adéquation avec l'objectif retraite.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: "Erreurs fréquentes dans la préparation retraite avec des SCPI",
      level: 'h2',
      type: 'list',
      content: [
        "L'expérience montre que plusieurs erreurs sont commises par les investisseurs qui utilisent les SCPI pour préparer leur retraite :",
      ],
      listItems: [
        "Commencer trop tard : investir après 60 ans pour un objectif retraite à 65 ans laisse un horizon trop court (5 ans) pour lisser les fluctuations et bénéficier de l'effet de capitalisation.",
        "Investir une somme unique trop importante sans programmation : l'investissement programmé est plus adapté à un objectif retraite qu'un investissement en une fois.",
        "Négliger la diversification : concentrer tout son investissement sur une seule SCPI ou un seul secteur expose à un risque spécifique élevé.",
        "Sous-estimer l'impact fiscal : les prélèvements sociaux (17,2 %) et l'impôt sur le revenu réduisent significativement le rendement net, surtout si la TMI reste élevée à la retraite.",
        "Ne pas réviser sa stratégie : la situation personnelle, la fiscalité et les performances des SCPI évoluent. Un suivi régulier est nécessaire.",
        "Oublier l'effet de l'inflation : un revenu de 500 € par mois aujourd'hui n'aura pas le même pouvoir d'achat dans 15 à 20 ans.",
        "Choisir des SCPI trop risquées dans l'espoir d'un rendement plus élevé, sans considérer la sécurité du capital à long terme.",
        "Ne pas anticiper la liquidité : la revente de parts peut prendre 6 à 12 mois, ce qui peut être problématique pour des besoins de trésorerie immédiats au moment de la retraite.",
        "Investir sans consulter un CGP-CIF comme Eric Bellaiche, inscrit ORIAS n°13001580, pour valider la cohérence du projet avec sa situation personnelle et ses objectifs de retraite.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour constituer un complément retraite avec des SCPI",
      level: 'h2',
      type: 'method-steps',
      content: [
        "La constitution d'un complément de retraite via les SCPI suit une méthode structurée en 7 étapes, dans le respect du cadre réglementaire des CGP-CIF. Eric Bellaiche ne formule aucune recommandation personnalisée sans analyse préalable complète de la situation du client.",
      ],
      methodSteps: [
        { title: "Analyse de la situation retraite actuelle et future", description: "Évaluation des droits à retraite (régime général, complémentaire, réversion), estimation du taux de remplacement, identification du besoin de complément de revenus." },
        { title: "Définition de l'objectif de revenu complémentaire", description: "Détermination du montant mensuel souhaité, de l'âge de départ visé et de la durée estimée des besoins (espérance de vie, dépendance éventuelle)." },
        { title: "Choix de la stratégie et du mode de détention", description: "Sélection de la stratégie la plus adaptée : nue-propriété, assurance-vie, direct, investissement programmé, ou combinaison, en fonction de l'âge, de la TMI et des objectifs." },
        { title: "Sélection des SCPI et diversification", description: "Analyse des sociétés de gestion, des historiques de distribution, des secteurs d'investissement et des zones géographiques. Construction d'un portefeuille diversifié de 3 à 5 SCPI." },
        { title: "Simulation financière et fiscale", description: "Calcul du capital nécessaire, simulation de l'effort d'épargne mensuel, projection des revenus attendus à la retraite intégrant la fiscalité et l'inflation." },
        { title: "Mise en place et suivi périodique", description: "Mise en œuvre de l'investissement programmé, des arbitrages éventuels, et suivi annuel de la performance et de l'adéquation avec l'objectif retraite." },
        { title: "Révision à l'approche de la retraite", description: "À 5 ans de la retraite, révision de la stratégie : basculement progressif vers des SCPI de distribution, sécurisation du capital, optimisation fiscale de la sortie." },
      ],
    },
    {
      id: 'horizon-taux-remplacement',
      title: "L'horizon de placement : pourquoi 15-20 ans est recommandé",
      level: 'h3',
      type: 'normal',
      content: [
        "L'horizon de placement recommandé pour un investissement en SCPI dans un objectif retraite est de 15 à 20 ans minimum. Cette durée s'explique par plusieurs raisons.",
        "Premièrement, les SCPI sont des placements immobiliers dont la performance se mesure sur le long terme. Les frais de souscription (8 à 12 %) sont amortis sur plusieurs années. Plus l'horizon est long, plus l'impact de ces frais sur le rendement annualisé est réduit.",
        "Deuxièmement, l'effet de capitalisation (réinvestissement des loyers) est d'autant plus puissant que la durée est longue. Sur 15 ans, les loyers réinvestis peuvent représenter une part significative du capital final.",
        "Troisièmement, un horizon long permet de lisser les fluctuations du marché immobilier et de réduire le risque de perte en capital au moment de la sortie.",
        "Quatrièmement, pour les stratégies en nue-propriété, la durée de démembrement (10 à 15 ans) est conçue pour correspondre à la période précédant la retraite.",
        "Un investissement débuté à 45-50 ans permet d'arriver à 60-65 ans avec un capital constitué et des revenus réguliers pour compléter la pension de retraite.",
      ],
    },
  ],
  faq: [
    { question: "Les SCPI sont-elles un bon placement pour préparer sa retraite ?", answer: "Oui, les SCPI sont adaptées à la préparation de la retraite grâce à leurs revenus réguliers, leur potentiel de valorisation à long terme et la diversification qu'elles offrent. L'horizon de placement recommandé est de 15 à 20 ans." },
    { question: "Quel rendement attendre d'une SCPI pour la retraite ?", answer: "Le taux de distribution moyen des SCPI de rendement se situe entre 4 % et 6 % brut par an. Le rendement net dépend de la fiscalité applicable (TMI + prélèvements sociaux). Ces chiffres sont donnés à titre indicatif et ne constituent pas une promesse de rendement." },
    { question: "SCPI en direct ou en assurance-vie pour la retraite ?", answer: "L'assurance-vie offre une fiscalité différée et un abattement après 8 ans, ce qui est avantageux pour un objectif retraite long terme. Le direct offre plus de choix de SCPI mais une fiscalité immédiate. Le choix dépend de votre TMI et de vos objectifs de transmission." },
    { question: "Quel est l'avantage de la nue-propriété de SCPI pour la retraite ?", answer: "La nue-propriété permet d'acquérir des parts à prix réduit (décote 30-40 %), sans fiscalité pendant la période de démembrement. À l'issue (10-15 ans), au moment de la retraite, l'investisseur récupère la pleine propriété et perçoit les loyers." },
    { question: "Peut-on investir en SCPI après 60 ans pour la retraite ?", answer: "Oui, c'est possible mais l'horizon est plus court. Il est recommandé de privilégier des SCPI de distribution pour percevoir des revenus rapidement, et de choisir des SCPI avec un bon historique et une bonne liquidité." },
    { question: "Quel budget mensuel pour préparer sa retraite avec des SCPI ?", answer: "Cela dépend de l'objectif de revenu visé. Pour un complément de 500 € par mois, un investissement programmé de 300 à 500 € par mois sur 15-20 ans peut être suffisant (sous réserve du rendement effectif). Un CGP-CIF peut vous aider à définir l'effort d'épargne nécessaire." },
    { question: "Les revenus des SCPI sont-ils imposés à la retraite ?", answer: "Oui, les loyers perçus sont imposés dans la catégorie des revenus fonciers (TMI + PS 17,2 %). À la retraite, la TMI est souvent plus faible, ce qui réduit l'imposition par rapport à la période d'activité." },
    { question: "SCPI ou PER pour la retraite : quel est le meilleur choix ?", answer: "Les deux sont complémentaires. Le PER offre une déduction fiscale à l'entrée mais un blocage des fonds. Les SCPI offrent plus de flexibilité et de liquidité. Une stratégie patrimoniale peut combiner les deux pour diversifier les sources de revenus à la retraite." },
    { question: "Faut-il investir dans plusieurs SCPI pour préparer sa retraite ?", answer: "Oui, la diversification entre plusieurs SCPI (différents secteurs, sociétés de gestion) est recommandée pour réduire le risque. Un portefeuille de 3 à 5 SCPI constitue une base équilibrée." },
    { question: "Quelle est la durée minimale d'investissement recommandée ?", answer: "L'horizon minimal recommandé est de 10 à 15 ans pour amortir les frais de souscription et bénéficier de l'effet de capitalisation. Idéalement, 15 à 20 ans pour une préparation retraite optimale." },
    { question: "Un conseiller est-il nécessaire pour préparer sa retraite avec des SCPI ?", answer: "Oui, fortement recommandé. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, vous aide à définir votre objectif de revenu, choisir la stratégie adaptée et sélectionner les SCPI en fonction de votre profil." },
    { question: "Peut-on cumuler plusieurs types de SCPI pour la retraite ?", answer: "Oui, c'est même recommandé. On peut combiner SCPI de distribution (revenus réguliers), SCPI à capitalisation (croissance du capital) et SCPI en nue-propriété (préparation à moyen terme) pour diversifier les sources de revenus." },
  ],
  ctaTitle: "Vous souhaitez préparer votre retraite avec des SCPI ?",
  ctaText: "Un échange permet d'évaluer votre situation, votre objectif de revenu complémentaire et la stratégie la plus adaptée. Eric Bellaiche, CGP-CIF, vous accompagne dans la construction de votre projet retraite.",
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/conseiller-scpi/', label: 'Conseiller SCPI : pourquoi se faire accompagner', position: 'inline' },
    { href: '/articles/scpi-revenus-complementaires/', label: 'SCPI pour revenus complémentaires', position: 'inline' },
    { href: '/articles/scpi-fiscalite/', label: 'SCPI et fiscalité : impact fiscal avant d\'investir', position: 'inline' },
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie : comparaison pour la retraite', position: 'inline' },
  ],
  externalLinks: [
    { href: 'https://maximusscpi.com/', label: 'MaximusSCPI', onlyInScpi: true },
  ],
  hasRisks: true,
};

export default article;
