import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'structurer-son-patrimoine',
  category: 'patrimoine',
  title: 'Structurer son patrimoine : méthode pour organiser ses placements et son immobilier',
  metaTitle: 'Structurer son patrimoine : méthode pour organiser ses placements et son immobilier | Eric Bellaiche',
  metaDescription: "Structurer son patrimoine, c'est organiser ses placements, son immobilier et son épargne dans une stratégie cohérente. Diversification, enveloppes fiscales, répartition : la méthode complète.",
  canonical: 'https://eric-bellaiche.fr/articles/structurer-son-patrimoine/',
  badge: 'Structuration patrimoine &bull; CGP-CIF &bull; ORIAS 13001580',
  intro: "Beaucoup d'épargnants accumulent des produits financiers au fil du temps sans vision d'ensemble : un livret A ouvert il y a vingt ans, une assurance-vie souscrite auprès d'une banque, un PER ouvert pour la défiscalisation, un investissement locatif saisi sur un coup de tête. Le résultat est souvent un patrimoine déséquilibré, fiscalement sous-optimal, et qui ne correspond pas aux objectifs réels. Structurer son patrimoine, c'est l'inverse de cette approche fragmentée. C'est organiser l'ensemble de ses actifs, de son épargne et de ses investissements dans un cadre cohérent, aligné sur des objectifs clairs, une fiscalité maîtrisée et une diversification adaptée. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, accompagne ses clients dans cette démarche de structuration patrimoniale.",
  shortAnswer: "Structurer son patrimoine consiste à organiser ses actifs (immobilier, placements financiers, épargne) et ses passifs (crédits) dans une stratégie cohérente et diversifiée. La méthode repose sur cinq piliers : un état des lieux complet de sa situation, la définition d'objectifs clairs (court, moyen, long terme), le choix des enveloppes fiscales adaptées (assurance-vie, PER, PEA, immobilier), la diversification entre les classes d'actifs (immobilier, actions, obligations, liquidités), et un suivi régulier pour ajuster la stratégie. Une structuration réussie permet d'optimiser la fiscalité, de réduire les risques par la diversification, d'améliorer la performance nette et de préparer sereinement la retraite et la transmission.",
  summaryItems: [
    { label: 'Pourquoi structurer son patrimoine est essentiel', anchor: 'pourquoi-structurer' },
    { label: 'Les grands principes de la structuration patrimoniale', anchor: 'grands-principes' },
    { label: 'Les 5 étapes pour structurer son patrimoine', anchor: 'cinq-etapes' },
    { label: 'Tableau des enveloppes fiscales et de leurs usages', anchor: 'tableau-enveloppes' },
    { label: 'Diversification : immobilier, financier, liquidités', anchor: 'diversification' },
    { label: 'Erreurs fréquentes dans la structuration du patrimoine', anchor: 'erreurs-frequentes' },
    { label: 'Exemple pédagogique anonymisé', anchor: 'exemple-pedagogique' },
    { label: "Méthode Eric Bellaiche pour structurer son patrimoine", anchor: 'methode' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 19,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['structuration patrimoine', 'diversification', 'épargne', 'placements', 'immobilier', 'CGP-CIF'],
  sections: [
    {
      id: 'pourquoi-structurer',
      title: 'Pourquoi structurer son patrimoine est essentiel',
      level: 'h2',
      type: 'normal',
      content: [
        'La structuration du patrimoine est une démarche qui consiste à organiser l\'ensemble de ses actifs et passifs dans un cadre cohérent, en fonction d\'objectifs définis et d\'une tolérance au risque mesurée. Elle s\'oppose à l\'approche consistant à accumuler des produits sans vision globale, qui conduit souvent à des déséquilibres préjudiciables.',
        'Un patrimoine non structuré présente plusieurs risques : une fiscalité excessive faute d\'avoir choisi les bonnes enveloppes, une concentration excessive sur une classe d\'actifs (trop d\'immobilier, trop d\'actions, trop de liquidités), un endettement mal maîtrisé, une absence de liquidité en cas de besoin, ou au contraire une épargne de précaution trop importante qui ne génère aucun rendement.',
        'Les bénéfices d\'une structuration patrimoniale bien menée sont nombreux :',
        '- Optimisation fiscale : chaque enveloppe (assurance-vie, PER, PEA, immobilier) a un régime fiscal spécifique. Bien structuré, un patrimoine permet de réduire l\'imposition sur les revenus et les plus-values.',
        '- Diversification du risque : répartir ses actifs entre plusieurs classes (immobilier, actions, obligations, monétaire) et plusieurs secteurs réduit la volatilité globale du patrimoine.',
        '- Cohérence avec les objectifs : un patrimoine structuré distingue clairement l\'épargne de précaution (accessible immédiatement), l\'épargne projet (moyen terme) et l\'épargne retraite/transmission (long terme).',
        '- Lisibilité : savoir précisément ce que l\'on possède, où cela se trouve, combien cela rapporte net de frais et de fiscalité.',
        '- Adaptabilité : un patrimoine structuré peut évoluer dans le temps en fonction des changements de situation (mariage, naissance, changement de statut professionnel, départ en retraite).',
        'La structuration n\'est pas un exercice ponctuel. Elle doit être révisée périodiquement pour tenir compte de l\'évolution de la situation personnelle, de la fiscalité et des marchés.',
      ],
    },
    {
      id: 'grands-principes',
      title: 'Les grands principes de la structuration patrimoniale',
      level: 'h2',
      type: 'list',
      content: [
        "La structuration d'un patrimoine repose sur plusieurs principes fondamentaux qui guident l'ensemble des décisions. Les voici :",
      ],
      listItems: [
        'La séparation des temporalités : distinguer l\'épargne de précaution (3 à 6 mois de revenus, disponible immédiatement), l\'épargne projet (3 à 8 ans, placement équilibré) et l\'épargne longue (8 ans et plus, investissement dynamique).',
        'La diversification : ne pas concentrer tous ses actifs sur une même classe (immobilier, actions, obligations, monétaire) ni sur un même secteur. La diversification est le premier levier de réduction du risque.',
        'L\'adéquation fiscale : choisir les enveloppes en fonction de sa TMI actuelle et future, de son exposition à l\'IFI, et de ses objectifs de transmission. Un PER n\'est pas pertinent dans toutes les situations.',
        'La liquidité mesurée : disposer de suffisamment d\'actifs liquides pour faire face aux imprévus, mais pas trop, car les liquidités non rémunérées perdent du pouvoir d\'achat avec l\'inflation.',
        'L\'effet de levier maîtrisé : l\'emprunt peut être un puissant accélérateur de constitution de patrimoine, mais un endettement excessif ou mal structuré peut fragiliser l\'ensemble.',
        'La cohérence avec le profil de risque : chaque investissement doit correspondre à la capacité de perte et à l\'horizon de placement. On n\'investit pas en actions à court terme ni en produits monétaires à 20 ans.',
        'L\'anticipation de la transmission : la structuration doit intégrer les aspects successoraux dès le départ, car les choix effectués (régime matrimonial, détention en direct ou via une enveloppe) ont des conséquences fiscales importantes.',
        'La révision périodique : un patrimoine se structure et se restructure dans le temps. Une revue annuelle ou biannuelle permet d\'ajuster la stratégie.',
      ],
    },
    {
      id: 'cinq-etapes',
      title: 'Les 5 étapes pour structurer son patrimoine',
      level: 'h2',
      type: 'normal',
      content: [
        "La structuration d'un patrimoine suit un processus logique en 5 étapes. Chaque étape est importante et conditionne la réussite des suivantes.",
        "1. Faire un état des lieux exhaustif : la première étape consiste à recenser l'intégralité de son patrimoine : actifs immobilier (résidence principale, secondaire, locatif, SCPI, SCI), actifs financiers (assurance-vie, PER, PEA, comptes-titres, livrets, cryptomonnaies), passifs (crédits immobiliers, crédits à la consommation, découverts), revenus et charges. Cet inventaire doit être le plus précis possible, avec les valeurs actualisées.",
        "2. Définir ses objectifs personnels : un patrimoine n'a de sens qu'au regard des objectifs de la personne ou du couple. Ces objectifs peuvent être : acheter une résidence principale, financer les études des enfants, préparer sa retraite, transmettre un patrimoine, optimiser sa fiscalité, constituer une épargne de précaution, ou une combinaison de plusieurs de ces objectifs. Chaque objectif doit être chiffré et daté.",
        "3. Analyser sa situation fiscale : la fiscalité personnelle conditionne le choix des enveloppes et des investissements. Il est essentiel de connaître sa TMI, son exposition à l'IFI, ses prélèvements sociaux, ses éventuels déficits fonciers, ses plus-values latentes, et sa situation au regard de l'impôt sur la fortune immobilière.",
        "4. Déterminer une répartition cible : en fonction des objectifs, de l'horizon et de la tolérance au risque, on définit une répartition entre les grandes classes d'actifs : immobilier, actions, obligations, produits monétaires, liquidités. Cette répartition est la clé de voûte de la structuration.",
        "5. Choisir les enveloppes et mettre en œuvre : une fois la répartition cible définie, on sélectionne les enveloppes les plus adaptées pour loger chaque type d'actif en optimisant la fiscalité. On met ensuite en œuvre les décisions : arbitrages, ouvertures de contrats, souscriptions, donations.",
        "Ces 5 étapes peuvent être réalisées en autonomie par un épargnant averti, mais l'accompagnement d'un CGP-CIF est recommandé pour les situations complexes ou pour éviter les erreurs coûteuses.",
      ],
    },
    {
      id: 'tableau-enveloppes',
      title: 'Tableau des enveloppes fiscales et de leurs usages',
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous présente les principales enveloppes fiscales et leurs caractéristiques pour vous aider à choisir la structure adaptée à chaque objectif patrimonial.",
      ],
      table: {
        headers: ['Enveloppe', 'Fiscalité des gains', 'Plafond', 'Disponibilité', 'Usage principal'],
        rows: [
          ['Livret A / LDD / LEP', 'Exonéré d\'impôt et de PS', '22 950 € / 12 000 € / 10 000 €', 'Immédiate', 'Épargne de précaution'],
          ['Assurance-vie (fonds euros)', 'Prélèvement forfaitaire unique (PFU) 30 % ou IR après 8 ans (abattement 4 600 €)', 'Aucun', 'Disponible (rachat partiel)', 'Épargne sécurisée moyen/long terme'],
          ['Assurance-vie (UC)', 'PFU 30 % ou IR après 8 ans (abattement 4 600 €). Exonération en cas de décès', 'Aucun', 'Disponible (rachat partiel)', 'Investissement dynamique, transmission'],
          ['PER individuel', 'Déduction des versements du RFR. Sortie en capital ou rente. Imposition de la rente à l\'IR', 'Plafond annuel : 10 % des revenus (max 35 194 € en 2024)', 'Blocage jusqu\'à la retraite (sauf exceptions)', 'Préparation retraite, déduction fiscale'],
          ['PEA', 'Exonération d\'IR après 5 ans (PS 17,2 % dus)', '150 000 € (225 000 € pour PEA-PME)', 'Disponible après 5 ans', 'Investissement actions long terme'],
          ['Compte-titres ordinaire', 'PFU 30 % (ou IR au choix)', 'Aucun', 'Disponible immédiatement', 'Tous types de valeurs mobilières'],
          ['SCPI en direct', 'Revenus fonciers imposés à la TMI + PS 17,2 %. Plus-values au PFU 30 %', 'Aucun', 'Peu liquide (délai de cession)', 'Diversification immobilière'],
          ['SCI à l\'IR', 'Transparence fiscale : revenus imposés à l\'IR des associés au prorata', 'Aucun', 'Dépend des statuts', 'Gestion collective de l\'immobilier'],
          ['SCI à l\'IS', 'Imposition à l\'IS (15 % jusqu\'à 42 500 €, 25 % au-delà). Dividendes imposés à l\'IR', 'Aucun', 'Dépend des statuts', 'Optimisation pour transmission'],
          ['Immobilier locatif (Pinel)', 'Réduction d\'impôt (9 à 12 % selon durée)', '300 000 € par an', 'Blocage location 6/9/12 ans', 'Défiscalisation immobilière'],
        ],
      },
    },
    {
      id: 'diversification',
      title: 'Diversification : immobilier, financier, liquidités',
      level: 'h2',
      type: 'normal',
      content: [
        'La diversification est le principe fondamental de toute structuration patrimoniale. Elle consiste à répartir ses actifs entre différentes classes pour réduire le risque global, car les classes d\'actifs n\'évoluent pas de manière corrélée.',
        'Immobilier : l\'immobilier représente souvent la part la plus importante du patrimoine des Français. Il inclut la résidence principale, la résidence secondaire, les investissements locatifs, les SCPI et les parts de SCI. L\'immobilier offre des avantages : effet de levier du crédit, valorisation potentielle à long terme, revenus locatifs. Mais il présente aussi des inconvénients : faible liquidité, coûts de transaction élevés, concentration du risque, fiscalité parfois lourde (IFI, TMI sur les revenus fonciers).',
        "Actifs financiers : cette classe regroupe les actions (via PEA, assurance-vie UC, compte-titres), les obligations (fonds euros, obligations d'État ou d'entreprises), les produits monétaires et les actifs diversifiés. Les actifs financiers offrent une grande liquidité, une large diversification possible, et une fiscalité souvent plus favorable que l'immobilier direct à long terme. Ils sont plus volatils à court terme mais permettent une meilleure diversification sectorielle et géographique.",
        "Liquidités : l'épargne de précaution (livrets, comptes courants, fonds monétaires) constitue le socle de sécurité du patrimoine. Son montant recommandé est généralement de 3 à 6 mois de revenus. Au-delà, les liquidités non rémunérées ou faiblement rémunérées perdent du pouvoir d'achat. L'enjeu est de trouver le bon équilibre entre sécurité et performance.",
        "Exemple de répartition pour un profil équilibré (horizon 10 ans, tolérance au risque modérée) : 10 à 15 % d'épargne de précaution, 20 à 30 % d'immobilier (hors résidence principale), 25 à 35 % d'actions diversifiées, 20 à 30 % d'obligations/fonds euros, 5 à 10 % d'actifs alternatifs (SCPI, private equity, matières premières). Cette répartition est donnée à titre indicatif. Chaque situation nécessite une analyse personnalisée.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans la structuration du patrimoine',
      level: 'h2',
      type: 'list',
      content: [
        'De nombreux épargnants commettent des erreurs de structuration qui peuvent coûter cher à long terme. Voici les plus fréquentes :',
      ],
      listItems: [
        'Avoir trop de liquidités non rémunérées : conserver des dizaines de milliers d\'euros sur des comptes courants ou livrets sans rendement réel, ce qui entraîne une perte de pouvoir d\'achat face à l\'inflation.',
        'Être surexposé à l\'immobilier : concentrer la quasi-totalité de son patrimoine sur un ou deux biens immobiliers, sans diversification financière, ce qui crée un risque d\'illiquidité et de concentration.',
        'Multiplier les contrats d\'assurance-vie sans stratégie : ouvrir plusieurs contrats chez différentes banques sans cohérence, avec des frais élevés et des supports redondants.',
        'Investir uniquement pour l\'avantage fiscal : choisir un produit uniquement parce qu\'il est défiscalisant (PER, Pinel, Girardin) sans vérifier sa cohérence avec le reste du patrimoine.',
        'Négliger l\'effet des frais : sous-estimer l\'impact des frais de gestion, des frais d\'entrée, des frais d\'arbitrage et des frais de sortie sur la performance nette à long terme.',
        'Confondre épargne de précaution et épargne investie : utiliser des placements risqués pour des projets court terme ou au contraire laisser sur des livrets une épargne destinée à la retraite.',
        'Oublier la prévoyance dans la structuration : ne pas prévoir de couverture décès, invalidité ou incapacité, ce qui peut gravement déséquilibrer un patrimoine en cas d\'accident de la vie.',
        'Ne pas tenir compte de l\'inflation : investir uniquement en fonds euros ou livrets sans considérer que l\'inflation réduit le rendement réel des placements sécurisés.',
        'Ignorer la fiscalité de sortie : ouvrir un PER sans anticiper la TMI à la retraite, investir en SCPI sans mesurer l\'imposition des revenus fonciers.',
        'Ne jamais réviser sa structuration : conserver la même répartition d\'actifs pendant 10 ou 15 ans sans l\'ajuster aux changements de situation personnelle, fiscale ou économique.',
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique anonymisé',
      level: 'h2',
      type: 'normal',
      content: [
        "Situation : un couple marié sous communauté, 40 ans et 38 ans, deux enfants de 6 et 8 ans. Revenus annuels cumulés : 150 000 €. TMI : 30 %. Résidence principale : 500 000 €, crédit en cours de 250 000 € à 1,5 % sur 18 ans. Assurance-vie : 120 000 € répartis sur 4 contrats (dont 2 anciens avec frais de gestion à 0,9 %). PER : 25 000 € chacun. PEA : 20 000 € (actions françaises). Épargne de précaution : 80 000 € sur livret A et LDD. SCPI : 30 000 € en direct. Pas de prévoyance incapacité. Objectifs : financer les études des enfants (dans 10-12 ans), préparer la retraite (dans 22-25 ans), optimiser la fiscalité.",
        "Les problèmes de structuration identifiés :",
        "- Épargne de précaution excessive : 80 000 € pour un couple dont les charges mensuelles sont de 5 000 €, soit 16 mois de revenus. 30 000 € (6 mois) suffisent, le solde de 50 000 € peut être investi.",
        "- Multiplicité des contrats d'assurance-vie : 4 contrats dont 2 avec des frais élevés. Proposition de regrouper sur 2 contrats performants avec frais réduits et meilleure sélection de supports.",
        "- Absence de diversification du PER : les deux PER sont investis en fonds euros, sans UC. Pour un horizon de 22-25 ans, une part d'UC (40-50 %) serait plus adaptée.",
        "- Pas de prévoyance incapacité : en cas d'arrêt de travail prolongé, les revenus du couple chuteraient significativement.",
        "- PEA investi uniquement en actions françaises : manque de diversification géographique.",
        "Les pistes d'amélioration proposées : après analyse, un rééquilibrage est proposé : réduction de l'épargne de précaution à 30 000 €, réinvestissement des 50 000 € sur deux assurances-vie (un contrat pour les études des enfants, un pour la retraite), diversification des PER en intégrant des UC, mise en place d'une garantie incapacité de travail, internationalisation du PEA via des ETF monde.",
        "Cet exemple anonymisé ne constitue pas une recommandation personnalisée. Chaque situation nécessite une analyse spécifique.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour structurer son patrimoine",
      level: 'h2',
      type: 'method-steps',
      content: [
        "Eric Bellaiche, CGP-CIF, applique une méthode structurée en 7 étapes pour accompagner ses clients dans la structuration de leur patrimoine. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète de la situation, du profil investisseur, des objectifs, de l'horizon et de la capacité de perte.",
      ],
      methodSteps: [
        { title: 'Recueil et consolidation des données', description: "Collecte de l'ensemble des documents patrimoniaux : avis d'imposition, relevés de comptes, contrats d'assurance-vie, PER, PEA, actes immobiliers, SCPI, crédits, prévoyance, situation familiale. Consolidation dans un tableau de bord patrimonial complet." },
        { title: 'Analyse de la situation globale', description: "Diagnostic fiscal : TMI, IFI, prélèvements sociaux, plus-values latentes, déficits. Diagnostic patrimonial : répartition actuelle entre les classes d'actifs, taux d'endettement, liquidité, exposition au risque. Identification des forces, faiblesses et incohérences." },
        { title: 'Définition des objectifs et contraintes', description: "Identification précise des objectifs (court, moyen, long terme), de l'horizon de placement, de la capacité d'épargne mensuelle, de la tolérance au risque et des contraintes personnelles (situation professionnelle, familiale, santé)." },
        { title: 'Détermination d\'une allocation cible', description: "Proposition d'une répartition cible entre les grandes classes d'actifs (immobilier, actions, obligations, monétaire, liquidités) en fonction des objectifs, de l'horizon et du profil de risque. Cette allocation est personnalisée et révisable." },
        { title: 'Choix des enveloppes fiscales adaptées', description: "Sélection des enveloppes les plus pertinentes pour loger chaque type d'actif : assurance-vie, PER, PEA, immobilier en direct, SCPI, SCI. Comparaison de l'impact fiscal de chaque option en fonction de la TMI et des objectifs." },
        { title: 'Mise en œuvre des arbitrages et investissements', description: "Accompagnement dans les décisions : arbitrage des contrats existants, ouverture de nouvelles enveloppes, souscriptions, répartition de l'épargne mensuelle, mise en place des couvertures de prévoyance. Chaque décision est documentée." },
        { title: 'Suivi et révision périodique', description: "Suivi annuel ou semestriel de la stratégie. Révision de l'allocation en fonction de l'évolution de la situation personnelle, des marchés, de la fiscalité et de l'approche des échéances (retraite, études des enfants). Ajustements si nécessaire." },
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance sur la structuration patrimoniale',
      level: 'h2',
      type: 'normal',
      content: [
        "La structuration d'un patrimoine est un exercice exigeant qui nécessite de prendre du recul et de ne pas céder aux sollicitations commerciales. Plusieurs points méritent une attention particulière :",
        "- Une structuration patrimoniale ne garantit pas un rendement ni une performance. Elle vise à organiser le patrimoine de manière cohérente, pas à maximiser le rendement à tout prix.",
        "- La fiscalité est un paramètre important, mais elle ne doit pas être le seul moteur des décisions. Un investissement fiscalement avantageux mais inadapté au profil de risque ou à l'horizon peut s'avérer contre-productif.",
        "- La diversification réduit le risque mais ne l'élimine pas. Elle peut également limiter le potentiel de hausse en période de marché favorable.",
        "- Les frais sont rarement neutres. Comparez toujours les frais de gestion, frais d'entrée, frais d'arbitrage et frais de sortie entre les différentes enveloppes.",
        "- Une structuration n'est jamais définitive. Elle doit être révisée périodiquement, notamment lors des changements significatifs (mariage, naissance, héritage, changement de TMI, départ en retraite).",
        "- Certains placements sont peu liquides (SCPI, immobilier direct, private equity). Assurez-vous de disposer d'une épargne de précaution suffisante avant d'investir dans ces actifs.",
        "Ces points ne remettent pas en cause l'intérêt de la structuration patrimoniale, mais rappellent qu'elle doit être menée avec méthode et accompagnement professionnel.",
      ],
    },
  ],
  faq: [
    { question: "Qu'est-ce que structurer son patrimoine ?", answer: "Structurer son patrimoine, c'est organiser l'ensemble de ses actifs (immobilier, placements, épargne) et passifs (crédits) dans une stratégie cohérente, diversifiée et adaptée à ses objectifs personnels, sa fiscalité et sa tolérance au risque." },
    { question: "Pourquoi est-il important de structurer son patrimoine ?", answer: "Pour éviter les déséquilibres : trop d'immobilier, trop de liquidités non rémunérées, fiscalité sous-optimale, absence de diversification. Une bonne structuration permet d'optimiser la performance nette, de réduire les risques et d'aligner le patrimoine sur ses objectifs de vie." },
    { question: "À partir de quel montant faut-il structurer son patrimoine ?", answer: "Il n'y a pas de seuil minimum. Dès lors que vous avez des objectifs patrimoniaux et des actifs à organiser, la structuration est utile. Un petit patrimoine bien structuré performe souvent mieux qu'un patrimoine moyen mal organisé." },
    { question: "Quelle est la différence entre structuration et diversification ?", answer: "La diversification est l'un des piliers de la structuration. La structuration est un concept plus large qui inclut la définition d'objectifs, le choix des enveloppes fiscales, la répartition entre classes d'actifs et le suivi dans le temps." },
    { question: "Faut-il un CGP pour structurer son patrimoine ou peut-on le faire seul ?", answer: "Un épargnant averti peut structurer lui-même son patrimoine s'il maîtrise la fiscalité, les enveloppes et la diversification. Mais un CGP apporte une expertise, un regard extérieur et une méthode éprouvée qui évitent les erreurs coûteuses." },
    { question: "À quelle fréquence faut-il réviser sa structuration patrimoniale ?", answer: "Idéalement une fois par an, ou à chaque changement significatif de situation (mariage, naissance, héritage, changement de TMI, départ en retraite, mutation professionnelle)." },
    { question: "Quelle part d'immobilier dans un patrimoine structuré ?", answer: "Il n'y a pas de règle universelle. Pour un profil équilibré, l'immobilier (hors résidence principale) représente généralement 20 à 40 % du patrimoine financier et immobilier, en fonction des objectifs, de l'horizon et de la tolérance au risque." },
    { question: "Quelle est la meilleure enveloppe pour commencer à structurer son épargne ?", answer: "L'assurance-vie est souvent l'enveloppe de base recommandée en raison de sa flexibilité, de sa fiscalité avantageuse après 8 ans, de son usage en transmission et de sa capacité à loger différents supports (fonds euros, UC, SCPI)." },
    { question: "Le PER est-il toujours intéressant pour structurer son patrimoine ?", answer: "Non, le PER est pertinent quand la TMI actuelle est élevée et que la TMI future estimée sera plus basse. Il n'est pas adapté si vous êtes dans une tranche faible ou si vous avez besoin d'épargne disponible avant la retraite." },
    { question: "Peut-on structurer son patrimoine en ligne ?", answer: "Oui, la structuration patrimoniale peut être réalisée à distance avec un CGP-CIF en visioconférence, avec transmission sécurisée des documents et signature électronique. C'est ce que propose Eric Bellaiche dans sa pratique." },
  ],
  ctaTitle: 'Vous souhaitez structurer votre patrimoine avec une méthode éprouvée ?',
  ctaText: 'Un premier échange gratuit permet de faire le point sur votre situation et d\'identifier les axes de structuration prioritaires. Aucun engagement, aucune recommandation personnalisée sans analyse préalable.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne : méthode et analyse', position: 'inline' },
    { href: '/articles/conseiller-patrimoine-en-ligne/', label: 'Conseiller en gestion de patrimoine en ligne', position: 'inline' },
    { href: '/articles/erreurs-gestion-patrimoine/', label: 'Les erreurs fréquentes en gestion de patrimoine', position: 'inline' },
    { href: '/articles/preparer-retraite-patrimoine/', label: 'Préparer sa retraite avec son patrimoine', position: 'inline' },
    { href: '/articles/per-ou-assurance-vie/', label: 'PER ou assurance-vie : quelle enveloppe choisir', position: 'inline' },
  ],
};

export default article;
