import { ArticleContent } from './articleTypes';

const article: ArticleContent = {
  slug: 'transmission-patrimoine-famille-recomposee',
  category: 'patrimoine',
  title: 'Transmission du patrimoine en famille recomposée : points de vigilance',
  metaTitle: 'Transmission du patrimoine en famille recomposée : points de vigilance | Eric Bellaiche',
  metaDescription: "Transmettre son patrimoine dans une famille recomposée est complexe : succession, assurance-vie, donation, régime matrimonial, clause bénéficiaire. Les points clés pour protéger ses proches.",
  canonical: 'https://eric-bellaiche.fr/articles/transmission-patrimoine-famille-recomposee/',
  badge: 'Transmission &bull; CGP-CIF &bull; ORIAS 13001580',
  intro: "Les familles recomposées représentent une part croissante des foyers français. Or, le droit successoral français est conçu pour la famille nucléaire traditionnelle : conjoint et enfants communs. En l'absence d'anticipation, la transmission du patrimoine dans une famille recomposée peut aboutir à des situations profondément injustes, voire à des conflits familiaux durables. Le conjoint survivant peut se retrouver démuni, les enfants d'un premier lit peuvent être avantagés ou inversement, et la fiscalité peut alourdir considérablement la charge successorale. Eric Bellaiche, CGP-CIF inscrit ORIAS n°13001580, accompagne les familles recomposées dans l'anticipation et l'optimisation de leur transmission patrimoniale.",
  shortAnswer: "La transmission du patrimoine dans une famille recomposée nécessite une anticipation minutieuse en raison des règles successorales qui favorisent les enfants plutôt que le conjoint survivant non parent des enfants. Les principaux outils à connaître sont : le régime matrimonial (communauté ou séparation de biens, avec ou sans clauses spécifiques), l'assurance-vie (qui permet de transmettre des capitaux au conjoint sans droits de succession et avec des abattements spécifiques par bénéficiaire), la donation entre époux (qui permet d'améliorer la protection du conjoint survivant), les donations-partages (qui permettent de transmettre de son vivant en équilibrant les parts entre enfants de lits différents), et le testament (qui permet de déroger partiellement aux règles successorales dans la limite de la quotité disponible). Une stratégie de transmission bien conçue permet de protéger le conjoint survivant, d'équilibrer les parts entre enfants de lits différents et d'optimiser la fiscalité successorale.",
  summaryItems: [
    { label: 'Pourquoi la transmission est complexe en famille recomposée', anchor: 'complexite-transmission' },
    { label: 'Les règles successorales applicables', anchor: 'regles-successorales' },
    { label: 'Les outils juridiques pour organiser sa transmission', anchor: 'outils-juridiques' },
    { label: "Tableau des outils de transmission et de leurs effets", anchor: 'tableau-outils' },
    { label: "Le rôle clé de l'assurance-vie dans la transmission", anchor: 'assurance-vie-transmission' },
    { label: 'Erreurs fréquentes dans la transmission en famille recomposée', anchor: 'erreurs-frequentes' },
    { label: 'Exemple pédagogique anonymisé', anchor: 'exemple-pedagogique' },
    { label: "Méthode Eric Bellaiche pour la transmission en famille recomposée", anchor: 'methode' },
    { label: 'Points de vigilance', anchor: 'points-vigilance' },
    { label: 'Questions fréquentes', anchor: 'faq' },
  ],
  readingTime: 19,
  updatedAt: '2026-06-11',
  author: 'Eric Bellaiche, CGP-CIF',
  tags: ['transmission', 'famille recomposée', 'succession', 'donation', 'assurance-vie', 'CGP-CIF'],
  sections: [
    {
      id: 'complexite-transmission',
      title: 'Pourquoi la transmission est complexe en famille recomposée',
      level: 'h2',
      type: 'normal',
      content: [
        "La transmission du patrimoine en famille recomposée est l'un des sujets les plus complexes de la gestion de patrimoine, car le droit successoral français repose sur des principes qui ne sont pas adaptés à cette configuration familiale.",
        "Le premier principe est celui de la réserve héréditaire : les enfants (de tous lits confondus) sont héritiers réservataires, ce qui signifie qu'une partie du patrimoine leur revient obligatoirement. Le conjoint survivant, quant à lui, n'est pas héritier réservataire. Il peut être totalement exclu de la succession si des enfants existent, sauf protection spécifique mise en place de son vivant par le défunt.",
        "Le deuxième principe est l'égalité entre les enfants : les enfants héritent à parts égales, quel que soit leur lien avec le conjoint survivant. Ainsi, les enfants d'un premier lit ont les mêmes droits successoraux sur le patrimoine de leur parent que les enfants communs. Cela peut sembler équitable, mais dans une famille recomposée, cela signifie que le conjoint survivant peut se retrouver à devoir partager la résidence principale avec les enfants de son conjoint décédé, voire à devoir la vendre pour liquider la succession.",
        "Le troisième principe est l'absence de droits successoraux entre beaux-parents et beaux-enfants. Un beau-parent n'a aucun droit sur la succession de son beau-enfant, et inversement. En l'absence d'anticipation, les enfants du conjoint décédé n'ont aucun lien successoral avec leur beau-parent survivant.",
        "Ces règles, conçues pour protéger les enfants, peuvent aboutir à des situations où le conjoint survivant se retrouve dans une situation financière difficile, notamment s'il n'a pas de patrimoine personnel et que la résidence principale appartenait au conjoint décédé. L'anticipation est donc essentielle pour concilier la protection du conjoint survivant, l'équité entre les enfants et l'optimisation fiscale.",
      ],
    },
    {
      id: 'regles-successorales',
      title: 'Les règles successorales applicables',
      level: 'h2',
      type: 'list',
      content: [
        "Pour comprendre les enjeux de la transmission en famille recomposée, il est indispensable de connaître les règles successorales de base. Voici les principales :",
      ],
      listItems: [
        "La réserve héréditaire des enfants : les enfants (communs et d'un premier lit) ont droit à une part minimale du patrimoine de leurs parents. S'il y a un enfant, sa réserve est de 50 % du patrimoine. Pour deux enfants, 66,67 % (33,33 % chacun). Pour trois enfants et plus, 75 % (25 % chacun). Le conjoint survivant n'a pas de réserve en présence d'enfants.",
        'La quotité disponible : c\'est la part du patrimoine dont le défunt peut librement disposer par donation ou testament, en dehors de la réserve des enfants. Elle est de 50 % avec un enfant, 33,33 % avec deux enfants, 25 % avec trois enfants ou plus.',
        "Les droits du conjoint survivant : à défaut de dispositions particulières, le conjoint survivant (marié) a le choix entre l'usufruit de la totalité du patrimoine ou la pleine propriété d'un quart. Dans une famille recomposée, ce choix a des implications très différentes selon que la résidence principale appartient au défunt ou est détenue en commun.",
        "La situation des concubins et partenaires de Pacs : le concubin n'a aucun droit successoral légal. Le partenaire de Pacs est exonéré de droits de succession mais n'est pas héritier s'il existe des enfants. Seul le conjoint marié a une protection successorale légale.",
        "L'absence de lien successoral entre beaux-parents et beaux-enfants : un beau-parent ne peut pas transmettre son patrimoine à ses beaux-enfants sans dispositions spécifiques (assurance-vie, testament avec droits limités par la réserve).",
        "La fiscalité des successions : le conjoint survivant est exonéré de droits de succession. Les enfants bénéficient d'un abattement de 100 000 € chacun (tous les 15 ans). Au-delà, les droits sont progressifs de 5 à 45 %. Il n'y a pas d'abattement spécifique pour les beaux-enfants (sauf adoption simple ou donation préalable).",
      ],
    },
    {
      id: 'outils-juridiques',
      title: 'Les outils juridiques pour organiser sa transmission',
      level: 'h2',
      type: 'normal',
      content: [
        "Face à la complexité des règles successorales dans une famille recomposée, plusieurs outils juridiques permettent d'organiser la transmission de manière plus équilibrée et protectrice. Ces outils doivent être combinés en fonction de la situation familiale, de la composition du patrimoine et des objectifs de chacun.",
        "La donation entre époux (ou donation au dernier vivant) : c'est l'outil de protection du conjoint survivant le plus courant et le plus important. Elle permet au conjoint survivant d'opter, au moment du décès, pour l'usufruit de la totalité du patrimoine (ce qui lui permet de continuer à utiliser les biens et d'en percevoir les revenus) ou pour un quart en pleine propriété. Dans une famille recomposée, l'usufruit est souvent préféré car il permet au conjoint survivant de rester dans la résidence principale et de continuer à percevoir les revenus des placements, tandis que les enfants (nus-propriétaires) récupéreront la pleine propriété au décès du conjoint survivant.",
        "La donation-partage : cet outil permet de transmettre de son vivant des biens à ses enfants, en les répartissant entre eux. Dans une famille recomposée, la donation-partage peut être utilisée pour équilibrer les parts entre les enfants d'un premier lit et les enfants communs. Elle peut être combinée avec un démembrement pour protéger le conjoint survivant (donation en nue-propriété aux enfants, avec usufruit conservé par le conjoint).",
        "Le testament : il permet de déroger dans une certaine mesure aux règles successorales, dans la limite de la quotité disponible. On peut par exemple léguer au conjoint survivant la quotité disponible en pleine propriété, en complément de ses droits légaux. Le testament est également utile pour léguer des biens spécifiques (résidence principale, meubles) ou pour désigner un exécuteur testamentaire.",
        "Le changement de régime matrimonial : pour les couples mariés, le choix du régime matrimonial a un impact direct sur la transmission. La communauté universelle avec clause d'attribution intégrale au conjoint survivant permet de transmettre l'ensemble du patrimoine au conjoint survivant sans droits de succession. Attention toutefois : cette clause ne protège pas des droits des héritiers réservataires (les enfants) sur la part du défunt dans la communauté.",
        "L'adoption simple : dans certains cas, l'adoption simple du beau-enfant par le beau-parent permet de créer un lien de filiation juridique et donc des droits successoraux. C'est une procédure lourde mais qui peut être pertinente dans certaines configurations familiales.",
        "L'assurance-vie, bien qu'elle ne soit pas un outil juridique à proprement parler, est un outil patrimonial majeur pour la transmission en famille recomposée. Elle fait l'objet d'un développement spécifique ci-dessous.",
      ],
    },
    {
      id: 'tableau-outils',
      title: 'Tableau des outils de transmission et de leurs effets',
      level: 'h2',
      type: 'table',
      content: [
        "Le tableau ci-dessous résume les principaux outils de transmission, leurs effets sur le conjoint survivant et sur les enfants, ainsi que les points de vigilance spécifiques aux familles recomposées.",
      ],
      table: {
        headers: ['Outil', 'Protection du conjoint', "Traitement des enfants", 'Fiscalité', 'Point de vigilance'],
        rows: [
          ['Donation entre époux', 'Usufruit ou 1/4 PP au choix', 'Enfants héritiers en nue-propriété ou 3/4 PP', 'Exonération entre époux', 'Ne protège pas si enfants vendent leurs droits'],
          ['Testament (quotité disponible)', 'Peut recevoir la QD en PP', 'Réserve héréditaire préservée', 'Exonération entre époux', 'Limité par le nombre d\'enfants'],
          ['Communauté universelle', 'Attribution de tous les biens', 'Enfants héritiers sur la part du défunt', 'Exonération entre époux', 'Risque de requalification'],
          ['Donation-partage', 'Peut conserver l\'usufruit', 'Parts égales ou inégales selon volonté', 'Abattement 100 000 €/enfant', 'N\'équilibre pas les beaux-enfants'],
          ['Assurance-vie', 'Capitaux hors succession', 'Bénéficiaires désignés librement', 'Abattement 152 500 €/bénéficiaire', 'Primes manifestement exagérées'],
          ['Adoption simple', 'Lien successoral créé', 'Beau-enfant devient héritier', 'Abattement enfant', 'Procédure lourde'],
          ['SCI avec démembrement', 'Maintien dans les lieux', 'Nue-propriété aux enfants', 'Droits de donation réduits', 'Gestion collective complexe'],
        ],
      },
    },
    {
      id: 'assurance-vie-transmission',
      title: "Le rôle clé de l'assurance-vie dans la transmission en famille recomposée",
      level: 'h2',
      type: 'normal',
      content: [
        "L'assurance-vie est un outil particulièrement puissant pour organiser la transmission dans une famille recomposée, car elle échappe en grande partie aux règles successorales classiques.",
        "Principe : les capitaux versés par l'assurance-vie au bénéficiaire désigné ne font pas partie de la succession. Ils sont transmis directement au bénéficiaire, sans passer par la succession et sans être soumis aux droits de succession dans les conditions habituelles. Cela permet de déroger à la réserve héréditaire, sous réserve du respect des règles relatives aux primes manifestement exagérées.",
        "Les avantages pour la famille recomposée sont considérables :",
        "- Le conjoint survivant peut être désigné comme bénéficiaire et recevoir des capitaux exonérés de droits de succession, même en présence d'enfants d'un premier lit.",
        "- Les beaux-enfants peuvent être désignés bénéficiaires (ce qu'ils ne peuvent pas être par succession directe sans lien de filiation).",
        "- L'assurance-vie permet d'équilibrer les parts entre enfants de lits différents, en attribuant des capitaux aux uns et d'autres biens aux autres.",
        "- Les capitaux transmis par assurance-vie bénéficient d'un abattement de 152 500 € par bénéficiaire (pour les primes versées avant 70 ans). Au-delà, ils sont taxés à 20 % jusqu'à 700 000 € puis à 31,25 %.",
        "Points de vigilance : les primes versées après 70 ans sont soumises à un régime spécifique (abattement global de 30 500 € pour l'ensemble des bénéficiaires). Les primes manifestement exagérées (disproportionnées par rapport au patrimoine et à l'âge de l'assuré) peuvent être réintégrées dans la succession par le juge, à la demande des héritiers réservataires.",
        "La rédaction de la clause bénéficiaire est cruciale. Une clause mal rédigée peut aboutir à une répartition non conforme à la volonté du souscripteur. Il est recommandé de la faire vérifier par un professionnel.",
      ],
    },
    {
      id: 'erreurs-frequentes',
      title: 'Erreurs fréquentes dans la transmission en famille recomposée',
      level: 'h2',
      type: 'list',
      content: [
        'Les erreurs de transmission en famille recomposée sont fréquentes et peuvent avoir des conséquences graves. Voici les plus courantes :',
      ],
      listItems: [
        "Ne rien anticiper en pensant que 'les enfants s'arrangeront entre eux'. C'est l'erreur la plus fréquente et la plus dangereuse. En l'absence d'anticipation, ce sont les règles successorales par défaut qui s'appliquent, et elles ne sont pas adaptées aux familles recomposées.",
        'Croire que le concubin ou le partenaire de Pacs est protégé par la loi. Un concubin n\'a aucun droit successoral. Un partenaire de Pacs est exonéré de droits mais n\'est pas héritier en présence d\'enfants.',
        'Confondre donation entre époux et communauté universelle. La donation entre époux permet une option au moment du décès. La communauté universelle avec clause d\'attribution intégrale est un régime matrimonial qui a des implications différentes.',
        'Rédiger une clause bénéficiaire d\'assurance-vie trop vague (exemple : « mes héritiers » ou « mon conjoint »). Une clause mal rédigée peut aboutir à une répartition non conforme à votre volonté.',
        'Oublier de mettre à jour la clause bénéficiaire après un divorce ou un remariage. Une clause désignant l\'ancien conjoint reste valable après divorce si elle n\'a pas été modifiée.',
        'Verser des primes excessives sur l\'assurance-vie juste avant le décès, sans considération pour la règle des primes manifestement exagérées qui peut faire réintégrer ces primes dans la succession.',
        'Donner des biens aux enfants d\'un premier lit sans prévoir la protection du conjoint survivant. Par exemple, donner la nue-propriété d\'un bien aux enfants peut priver le conjoint de son usufruit.',
        'Ne pas tenir compte de l\'ISF/IFI dans la stratégie de transmission. La transmission d\'un patrimoine immobilier important peut avoir des conséquences fiscales lourdes.',
        'Ignorer le droit de retour légal des ascendants : en l\'absence d\'enfant, les parents du défunt peuvent avoir droit à une partie de la succession, au détriment du conjoint survivant.',
        'Ne pas consulter un notaire et un CGP ensemble. La transmission patrimoniale nécessite une coordination entre le conseil juridique (notaire) et le conseil patrimonial (CGP).',
      ],
    },
    {
      id: 'exemple-pedagogique',
      title: 'Exemple pédagogique anonymisé',
      level: 'h2',
      type: 'normal',
      content: [
        "Situation : un couple remarié, Monsieur (55 ans) et Madame (48 ans). Monsieur a deux enfants d'un premier mariage (20 et 22 ans). Madame a un enfant d'une précédente relation (16 ans). Ils n'ont pas d'enfant commun. Ils sont mariés sous la communauté réduite aux acquêts.",
        "Patrimoine : résidence principale : 500 000 € (bien commun). Assurance-vie de Monsieur : 200 000 €, clause bénéficiaire actuelle : 'mon conjoint'. Assurance-vie de Madame : 80 000 €. PER de Monsieur : 60 000 €. Épargne financière commune : 120 000 €. Pas de donation entre époux. Pas de testament.",
        "Problèmes identifiés sans anticipation :",
        "- En l'absence de donation entre époux, au décès de Monsieur, Madame a le choix entre l'usufruit de la totalité (y compris la résidence principale) ou le quart en pleine propriété. Les enfants de Monsieur héritent de la réserve (66,67 % de la quotité disponible). Ils pourraient exiger le rachat de l'usufruit et forcer la vente de la résidence principale.",
        "- Les enfants de Monsieur héritent de la moitié de la communauté (parts de leur père) + de sa part dans les biens propres. Madame doit partager la résidence avec ses beaux-enfants.",
        "- L'enfant de Madame (beau-enfant de Monsieur) n'hérite de rien de Monsieur.",
        "- L'assurance-vie de Monsieur (200 000 €) bénéficie à Madame, ce qui est positif, mais les primes n'ont pas été optimisées.",
        "Stratégie proposée :",
        "1. Signature d'une donation entre époux : Madame pourra opter pour l'usufruit de la totalité au décès de Monsieur, lui permettant de conserver la résidence principale et les revenus des placements.",
        "2. Révision des clauses bénéficiaires des assurances-vie : clause plus précise avec répartition claire entre le conjoint et les enfants, en utilisant l'abattement de 152 500 € par bénéficiaire.",
        "3. Réalisation de donations-partages de Monsieur à ses enfants (nue-propriété de certains biens, Monsieur conservant l'usufruit) pour anticiper la transmission et éviter les conflits au moment de son décès.",
        "4. Souscription d'une assurance-vie par Monsieur au profit de son beau-enfant (enfant de Madame) pour lui transmettre des capitaux, puisqu'il n'a pas de droit successoral direct.",
        "5. Rédaction d'un testament pour préciser la répartition de la quotité disponible.",
        "Cet exemple anonymisé ne constitue pas une recommandation personnalisée. Chaque situation nécessite une analyse spécifique avec un notaire et un CGP-CIF.",
      ],
    },
    {
      id: 'methode',
      title: "Méthode Eric Bellaiche pour la transmission en famille recomposée",
      level: 'h2',
      type: 'method-steps',
      content: [
        "Eric Bellaiche, CGP-CIF, applique une méthode structurée en 6 étapes pour accompagner ses clients dans la transmission de leur patrimoine en famille recomposée. Aucune recommandation personnalisée n'est formulée sans analyse préalable complète de la situation, du profil investisseur, des objectifs, de l'horizon et de la capacité de perte. Les aspects juridiques sont coordonnés avec un notaire partenaire.",
      ],
      methodSteps: [
        { title: 'Analyse de la situation familiale et juridique', description: "Recueil de la composition familiale complète : enfants de chaque lit, régime matrimonial, donations antérieures, testaments existants, clauses bénéficiaires des assurances-vie. Analyse des droits successoraux de chaque membre de la famille." },
        { title: 'Identification des déséquilibres et des risques', description: "Repérage des situations à risque : conjoint non protégé, beaux-enfants exclus, conflit potentiel entre enfants de lits différents, fiscalité successorale excessive, clauses bénéficiaires inadaptées. Quantification des impacts pour chaque scénario." },
        { title: 'Proposition d\'une stratégie de protection du conjoint', description: "Recommandation des outils adaptés : donation entre époux, testament, changement de régime matrimonial, assurance-vie. Objectif : garantir au conjoint survivant un logement et des revenus suffisants." },
        { title: 'Équilibrage entre les enfants de lits différents', description: "Proposition d'une répartition équilibrée utilisant la donation-partage, l'assurance-vie, le démembrement. Recherche d'une solution acceptée par tous les membres de la famille pour prévenir les conflits futurs." },
        { title: 'Optimisation fiscale de la transmission', description: "Utilisation optimale des abattements successoraux (100 000 € par enfant tous les 15 ans), des abattements assurance-vie (152 500 € par bénéficiaire avant 70 ans), optimisation des primes versées après 70 ans. Planification dans le temps des donations." },
        { title: 'Coordination avec le notaire et suivi', description: "Rédaction des actes juridiques en coordination avec le notaire. Mise à jour régulière des clauses bénéficiaires. Révision de la stratégie à chaque changement familial (mariage, divorce, naissance, décès, donation)." },
      ],
    },
    {
      id: 'points-vigilance',
      title: 'Points de vigilance sur la transmission en famille recomposée',
      level: 'h2',
      type: 'normal',
      content: [
        "La transmission en famille recomposée est un sujet sensible qui nécessite une approche prudente et méthodique. Plusieurs points doivent être gardés à l'esprit :",
        "- Aucune stratégie de transmission ne peut totalement déroger à la réserve héréditaire des enfants. Les outils présentés permettent d'organiser la transmission dans le respect des règles légales, mais pas de les contourner complètement.",
        "- La donation entre époux ne protège pas contre tous les risques. Par exemple, si les enfants du défunt décident de vendre leurs droits dans la succession, le conjoint survivant peut se retrouver en indivision avec des tiers.",
        '- Les primes versées sur un contrat d\'assurance-vie ne doivent pas être "manifestement exagérées" au regard du patrimoine et de l\'âge de l\'assuré. Dans le cas contraire, elles peuvent être réintégrées dans la succession.',
        "- La fiscalité des successions peut évoluer. Les abattements et les barèmes peuvent être modifiés par le législateur. Une stratégie de transmission doit être régulièrement révisée.",
        "- Une séparation ou un divorce peut remettre en cause les dispositions prises. Il est important de réviser la stratégie après chaque changement de situation familiale.",
        "- La transmission en famille recomposée nécessite une coordination étroite entre le conseiller en gestion de patrimoine (CGP-CIF) et le notaire. Le CGP analyse la situation patrimoniale et propose des orientations, le notaire rédige les actes juridiques.",
        "Ces points ne remettent pas en cause l'intérêt d'anticiper sa transmission, mais soulignent la nécessité d'une approche professionnelle et coordonnée.",
      ],
    },
  ],
  faq: [
    { question: "Pourquoi la transmission est-elle plus complexe dans une famille recomposée ?", answer: "Parce que le droit successoral français privilégie les enfants du défunt et ne protège pas automatiquement le conjoint survivant en présence d'enfants. Le conjoint survivant peut se retrouver en indivision avec les enfants du premier lit, et les beaux-enfants n'ont aucun droit successoral." },
    { question: "Qu'est-ce que la donation entre époux et pourquoi est-elle importante ?", answer: "La donation entre époux (ou donation au dernier vivant) permet au conjoint survivant de choisir entre l'usufruit de la totalité du patrimoine ou le quart en pleine propriété. Elle est essentielle pour protéger le conjoint dans une famille recomposée." },
    { question: "Comment l'assurance-vie peut-elle aider dans une famille recomposée ?", answer: "L'assurance-vie permet de transmettre des capitaux hors succession, avec un abattement de 152 500 € par bénéficiaire. Elle peut être utilisée pour protéger le conjoint survivant et pour transmettre aux beaux-enfants (qui n'ont pas de droit successoral direct)." },
    { question: "Puis-je déshériter mes enfants au profit de mon conjoint ?", answer: "Non, les enfants sont héritiers réservataires. Vous ne pouvez pas les priver de leur réserve héréditaire (50 % avec un enfant, 66,67 % avec deux, 75 % avec trois ou plus). Vous pouvez seulement disposer librement de la quotité disponible." },
    { question: "Quelle est la différence entre donation entre époux et communauté universelle ?", answer: "La donation entre époux est une disposition testamentaire qui permet une option au moment du décès. La communauté universelle avec clause d'attribution intégrale est un régime matrimonial qui prévoit que tous les biens sont communs et qu'ils reviennent au conjoint survivant au premier décès." },
    { question: "Un concubin est-il protégé en matière de succession ?", answer: "Non, le concubin n'a aucun droit successoral légal. En l'absence de disposition spécifique (assurance-vie, testament), il n'hérite de rien. C'est une situation très risquée pour le concubin survivant." },
    { question: "Quels sont les droits des beaux-enfants dans une succession ?", answer: "Les beaux-enfants n'ont aucun droit successoral direct sur le patrimoine de leur beau-parent. Pour leur transmettre des biens, il faut utiliser l'assurance-vie (désignation comme bénéficiaire), le testament (dans la limite de la quotité disponible) ou l'adoption simple." },
    { question: "Qu'est-ce que la règle des primes manifestement exagérées en assurance-vie ?", answer: "Si les primes versées sur un contrat d'assurance-vie sont disproportionnées par rapport au patrimoine et à l'âge de l'assuré, les héritiers réservataires peuvent demander au juge leur réintégration dans la succession." },
    { question: "Faut-il un notaire pour organiser sa transmission ?", answer: "Oui, certains actes (donation entre époux, testament authentique, donation-partage, changement de régime matrimonial) doivent être rédigés par un notaire. Le CGP-CIF analyse la situation et propose une stratégie, le notaire formalise les actes juridiques." },
    { question: "Quand faut-il commencer à anticiper sa transmission ?", answer: "Le plus tôt possible, dès la constitution de la famille recomposée. Plus l'anticipation est précoce, plus les outils sont efficaces (notamment pour les donations et l'assurance-vie). Il n'est jamais trop tard, mais certaines solutions ne sont plus disponibles à un âge avancé." },
  ],
  ctaTitle: 'Vous êtes en famille recomposée et souhaitez organiser votre transmission ?',
  ctaText: 'Un premier échange gratuit permet d\'analyser votre situation et d\'identifier les outils de transmission adaptés. Aucun engagement, aucune recommandation personnalisée sans analyse préalable.',
  ctaLink: 'https://calendly.com/eric-bellaiche/consultation-avec-eric-bellaiche-clone',
  internalLinks: [
    { href: '/articles/structurer-son-patrimoine/', label: 'Structurer son patrimoine', position: 'inline' },
    { href: '/articles/audit-patrimonial-en-ligne/', label: 'Audit patrimonial en ligne', position: 'inline' },
    { href: '/articles/erreurs-gestion-patrimoine/', label: 'Les erreurs fréquentes en gestion de patrimoine', position: 'inline' },
  ],
};

export default article;
